### ISSUE TITLE
BiasedMerc - OCC_Modular allows loan creation with 0 APR, but refinancing doesn't allow 0 APR

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#1]
BiasedMerc

medium

# OCC_Modular allows loan creation with 0 APR, but refinancing doesn't allow 0 APR

## Summary

Normally a loan can have 0 APR when being created, however a loan cannot be refinanced to 0 APR.

## Vulnerability Detail

When creating a loan, APR can be set to any uint256 value as there is no require check to keep it within any bounds, including 0.

[OCC_Modular::createOffer](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L540-L557)
```solidity
    function createOffer(
        address borrower,
        uint256 borrowAmount,
        uint256 APR,
        uint256 APRLateFee,
        uint256 term,
        uint256 paymentInterval,
        uint256 gracePeriod,
        int8 paymentSchedule
    ) isUnderwriter external {
        require(term > 0, "OCC_Modular::createOffer() term == 0");
        require(
            paymentInterval == 86400 * 7 || paymentInterval == 86400 * 14 || paymentInterval == 86400 * 28 || 
            paymentInterval == 86400 * 91 || paymentInterval == 86400 * 364, 
            "OCC_Modular::createOffer() invalid paymentInterval value, try: 86400 * (7 || 14 || 28 || 91 || 364)"
        );
        require(gracePeriod >= 7 days, "OCC_Modular::createOffer() gracePeriod < 7 days"); // @audit no upper cap
        require(paymentSchedule <= 1, "OCC_Modular::createOffer() paymentSchedule > 1"); // @audit can be negative
```

The function `approveRefinance()` allows an underwriter to propose a new APR that a loan owner can accept by calling `applyRefinance()`. This new APR would likely be agreed upon off-chain and put into effect on-chain calling those two functions.

[OCC_Modular::approveRefinance](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L932-L935)
```solidity
    function approveRefinance(uint256 id, uint256 APR) external isUnderwriter {
        emit RefinanceApproved(id, APR);
        refinancing[id] = APR;
    }
```
There is check for`APR = 0`, the same as when creating a loan. There are also no comments mentioning that refinancing to 0 APR is not allowed.

However, when the user calls `applyRefinance()` to apply the APR change, the function reverts due to a check on `refinancing[id]`:
[OCC_Modular::applyRefinance)](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L859-L861)
```solidity
    function applyRefinance(uint256 id) external {
        require(_msgSender() == loans[id].borrower, "OCC_Modular::applyRefinance() _msgSender() != loans[id].borrower");
        require(refinancing[id] != 0, "OCC_Modular::applyRefinance() refinancing[id] == 0"); // @audit new APR cannot be 0
```
The 2nd require statement ensures that `refinancing[id] != 0`. This is because `refinancing[id] = 0` is being used as a flag that refinancing is unapproved as can be seen here in `unapproveRefinance()`, where the refinancing is being cleared:

[OCC_Modular::unapproveRefinance](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L967-L970)
```solidity
    function unapproveRefinance(uint256 id) external isUnderwriter {
        emit RefinanceUnapproved(id);
        refinancing[id] = 0;
    }
```

This seems to deviate from the expected behaviour as during loan creation there are no checks ensuring the loan does not have 0 APR, and there is no docs or code comments specifying that the refinancing behaviour would differ. It can be reasonably expected that certain loans can have 0 APR, especially if Zivoe has connections with certain partners or when offering promitions, etc.

## Impact

Loan borrowers are unable to refinance their loan to 0 APR, which will result in higher loan payments causing users to pay more in fees, and potentially causing reputational/ legal damages if the 0 APR refinancing was agreed upon off-chain through legal contracts but cannot be implemented on-chain. 

## Code Snippet

[OCC_Modular.sol#L540-L557](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L540-L557)
[OCC_Modular.sol#L932-L935](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L932-L935)
[OCC_Modular.sol#L859-L861](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L859-L861)
[OCC_Modular.sol#L967-L970](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L967-L970)

## Tool used

Manual Review

## Recommendation

If refinancing to 0 APR is intended, then use a similar struct mapping as for [combinations](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L127):

Create a refinance struct:
```solidity
  struct Refinance {
      bool valid;
      uint256 newAPR; 
```

 and use a mapping such as:

```solidity
mapping(uint256 => Refinance) public Refinance;
```

OR

If refinancing to 0 APR is not allowed, then add this information to the docs, add comments to the code and a require to `approveRefinance()` to ensure that the invalid refinancing `APR` reverts the call: 

[OCC_Modular.sol#L127](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L127)
```diff
    function approveRefinance(uint256 id, uint256 APR) external isUnderwriter {
+      require(APR > 0, "OCC_Modular::approveRefinance(), APR == 0")
        emit RefinanceApproved(id, APR);
        refinancing[id] = APR;
    }
```

**Comment by pseudonaut** [comment]
Interesting find - not important/relevant for our purposes to implement this
