### ISSUE TITLE
eeshenggoh - Hardcoded address which is migratable can cause lost funds

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#10]
eeshenggoh

high

# Hardcoded address which is migratable can cause lost funds

## Summary
Zivoe allocates stablecoins and stakes the LP tokens on Convex. 
## Vulnerability Detail
The Convex booster address can be migrated, ability to shut everything down and do a v2.
Furthermore, Curve addresses support the migrating of Liquidity between Pools. It's important to note that the old pool's liquidity and assets are not lost or removed upon migration. Users can still interact with the old pool, including withdrawing their liquidity or assets. The migration process primarily involves transferring liquidity provider (LP) tokens from the old pool to the new pool, not the underlying assets themselves. Therefore, users can still withdraw their assets from the old pool, but they will not receive new LP tokens in the old pool after the migration.

```solidity
//OCY_Convex_A.sol
    address public convexDeposit = 0xF403C135812408BFbE8713b5A23a04b3D48AAE31;
    address public curveBasePool = 0xDcEF968d416a41Cdac0ED8702fAC8128A64241A2;
    address public curveBasePoolToken = 0x3175Df0976dFA876431C2E9eE6Bc45b65d3473CC; /// @dev Index 1, MetaPool
```
```solidity
//OCY_Convex_B.sol
    address public convexDeposit = 0xF403C135812408BFbE8713b5A23a04b3D48AAE31;
    address public curveBasePool = 0x383E6b4437b59fff47B619CBA855CA29342A8559;
    address public curveBasePoolToken = 0x383E6b4437b59fff47B619CBA855CA29342A8559;
```
## Impact
 Zivoe will not receive new LP tokens in the old pool after the migration.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_C.sol#L54
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_C.sol#L61
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_A.sol#L60
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_A.sol#L68

## Tool used

Manual Review

## Recommendation
Add an option to change addresses.

**Comment by goheesheng** [comment]
> 1 comment(s) were left on this issue during the judging contest.
> 
> **panprog** commented:
> 
> > invalid, no funds loss and this appears to be by-design and the flow for the admins in case of any convex address changes: a new OCY_CONVEX_A (C) locker will have to be created, all funds pulled from the old one and then pushed to the new one. So this is a design choice, even though it's probably possible to allow migration of the addresses, but this is at most informational issue.

Hi, funds will be lost in the case that Convex migrated their address and there are deposits called into this contract. There isn't any indication that new locker of the same funds will be created, hence the submission. Furthermore, the DAO can execute the deposit within the 7 days period any potentially not cancelling it. This means that funds sent to this contract, will be lost.

**Comment by goheesheng** [comment]
escalate

**Comment by sherlock-admin3** [comment]
> escalate

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by panprog** [comment]
Even though external admins are restricted, this doesn't mean they will behave in malicious way, meaning that we can't reasonably expect that if convex migrates to another address, that the old address will make all deposits lost, more likely and normal migration way is to either revert all deposits and allow withdrawals, or simply keep it as is, just change UI/docs addresses to new ones, so there should be no funds loss in either case.

**Comment by goheesheng** [comment]
> Even though external admins are restricted, this doesn't mean they will behave in malicious way, meaning that we can't reasonably expect that if convex migrates to another address, that the old address will make all deposits lost, more likely and normal migration way is to either revert all deposits and allow withdrawals, or simply keep it as is, just change UI/docs addresses to new ones, so there should be no funds loss in either case.

You are right that the old pool's liquidity and assets are not lost or removed upon migration. Users can still interact with the old pool, including withdrawing their liquidity or assets. **However,** for future deposits into that particular locker, funds will still be deposited which I confirmed with the Convex Deve team and I quoted and reported as you can see from the issue. 

Funds deposited into that old address, deposits **will not revert** but, users can still withdraw their assets from the old pool, but they will not receive new LP tokens in the old pool after the migration. 

To conclude, any deposits into the pool will not earn any yield, causing protocol to lose funds.

**Comment by panprog** [comment]
Pushing to locker and pulling from locker is admin action - admin decides how much of funds they want in each locker and push accordingly. As such, if convex address changes, admins will simply pull all funds from this locker and create a new one with a new address, so nothing is lost. I agree that it's better to have the mechanism to change the address, but it's more a feature request / informational, the way it is now there will be no issues, just small inconvenience in case the address has to be changed.
