### ISSUE TITLE
lionking927 - updateMaxZVEPerJTTMint function in ZivoeTranches.sol doesn't check current ratio calcaulted by seniorSupp and juniorSupp.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#107]
lionking927

medium

# updateMaxZVEPerJTTMint function in ZivoeTranches.sol doesn't check current ratio calcaulted by seniorSupp and juniorSupp.

## Summary
updateMaxZVEPerJTTMint function in ZivoeTranches.sol doesn't check current ratio calculated by this expression.
currentTrancheRatioBIPS = seniorSupp / juniorSupp * BIPS
otherwise already minted ZVE tokens per zJTT tokens can be considered broking the isJuniorOpen condition.

## Impact
After this rate is updated lower than current ratio, the web3 or any other party using this contract can determine current deposited junior amounts is exceed the max ratio and the system can face unpredicted behaviour.
For example, I suppose there is a page to show junior deposit opens or not based on typed amount but it will always return false for even zero values.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L360

In this line, we can check minimum TrancheRatioBIPS by calculating this expression and compare the given parameter with this value.
currentTrancheRatioBIPS = seniorSupp / juniorSupp * BIPS
require(ratio >= currentTrancheRatioBIPS , "ZivoeTranches::updateMaxTrancheRatio() ratio < currentTrancheRatioBIPS ");

## Tool used

Manual Review

**Comment by pseudonaut** [comment]
It doesn't need to, not valid
