### ISSUE TITLE
lionking927 - rewardZVEJuniorDeposit and rewardZVESeniorDeposit use standarize function of GBL contract but it can mint hudge different amount of tokens for different assets.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#110]
lionking927

medium

# rewardZVEJuniorDeposit and rewardZVESeniorDeposit use standarize function of GBL contract but it can mint hudge different amount of tokens for different assets.

## Summary
rewardZVEJuniorDeposit and rewardZVESeniorDeposit in ZivoeTranches contract use standarize function of GBL contract but it can mint hudge different amount of tokens for different assets.
## Vulnerability Detail
rewardZVEJuniorDeposit and rewardZVESeniorDeposit in ZivoeTranches contract use standarize function of GBL contract but it can mint hudge different amount of tokens for different assets because some stable coins have 6 decimals but some stable coins like DAI have 18 decimals.
so a user who deposited USDT will get reward 10**12x than DAI depositor.
## Impact
I know stable coin addresses are managing by governance but current code can make it difficult to extend to integrate more stable coins to this contract. Otherwise if governance add different decimal stable coins, it can lead user complaints and users may trick by swapping tokens from DAI to USDT to get much more reward tokens.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L304
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L279
## Tool used

Manual Review

**Comment by pseudonaut** [comment]
The only incentive is ZVE, not valid
