### ISSUE TITLE
boredpukar - Out-of-Bounds Array Access and Incorrect Calculation in _checkpointsLookup Function

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#115]
boredpukar

medium

# Out-of-Bounds Array Access and Incorrect Calculation in _checkpointsLookup Function

## Summary

The [_checkpointsLookup](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/libraries/ZivoeVotes.sol#L71) function is intended to find the earliest checkpoint after a given block number using a binary search algorithm. However, improper handling of the array indices can lead to scenarios where the function tries to access elements outside the valid range of the checkpoints array. The cost of massive optimization means there are many edge cases which aren't properly met.

## Vulnerability Detail

Example I -
Checkpoints Array: [100, 200, 300, 10000, 20000] and Block Number: 350

* The length of the array is 5, applying Math.sqrt(5) results in 2, thus mid is initially set to 3.
* The value at index 3 is 10000, which is set as the new high.
* The binary search begins, but since the values from index 0 to 2 are less than 350, it does not locate any checkpoints after 350.
* Ends up selecting the checkpoint at index 2 (300), which is incorrect.

Example II - 
Checkpoints Array: [100, 200, 300, 10000, 20000] and Block Number: 400

* The length of the array is 5. Applying Math.sqrt(5), rounding down to 2. Thus, mid becomes 5 - 2 = 3.
* The fromBlock at index 3 is 10000, which is much greater than 400, so high is set to 3.
* Now, low is 0 and high is 3.
* Calculate new mid as the average of low (0) and high (3), resulting in 1 (assuming integer rounding).
* At index 1, fromBlock is 200, which is less than 400, so low becomes 2.
* New mid with low = 2 and high = 3 is 2.
* At index 2, fromBlock is 300, which is still less than 400, so low becomes 3.
* low equals high (both 3), and the loop terminates.
* Function should return _unsafeAccess(ckpts, 3 - 1).votes which would access ckpts[2].votes, corresponding to block 300, which is incorrect.

Example III - 
Checkpoints Array: [100, 200, 300] and Block Number: 350

* Initialize low to 0 and high to 3 (length of the array).
* Binary search progresses without finding any checkpoint greater than 350.
* low moves to 3, making low equal to high.
* Function attempts to return _unsafeAccess(ckpts, 3 - 1).votes which accesses ckpts[2].votes.
* Since all elements are less than or equal to 350, the function incorrectly identifies 300 as the checkpoint after 350.

## Impact

This vulnerability can lead to situations where the protocol exhibit incorrect application behavior.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/libraries/ZivoeVotes.sol#L71

```solidity
     /**
     * @dev Lookup a value in a list of (sorted) checkpoints.
     */
    function _checkpointsLookup(Checkpoint[] storage ckpts, uint256 blockNumber) private view returns (uint256) {
        // We run a binary search to look for the earliest checkpoint taken after `blockNumber`.
        //
        // Initially we check if the block is recent to narrow the search range.
        // During the loop, the index of the wanted checkpoint remains in the range [low-1, high).
        // With each iteration, either `low` or `high` is moved towards the middle of the range to maintain the invariant.
        // - If the middle checkpoint is after `blockNumber`, we look in [low, mid)
        // - If the middle checkpoint is before or equal to `blockNumber`, we look in [mid+1, high)
        // Once we reach a single value (when low == high), we've found the right checkpoint at the index high-1, if not
        // out of bounds (in which case we're looking too far in the past and the result is 0).
        // Note that if the latest checkpoint available is exactly for `blockNumber`, we end up with an index that is
        // past the end of the array, so we technically don't find a checkpoint after `blockNumber`, but it works out
        // the same.
        uint256 length = ckpts.length;

        uint256 low = 0;
        uint256 high = length;

        if (length > 5) {
            uint256 mid = length - Math.sqrt(length);
            if (_unsafeAccess(ckpts, mid).fromBlock > blockNumber) {
                high = mid;
            } else {
                low = mid + 1;
            }
        }

        while (low < high) {
            uint256 mid = Math.average(low, high);
            if (_unsafeAccess(ckpts, mid).fromBlock > blockNumber) {
                high = mid;
            } else {
                low = mid + 1;
            }
        }

        return high == 0 ? 0 : _unsafeAccess(ckpts, high - 1).votes;
    }
```

## Tool used

Manual Review

## Recommendation

Readjust the code to ensure that all of the edge cases are properly documented.

**Comment by pseudonaut** [comment]
The first example you provided wouldn't occur because length == 5 and that if statement is skipped

I am not sure on validity of rest of this, as no test-cases were provided or code to validate findings in solidity
