### ISSUE TITLE
Timenov - Governor's functionality can be disrupt.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#120]
Timenov

medium

# Governor's functionality can be disrupt.

## Summary
The `ZivoeGovernorV2` smart contract is used as governance contract. It's functionality can be disrupt because of the following reasons: short voting time, big proposal threshold and potential of 0 quorum percentage.

## Vulnerability Detail
The three problems listed above with explanation:

#### Short voting time
On deployment the `votingDelay` is set to 1 block and the `votingPeriod` is set to 3600 blocks. Both of the values can be changed later through functions protected with `onlyGovernance` modifier, but must pass `0 <= votingDelay <= 300` and `2400 <= votingPeriod <= 21600`. However this may not be long enough for users to cast their votes.

The `votingDelay` and `votingPeriod` are both represented in number of blocks. Lets calculate them based on deployment values which are `1` and `3600`.

$$ votingDelay = 1 blocks * 12 secondsPerBlock \over 3600 $$

$$ votingPeriod = 3600 blocks * 12 secondsPerBlock \over 3600 $$

The results will be:

`votingDelay = 0.0033 hours`
`votingPeriod = 12 hours`

This is not enough time for users to both carefully review the proposal and vote. Even if we take the maximum amount these variables can hold, we will have the following:

$$ votingDelay = 300 blocks * 12 secondsPerBlock \over 3600 $$

$$ votingPeriod = 21600 blocks * 12 secondsPerBlock \over 3600 $$

The results will be:

`votingDelay = 1 hour`
`votingPeriod = 72 hours`

Which still is not long enough for users to vote and may not reach quorum.

#### Big proposal threshold
On deployment the `proposalThreshold` is set to `100000 ether`. This threshold as per [OpenZeppelin docs](https://docs.openzeppelin.com/contracts/4.x/governance#governor) is used to `This restricts proposal creation to accounts who have enough voting power`. This means that in order to create a proposal, user must have at least `100000e18` worth of `ZivoeTokens`.

This threshold will allow only a fraction of the users(the most "wealthy" ones) to create proposals. This breaks the whole functionality and makes the governance centralized. Yes, this threshold can be changed through the `setProposalThreshold` function in the same contract. However this function has `onlyGovernance` meaning that a proposal will need to be created and accepted in order for this function to be called. The few users that will be able to create proposals may not create such proposal, as that will revoke them from the power they have, which is to control the governance.

This will result in blocked and centralized governance.

#### Quorum percentage set to 0
On deployment the `quorumNumerator` is set to `10%`. This means that in order for a proposal to be accepted at least 10% of the votes should be `For`. There is also a function called `updateQuorumNumerator` which allows the quorum percentage to be updated through proposal, but must be `0 <= newQuorumNumerator <= 30`. Setting it to 0 will mean that every proposal will be accepted.

Consider the following scenario:

1. Malicious group(that holds at least 10% of the voting tokens) creates a proposal to set the `quorumNumerator` to 0.
2. The same group approves that proposal.
4. The `quorumNumerator` is updated.
5. The malicious group can execute whatever they want.

## Impact
The listed problems can seriously affect the governance of the protocol.

#### Short voting time
```solidity
    constructor(IVotes _token, ZivoeTLC _timelock, address _GBL)
        Governor("ZivoeGovernorV2") GovernorSettings(1, 3600, 100000 ether)
        GovernorVotes(_token) GovernorVotesQuorumFraction(10) ZivoeGTC(_timelock) { GBL = _GBL; }
```

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGovernorV2.sol#L62-L64

```solidity
    function setVotingDelay(uint256 newVotingDelay) public override(GovernorSettings) onlyGovernance {
        require(newVotingDelay <= 300, "ZivoeGovernorV2::setVotingDelay newVotingDelay > 300 blocks");
        _setVotingDelay(newVotingDelay);
```

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGovernorV2.sol#L84-L87

```solidity
    function setVotingPeriod(uint256 newVotingPeriod) public override(GovernorSettings) onlyGovernance {
        require(newVotingPeriod >= 2400, "ZivoeGovernorV2::setVotingPeriod newVotingPeriod < 2400 blocks");
        require(newVotingPeriod <= 21600, "ZivoeGovernorV2::setVotingPeriod newVotingPeriod > 21600 block");
        _setVotingPeriod(newVotingPeriod);
    }
```

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGovernorV2.sol#L91-L95

#### Big proposal threshold
```solidity
    constructor(IVotes _token, ZivoeTLC _timelock, address _GBL)
        Governor("ZivoeGovernorV2") GovernorSettings(1, 3600, 100000 ether)
        GovernorVotes(_token) GovernorVotesQuorumFraction(10) ZivoeGTC(_timelock) { GBL = _GBL; }
```

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGovernorV2.sol#L62-L64

```solidity
    function setProposalThreshold(uint256 newProposalThreshold) public override(GovernorSettings) onlyGovernance {
        require(
            newProposalThreshold <= 125000 ether, 
            "ZivoeGovernorV2::setProposalThreshold newProposalThreshold > 125000 ether"
        );
        _setProposalThreshold(newProposalThreshold);
    }
```

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGovernorV2.sol#L98-L104

#### Quorum percentage set to 0
```solidity
    constructor(IVotes _token, ZivoeTLC _timelock, address _GBL)
        Governor("ZivoeGovernorV2") GovernorSettings(1, 3600, 100000 ether)
        GovernorVotes(_token) GovernorVotesQuorumFraction(10) ZivoeGTC(_timelock) { GBL = _GBL; }
```

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGovernorV2.sol#L62-L64

```solidity
    function updateQuorumNumerator(uint256 newQuorumNumerator) public override(GovernorVotesQuorumFraction) onlyGovernance {
        require(newQuorumNumerator <= 30, "ZivoeGovernorV2::updateQuorumNumerator newQuorumNumerator > 30");
        _updateQuorumNumerator(newQuorumNumerator);
    }
```

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGovernorV2.sol#L107-L110

## Tool used
Manual Review, OpenZeppelin docs

#### Short voting time
Consider increasing the time for voting. As per [OZ governance](https://docs.openzeppelin.com/contracts/4.x/governance#governor), the suggested time for `votingDelay` is at least 1 day and for `votingPeriod` is at least 1 week.

#### Big proposal threshold
As per my understanding of how a governance should work everyone should have the ability to create a proposal. So set it to 0 on deployment and maybe leave that `setProposalThreshold` but restrict it to much less(lets say 10 ether).

#### Quorum percentage set to 0
Set the `quorumNumerator` to 20 on deployment. In the `updateQuorumNumerator` make the validation be `10 <= newQuorumNumerator <= 30`.

**Comment by pseudonaut** [comment]
Not relevant, will adjust post-launch once initial governance actions across initial parites is conducted
