### ISSUE TITLE
Tychai0s - Incorrect Handling of Fee-on-Transfer Tokens Across Multiple Contracts

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#121]
Tychai0s

medium

# Incorrect Handling of Fee-on-Transfer Tokens Across Multiple Contracts

## Summary
The audit identified several instances across multiple Solidity contracts where the handling of fee-on-transfer tokens was not properly addressed. This can lead to inaccurate tracking of user balances and potential loss of funds.

## Vulnerability Detail

1. In [`ZivoeITO.sol:263`](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L263) and [`ZivoeITO.sol:290`](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L290)
The `depositJunior()` and `depositSenior()` functions do not take into account the potential fee charged by the stable tokens during the transfer. This can result in the contract recording an incorrect balance for the user.

2. In [`ZivoeRewards.sol:229`](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L229)
The `depositReward()` function does not handle the case where the reward token has a fee-on-transfer mechanism. This can lead to inaccurate tracking of the reward balance.

3. In [`ZivoeRewardsVesting.sol:353`](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L353)
Similar to the issue in `ZivoeRewards.sol`, the `depositReward()` function in `ZivoeRewardsVesting.sol` does not support fee-on-transfer tokens, which can cause problems with the reward balance tracking.

4. In [`ZivoeTranches.sol:277`](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L277)
The `depositJunior()` and `depositSenior()` functions do not correctly handle the transfer of tokens that have a fee-on-transfer mechanism. This can lead to inaccurate tracking of user balances.

## Impact
If the tokens being deposited or used as rewards have a fee-on-transfer mechanism, the contracts will not be able to accurately track the user balances and reward balances. This can lead to incorrect distribution of rewards, potential loss of funds, and other issues related to the affected systems.

## Code Snippet
```solidity
    // @audit-issue M-02 doesn't take into account fee on transfer stable tokens; it might the case where the amount received is not the same as the amount sent.
    address caller = _msgSender();
    uint256 standardizedAmount = IZivoeGlobals_ITO(GBL).standardize(amount, asset);
```

## Tool used
Manual Review

## Recommendation
To address these issues, the contracts should be updated to consider the fee-on-transfer mechanism of the tokens being used. This can be done by calculating the actual amount received by the contract after the transfer and using that value for balance tracking and other relevant operations.

Here's an example of how the affected functions can be updated, giving as an example how it can be handled in the `ZivoeITO.depositSenior()` function, but the general idea can be applied elsewhere:

```solidity
function depositSenior(uint256 amount, address asset) public { 
        // ...
        uint256 balanceBefore = IERC20(asset).balanceOf(address(this));
        IERC20(asset).safeTransferFrom(caller, address(this), amount);
        uint256 balanceAfter = IERC20(asset).balanceOf(address(this));
        uint256 actualAmount = balanceBefore - balanceAfter;
        uint256 standardizedAmount = IZivoeGlobals_ITO(GBL).standardize(actualAmount, asset);

        seniorCredits[caller] += standardizedAmount * 3;

        emit SeniorDeposit(caller, asset, amount, standardizedAmount * 3, standardizedAmount);

        IERC20Mintable_ITO(IZivoeGlobals_ITO(GBL).zSTT()).mint(address(this), standardizedAmount);
    }

```

By implementing these changes, the contracts can accurately track user balances and reward balances, even when handling fee-on-transfer tokens.

**Comment by pseudonaut** [comment]
Irrelevant
