### ISSUE TITLE
4b - `ZivoeGlobals::initializeGlobals()` can be initialized more than once

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#127]
4b

high

# `ZivoeGlobals::initializeGlobals()` can be initialized more than once

## Summary
[`initializeGlobals()`](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGlobals.sol#L179-L205) can be called more than once.
## Vulnerability Detail
[This comment](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGlobals.sol#L176) indicates the invariant that the function `initializeGlobals()` should be called once, but there's no line of code or modifier enforcing that 
## Impact
The contract can be initialized more than once hence re-initialization which is a breach of the [invariant](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGlobals.sol#L176) stated in the code.
## Code Snippet

`ZivoeGlobals::initializeGlobals()`

```solidity
    function initializeGlobals(
        address[] calldata globals,
        address[] calldata stablecoins
    ) external onlyOwner {
        require(DAO == address(0), "ZivoeGlobals::initializeGlobals() DAO != address(0)");

       ...

}
```

## Tool used

Manual Review

## Recommendation
1.consider using openzeppelin's initializer(1) function.
2. Introducing a bool and setting it to true when the function is called and pass in a modifier to check that bool before  execution.

**Comment by pseudonaut** [comment]
It enforces it when DAO != address(0) which should be assumed handled properly during deployment
