### ISSUE TITLE
KingNFT - Users can't ````getRewards()```` if any one of reword tokens is paused

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#130]
KingNFT

medium

# Users can't ````getRewards()```` if any one of reword tokens is paused

## Summary
Per contest readme, issues related to  external contracts pausing are not acceptable.
>In case of external protocol integrations, are the risks of external contracts pausing or executing an emergency withdrawal acceptable? If not, Watsons will submit issues related to these situations that can harm your protocol's functionality.

>Not acceptable

In current implementation of ````ZivoeRewards```` contract, all rewards must be claimed atomically by calling ````getRewards()````. If any of external reward tokens is paused, would cause ````getRewards()```` revert entirely. Pausing of some reward token should not block others from claiming.

## Vulnerability Detail
Tokens such as ````USDC```` and ````USDT```` could be paused. If any of them are added as reward token, the pausing of these external tokens would cause revert on L292 of ````_getRewardAt()````, then trigger revert of the whole ````getRewards()```` call. As the ````getRewards()```` function is the only interface for claiming rewards, pausing of any reward token would block all other ````rewardTokens```` from claiming.
```solidity
File: zivoe-core-foundry\src\ZivoeRewards.sol
281:     function getRewards() public updateReward(_msgSender()) {
282:         for (uint256 i = 0; i < rewardTokens.length; i++) { _getRewardAt(i); }
283:     }

File: zivoe-core-foundry\src\ZivoeRewards.sol
287:     function _getRewardAt(uint256 index) internal nonReentrant {
288:         address _rewardsToken = rewardTokens[index];
289:         uint256 reward = rewards[_msgSender()][_rewardsToken];
290:         if (reward > 0) {
291:             rewards[_msgSender()][_rewardsToken] = 0;
292:             IERC20(_rewardsToken).safeTransfer(_msgSender(), reward);
293:             emit RewardDistributed(_msgSender(), _rewardsToken, reward);
294:         }
295:     }

```

## Impact
Core feature of ````ZivoeRewards```` contract get blocked.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L281

## Tool used

Manual Review

## Recommendation
Allow users to specify which reward tokens they'd like to claim.

Duplicate of #657

**Comment by pseudonaut** [comment]
Thanks. Technically true however known and not of concern
