### ISSUE TITLE
beWater0given - Pay adequate vesting tokens to create a vesting schedule is possible

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#134]
beWater0given

medium

# Pay adequate vesting tokens to create a vesting schedule is possible

## Summary
The `vestingTokenAllocated` variable underrepresents the actual amount of tokens allocated, leading to a scenario where ZVL can create a vesting schedule without transferring an adequate amount of vesting tokens.

## Vulnerability Detail
Variable `vestingTokenAllocated` represents "The amount of vestingToken currently allocated". It tracks the total vested token amount:

1. The `createVestingSchedule` function accumulates the amount of tokens to be vested (`amountToVest`) to the `vestingTokenAllocated`.
2. The `withdraw` function accounts for tokens that have been withdrawn by reducing the `vestingTokenAllocated` accordingly.

In the `revokeVestingSchedule` function, when a vesting schedule is revoked, only the unlocked tokens are withdrawn from the contract, and the remaining locked tokens (`totalVesting - amount`) are still retained in the contract. However, the total vested token amount of the account is reduced from `vestingTokenAllocated`, leading to a discrepancy between the actual amount of tokens locked in the contract and the amount represented by `vestingTokenAllocated`.

## Impact
The value of variable `vestingTokenAllocated` is lower than the actual value. Consequently, when new vesting schedules are created, depositors are not required to transfer the sufficient amount of vesting tokens ([L393](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L393)). 

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L442

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L449

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L393

## Tool used

Manual Review

## Recommendation
Should not subtract `(vestingAmount - vestingScheduleOf[account].totalWithdrawn)` from the `vestingTokenAllocated`.

**Comment by pseudonaut** [comment]
Valid, mentioned elsewhere, accounting updates needed
