### ISSUE TITLE
beWater0given - Rounding issue prevents distribution of a small amount reward tokens

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#136]
beWater0given

medium

# Rounding issue prevents distribution of a small amount reward tokens

## Summary
A rounding issue in the contract prevents the distribution of a small amount of reward tokens to depositors. Due to this issue, a portion of reward tokens remains locked within the contract.

## Vulnerability Detail
When the `depositReward` function is used to deposit a reward token amount that is not a number multiple of `rewardData[_rewardsToken].rewardsDuration`, the reward rate calculation results in will lose 1 ~ `rewardData[_rewardsToken].rewardsDuration - 1` of reward tokens due to rounding down:
```solidity
    rewardData[_rewardsToken].rewardRate = reward.div(rewardData[_rewardsToken].rewardsDuration);
```

Consequently, a small portion of reward tokens cannot be distributed, leading to their permanent lock within the contract.

## Impact
A small amount of reward tokens are locked in the contract.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewards.sol#L233

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewards.sol#L237

## Tool used

Manual Review

## Recommendation
Refund the remaining tokens.

Duplicate of #129

**Comment by pseudonaut** [comment]
Are we sure? Is this dust acceptable? I think not relevant
