### ISSUE TITLE
beWater0given - Inaccurate `totalVesting` representation in revoked vesting schedules

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#137]
beWater0given

medium

# Inaccurate `totalVesting` representation in revoked vesting schedules

## Summary
The totalVesting attribute within a revoked vesting schedule inaccurately reflects the total amount of tokens intended to vest.

## Vulnerability Detail
The `VestingSchedule.totalVesting` represents "The total amount to vest".

Upon initializing a vesting schedule, `totalVesting` is correctly set to represent the entire amount of tokens ([L410](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L410)). When withdrawing unlocked vesting tokens, the totalVesting remains static ([L501](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L501)). However, it is updated to `vestingScheduleOf[account].totalWithdrawn` in the `revokeVestingSchedule` function, transforming its meaning to represent the total amount of tokens that have been withdrawn, rather than maintaining its original purpose of indicating the total tokens to be vested.

## Impact
This inconsistency causing confusion that `totalVesting` of a revoked vesting schedule retrieved by the `viewSchedule` function is the withdrawn token amount.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L445

## Tool used

Manual Review

## Recommendation
Do not update `vestingScheduleOf[account].totalVesting` in the `revokeVestingSchedule` function.

**Comment by pseudonaut** [comment]
Valid, need to update accounting
