### ISSUE TITLE
marchev - `ZivoeITO` blacklisting during ITO bricks the protocol and results in total loss of ITO funds

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#141]
marchev

medium

# `ZivoeITO` blacklisting during ITO bricks the protocol and results in total loss of ITO funds

## Summary

If the `ZivoeITO` contract is blacklisted for any of the supported stablecoins during the Initial Tranche Offering (ITO), all raised funds will be irretrievably lost, and the entire Zivoe protocol will be bricked as well.

## Vulnerability Detail

The `ZivoeITO` contract is a crucial component of the Zivoe protocol. It has two main responsibilities:

- Raise capital via a pre-sale called ITO ("Initial Tranche Offering")
- Bootstrap the Zivoe protocol once the ITO completes

The `ZivoeITO` contract allows users to participate in the ITO by depositing one of the following stablecoins: USDC, USDT, DAI and FRAX. 

Once the ITO completes, funds are transferred to the `ZivoeDAO` contract using the `migrateDeposits()`:

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L329-L331

This function also bootstraps the Zivoe protocol by unlocking the YDL and Tranche contracts:

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L333-L334

This function employs a push-based migration method, transferring all balances in a single transaction. If the `ZivoeITO` contract gets blacklisted for any of its supported stablecoins, the `migrateDeposits()` function will revert, trapping all funds within the contract permanently. Notably, USDC, USDT, and DAI have blacklisting features, which increases the risk.

Furthermore, the Zivoe protocol cannot be bootstrapped. The reason is `ZivoeITO` is the only contract that can unlock `ZivoeYDL` and `ZivoeTranches`. This effectively renders the whole protocol defunct.

The stablecoin configuration for the `ZivoeITO` contract is fixed during creation and cannot be updated later. Thus, there are no available mechanisms to allow the protocol owners or the Zivoe governance to resolve the issue.

## Impact

The `migrateDeposits()` function is of critical importance for the protocol and its failure due to blacklisting can have detrimental effects:

- Permanent loss of all funds collected during the ITO
- The protocol gets bricked, as the essential function to bootstrap it would be blocked

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L329-L334

## Tool used

Manual Review

## Recommendation

To mitigate this risk, the following strategies could be implemented:

- Allow Zivoe governance to exclude certain stablecoins from the migration process
- Enable the migration of stablecoin balances on an individual basis

These changes would ensure that blacklisting one stablecoin does not affect the entire fund migration process or halt protocol operations.

**Comment by pseudonaut** [comment]
Not relevant
