### ISSUE TITLE
Tendency - `ema` is miscalculated during the first yield distribution

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#142]
Tendency

medium

# `ema` is miscalculated during the first yield distribution

       
## Summary
The wrong `emaSTT` and `emaJTT` values are stored during the first yield distribution, due to wrongly using `N` as 1 during the ema calculation, instead of starting with N as 2.
## Vulnerability Detail
The `ema(exponential moving average)` of the junior and senior tranche token supplies is preferred to be used for computation in the system, this is mostly to ensure a steady increase in yield target and to avoid a sudden spike in yield target between the period of last to the current distribution, this is done by getting the exponential moving average of the former supply and the current supply to smoothen the supply. The problem here is, during the first yield distribution only the current value is returned and not an `ema` value, this is because `distributionCounter` equals one, thus the current value is returned instead.

+ To Illustrate

given the formula: 
```solidity
    function ema(uint256 bV, uint256 cV, uint256 N) external pure returns (uint256 eV) {
        assert(N != 0);
        uint256 M = (WAD * 2).floorDiv(N + 1);
        eV = ((M * cV) + (WAD - M) * bV).floorDiv(WAD);
    }
```
When N equals 1, M becomes:
        = 1e18 * 2 / (1 + 1) => 2e18 / 2 ==> 1e18
 eV, becomes:
        (1e18 * cV + (1e18 - 1e18)) / 1e18 ==> 1e18 * cV + 0 /1e18
        ==> cV
Where WAD  equals 1e18

As seen from the calculation above, when N(distribution counter in our case) is 1, the current value/supply is stored as the `ema`, and since there is a waiting period of 60 days since the contract became unlocked to the first distribution, if the supply has increased a lot due to increased user participation between this time frame, this creates a situation where yield target obligations are increased, without sufficient time for capital to be deployed off-chain to generate yield

## Impact
+ Will overstate the senior proportion and understate the junior proportion
+ Yield targets could be on the high side, as the first `ema` value will affect the subsequent `ema` values
This is because in ema calculations, the current value will go on to be the base value for the next ema calculation, and the higher this base value, the higher the ema returned

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeYDL.sol#L213

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeMath.sol#L35-L40
## Tool used

Manual Review

## Recommendation
Add a counter variable for `ema` calculations that will be initially set to 1, it should be incremented when [distributionCounter](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeYDL.sol#L226) is incremented, to ensure the `ema` calculation starts with N = 2, just as done in the tests and as discussed with a sponsor `johnnyq` from the team

Duplicate of #201

**Comment by pseudonaut** [comment]
Valid, a fix is to set distributionCounter to 1 initially so 2 will be the first submitted input
