### ISSUE TITLE
Tendency - Deposited Rewards Could Be Stuck

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#147]
Tendency

medium

# Deposited Rewards Could Be Stuck

## Summary
Reward deposits when there are no stakers, will cause a portion of the deposited reward to be stuck
## Vulnerability Detail
The `depositReward` functionality in the system for either `ZivoeRewards` or for `ZivoeRewardsVesting` contract is intended to be used to deposit reward into the contract, which will then be evenly shared to stakers in the contract based on their stake and the reward duration.
The problem is that, when this reward contracts have no stakers, i.e. total supply being zero, a portion or all of the deposited reward will be lost.

Though the `depositReward` functionality is open to reward deposits from anybody, the majority of its reward is intended to come from `ZivoeYDL` as yield, see [ZivoeYDL::distributeYield](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeYDL.sol#L213-L311) function.

These staking contracts having no stakers seems unlikely but it is possible, for example, for `ZivoeRewardsVesting` contract, this could happen when the ZVL hasn't created any new vesting schedule for a while and all other vests have withdrawn.

+ To Illustrate how a portion of the reward could be stuck in the contract

Let's assume the reward token is USDC and the reward duration is 10 days:
If 1000 USDC is deposited as a reward when there are currently no stakers, the reward rate is calculated as:

reward / reward duration ==> 1000 / 10  -> 100
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewards.sol#L233

What this means is, the complete reward will only be returned at least 10 days later.
But when a user stakes, let's say 5 days later, the token `lastUpdateTime` gets set to that time, making the max claimable reward after this deposit to be:
10 - 5 ==> 5 days * 100 -> 500 USDC

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewards.sol#L127

this is assuming the full reward duration is reached

As seen above, the claimable reward will depend on when the next staker stakes, the rest stays stuck in the contract since there is no functionality for rescuing these rewards.

## Impact
The deposited rewards will be stuck without a way to rescue them
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewards.sol#L228-L243

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewards.sol#L189-L190

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewards.sol#L123-L134

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeYDL.sol#L213-L311
## Tool used

Manual Review

## Recommendation
Consider adding logic to handle this scenario, you could maybe send the reward to the DAO instead, or simply include an additional withdrawal functionality for the ZVL to rescue stuck reward tokens.

Duplicate of #113

**Comment by pseudonaut** [comment]
Acceptable
