### ISSUE TITLE
Tendency - After ITO Ends, Users Claimable `$ZVE` Tokens are Prone to Manipulation

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#149]
Tendency

high

# After ITO Ends, Users Claimable `$ZVE` Tokens are Prone to Manipulation

## Summary
`ZivoeTranches` is initially left unpaused, allowing deposits after ITO ends and its contract unlocked, this hence reduces users' claimable ZVE as more users deposit into the tranches.
## Vulnerability Detail
In `ZivoeITO` contract, after an ITO ends [claimAirdrop](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeITO.sol#L203-L242) is called by depositors to claim their airdropped tokens, depending on the tranch the user deposited into, this could be senior tranche tokens($zSTT) or junior tranche tokens($zJTT), vesting is also scheduled for Zivoe tokens($ZVE).
The amount of $ZVE to vest for the user is calculated as:
(upper * middle) / lower
```solidity
        uint256 upper = seniorCreditsOwned + juniorCreditsOwned;
        uint256 middle = IERC20(IZivoeGlobals_ITO(GBL).ZVE()).totalSupply() /
            20;
        uint256 lower = IERC20(IZivoeGlobals_ITO(GBL).zSTT()).totalSupply() *
            3 +
            (IERC20(IZivoeGlobals_ITO(GBL).zJTT()).totalSupply());
```
As seen above the `lower` depends on the total supply of the senior and the junior tranche tokens. 
The problem now is, after ITO is complete and deposits are migrated via [ZivoeITO::migrateDeposits](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeITO.sol#L313-L335) function, `ZivoeTranches` contract is unlocked. After this contract is unlocked all junior and senior deposits in `ZivoeTranches` also mint an equivalent amount of $zSTT or $zJTT as the case may be, this will thus create a spike in lower for our calculation above, since it is used to determine users' ZVE, this will create a scenario where for 500 stable deposits between two users during ITO, the user who claims before any deposit happened in `ZivoeTranches`, will get way more than the user who tries to claim afterwards. 

As more deposits are made in `ZivoeTranches`, users' claimable ZVE diminishes

## Impact
Some users will claim less ZVE than they should get
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeITO.sol#L203-L242

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeITO.sol#L313-L335

## Tool used

Manual Review

## Recommendation
Consider initializing the paused variable to true in the constructor, to ensure the contract is only unpaused after all users claim their airdrops.

Note that `ZivoeTranches` initial state is meant to be paused, since no deposits are meant to be allowed until after ITO ends

Duplicate of #12

**Comment by pseudonaut** [comment]
Valid, need to snapshot
