### ISSUE TITLE
Ruhum - OCL_ZVE assumes that ZVE will always be tokenB

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#158]
Ruhum

medium

# OCL_ZVE assumes that ZVE will always be tokenB

## Summary
OCL_ZVE assume that ZVE will always be tokenB which is not necessarily true. It depends on the pair asset. 

## Vulnerability Detail
Uni V2 forces the pair's tokens to be ordered such that `tokenA < tokenB`: https://github.com/Uniswap/v2-core/blob/master/contracts/UniswapV2Factory.sol#L25
Thus, ZVE can only be tokenB if `pairAsset < ZVE`. 

In OCL_ZVE the contract assumes that ZVE is always tokenB as seen here:
```sol
        (uint256 depositedPairAsset, uint256 depositedZVE, uint256 minted) = IRouter_OCL_ZVE(router).addLiquidity(
            pairAsset, 
            ZVE, 
            balPairAsset,
            balZVE, 
            (balPairAsset * 9) / 10,
            (balZVE * 9) / 10, 
            address(this), block.timestamp + 14 days
        );
```
That will cause the call to `addLiquidity()` to revert.

## Impact
The contract won't be usable with any token where the pool's tokenB won't be ZVE.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L200

## Tool used

Manual Review

## Recommendation
tokenA and tokenB should be set in the contract's constructor depending on the `pairAsset` that is used.

**Comment by pseudonaut** [comment]
Interesting, seems potentially valid and should be addressed

The contract you linked is not relevant, it's the UniswapV2Router02.sol that's relevant for the addLiquidity() endpoint to examine if what you're suggesting is valid. Let's look into this further
