### ISSUE TITLE
AllTooWell - If ```OCC_Modular``` address was blacklisted by USDT/USDC admin, the lending modular won't work

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#159]
AllTooWell

medium

# If ```OCC_Modular``` address was blacklisted by USDT/USDC admin, the lending modular won't work

## Summary
If ```OCC_Modular``` address was blacklisted by USDT/USDC admin, the lending modular won't work.
## Vulnerability Detail
There will be four ```OCC_Modular```: OCC_Modular_USDC / OCC_Modular_USDT / OCC_Modular_DAI / OCC_Modular_FRAX.
Sherlock docs:
> Non-Standard tokens: Issues related to tokens with non-standard behaviors, such as [weird-tokens](https://github.com/d-xo/weird-erc20) are not considered valid by default unless these tokens are explicitly mentioned in the README.

contest README:
> Which ERC20 tokens do you expect will interact with the smart contracts?
USDC, DAI, USDT, FRAX, and in some yield lockers CRV, CVX

> Are the admins of the protocols your contracts integrate with (if any) TRUSTED or RESTRICTED?
RESTRICTED

USDC, USDT have a contract level admin controlled address blacklist. If an address is blacklisted, then transfering to and from that address are forbidden. If ```OCC_Modular``` address was blacklisted by USDT/USDC admin, the lending modular won't work. The lending modular is the core of protocol.
## Impact
If ```OCC_Modular``` address was blacklisted by USDT/USDC admin, the lending modular won't work.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L116
## Tool used
manual
## Recommendation
Monitor the blacklist situation and have some contingency plans.

**Comment by pseudonaut** [comment]
Not relevant
