### ISSUE TITLE
AllTooWell - If ```Convex``` admin shut down the system or the integrated pool, can't deploy capital into ```convex``` and can't get rewards

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#160]
AllTooWell

medium

# If ```Convex``` admin shut down the system or the integrated pool, can't deploy capital into ```convex``` and can't get rewards

## Summary
If ```Convex``` admin shut down the system or the integrated pool, can't deploy capital into ```convex``` and can't get rewards.
## Vulnerability Detail
contest README:
> Are the admins of the protocols your contracts integrate with (if any) TRUSTED or RESTRICTED?
RESTRICTED

> In case of external protocol integrations, are the risks of external contracts pausing or executing an emergency withdrawal acceptable? If not, Watsons will submit issues related to these situations that can harm your protocol's functionality.
Not acceptable

Some on-chain yield is got from ```Convex``` protocol. The ```Convex``` protocol first deploy capital into curve pool and then stake curve pool lp tokens into gauge system.
Code from [```ConvexBooster```](https://etherscan.io/address/0xF403C135812408BFbE8713b5A23a04b3D48AAE31#code) (entry point of depositing):
```solidity
//deposit lp tokens and stake
    function deposit(uint256 _pid, uint256 _amount, bool _stake) public returns(bool){
        require(!isShutdown,"shutdown");
        PoolInfo storage pool = poolInfo[_pid];
        require(pool.shutdown == false, "pool is closed");

        ······
       }
```
```earmarkRewards``` in ```ConvexBooster``` is used to transfer rewards to reward contract.
```solidity
function earmarkRewards(uint256 _pid) external returns(bool){
        require(!isShutdown,"shutdown");
        _earmarkRewards(_pid);
        return true;
    }
```
```solidity
//claim crv and extra rewards and disperse to reward contracts
    function _earmarkRewards(uint256 _pid) internal {
        PoolInfo storage pool = poolInfo[_pid];
        require(pool.shutdown == false, "pool is closed");

        ······
       }
```
As can be seen from the above code, if ```isShutdown``` is ```true``` and ```pool.shutdown``` is ```true```, ```deposit``` and ```earmarkRewards``` will revert, can't deploy capital into ```convex``` and can't get rewards. The ```withdraw``` function maintains its functionality even during system or pool shutdowns.
## Impact
If ```Convex``` admin shut down the system or the integrated pool, can't deploy capital into ```convex``` and can't get rewards.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_A.sol#L167
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_A.sol#L247
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_C.sol#L139
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_C.sol#L201
## Tool used
manual
## Recommendation
Monitor the situation and have some contingency plans.

Duplicate of #657

**Comment by pseudonaut** [comment]
Not relevant
