### ISSUE TITLE
pseudoArtist - `OCC_Modular::makePayment()` `makePayment()` will DoS for Blacklisted users of `distributedAsset` .

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#164]
pseudoArtist

medium

# `OCC_Modular::makePayment()` `makePayment()` will DoS for Blacklisted users of `distributedAsset` .

## Summary
The function [makePayment()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L575C14-L602) is used by anyone to make a payment on someone's loan, however the interest and the lateFee are paid in the form of `distributedAsset` which can be USDC as per the information available from the discord chat and the sponsor's input, so the users who are blacklisted for the stablecoin USDC won't be able to `makePayment()` on behalf of someone else.
## Vulnerability Detail
The function [makePayment()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L575C14-L602) is used by anyone to make a payment on someone's loan, and if you see the code for `makePayment()` it transfers the `interest + lateFee` to YDL if they are in the same format: 

```solidity
 if (stablecoin == IZivoeYDL_OCC(IZivoeGlobals_OCC(GBL).YDL()).distributedAsset()) {
@>            IERC20(stablecoin).safeTransferFrom(_msgSender(), IZivoeGlobals_OCC(GBL).YDL(), interestOwed + lateFee);
        }
        else {
            IERC20(stablecoin).safeTransferFrom(_msgSender(), OCT_YDL, interestOwed + lateFee);
        }
        if (principalOwed > 0) { IERC20(stablecoin).safeTransferFrom(_msgSender(), owner(), principalOwed); }
```        
However the transfer of the interest+lateFee will be failed due to the user being blacklisted for the asset and making the function `makePayment`   completely useless for them.

## Impact
User's won't be able to pay interest on behalf of someone else.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L575C14-L602

```solidity
  function makePayment(uint256 id) external nonReentrant {
        require(loans[id].state == LoanState.Active, "OCC_Modular::makePayment() loans[id].state != LoanState.Active");

        (uint256 principalOwed, uint256 interestOwed, uint256 lateFee,) = amountOwed(id);

        emit PaymentMade(
            id, _msgSender(), principalOwed + interestOwed + lateFee, principalOwed,
            interestOwed, lateFee, loans[id].paymentDueBy + loans[id].paymentInterval
        );

        // Transfer interest + lateFee to YDL if in same format, otherwise keep here for 1INCH forwarding.
        if (stablecoin == IZivoeYDL_OCC(IZivoeGlobals_OCC(GBL).YDL()).distributedAsset()) {
            IERC20(stablecoin).safeTransferFrom(_msgSender(), IZivoeGlobals_OCC(GBL).YDL(), interestOwed + lateFee);
        }
        else {
            IERC20(stablecoin).safeTransferFrom(_msgSender(), OCT_YDL, interestOwed + lateFee);
        }
        if (principalOwed > 0) { IERC20(stablecoin).safeTransferFrom(_msgSender(), owner(), principalOwed); }

        if (loans[id].paymentsRemaining == 1) {
            loans[id].state = LoanState.Repaid;
            loans[id].paymentDueBy = 0;
        }
        else { loans[id].paymentDueBy += loans[id].paymentInterval; }

        loans[id].principalOwed -= principalOwed;
        loans[id].paymentsRemaining -= 1;
    }
```    
## Tool used

Manual Review

## Recommendation
Make the users aware about this particular scenario where using a blacklisted address will DoS

**Comment by pseudonaut** [comment]
Not relevant
