### ISSUE TITLE
Timenov - User's rewards can get stuck.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#17]
Timenov

medium

# User's rewards can get stuck.

## Summary
In `ZivoeRewards` and `ZivoeRewardsVesting` users can stake a token though `stake` and `createVestingSchedule` functions. Later on, they can withdraw that token and get other tokens as rewards. Due to the current implementation of `getRewards()` in both contracts, user's rewards can get stuck forever.

## Vulnerability Detail
The `getRewards` function can be called alone or through `fullWithdraw` that will first withdraw and then get the rewards. An internal function `_getRewardAt` will be called for every reward token. How could this be a problem:

1. The reward tokens are USDC, USDT and DAI.
2. User stakes a token.
3. After some time the user want to withdraw and get his rewards.
4. User is in USDC blacklist(this can be before step 1 or in between staking and withdrawing).
5. User will not be able to get any rewards.

## Impact
User's rewards will be stuck forever in the contracts.

## Code Snippet
```solidity
    function fullWithdraw() external {
        withdraw(_balances[_msgSender()]);
        getRewards();
    }
```

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L246-L249
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L370-L373

```solidity
    function getRewards() public updateReward(_msgSender()) {
        for (uint256 i = 0; i < rewardTokens.length; i++) { _getRewardAt(i); }
    }
```

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L281-L283
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L484-L486

```solidity
function _getRewardAt(uint256 index) internal nonReentrant {
        address _rewardsToken = rewardTokens[index];
        uint256 reward = rewards[_msgSender()][_rewardsToken];
        if (reward > 0) {
            rewards[_msgSender()][_rewardsToken] = 0;
            IERC20(_rewardsToken).safeTransfer(_msgSender(), reward);
            emit RewardDistributed(_msgSender(), _rewardsToken, reward);
        }
    }
```

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L287-L295
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L490-L498

## Tool used
Manual Review

## Recommendation
Add parameter `receiver` and send the tokens to that address.

```solidity
    function _getRewardAt(address receiver, uint256 index) internal nonReentrant {
        address _rewardsToken = rewardTokens[index];
        uint256 reward = rewards[_msgSender()][_rewardsToken];
        if (reward > 0) {
            rewards[_msgSender()][_rewardsToken] = 0;
            IERC20(_rewardsToken).safeTransfer(receiver, reward);
            emit RewardDistributed(_msgSender(), _rewardsToken, reward);
        }
    }
```

Duplicate of #13

**Comment by pseudonaut** [comment]
Not relevant
