### ISSUE TITLE
JigglypuffAndPikachu - `OUSD.rebaseOptIn()` is missing for contracts that willl hold `OUSD`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#170]
JigglypuffAndPikachu

medium

# `OUSD.rebaseOptIn()` is missing for contracts that willl hold `OUSD`

## Summary
Contracts like `ZVE_DAO` and `OCT_YDL` will hold `OUSD` but will fail to earn yield as they did not execute `rebaseOptIn()`. 

## Vulnerability Detail
Smart contracts holding `OUSD` is required to explicitly turn on rebasing for the yield generation using `rebaseOptIn()`. 

This is only done for `OCY_OUSD` but not the other contracts like `ZVE_DAO` and `OCT_YDL`, which will also hold `OUSD`. This is evident from the design that `OCY_OUSD` will transfer `OUSD` from its owner (`ZVE_DAO` contract). In addition, `OCY_OUSD` will also forward to `OCT_YDL` for conversion.

```Solidity
    function rebase() public {
        //@audit this is only done for OCY_USD and not ZVE_DAO / OCT_YDL
        IOUSD_OCY_OUSD(OUSD).rebaseOptIn();
    }
```

The docs of `OUSD` has stated,

> If you are using a multi-sig wallet or another smart contract that wishes to participate in the rebasing aspect of OUSD or OETH you must call therebaseOptIn() function.

https://docs.oeth.com/core-concepts/elastic-supply/rebasing-and-smart-contracts

## Impact
As rebasing for OUSD are not turned on for certain contracts, it will cause the protocol to lose any yields from `OUSD`.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_OUSD.sol#L127-L130
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeDAO.sol
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCT/OCT_YDL.sol

## Tool used

Manual Review

## Recommendation
Turn on rebasing for contracts that will hold `OUSD` by calling `rebaseOptIn()`.

**Comment by pseudonaut** [comment]
Not desired
