### ISSUE TITLE
JigglypuffAndPikachu - `OCL_ZVE` profit calculation is wrong

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#171]
JigglypuffAndPikachu

medium

# `OCL_ZVE` profit calculation is wrong

## Summary
`OCL_ZVE` profit calculation is wrong.

## Vulnerability Detail
`OCL_ZVE` allocates capital to a `ZVE/pairAsset` pool for liquidity provisioning, where `pairAsset` is a stablecoin. And it will forward a percentage of the profits from the LP-ing to the `ZivoeYDL` as yield distribution. 

It calculates profit based on its LP share amount of the `pairAsset` within `fetchBasis()`, and proceeds to take profit when its share amount of `pairAsset` increases. This occurs when ZVE price increases (as LP will have more `pairAsset` relative to `ZVE`) and when LP earn swap fees, which will increase LP share amount of both `ZVE` and `pairAsset`. It assumes that the LP is in profit when `ZVE` price increase or when LP share amount of `pairAsset` increases.

The problem is that the LP mainly earn from swap fees. So it is possible to have profit even if `ZVE` price remains constant. On the other hand, LP could also incur losses even if `ZVE` price increases, due to impermanent loss.

Furthermore, it is also possible for the pairAsset (stablecoin) to depeg, resulting in a miscalculation in the actual price of `ZVE`. 

```Solidity
    function fetchBasis() public view returns (uint256 amount, uint256 lp) {
        address pool = IFactory_OCL_ZVE(factory).getPair(pairAsset, IZivoeGlobals_OCL_ZVE(GBL).ZVE());
        uint256 pairAssetBalance = IERC20(pairAsset).balanceOf(pool);
        uint256 poolTotalSupply = IERC20(pool).totalSupply();
        lp = IERC20(pool).balanceOf(address(this));

        //@audit the basis for profit calculation only consider pairAsset value and not total LP value
        amount = lp * pairAssetBalance / poolTotalSupply;
    }
```

## Impact
The wrong profit calculation will cause the yield distribution to be incorrect, leading to loss of yield for the users.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L336-L342

## Tool used

Manual Review

## Recommendation
This can be fixed by calculating profit based on the combined value of both `ZVE` and `pairAsset` for the LP share amount.

**Comment by pseudonaut** [comment]
Profit is only calculated on pairAsset balance at present and is intended accounting system, not desireable to use both (nor feasible given it's making the market for ZVE so deriving price from ZVE is redundant and not based in reality)
