### ISSUE TITLE
0xAnmol - Voting delay in GovernorV2 is extremely short.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#182]
0xAnmol

medium

# Voting delay in GovernorV2 is extremely short.

## Summary
Voting delay in the `GovernorV2` is set to 1 block which is < 15 sec in ETH Mainnet. 15 seconds is very little time for the token holders to delegate their votes and prepare for voting.

## Vulnerability Detail
In  `GovernorV2` initial voting configuration is done. 

```solidity
  constructor(IVotes _token, ZivoeTLC _timelock, address _GBL)
        Governor("ZivoeGovernorV2") GovernorSettings(1, 3600, 100000 ether)
        GovernorVotes(_token) GovernorVotesQuorumFraction(10) ZivoeGTC(_timelock) { GBL = _GBL; }

```

Here in initialization of `GovernorSetting` the first parameter is `votingDelay` which is set to 1 block(<15sec).  The voting delay is used as a time when the voting token holders can delegate token votes and prepare for the upcoming voting. 

It is practically impossible for enough users to delegate and prepare within a voting delay of less than 15 seconds from the proposal time.
## Impact
It is practically impossible for enough users to delegate and prepare within a voting delay of less than 15 seconds from the proposal time.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeGovernorV2.sol#L63
## Tool used

Manual Review

## Recommendation
Increase the voting delay to at least 1 day. I also feel the voting period of 3600 blocks (< 12 hours) is short and it should be at least 1 week

**Comment by pseudonaut** [comment]
1 week before people can vote? No, 1 block is fine
