### ISSUE TITLE
JigglypuffAndPikachu - Excess `ZVE` will be permanently stuck within `ZivoeRewardsVesting`

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#184]
JigglypuffAndPikachu

high

# Excess `ZVE` will be permanently stuck within `ZivoeRewardsVesting`

## Summary
`ZivoeRewardsVesting` lacks a function to retrieve any excess ZVE  that are not claimed after ITO airdrop or revoked from vesting schedule.

## Vulnerability Detail
`ZivoeRewardsVesting` provides ITO airdrop claimers their allocated `vestZVE`, which will earn staking rewards and also vest into `ZVE`.
 
Upon claiming of the airdrops, the `createVestingSchedule()` will ensure that the contract has enough`ZVE` tokens  for the vesting schedule. This means that `ZVE` tokens are pre-transferred into `ZivoeRewardsVesting` before airdrop is live.

```Solidity
    function createVestingSchedule(
        address account, 
        uint256 daysToCliff, 
        uint256 daysToVest, 
        uint256 amountToVest, 
        bool revokable
    ) external onlyZVLOrITO {
     ...
         //@audit this shows that ZVE tokens are pre-transferred into ZivoeRewardsVesting for vesting
        require(
            IERC20(vestingToken).balanceOf(address(this)) - vestingTokenAllocated >= amountToVest, 
            "ZivoeRewardsVesting::createVestingSchedule() amountToVest > vestingToken.balanceOf(address(this)) - vestingTokenAllocated"
        );
```

The problem is that there are no means to withdraw any excess `ZVE` tokens, which will be left stuck within the contract. 

Excess `ZVE` in `ZivoeRewardsVesting` could occur when they are unclaimed by ITO airdrop or when the vesting schedule is revoked.

## Impact
Excess `ZVE` will be permanently locked within contract as there are no means to retrieve them.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L392-L395

## Tool used

Manual Review

## Recommendation
Add a governance function that can retrieve any leftover `ZVE` that are unclaimed from ITO airdorp or revoked from vesting schedule.

**Comment by pseudonaut** [comment]
Not relevant
