### ISSUE TITLE
t0x1c - TLC's update of critical params inside ZivoeYDL get applied retrospectively, causing loss of pending yield

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#188]
t0x1c

medium

# TLC's update of critical params inside ZivoeYDL get applied retrospectively, causing loss of pending yield

## Summary
The yield accrues for `daysBetweenDistributions` inside `ZivoYDL.sol` before it can be claimed by calling [distributeYield()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L216). This pending yield is distributed as per the [contract's parameters](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L89-L107) to various participants in pre-decided proportion. The exact values are calulated via an [internal call](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L232) to the function [earningsTrancheuse()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L447).<br>

The TLC role can update these contract parameters via calls to:
- [updateDistributedAsset()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L356)
- [updateProtocolEarningsRateBIPS()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L375)
- [updateTargetAPYBIPS()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L420)
- [updateTargetRatioBIPS()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L428)
- [updateRecipients()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L392)

All these changes are applied retrospectively to the pending yield yet to be claimed and may even result in complete loss of this yield to the senior & junior tranches along with the other recipients.

## Similar Past Findings
1. Sherlock finding "**[M-5: Update to `managerFeeBPS` applied to pending tokens yet to be claimed](https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/198)**" in the Arrakis contest. _(Alternate Solodit url: [https://solodit.xyz/issues/m-5-update-to-managerfeebps-applied-to-pending-tokens-yet-to-be-claimed-sherlock-none-arrakis-git](https://solodit.xyz/issues/m-5-update-to-managerfeebps-applied-to-pending-tokens-yet-to-be-claimed-sherlock-none-arrakis-git))_

2. Cyfrin finding "**[Update to StratFeeManagerInitializable::beefyFeeConfig retrospectively applies new fees to pending LP rewards yet to be claimed](https://github.com/solodit/solodit_content/blob/main/reports/Cyfrin/2024-04-06-cyfrin-beefy-finance.md#update-to-stratfeemanagerinitializablebeefyfeeconfig-retrospectively-applies-new-fees-to-pending-lp-rewards-yet-to-be-claimed)**" for beefy finance. _(Alternate Solodit url: [https://solodit.xyz/issues/update-to-stratfeemanagerinitializablebeefyfeeconfig-retrospectively-applies-new-fees-to-pending-lp-rewards-yet-to-be-claimed-cyfrin-none-cyfrin-beefy-finance-markdown](https://solodit.xyz/issues/update-to-stratfeemanagerinitializablebeefyfeeconfig-retrospectively-applies-new-fees-to-pending-lp-rewards-yet-to-be-claimed-cyfrin-none-cyfrin-beefy-finance-markdown))_

## Vulnerability Detail
An example scenario:
- `daysBetweenDistributions` is 20 days. The yield has so far accrued for 19.99 days.
- The current `distributedAsset` is DAI. This is the token used to dole out the rewards.
- TLC decides to call (maliciously or otherwise) [updateDistributedAsset()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L356) and changes `distributedAsset` to USDC.
- Now when `distributeYield()` is called at the end of 20 days, the `earnings` variable on [L221](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L221) evaluates to `IERC20(distributedAsset).balanceOf(address(this)) = 0` since there is no USDC balance, only the DAI balance. 
- All pending yield is lost.

- Similarly, `targetAPYBIPS` or `targetRatioBIPS` could have been modified to change the proportion of the yield the senior & junior tranche would have received as per the calculations of [earningsTrancheuse()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L461-L462).

- Even the particpants' list can be changed altogether via [updateRecipients()]([earningsTrancheuse()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L392)), having a retrospective effect.

## Other Code Areas With Same Issue
Similar issue can be found inside:
- `OCE_ZVE.sol` : [updateCompoundingRateBIPS()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCE/OCE_ZVE.sol#L163) and [updateExponentialDecayPerSecond](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCE/OCE_ZVE.sol#L183) have a retrospective effect on [forwardEmissions()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCE/OCE_ZVE.sol#L139).
- `OCL_ZVE.sol` : [updateCompoundingRateBIPS()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L347) has a retrospective effect on [forwardYield()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L311).

## Impact
Loss of yield for the participants of ZivoeYDL.

## Code Snippet
- [https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L221](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L216)
- [https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L461-L462](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L447)

## Tool used
Manual Review

## Recommendation
The current values of contract parameters which are being updated should be stored up until the next call to `distributeYield()` is not made. The new parameter changes should be considered as "pending" till then. Once the call to `distributeYield()` has concluded based on the old values, these "pending" values should then come into effect, overwriting the old ones.

**Comment by pseudonaut** [comment]
Not relevant, intended
