### ISSUE TITLE
eeshenggoh - No Slippage Parameter amount of tokens when removing liquidity causing sandwich attack

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#19]
eeshenggoh

high

# No Slippage Parameter amount of tokens when removing liquidity causing sandwich attack

## Summary
`_forwardYield` is used to forward yield to the YDL in the form of pairAsset. It calls the uniswapv2 to `removeLiquidity` function.
## Vulnerability Detail
The problem lies in hardcoding the minimum amount of tokens to receive as zero. When removing liquidity the minimum amount of 0 output tokens from the swap, opening up to a catastrophic loss of funds via  sandwich attack
```solidity
function _forwardYield(uint256 amount, uint256 lp) private nonReentrant {
-- SNIP--
        (uint256 claimedPairAsset, uint256 claimedZVE) = IRouter_OCL_ZVE(router).removeLiquidity(
            pairAsset, ZVE, lpBurnable, 0, 0, address(this), block.timestamp + 14 days
        );
-- SNIP--
```
## Impact
Lesser LP tokens will be received causing the protocol to lose the assets.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L316C1-L317C21
## Tool used

Manual Review

## Recommendation
Add minimum return amount checks.
Accept a function parameter that can be chosen by the transaction sender, then check that the actually received amount is above this parameter.

Duplicate of #146

**Comment by pseudonaut** [comment]
Not relevant, will use flash-bots
