### ISSUE TITLE
0xboriskataa - ZivoeDAO does not have control over the capital in `OCC_Modular`

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#190]
0xboriskataa

high

# ZivoeDAO does not have control over the capital in `OCC_Modular`

## Summary
The `OCC_Modular` locker is going to be used to lend out stablecoin loans to borrowers. It will receive these stablecoins from the `ZivoeDAO` contract according to the documentation:
>To originate a loan through Zivoe, the DAO must first allocate capital to one of these credit lockers via a governance proposal. The DAO can also pull capital from a locker if it is not satisfied with the way the underwriter is originating loans.  This ensures that the DAO retains full control of its capital. 

## Vulnerability Detail
To push or pull capital from lockers the `ZivoeDAO` has `push()` and `pull()` functions and some variations of them. However in order to use these, the locker must implement it's corresponding `pushToLocker()` and `pullFromLocker()` functions. . Here's the code for `push()` in `ZivoeDAO` with the important lines commented out (the same principals apply for `pull()` functions too):
```solidity
function push(address locker, address asset, uint256 amount, bytes calldata data) external onlyOwner nonReentrant {
        require(IZivoeGlobals_DAO(GBL).isLocker(locker), "ZivoeDAO::push() !IZivoeGlobals_DAO(GBL).isLocker(locker)");
//@>        require(ILocker_DAO(locker).canPush(), "ZivoeDAO::push() !ILocker_DAO(locker).canPush()");
        emit Pushed(locker, asset, amount, data);
        IERC20(asset).safeIncreaseAllowance(locker, amount);
//@>        ILocker_DAO(locker).pushToLocker(asset, amount, data);
        if (IERC20(asset).allowance(address(this), locker) > 0) { IERC20(asset).safeDecreaseAllowance(locker, 0); }
    }
```
As we can see we first check that the locker function `canPush()` returns true meaning the locker has given permission to the DAO to push capital to it.

After that the function `pushToLocker()` is called on the locker that we want to push capital to. If the locker hasn't implemented that function this will not work. That is exactly the case for  `OCC_Modular` which implements `canPush()`, `canPull()`, `canPullPartial()` which all return true but it does not implement `pushToLocker()`, `pullFromLocker()` and `pullFromLockerPartial()`:
```solidity
    /// @notice Permission for owner to call pushToLocker().
    function canPush() public override pure returns (bool) { return true; }

    /// @notice Permission for owner to call pullFromLocker().
    function canPull() public override pure returns (bool) { return true; }

    /// @notice Permission for owner to call pushToLockerPartial().
    function canPullPartial() public override pure returns (bool) { return true; }
```

This means that the `ZivoeDAO` has no control over the capital in `OCC_Modular` but it should according to the documentation. It cannot send capital to  `OCC_Modular` nor pull from it. It can only receive capital when borrowers pay out their loans.

## Impact
`ZivoeDAO` MUST have control over the capital in `OCC_Modular` but it doesn't.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeDAO.sol#L244
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeDAO.sol#L258
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeDAO.sol#L273
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol/#L392-L399

## Tool used

Manual Review

## Recommendation
Implement `pushToLocker()`, `pullFromLocker()` and `pullFromLockerPartial()` in `OCC_Modular`

**Comment by pseudonaut** [comment]
Intended
