### ISSUE TITLE
0xboriskataa - No governance proposals can be made because of missing functions

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#192]
0xboriskataa

medium

# No governance proposals can be made because of missing functions

## Summary
`ZivoeGovernorV2.sol` has the following internal functions for governance: `_execute()`, `_cancel()` and `_getVotes()`

## Vulnerability Detail
In order to call these functions there should be external functions that call these internal ones. However such external functions do not exist in the contract.

## Impact
Governance proposal cannot be made due to missing functionality.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGovernorV2.sol#L123
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGovernorV2.sol#L134
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGovernorV2.sol#L144

## Tool used

Manual Review

## Recommendation
Implement the needed external functions call call these internal ones.

**Comment by pseudonaut** [comment]
Not valid
