### ISSUE TITLE
JigglypuffAndPikachu - Ineffective Deadline Check

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#194]
JigglypuffAndPikachu

medium

# Ineffective Deadline Check

## Vulnerability Detail

The deadline is set to to `block.timestamp + 14 days` which they intended to be 14 days after the transaction is submitted. However `block.timestamp` is the time transaction is accepted into a block, not when it is submitted, so the deadline check doesn't work 

## Impact

The deadline check doesn't work

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L205

## Tool used

Manual Review

## Recommendation

Allow deadline check to be selected by the user through input parameters.

Duplicate of #144

**Comment by pseudonaut** [comment]
To be fair we're not interested in enforcing this so if `block.timestamp` is acceptable we would use it, although we'll need at least more than that presumably
