### ISSUE TITLE
0xboriskataa - Incorrect initial value for `upperRatioIncentiveBIPS`

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#196]
0xboriskataa

medium

# Incorrect initial value for `upperRatioIncentiveBIPS`

## Summary
In the `ZivoeTranches.sol` contract there is a function that can be used to update the `upperRatioIncentiveBIPS` variable.

## Vulnerability Detail
This function has the following check:
```solidity
function updateUpperRatioIncentiveBIPS(uint256 _upperRatioIncentiveBIPS) external onlyGovernance {
      //...
        require(
            _upperRatioIncentiveBIPS <= 2500, 
            "ZivoeTranches::updateUpperRatioIncentiveBIPS() _upperRatioIncentiveBIPS > 2500"
        );
        emit UpdatedUpperRatioIncentiveBIPS(upperRatioIncentiveBIPS, _upperRatioIncentiveBIPS);
        upperRatioIncentiveBIPS = _upperRatioIncentiveBIPS; 
    }
```
From that check we can assume that the maximum value `upperRatioIncentiveBIPS` should have is 2500. 

However the variable's initial value is set to 3500
```solidity
uint256 public upperRatioIncentiveBIPS = 3500;
```

## Impact
The calculations of rewards will not be as intended because they use `upperRatioIncentiveBIPS`

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol/#L81
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol/#L395-L398

## Tool used

Manual Review

## Recommendation
Set the initial value for the variable to 2500 or change the require statement in `updateUpperRatioIncentiveBIPS()`

**Comment by pseudonaut** [comment]
Fair, we do intend to lower this
