### ISSUE TITLE
JigglypuffAndPikachu - Wrong Slippage Parameters

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#197]
JigglypuffAndPikachu

high

# Wrong Slippage Parameters

## Summary

The slippage parameters do not effectively prevent liquidity deposit frontrunning attacks.

## Vulnerability Detail

They set slippage based on the token ratio in the OCE_ZVL locker. Instead, the slippage should be based on an acceptable token ratio which corresponds to a token exchange rate in the Uniswap v2 pool. Usually, the slippage `minAmountIn` is selected by the user, but some protocols this is done with a short TWAP of the past reserves. Additionally, even if they intended to use the balances of the OCE_ZVL contract the hardcoded 10% slippage is far too high.

```solidity
        (uint256 depositedPairAsset, uint256 depositedZVE, uint256 minted) = IRouter_OCL_ZVE(router).addLiquidity(
            pairAsset, 
            ZVE, 
            balPairAsset,
            balZVE, 
            //slippage parameters here
            (balPairAsset * 9) / 10,
            (balZVE * 9) / 10, 
            address(this), block.timestamp + 14 days
        );
```

## Impact

Liquidity deposits lose money to frontrunning/MEV attacks.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L198-L206

## Tool used

Manual Review

## Recommendation

Set `minAmountIn` of the two tokens as input parameters.

**Comment by pseudonaut** [comment]
10% is acceptable, it can be mitigated by flash-bots at any rate
