### ISSUE TITLE
pivanov - [ZivoeDAO.sol] - Excessive Permissions Granted to External Contracts

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#2]
pivanov

high

# [ZivoeDAO.sol] - Excessive Permissions Granted to External Contracts

## Summary
The `ZivoeDAO` contract grants and does not revoke excessive permissions to external locker contracts for ERC1155 asset management, introducing a significant security vulnerability.

## Vulnerability Detail
In its current implementation, `ZivoeDAO` uses `setApprovalForAll` to grant unlimited approval to external lockers for ERC1155 token operations. This approval remains even after the intended operations are completed, leaving the DAO's ERC1155 assets vulnerable to unauthorized transfers by these lockers at any future point.

## Impact
This oversight allows potentially malicious or compromised lockers unrestricted access to move any of the DAO's ERC1155 assets without subsequent approval. Such a scenario could lead to significant asset loss or manipulation, undermining the DAO's asset integrity and security.

## Code Snippet
See the related code segment [here](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeDAO.sol#L442-L443)
```solidity
IERC1155(asset).setApprovalForAll(locker, true);
ILocker_DAO(locker).pushToLockerERC1155(asset, ids, amounts, data);
// Currently missing: Revocation of the granted permission post-operation
```

## Tool used
Manual Review

## Recommendation
To mitigate this risk, the DAO should adopt a secure pattern that revokes any granted permissions immediately after their necessity concludes. This can be achieved by calling `setApprovalForAll(locker, false)` post-interaction to ensure no residual permissions are left open. Alternatively, for more granular control, employing safeTransferFrom for individual transfers can avoid the need for such broad permissions entirely. Here's how the adjustments might look:

```solidity
// After completing the pushToLockerERC1155 operation
IERC1155(asset).setApprovalForAll(locker, false);

// Or, opting for a more secure transfer mechanism
IERC1155(asset).safeTransferFrom(address(this), locker, id, amount, data);
```

Implementing these changes will significantly bolster the security around ERC1155 asset management, ensuring the DAO retains strict control over its asset permissions and mitigating the risk of unauthorized asset manipulation.

**Comment by pseudonaut** [comment]
We follow a standard approve -> allow downstream locker to manage assets from there
Isolating this isn't possible with ERC1155s as it is with ERC20s/ERC721s so acceptable implementation is as is to setApprovalForAll for specified ERC1155
