### ISSUE TITLE
JigglypuffAndPikachu - Remaining Allowance Greater Than Zero After Sending to Uniswap Router

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#200]
JigglypuffAndPikachu

high

# Remaining Allowance Greater Than Zero After Sending to Uniswap Router

## Summary

When sending tokens to the Uniswap v2 Router, the approved amount differs from the amount sent. This will cause the `OCE_ZVE#addLiqiudity` function to almost always revert.

## Vulnerability Detail

Ziove increases the allowance of the Uniswap v2 router to match the balance of ZVE and pairAsset in the OCE_ZVL contract. The same amounts are also passed in as the `amountADesired` and `amountBDesired` parameters in `IRouter_OCL_ZVE` which is the interface for a Uniswap v2 Router.

```solidity
        IERC20(pairAsset).safeIncreaseAllowance(router, balPairAsset);
        IERC20(ZVE).safeIncreaseAllowance(router, balZVE);
```

The issue is that, in UniV2: the `amountADesired` is not the actual amount that is ultimately `safeTransfer`ed from the contract. Instead, in [UniswapV2Router02#addLiquidity](https://github.com/Uniswap/v2-periphery/blob/0335e8f7e1bd1e8d8329fd300aea2ef2f36dd19f/contracts/UniswapV2Router02.sol#L61) a liquidity deposit is simulated and [the amount actually transferred is between `amountAMin` and `amountADesired`](https://github.com/Uniswap/v2-periphery/blob/0335e8f7e1bd1e8d8329fd300aea2ef2f36dd19f/contracts/UniswapV2Router02.sol#L71-L74).  This discrepancy occurs because the proportion of tokens deposited into Uniswap must align with the proportion of tokens already in the pool, which typically differs from the token ratio specified in the OCE_ZVL contract. 

Since the full balance is not transferred, there remains an allowance to the Uniswap v2 router, leading to the failure of these assertions:

```solidity
assert(IERC20(pairAsset).allowance(address(this), router) == 0);
assert(IERC20(ZVE).allowance(address(this), router) == 0);
```

## Impact

The `addLiqudity` function will basically always revert, unless the amount of tokens in `OCE_ZVL` exactly matches the pool reserves, which would be uncommon as there is zero margin for error.

## Code Snippet

https://github.com/Uniswap/v2-periphery/blob/0335e8f7e1bd1e8d8329fd300aea2ef2f36dd19f/contracts/UniswapV2Router02.sol#L71-L74

## Tool used

Manual Review

## Recommendation

Removing the 2 `assert` statements will fix the issue.

Duplicate of #18

**Comment by pseudonaut** [comment]
Valid, have other ideas for fix
