### ISSUE TITLE
JigglypuffAndPikachu - Basis Uses BalanceOf Rather Than Internal Reserves Accounting Of Uniswap v2

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#202]
JigglypuffAndPikachu

high

# Basis Uses BalanceOf Rather Than Internal Reserves Accounting Of Uniswap v2

## Summary

The `balanceOf(usdc)` can be manipulated without changing the `reserves[usdc]` which allows frontrunners to manipulate the basis. 

This issue writeup also explains why an apparent vulnerability swapping through the pool to inflate the yield won't work, which makes `balanceOf` manipulation necessary for a profitable attack.

## Vulnerability Detail

In `UniswapV2Pair#mint` or `swap`, [the `balanceOf - reserves` is counted as the caller's token deposit](https://github.com/Uniswap/v2-core/blob/ee547b17853e71ed4e0101ccfd52e70d5acded58/contracts/UniswapV2Pair.sol#L111-L115). After the mint/swap, [the `reserve` is synced with the `balanceOf`](https://github.com/Uniswap/v2-core/blob/ee547b17853e71ed4e0101ccfd52e70d5acded58/contracts/UniswapV2Pair.sol#L82-L83).

Usually, minting is executed via a router, but this is not necessarily the case. By frontrunning `forwardYield()` by sending `USDC` to the Uniswap pool, the the `balanceOf(usdc)` will return a value greater than the actual USDC in reserves (`reserves[usdc]`) which inflates the `basis`. After `forwardYield` is complete, the frontrunner can get their USDC back by also sending ZVE such that the USDC and ZVE deposit matches the pool ratio, `mint` liqudidity, and then immediately burn their minted liquidity.

The frontrunning sequence:

1. Send USDC and ZVE proportional to the Uniswap pool
2. `forwardYield` is called. The basis calculated is `balanceOf(usdc)` which is `reserves[usdc]` + the tokens you just sent to the pool.
3. When liquidity is removed, the internal `reserves[usdc]` is used to determine the ratio of tokens out, which is out of sync with what Zivoe expected since they used `balanceOf[usdc]`
4. Send ZVE into the contract and call `mintLiquidity`
6. You can instantly remove liquidity after and get all your USDC and ZVE from step 1 back.

**Why the forwardYield Frontrunning Wont Work With A Swap Manipulation**

There appears to be a way to inflate `basis` simply by sandwiching a call to `forwardYield()` with a swap which increases the USDC amount in the reserves and then rebalancing the pool afterwards. The problem with this attack vector is that any time you inflate `amount(usdc)` to be greater than `basis`, liquidity is removed from to `USDC/ZVE` Uniswap pool. When liquidity is removed before the attacker swaps back, **the attacker suffers a large loss of funds due their rebalancing swap going through a lower amount of liquidity than their pool manipulation swap** 

Here's a general heuristic:

If 
1. attacker manipulates pool
2. user deposits liquidity
3. attacker swaps back

The attacker gains $ by rebalancing the pool through a greater amount of liquidity than they manipulated through.

In a scenario where:

1. attacker manipulates pool
2. user **removes** liquidity
3. attacker swaps back

The attacker **loses** $ by rebalancing the pool through a greater amount of liquidity than they manipulated through.

Which is why the `balanceOf` manipulation allows a frontrunning attack that is not possible using just a `swap` manipulation to change the reserves:

## Impact

Basis can be manipulated changing the internal reserves of Uniswap v2 to force `OCE_ZVL` to overdistribute rewards

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L338

## Tool used

Manual Review

## Recommendation

Use [`getReserves`](https://github.com/Uniswap/v2-core/blob/ee547b17853e71ed4e0101ccfd52e70d5acded58/contracts/UniswapV2Pair.sol#L38-L42) to fetch the reserves rather than the `balanceOf` the token

Duplicate of #296

**Comment by pseudonaut** [comment]
Not of concern, also the description says the vulnerability isn't possible due to financial losses
