### ISSUE TITLE
Tendency - Users Never Lose Their Assigned Weight After Their Vesting Schedule is Revoked

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#204]
Tendency

high

# Users Never Lose Their Assigned Weight After Their Vesting Schedule is Revoked

## Summary
When a revokeable vesting schedule is revoked in [ZivoeRewardsVesting::revokeVestingSchedule](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L429-L467) function, only the current user withdrawable amount is deducted from the user stored weight, while the user balance is defaulted to zero, thus leaving the user with voting weight in the contract without any vested ZVE or balance. 
## Vulnerability Detail
Assuming the ZVL intends to create a 500 ZVE revokeable vesting schedule for a user, the ZVL will call [ZivoeRewardsVesting::createVestingSchedule](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L381-L425) function to create the schedule for the user. Here, the user's balance and weight will be incremented:
```solidity
_writeCheckpoint(_checkpoints[account], _add, amount);
```
i.e. User weight = 1,000

Assuming half the vesting duration passes by and the user hasn't yet claimed/withdrawn his now withdrawal 500 ZVE, but the ZVL decides to revoke/end the user vesting schedule, [ZivoeRewardsVesting::revokeVestingSchedule](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L429-L467) function will be called, in `revokeVestingSchedule`, the user now withdrawable amount is stored here:
```solidity
  uint256 amount = amountWithdrawable(account);
```
Remember the user currently has 1,000 weight, this weight is equivalent to how much ZVE the user has vested in `ZivoeRewardsVesting` contract, but currently, when the user schedule is revoked, only the withdrawable amount is deducted from the user's current weight.
```solidity
    _writeCheckpoint(_checkpoints[account], _subtract, amount);
```
i.e. user weight = 1,000 - 500 ==> 500
thus still leaving the user with a weight of 500 in the contract, while the user has a balance of zero and no vested ZVE.
The user received/claimed 500 ZVE is equivalent to a weight of 500 in `ZivoeToken` contract, the user will now thus, have a combined 1,000 weight in the general system.

Assuming the user delegates his 500 weight in ZVE token contract to himself, [ZivoeGovernorV2::_getVotes](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeGovernorV2.sol#L144-L152) will wrongly return 1,000 weight/votes for this user, when the user only owns 500 ZVE
```solidity
    function _getVotes(
        address account,
        uint256 blockNumber,
        bytes memory /*params*/
    )
        internal
        view
        virtual
        override(Governor, GovernorVotes)
        returns (uint256)
    {
        return
            token.getPastVotes(account, blockNumber) +
            IZivoeRewardsVesting_ZVG(IZivoeGlobals_ZVG(GBL).vestZVE())
                .getPastVotes(account, blockNumber) +
            IZivoeRewards_ZVG(IZivoeGlobals_ZVG(GBL).stZVE()).getPastVotes(
                account,
                blockNumber
            );
    }
```

## Impact
Users never lose their initial assigned weight even after their schedule is ended/revoked, this gives the user an unfair advantage during voting actions, since even if the user transfers out the claimed 500 ZVE tokens, the user still never loses his 500 voting power/weight in `ZivoeRewardsVesting` contract.
## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L429-L467

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L381-L425

## Tool used

Manual Review

## Recommendation
Deduct the user-stored balance from the user weight instead, since both the user balance and weight in `ZivoeRewardsVesting` contract are intended to be zero after this action.

Duplicate of #118

**Comment by pseudonaut** [comment]
Valid, need to update accounting there
