### ISSUE TITLE
JigglypuffAndPikachu - Senior Proportion of is Capped at 100% When in Fact (Senior + Junior) Proportion Is Meant to be Capped at 100%

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#210]
JigglypuffAndPikachu

high

# Senior Proportion of is Capped at 100% When in Fact (Senior + Junior) Proportion Is Meant to be Capped at 100%

## Summary

When there is no residual yield, 100% yield distributed is meant to be given to the Senior and Junior Tranches based on the predetirmned ratio. However, the yield is allocated 100% to senior tranche instead in some cases.

## Vulnerability Detail

During a yield shortfall, the actual yield is meant to be split based on the same ratio as if the yield target was split. Eg if target yield of junior tranche should be 1.5x senior tranche, this should still be true in shortfall. The sponsor confirmed that this in discord thread. We can clearly see in this quote from the [Mathematics section of the Zivoe documentation](https://docs.zivoe.com/user-docs/yield-distribution/mathematics), that it is `seniorProportion + juniorProportion` that should be capped at 100% not just senior proportion:

> Furthermore, we ensure the maximum value returned is relative to the value of sP given that the **invariant sP + jP <= RAY** must be enforced"

This is the basis for the 2 formulas in `seniorProportion`.

The logic of `.min(RAY)` at the end of the formula is that if the proportion required to hit the target yield of the senior tranche cannot be met, then all the tokens will be given to the `senior tranche`.

This is incorrect as it breaks the intention of splitting to junior tranche. Instead, the `min` should not be RAY, but an amount less than `RAY` which ensures that all of the yield is split between the junior and senior tranches according to the intended ratio.

The true maximum amount should be less than 1, because there should always be leftover for the junior tranche.

```solidity
function seniorProportionBase(uint256 yD, uint256 eSTT, uint256 Y, uint256 T) public pure returns (uint256 sPB) {

    //@audit-info yield target/yield distributed

    sPB = ((RAY * Y * (eSTT) * T / BIPS) / 365).floorDiv(yD).min(RAY);

}
```

## Impact

The senior tranche gets 100% of the yield when the intention is to split it between the senior and junior tranche.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeMath.sol#L106-L108

## Tool used

Manual Review

## Recommendation

The cap should be `1 /  (1 + Q)` scaled by `RAY` rather than just `RAY`. For example if the junior tranche should get 20% of senior tranche's yield, then out of the yield distributed, `83.33%` should go to senior and` 16.67%` should go to junior.

**Comment by pseudonaut** [comment]
Not valid, misinterpretation of min() function, it takes the min of the two compared variables
