### ISSUE TITLE
JigglypuffAndPikachu - Applying Combine on Thursday 0:00 to Saturday 0:00 Gives A Week of Interest Free Loans

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#212]
JigglypuffAndPikachu

medium

# Applying Combine on Thursday 0:00 to Saturday 0:00 Gives A Week of Interest Free Loans

## Summary

The grace period for initialising loans is incorrectly applied to combining loans, which allows borrowers that combine a loan to gain a week of interest free loans.

## Vulnerability Detail

When combining loans, one can get an extra interest free period by combining on Thursday-Friday. Loans repayments are always due on end of Friday, or `Saturday 0:00` UTC time. When combining loans [the same grace period of up to 9 days](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L803-L806) is given to calculate the next first repayment time which can be abused to give an extra week of interest free loans.

```solidity
block.timestamp - block.timestamp % 7 days + 9 days + paymentInterval
```

For example, you have a loan payment coming on the upcoming end of Friday. If the time is `23:59 Wednesday`, and you `applyCombine()`, the loans repayment is also on `Saturday 0:00` of **this week**, the same as before. However, if you combine on `Thursday 0:01`, your next repayment is **next week** at`Saturday 0:00`, and up until that point your loan is interest free. This is despite the two times of calling `applyCombine()` being only 2 minutes apart. Note that the borrower can call `applyCombine()` up to 72 hours after it is approved

This is a problem as combining loans should not give any extra interest free days.

## Impact

Borrowers can get a week extra of interest free loans by correctly timing the call to `applyCombine()`

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L803-L807

## Tool used

Manual Review

## Recommendation

In `applyCombine()`, the first repayment should have a partial repayment applied for the time the loan is combined and to the loan time the first payment interval

**Comment by pseudonaut** [comment]
Intended
