### ISSUE TITLE
Tendency - Interest Isn't Charged When Combining a Loan

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#216]
Tendency

high

# Interest Isn't Charged When Combining a Loan

## Summary
Due to not paying off the loan ids current term interests during loan ids combination, interest is lost during each combination, and this could be further gamed to avoid paying interests while borrowing.
## Vulnerability Detail
In `OCC_Modular` contract, a borrower's loan ids can be combined by the underwriter via a call to [OCC_Modular::approveCombine](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L877-L905) function, then the approved combination can then be applied by the borrower, via a call to [OCC_Modular::applyCombine](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L742-L808) function, the problem here is that, using these functionalities, a user can successfully borrow a loan for an extended interval without paying any interest.

+ To Illustrate

The borrower will apply for two loans with the same interval, let's say 7 days, in which the underwriter will call [OCC_Modular::createOffer](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L540-L570), to create the loan offer, to later be accepted by the borrower via [OCC_Modular::acceptOffer](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L461-L487).
On the 6th day, the borrower will then apply to combine his loan ids, with the same 7-day interval, and also apply to create another loan. If his combination is approved, and a new loan offer is created, he can combine his approved loan ids via a call to [OCC_Modular::applyCombine](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L742-L808) and accept the loan offer by calling [OCC_Modular::acceptOffer](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L461-L487), the successful combination of these loan ids thus allows the borrower to skip paying any interests for both his loans intervals. The borrower can repeat the action of creating and combining loans as long as it is approved, hence going many terms without paying any interest, to only pay interest on the last interval when he decides to clear off his loan.

## Impact
+ Loss of yield: Since the interests accrued here are sent to `OCT_YDL` locker contract, which will later be forwarded to `ZivoeYDL` contract, to reward the senior and junior tranche stakers.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L742-L808

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L540-L570

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L877-L905
## Tool used

Manual Review

## Recommendation
The borrower should pay off the loan ids current term/interval interests before combining the loan ids, or add the interests to the notional

Duplicate of #95

**Comment by pseudonaut** [comment]
Known and not of concern
