### ISSUE TITLE
Tendency - Undoing Already Approved Actions Could Be Impossible

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#217]
Tendency

medium

# Undoing Already Approved Actions Could Be Impossible

## Summary
The available functions to undo the underwriter's previously approved actions will mostly not function as intended, due to frontrunning.
## Vulnerability Detail
The below functions in `OCC_Modular` are meant to be called by the underwriter to undo a previously done action, but all of these actions are subject to frontrunning attack, since a user could quickly pay more gas to get the action approved before it's defaulted/unapproved by the underwriter.

These are the affected functions in `OCC_Modular`:

[unapproveCombine](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L939-L942)

[unapproveConversionToAmortization](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L946-L949)

[unapproveConversionToBullet](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L953-L956)

[unapproveExtension](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L960-L963)

[unapproveRefinance
](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L967-L970)

## Impact
Trying to undo  an already approved action could be impossible
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L939-L942

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L742
## Tool used

Manual Review

## Recommendation
Consider adding a wait/cooldown period to these functions, to allow the underwriter to undo these actions successfully if need be, within a certain time frame.

**Comment by pseudonaut** [comment]
Not relevant
