### ISSUE TITLE
JigglypuffAndPikachu - Late Fees Are Charged Multiple Times Over Payment Intervals

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#223]
JigglypuffAndPikachu

high

# Late Fees Are Charged Multiple Times Over Payment Intervals

## Summary

When a loan is overdue, and the overdue duration spans over multiple payment intervals, their late fees are overcharged.

## Vulnerability Detail

In `OCCModular#amountOwed`, the `lateFee` is scaled based on `(block.timestamp - loans[id].paymentDueBy)`. therefore, after the first repayment, the payer has completely payed for all the late fees from the `paymentDueBy` to the current timestamp. We should not expect the user to have to pay any more late fees for the period between the past `paymentDueBy` to now (`block.timestamp`)

After this payment, `paymentDueBy` is increased by the `paymentInterval`. The problem arises when the new `paymentDueBy` is before `block.timestamp`.  This occurs when the lateness of the payment spans multiple payment intervals. This case is expected to happen as shown by [the documentation](https://docs.zivoe.com/user-docs/borrowers/how-do-defaults-work):

> In some cases, the grace period may be longer than the payment interval, and the borrower may miss several loan payments before a loan enters default. 

In this case, when the borrower call `processPayment` again, they still are charged from the `lateFees` from the new `paymentDueBy` to `block.timestamp`, even though those late fees were already paid. As a result, the borrower has to pay multiple times what of the `lateFee` they actually owe.

## Impact

The borrower has to pay multiple times what of the `lateFee` they actually owe if their repayment is later by more than 1 payment interval.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L451-L454

## Tool used

Manual Review

## Recommendation

When the new payment period is not after `block.timestamp`, only late fee up to the next payment period. The rest of the late fees can be charged when the borrower repays the other late payment intervals.

**Comment by Banditx0x** [comment]
Escalate on behalf of JigglypuffAndPikachu.

I believe there is a technical misunderstanding in evaluating this issue. Yes, each payment has a seperate lateFee. The key issue is the fee payment is multiplied by `block.timestamp - paymentEndDate`. When this exceeds 1 payment interval, the late fees are overcharged when iterated over the seperate lateFee charges. The `block.timestamp - paymentEndDate` should actually be `min(block.timestamp - paymentEndDate, paymentInterval)`

**Comment by sherlock-admin3** [comment]
> Escalate on behalf of JigglypuffAndPikachu.
> 
> I believe there is a technical misunderstanding in evaluating this issue. Yes, each payment has a seperate lateFee. The key issue is the fee payment is multiplied by `block.timestamp - paymentEndDate`. When this exceeds 1 payment interval, the late fees are overcharged when iterated over the seperate lateFee charges. The `block.timestamp - paymentEndDate` should actually be `min(block.timestamp - paymentEndDate, paymentInterval)`

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by panprog** [comment]
I don't think it's correct, the late fees are charged separately for each missed payment, so if 2 payments are missed - late fees are charged twice, which is intended.

**Comment by panprog** [comment]
Asked the sponsor to confirm the intentions again and the response is that it's intended.

**Comment by ZdravkoHr** [comment]
This escalation will probably be rejected, but in case it is approved, please note that #25 is a duplicate.

**Comment by WangSecurity** [comment]
Agree with the lead judge that it's an intended design to repay all the missed payments separately and late fees are intended to be charged for each missed repayment.

Planning to reject the escalation and leave the issue as it is.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [banditx0x](https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/223/#issuecomment-2106423403): rejected
