### ISSUE TITLE
0xAnmol - Creating a new governance proposal can be prevented by anyone

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#224]
0xAnmol

medium

# Creating a new governance proposal can be prevented by anyone

## Summary
Governal proposal creation may be blocked because of frontrunning. 
## Vulnerability Detail
The project is using the old v4.8.0 of openzeppelin where there was a problem of proposal frontrunning. Rather than describing the issue by myself please refer to the bug description by OZ [here](https://github.com/OpenZeppelin/openzeppelin-contracts/security/advisories/GHSA-5h3x-9wvq-w4m2)
## Impact
By frontrunning the creation of a proposal, an attacker can become the proposer and gain the ability to cancel it. The attacker can do this repeatedly to try to prevent a proposal from being proposed at all.

## Code Snippet
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/4e5b11919e91b18b6683b6f49a1b4fdede579969/contracts/governance/Governor.sol#L245C5-L285C1
## Tool used

Manual Review

## Recommendation
Please use the latest version of OZ.

**Comment by pseudonaut** [comment]
Our Governor contract is controlled by ZivoeTLC (TimelockController) and prevents proposer from cancelling their own proposal, not valid

**Comment by pokhrelanmol** [comment]
Escalate

The chat conversation in Discord has indicated that all frontrunning problems, excluding keepers transactions are considered valid. I firmly believe that both the propose and cancel transactions will originate from users, making them susceptible to frontrunning. You can find the specific conversation in this Discord channel: [Link](https://discord.com/channels/812037309376495636/1226909446891110512/1227656897545371658)]. I'm aware that the discord chat is not considered valid in escalation but I do not have any other reference point at the moment.

Furthermore, I confidently assert that this issue falls within the scope of the Sherlock rule, which states that if a vulnerability exists in a library and affects an in-scope contract utilizing that library, it is considered a valid issue. You can refer to the documentation here for more information on the Sherlock rule: https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid:~:text=In case the vulnerability exists in a library and an in-scope contract uses it and is affected by this bug this is a valid issue.

It's worth noting that in previous Sherlock contests, issues of this nature were classified as medium severity. For an in-depth conversation on the validity of these types of issues, please refer to the past discussion [Here](https://github.com/sherlock-audit/2023-07-kyber-swap-judging/issues/25).

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> The chat conversation in Discord has indicated that all frontrunning problems, excluding keepers transactions are considered valid. I firmly believe that both the propose and cancel transactions will originate from users, making them susceptible to frontrunning. You can find the specific conversation in this Discord channel: [Link](https://discord.com/channels/812037309376495636/1226909446891110512/1227656897545371658)]. I'm aware that the discord chat is not considered valid in escalation but I do not have any other reference point at the moment.
> 
> Furthermore, I confidently assert that this issue falls within the scope of the Sherlock rule, which states that if a vulnerability exists in a library and affects an in-scope contract utilizing that library, it is considered a valid issue. You can refer to the documentation here for more information on the Sherlock rule: https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid:~:text=In case the vulnerability exists in a library and an in-scope contract uses it and is affected by this bug this is a valid issue.
> 
> It's worth noting that in previous Sherlock contests, issues of this nature were classified as medium severity. For an in-depth conversation on the validity of these types of issues, please refer to the past discussion [Here](https://github.com/sherlock-audit/2023-07-kyber-swap-judging/issues/25).

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by pokhrelanmol** [comment]
This is my first sherlock contest so I think I do not have the power to create an escalation. commenting instead.

The chat conversation in Discord has indicated that all frontrunning problems, excluding keepers transactions are considered valid. I firmly believe that both the propose and cancel transactions will originate from users, making them susceptible to frontrunning. You can find the specific conversation in this Discord channel: [Link](https://discord.com/channels/812037309376495636/1226909446891110512/1227656897545371658)]. I'm aware that the discord chat is not considered valid in escalation but I do not have any other reference point at the moment.

Furthermore, I confidently assert that this issue falls within the scope of the Sherlock rule, which states that if a vulnerability exists in a library and affects an in-scope contract utilizing that library, it is considered a valid issue. You can refer to the documentation here for more information on the Sherlock rule: https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid:~:text=In case the vulnerability exists in a library and an in-scope contract uses it and is affected by this bug this is a valid issue.

It's worth noting that in previous Sherlock contests, issues of this nature were classified as medium severity. For an in-depth conversation on the validity of these types of issues, please refer to the past discussion https://github.com/sherlock-audit/2023-07-kyber-swap-judging/issues/25.

**Comment by pokhrelanmol** [comment]
The chat conversation in Discord has indicated that all frontrunning problems, excluding keepers transactions are considered valid. I firmly believe that both the propose and cancel transactions will originate from users, making them susceptible to frontrunning. You can find the specific conversation in this Discord channel: [Link](https://discord.com/channels/812037309376495636/1226909446891110512/1227656897545371658)]. I'm aware that the discord chat is not considered valid in escalation but I do not have any other reference point at the moment.

Furthermore, I confidently assert that this issue falls within the scope of the Sherlock rule, which states that
```shell
 if a vulnerability exists in a library and affects an in-scope contract utilizing that library, it is considered a valid issue.
```
In docs section **Sherlock's standards: point 7.2**

 You can refer to the documentation here for more information on the Sherlock rule: https://docs.sherlock.xyz/audits/judging/judging#:~:text=the%20contest%20README.-,Contract%20Scope%3A,-If%20a%20contract

It is worth noting that in previous Sherlock contests, issues of this nature were classified as medium severity. For an in-depth conversation on the validity of these types of issues, please refer to the past discussion https://github.com/sherlock-audit/2023-07-kyber-swap-judging/issues/25.

**Comment by panprog** [comment]
Actually, the OZ vulnerability is in 4.9.0, read the issue reference in the bug description:
> The vulnerability was introduced [on Jan 26, 2023](https://github.com/OpenZeppelin/openzeppelin-contracts/commit/5e28952cbdc0eb7d19ee62580ab31b30c2376e48) and was part of the [latest OZ release 4.9.0](https://github.com/OpenZeppelin/openzeppelin-contracts/releases/tag/v4.9.0)

If you check the 4.9.0 Governor code, you'll see public `cancel` function, which is the reason of the bug. In 4.8.0 there is no public `cancel` function, so no such bug.
