### ISSUE TITLE
t0x1c - Neither approveCombine() nor applyCombine() checks if late fee is applicable on any of the constituent loans, which could have even accrued after underwriter's call to approveCombine()

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#237]
t0x1c

medium

# Neither approveCombine() nor applyCombine() checks if late fee is applicable on any of the constituent loans, which could have even accrued after underwriter's call to approveCombine()

## Summary
When an underwriter approves multiple loans to be combined and calls [approveCombine()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L877) there is no check to verify that the constituents loan are liable to pay a `lateFee` or not. <br>
Even if we consider that this has been checked by the underwriter off-chain, the borrower has [72 hours to accept](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L897C86-L897C112) this offer before calling [applyCombine()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L742). It's quite possible that the loan slips past the `paymentDueBy` date within these 72 hours.

## Vulnerability Detail
Consider the scenario:
- Loan1 and Loan2 are to be combined. Underwriter verifies off-chain that the loans are active with no overdue payments. He calls `approveCombine()` at timestamp `t`. This offer would be valid till `t + 72 hours` due to the code on [L897](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L897C86-L897C112).
- Loan1 has `paymentDueBy` at `t + 20 hours`.
- For some reason borrower waits until `t + 70 hours` before calling `applyCombine()`. 
- Borrower escapes paying the `lateFee` applicable for the duration of `50 hours`. Once combined with Loan2, he has a "healthy" loan.

## Impact
Loss of interest for the protocol that had accrued as a result of late payment.

## Code Snippet
- https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L897C86-L897C112
- https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L877

## Tool used
Manual Review

## Recommendation
A simple way would be to check inside `approveCombine()` that none of the constituent loans being combined have a `paymentDueBy` within the next 72 hours. Alternatively, it can also be checked inside `applyCombine()` that none of the constituent loans are past their due date.

Duplicate of #95

**Comment by pseudonaut** [comment]
Known, not of concern
