### ISSUE TITLE
FastTiger - If update the distribution between reward contracts, $ZVE may be distributed incorrectly.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#241]
FastTiger

high

# If update the distribution between reward contracts, $ZVE may be distributed incorrectly.

## Summary
Updating the distribution between reward contracts may result in incorrect distribution of $ZVE, as previously undistributed $ZVE are distributed according to the newly updated distribution.
## Vulnerability Detail
The function that distributes $ZVE in `OCE_ZVE` is as follows.
```solidity
    function forwardEmissions() external nonReentrant {
132:    uint zveBalance = IERC20(IZivoeGlobals_OCE_ZVE(GBL).ZVE()).balanceOf(address(this));
133:    _forwardEmissions(zveBalance - decay(zveBalance, block.timestamp - lastDistribution));
134:    lastDistribution = block.timestamp;
    }

    function _forwardEmissions(uint256 amount) private {
        require(amount >= 100 ether, "OCE_ZVE::_forwardEmissions amount < 100 ether");

142:    uint amountZero = amount * distributionRatioBIPS[0] / BIPS;
143:    uint amountOne = amount * distributionRatioBIPS[1] / BIPS;
144:    uint amountTwo = amount * distributionRatioBIPS[2] / BIPS;
        address ZVE = IZivoeGlobals_OCE_ZVE(GBL).ZVE();
        address stZVE = IZivoeGlobals_OCE_ZVE(GBL).stZVE();
        address stSTT = IZivoeGlobals_OCE_ZVE(GBL).stSTT();
        address stJTT = IZivoeGlobals_OCE_ZVE(GBL).stJTT();

        emit EmissionsForwarded(amountZero, amountOne, amountTwo);

        IERC20(ZVE).safeIncreaseAllowance(stZVE, amountZero);
        IERC20(ZVE).safeIncreaseAllowance(stSTT, amountOne);
        IERC20(ZVE).safeIncreaseAllowance(stJTT, amountTwo);
155:    IZivoeRewards_OCE_ZVE(stZVE).depositReward(ZVE, amountZero);
156:    IZivoeRewards_OCE_ZVE(stSTT).depositReward(ZVE, amountOne);
157:    IZivoeRewards_OCE_ZVE(stJTT).depositReward(ZVE, amountTwo);
    }
```
As you can see, $ZVE is distributed according to emission time and distribution.
The function that updates the distribution of the compensation contract is as follows.
```solidity
    function updateDistributionRatioBIPS(uint256[3] calldata _distributionRatioBIPS) external {
        require(
            _msgSender() == IZivoeGlobals_OCE_ZVE(GBL).TLC(), 
            "OCE_ZVE::updateDistributionRatioBIPS() _msgSender() != IZivoeGlobals_OCE_ZVE(GBL).TLC()"
        );
        require(
            _distributionRatioBIPS[0] + _distributionRatioBIPS[1] + _distributionRatioBIPS[2] == BIPS,
            "OCE_ZVE::updateDistributionRatioBIPS() sum(_distributionRatioBIPS[0-2]) != BIPS"
        );

        emit UpdatedDistributionRatioBIPS(distributionRatioBIPS, _distributionRatioBIPS);
        distributionRatioBIPS[0] = _distributionRatioBIPS[0];
        distributionRatioBIPS[1] = _distributionRatioBIPS[1];
        distributionRatioBIPS[2] = _distributionRatioBIPS[2];
    }
```
As you can see, the $ZVE that should be distributed up to now has not been distributed.
Therefore, thereafter $ZVE is distributed according to the updated distribution.

For example:
Let us assume that the $ZVE to be distributed at the time the `updateDistributionRatioBIPS()` function is called is 100 ether. And let's say the current distribution BIPS is 3000, 3000, and 4000. Also, let's say that the emission amount is also 100 ether at the emission point after the `updateDistributionRatioBIPS()` function is called.

1.If `forwardEmissions()` function is called,
    amountZero = 100 ether * 0.3 = 30 ether //stZVE
    amountOne = 100 ether * 0.3 = 30 ether //stSTT
    amountTwo = 100 ether * 0.4 = 40 ether //stJTT
2.Call `updateDistributionRatioBIPS(5000,2000,3000)`.
3.Call `forwardEmissions()`.
    amountZero = 50 ether
    amountOne = 20 ether
    amountTwo = 30 ether

Therefore, stZVE, stSTT, and stJTT must receive 80 ether, 50 ether, and 70 ether, respectively.
However, If `forwardEmissions()` is not called before calling the `updateDistributionRatioBIPS()` function, it is calculated as follows:
    amountZero = 200 ether * 0.5 = 100 ether
    amountOne = 200 ether * 0.2 = 40 ether
    amountTwo = 200 ether * 0.3 = 60 ether
As a result, stSTT and stJTT does not receive 10 ether, respectively. In other words, stakers of stSTT and stJTT will not receive adequate compensation.
## Impact
Because $ZVE is not distributed accurately, stakers cannot receive compensation accurately.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCE/OCE_ZVE.sol#L163-L177
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCE/OCE_ZVE.sol#L139-L158
## Tool used

Manual Review

## Recommendation
Add the following code to the `updateDistributionRatioBIPS()` function.
```solidity
    function updateDistributionRatioBIPS(uint256[3] calldata _distributionRatioBIPS) external {
        require(
            _msgSender() == IZivoeGlobals_OCE_ZVE(GBL).TLC(), 
            "OCE_ZVE::updateDistributionRatioBIPS() _msgSender() != IZivoeGlobals_OCE_ZVE(GBL).TLC()"
        );
        require(
            _distributionRatioBIPS[0] + _distributionRatioBIPS[1] + _distributionRatioBIPS[2] == BIPS,
            "OCE_ZVE::updateDistributionRatioBIPS() sum(_distributionRatioBIPS[0-2]) != BIPS"
        );

+++     uint zveBalance = IERC20(IZivoeGlobals_OCE_ZVE(GBL).ZVE()).balanceOf(address(this));
+++     uint amount = zveBalance - decay(zveBalance, block.timestamp - lastDistribution);
+++     if(amount > 100 ether){
+++         uint amountZero = amount * distributionRatioBIPS[0] / BIPS;
+++         uint amountOne = amount * distributionRatioBIPS[1] / BIPS;
+++         uint amountTwo = amount * distributionRatioBIPS[2] / BIPS;
+++         address ZVE = IZivoeGlobals_OCE_ZVE(GBL).ZVE();
+++         address stZVE = IZivoeGlobals_OCE_ZVE(GBL).stZVE();
+++         address stSTT = IZivoeGlobals_OCE_ZVE(GBL).stSTT();
+++         address stJTT = IZivoeGlobals_OCE_ZVE(GBL).stJTT();

+++         emit EmissionsForwarded(amountZero, amountOne, amountTwo);

+++         IERC20(ZVE).safeIncreaseAllowance(stZVE, amountZero);
+++         IERC20(ZVE).safeIncreaseAllowance(stSTT, amountOne);
+++         IERC20(ZVE).safeIncreaseAllowance(stJTT, amountTwo);
+++         IZivoeRewards_OCE_ZVE(stZVE).depositReward(ZVE, amountZero);
+++         IZivoeRewards_OCE_ZVE(stSTT).depositReward(ZVE, amountOne);
+++         IZivoeRewards_OCE_ZVE(stJTT).depositReward(ZVE, amountTwo);
+++     }
+++     lastDistribution = block.timestamp;


        emit UpdatedDistributionRatioBIPS(distributionRatioBIPS, _distributionRatioBIPS);
        distributionRatioBIPS[0] = _distributionRatioBIPS[0];
        distributionRatioBIPS[1] = _distributionRatioBIPS[1];
        distributionRatioBIPS[2] = _distributionRatioBIPS[2];
    }
```

**Comment by pseudonaut** [comment]
Intended
