### ISSUE TITLE
maushish - Blacklisted Address earnings locked forever.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#248]
maushish

medium

# Blacklisted Address earnings locked forever.

## Summary
Its impossible for a `recipient` to claim their residual or protocol earnings. If for some reason `recipient` got blacklisted by USDC/USDT. These funds will permanently frozen as now there is no mechanices to move them to another address.
## Vulnerability Detail

During the yield distribution, if recipients are blacklisted by either USDC or USDT, their funds will become frozen in the contract. Currently, there is no mechanism available to either transfer these funds to another recipient address or to check for transfers involving blacklisted addresses.

## Impact
Already mentioned above
## Code Snippet
When the distribution of yield is happening there are no checks for blacklisted recipient addresses neither in protocol earnings 

 https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L266   

```solidity
            else {
                IERC20(distributedAsset).safeTransfer(_recipient, _protocol[i]);
                emit YieldDistributedSingle(distributedAsset, _recipient, _protocol[i]);
            }
        }
```
nor in residual earnings
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L305

## Tool used

Manual Review

## Recommendation
Either introduce a mechanism to transfer these unclaimable yield to some other address or implement the checks for blacklisted addresses.

**Comment by pseudonaut** [comment]
Not of concern

**Comment by maushish** [comment]
**My issue is:** *If a residual or protocol recepient gets blacklisted, currently there is no mechanism that either tracks their yield or transfers it to another address.*

@panprog acc to your comment: 
> invalid, admin can change residual or protocol recepients

*Admin can only do so if the recepient somehow report it to the **Admin** or **Admin** notices a loss of yield distribution which is highly unlikely not to mention this whole process will be completely off-chain due to which, a pretty high chance recepients will lose out on yield on different yield distribution cycles.*

> **For the above given reason, I believe my issue is completely valid.**

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> **My issue is:** *If a residual or protocol recepient gets blacklisted, currently there is no mechanism that either tracks their yield or transfers it to another address so that they dont lose out on yield distribution*
> 
> @panprog acc to your comment: 
> > invalid, admin can change residual or protocol recepients
> 
> *Admin can only do so if the recepient somehow report it to the admin or Admin notices a loss of yield distribution which is highly unlikely not to mention this whole process will be completely off-chain due to which, pretty high chance recepient will lose out on yield on different yield distribution cycles.*
> 
> > **For the above given reason, I believe my issue is completely valid.**
> 

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by panprog** [comment]
The transaction will simply revert, so this will be noticed. Also, admin is trusted thus he's supposed to monitor such things anyway.
