### ISSUE TITLE
BiasedMerc - OCY_Convex_C use of PYUSD can lead to DAO and User funds being DOS

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#249]
BiasedMerc

medium

# OCY_Convex_C use of PYUSD can lead to DAO and User funds being DOS

## Summary

`OCY_Convex_C` utilises `PYUSD` as one of the stablecoins to provide liquidity for on curve. `PYUSD` is pausable by the owner which is a multisig. If the owner was to pause `PYUSD` it would cause a DOS when trying to call `pullFromLocker` as the `PYUSD` transfer would not succeed. A similar issue applies to `USDC`, which can also be paused by the EOA pauser.

## Vulnerability Detail

Per the contest page, the admins of the protocols that Zivoe interacts with are considered `Restricted`. Meaning that any issues related to any other tokens/ protocols where the admin's action could negatively affect the Zivoe protocol or users, through loss of funds, rewards or DOS, will be considered valid:
>Are the admins of the protocols your contracts integrate with (if any) TRUSTED or RESTRICTED?
>RESTRICTED

When the DAO wants to remove liquidity from the `OCY_Convex_C` locker they can call [OCY_Convex_C::pullFromLocker()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_C.sol#L146-L169):
```solidity
    function pullFromLocker(address asset, bytes calldata data) external override onlyOwner {
        require(asset == convexPoolToken, "OCY_Convex_C::pullFromLocker() asset != convexPoolToken");
        
        claimRewards(false);

        // Withdraw from ConvexRewards and unstake CurveLP tokens from ConvexBooster
        IBaseRewardPool_OCY_Convex_C(convexRewards).withdrawAndUnwrap(
            IERC20(convexRewards).balanceOf(address(this)), false
        );
        
        (uint _bp_min0, uint _bp_min1) = abi.decode(data, (uint, uint));
        
        // Burn BasePool Tokens
        uint256[] memory _min_amounts_bp = new uint[](2);
        _min_amounts_bp[0] = _bp_min0;
        _min_amounts_bp[1] = _bp_min1;
        IBasePool_OCY_Convex_C(curveBasePool).remove_liquidity(
            IERC20(curveBasePoolToken).balanceOf(address(this)), _min_amounts_bp
        );

        // Return tokens to DAO
        IERC20(PYUSD).safeTransfer(owner(), IERC20(PYUSD).balanceOf(address(this)));
        IERC20(USDC).safeTransfer(owner(), IERC20(USDC).balanceOf(address(this)));
    }
```
At the end of the function, the removed liquidity of `PYUSD` is transfered back to the DAO. The `PYUSD` transfer function is as follows:

[PYUSD](https://etherscan.deth.net/address/0x6c3ea9036406852006290770BEdFcAbA0e23A0e8)
```solidity
    function transfer(address _to, uint256 _value) public whenNotPaused returns (bool) {
```
The transfer function contains the `whenNotPaused` modifier:
```solidity
    modifier whenNotPaused() {
        require(!paused, "whenNotPaused");
        _;
    }
```
Therefore the transfer call will revert when PYUSD is paused.

[USDC](https://etherscan.deth.net/address/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48)
```solidity
    function transfer(address to, uint256 value)
        external
        override
        whenNotPaused
        notBlacklisted(msg.sender)
        notBlacklisted(to)
        returns (bool)
    {
        _transfer(msg.sender, to, value);
        return true;
    }
```
`USDC::transfer()` also has a `whenNotPaused` modifier, and the pauser is an EOA that can call `pause()` which will cause the same issue as with `PYUSD`.

A similar issue regarding DOS from admins of a protocol integration: [Link](https://github.com/sherlock-audit/2024-01-napier-judging/issues/95)

## Impact

If the owner of PYUSD pauses the contract then the DAO funds will be unable to be withdrawn and this will cause DOS for removing liquidity until the contract is unpaused. This DOS will affect the redemption of both `PYUSD` and `USDC` as the whole call to `pullFromLocker` or `pullFromLockerPartial` will revert.

The same issues applies to USDC, which has an EOA pauser that can pause the contract, which will also cause transfers to revert.

## Code Snippet

[OCY_Convex_C::pullFromLocker()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_C.sol#L146-L169)
[PYUSD](https://etherscan.deth.net/address/0x6c3ea9036406852006290770BEdFcAbA0e23A0e8)

## Tool used

Manual Review

## Recommendation

Consider replacing `PYUSD` with a stablecoin that cannot be paused such as DAI.
The same suggestion applies for `USDC`.

Duplicate of #657

**Comment by pseudonaut** [comment]
Not of concern
