### ISSUE TITLE
Ironsidesec - Depositors will deposit only on the last day of ITO.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#252]
Ironsidesec

medium

# Depositors will deposit only on the last day of ITO.

## Summary
Depositing into senior or junior tranches in an ITO phase, will earn you credits, which can then be used to create vesting schedules to vest the vestZVE tokens after the ITO is concluded or migrated.

If ITO ends in 30 days, there's no difference in depositing early/late, everyone can start creating vesting schedules only after ITO is scheduled. So an attacker, can advertise on twitter & discord, may even comment on each ZIVOE twitter post during ITO advising people not to deposit stable coins during the starting phase of the ITO. But do it on the last day. so that for 29 days they can farm stabe coins somewhere. Depositors have no incentive to deposit early at the ITO. 

## Vulnerability Detail

Look at
    1.  [ZivoeITO.claimAirdrop](https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/ZivoeITO.sol#L203)

    2.  [ZivoeITO.migrateDeposits](https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/ZivoeITO.sol#L313)

    3.  [ZivoeITO.depositJunior](https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/ZivoeITO.sol#L248)

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/ZivoeITO.sol#L237

```solidity
File:  2024-03-zivoe\zivoe-core-foundry\src\ZivoeITO.sol
204:     function claimAirdrop(address depositor) external returns (
205:         uint256 zSTTClaimed, uint256 zJTTClaimed, uint256 ZVEVested
206:     ) {


             ***



237:         IERC20(IZivoeGlobals_ITO(GBL).zJTT()).safeTransfer(depositor, juniorCreditsOwned);
238:         IERC20(IZivoeGlobals_ITO(GBL).zSTT()).safeTransfer(depositor, seniorCreditsOwned / 3);
239:
240:         if (upper * middle / lower > 0) {
241:             ITO_IZivoeRewardsVesting(IZivoeGlobals_ITO(GBL).vestZVE()).createVestingSchedule(
242:   >>>>           depositor, 0, 360, upper * middle / lower, false
243:             );
244:         }
245:        
246:         return (seniorCreditsOwned / 3, juniorCreditsOwned, upper * middle / lower);
247:     }


```

A user can create his vesting schedule on the last day of ITO , and he is treated the same regardless of when he deposited during that 30-day ITO phase. So the best way to overcome this issue is to create a cliff for the late depositors, and no cliff for the early depositors. Look at the recommendation section.

The cliff is zero for all depositors. This should be 0 for early depositors and > 0 according to deposit timestamp. So for example, if a depositor deposits on the 8th day, he will get 7 days as a cliff; if he deposits on the 2nd day, he will get 1 day as a cliff; if he deposits at the 30th day, he will get a 29-day cliff.

## Impact

A user can create his vesting schedule on last day of ITO , and he is treated the same regardless of when he deposited during that 30 days ITO phase. This issue can be leveraged to make depositors to deposit only at the ending phase. This will destroy the hype of ZIVOE during ITO, because the fewer deposits of stable coins will discourage Twitter degens discouraged looking at the TVL.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/ZivoeITO.sol#L203

## Tool used

Manual Review

## Recommendation

Create a new storage state that stores when a depositor deposits into a junior or senior tranche. When he calls claim airdrop, create a `cliff  = depsoit timestamp - (ITO end timestamp  - 30 days ) `. So early depositors will get less cliff.

**Comment by pseudonaut** [comment]
This is not of concern
