### ISSUE TITLE
Ironsidesec - ZivoeRewards.sol does Inefficient reward distribution

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#254]
Ironsidesec

high

# ZivoeRewards.sol does Inefficient reward distribution

## Summary
Issue occurs in [ZivoeRewards.depositReward](https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/ZivoeRewards.sol#L228-L243)

This issue is about `inefficient reward distribution`, not the second issue mentioned below.
There are 2 issues when a new reward token is added and some rewards are deposited.
    1. Inefficient reward distribution.
    2. Since old stakers have `accountRewardPerTokenPaid` == 0 for this new reward token and they also have staking token `balance` > 0, they can claim rewards as soon as some rewards are deposited because earned = bal * (rewardPerTokenStored - accountRewardPerTokenPaid) = bal * (1e18 - 0). So a potential backrun can drain all the rewards.

Although the issue exists in [synthetix staking contract,](https://0xmacro.com/blog/synthetix-staking-rewards-issue-inefficient-reward-distribution/) it is medium to low there because the reward token is only one token and the staking balance will mostly be > 0, so the impact is medium to low.
In Zivoe, this issue is high to medium because, 
1.  many reward emitting function from [OCE_ZVE.forwardEmissions](https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCE/OCE_ZVE.sol#L131) and [ZivoeYDL.distributeYield](https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/ZivoeYDL.sol#L246)
2. staking balance will always  == 0 when a new reward token is added + deposited. 

**Root cause**

The root cause for this issue is, when staking balance == 0, a new reward token is added, and reward emission is started, since staking balance is zero, the streamed rewards are wasted. So a reward stream for that period should only be started on the first stake() call. 

We cannot account for the staking balance that was deposited a month ago to be eligible for this new rewards. So staking balance will always == 0 in terms of new reward token.

## Vulnerability Detail

**Issue path:**

1. A new reward token is added. And a reward deposit is made. When a deposit is made, the rewards start streaming until the 30-day reward period ending timestamp.
2. One day has passed, and still no one has called stake. So here, 1 day worth of rewards is emitted, and no one can claim it; it's just wasted because staking balance = 0.
3. Now, after a day, someone calls stake, and at least now the rewards emitted for the next 29 days can be claimed by someone.

**In a math example,**
current total staking balance = 0
A new reward token is added for 30 days at 100 reward tokens per day (total =  30 * 100e18), per second emission =  100e18 / 86400

Now, 1 day is passed and 100 reward tokens are emitted, but no one can claim them because no one ever staked, making the staking balance = 0. The staking balance will be 0 for new reward tokens. This is the root cause. And solvable by starting the reward emission on first stake call if staking bal = 0.

This issue is inspired from https://0xmacro.com/blog/synthetix-staking-rewards-issue-inefficient-reward-distribution/

Although the issue exists in synthetix staking contract, it is medium to low there because the reward token is only one token and the staking balance will mostly be > 0, so the impact is medium to low.
Here the imapct is high to medium because, the staking balance will be zero for new reward tokens, because nobody knows about this new rewards.

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/ZivoeRewards.sol#L228-L243

```solidity
File: 2024-03-zivoe\zivoe-core-foundry\src\ZivoeRewards.sol


228:     function depositReward(address _rewardsToken, uint256 reward) external updateReward(address(0)) nonReentrant {
229:         IERC20(_rewardsToken).safeTransferFrom(_msgSender(), address(this), reward);
230:
231:         // Update vesting accounting for reward (if existing rewards being distributed, increase proportionally).
232:         if (block.timestamp >= rewardData[_rewardsToken].periodFinish) {
233:             rewardData[_rewardsToken].rewardRate = reward.div(rewardData[_rewardsToken].rewardsDuration);
234:         } else {
235:             uint256 remaining = rewardData[_rewardsToken].periodFinish.sub(block.timestamp);
236:             uint256 leftover = remaining.mul(rewardData[_rewardsToken].rewardRate);
237:             rewardData[_rewardsToken].rewardRate = reward.add(leftover).div(rewardData[_rewardsToken].rewardsDuration);
238:         }
239:
240:  >>>>   rewardData[_rewardsToken].lastUpdateTime = block.timestamp;
241:  >>>>   rewardData[_rewardsToken].periodFinish = block.timestamp.add(rewardData[_rewardsToken].rewardsDuration);
242:         emit RewardDeposited(_rewardsToken, reward, _msgSender());
243:     }


```

The best way to deal with this issue is, when a new reward token is added and rewards are deposited, don't update `lastUpdateTime` in line 240, `periodFinish` in line 241.
Update when someone calls stake for the first time after `depositReward` is called.

## Impact

Loss of rewards depends on how much time has passed since a new reward token is deposited and someone stakes.

Whenever a protocol starts a reward cycle, it intends to distribute X amounts of rewards during that time.
If a certain amount remains unused (like the above example inside the contract), and a new reward cycle is not started, that amount remains dormant inside the contract.
Even if the given protocol decides to start a new reward cycle to cover this unused amount, it is a redundant execution.
As there will likely be a delay between the first stake and the reward cycle initiation, consider resolving this issue.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/ZivoeRewards.sol#L228-L243

## Tool used

Manual Review

## Recommendation

The best way to deal this issue is, when a new reward token is added and rewards are deposited on [ZivoeRewards.depositReward](https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/ZivoeRewards.sol#L228-L243)
, don't update `lastUpdateTime` , `periodFinish`  on reward deposit action.
Update when someone calls stake for the first time after `depositReward` is called.

Look at example https://github.com/PeggyJV/cellar-contracts/blob/afd970c36e9a520326afc888a11d40cdde75c6a7/src/CellarStaking.sol?ref=0xmacro.com#L219

Duplicate of #113

**Comment by pseudonaut** [comment]
Doesn't seem of concern, staking contracts should have > 0 ... or in the event they don't (stZVE potentially) then no rewards would be distributed ... considering whitelist for depositReward
