### ISSUE TITLE
SilverChariot - Borrowers can accept cancelled orders by frontrunning the cancel tx

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#26]
SilverChariot

medium

# Borrowers can accept cancelled orders by frontrunning the cancel tx

## Summary
[OCC_Modular.cancelOffer()](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L522C1-L529C6) can be frontrun by a borrower to accept a given offer. 

## Vulnerability Detail
[OCC_Modular.cancelOffer()](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L522C1-L529C6) is expected to cancel any order that is still not accepted by a borrower. For example, a mistake has been made and the offer needs to be cancelled because its conditions are not in favor for the protocol. The loan's borrower can frontrun the cancel transaction by [accepting](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L461C1-L487C6) the offer. 
The loan will not be cancellable anymore because of the following `require`

```solidity
        require(
            loans[id].state == LoanState.Offered, 
            "OCC_Modular::cancelOffer() loans[id].state != LoanState.Offered"
        );
```

## Impact
It's possible to execute an order that should be cancelled.

## Code Snippet

```solidity
    function cancelOffer(uint256 id) isUnderwriter external {
        require(
            loans[id].state == LoanState.Offered, 
            "OCC_Modular::cancelOffer() loans[id].state != LoanState.Offered"
        );
        emit OfferCancelled(id);
        loans[id].state = LoanState.Cancelled;
    }
```

## Tool used

Manual Review

## Recommendation
A possible solution may be to add some `timeToAccept` that the borrower has to wait before they are able to accept a given loan.

**Comment by pseudonaut** [comment]
Not relavent, or of concern
