### ISSUE TITLE
Drynooo - Division may cause a lot of reward tokens to be locked in the contract

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#262]
Drynooo

high

# Division may cause a lot of reward tokens to be locked in the contract

## Summary
The rewardRate is calculated by division in the depositReward function, but the loss of precision is not considered. This results in some funds being locked up in the contract.

## Vulnerability Detail
If rewardsToken is USDC, the token precision is 6. Calculated based on the rewardsDuration in the test contract being 30 days, each call to the depositReward function may cause a maximum loss of 2.592000. rewardsDuration may be set longer, calling the depositReward function multiple times will cause accumulated losses.

Additionally, anyone can call this function. An attacker can maliciously repeat the call, undoubtedly increasing the amount locked.

## Impact
Division may cause a lot of reward tokens to be locked in the contract

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewards.sol#L228
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L352
```solidity
    function depositReward(address _rewardsToken, uint256 reward) external updateReward(address(0)) nonReentrant {
        IERC20(_rewardsToken).safeTransferFrom(_msgSender(), address(this), reward);

        // Update vesting accounting for reward (if existing rewards being distributed, increase proportionally).
        if (block.timestamp >= rewardData[_rewardsToken].periodFinish) {
            rewardData[_rewardsToken].rewardRate = reward.div(rewardData[_rewardsToken].rewardsDuration);
        } else {
            uint256 remaining = rewardData[_rewardsToken].periodFinish.sub(block.timestamp);
            uint256 leftover = remaining.mul(rewardData[_rewardsToken].rewardRate);
            rewardData[_rewardsToken].rewardRate = reward.add(leftover).div(rewardData[_rewardsToken].rewardsDuration);
        }

        rewardData[_rewardsToken].lastUpdateTime = block.timestamp;
        rewardData[_rewardsToken].periodFinish = block.timestamp.add(rewardData[_rewardsToken].rewardsDuration);
        emit RewardDeposited(_rewardsToken, reward, _msgSender());
    }
```

## Tool used

Manual Review

## Recommendation
It is recommended to improve the precision of division, or not allow everyone to call the depositReward function.

Duplicate of #129

**Comment by Albort-J** [comment]
medium
