### ISSUE TITLE
Drynooo - Users who repay early will be charged more interest

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#266]
Drynooo

medium

# Users who repay early will be charged more interest

## Summary
Users' early repayment will not reduce their interest, but they will pay more interest.

## Vulnerability Detail
If the user has spare money, but not enough to pay off the loan. He may call the [processPayment function](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L636) multiple times for early repayment. However, the agreement calculates interest based on a fixed [paymentInterval](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L455C56-L455C72), and users who repay early will not receive less interest.

## Impact
Users who repay early will be charged more interest

## Code Snippet
```solidity
        // Add late fee if past loans[id].paymentDueBy.
        if (block.timestamp > loans[id].paymentDueBy && loans[id].state == LoanState.Active) {
            lateFee = loans[id].principalOwed * (block.timestamp - loans[id].paymentDueBy) *
                loans[id].APRLateFee / (86400 * 365 * BIPS);
        }
        interest = loans[id].principalOwed * loans[id].paymentInterval * loans[id].APR / (86400 * 365 * BIPS);
        total = principal + interest + lateFee;
    }
```

## Tool used

Manual Review

## Recommendation
It is recommended that interest be calculated based on the time that the loan has elapsed.

**Comment by drynooo** [comment]
Escalate

For Amortization loans, users have extra spare money and hope to repay in advance. This means that the prepayment period should not be counted as a borrowing period, and interest should not be calculated. I believe this is common sense for any bank.

According to the [docs](https://docs.zivoe.com/user-docs/borrowers), the contract allows users to freely repay in advance, and the contract will calculate the interest payable by the user. Users have some idle funds that they want to repay in order not to pay interest on the funds, but the reality is that this cannot be the case. This is a loss for users.

For example, if the user calls the processPayment function twice in a row to make repayments, the repayment period for the second repayment should be 0, but the interest is still calculated according to the paymentInterval. This is unreasonable.

(The reason why the user does not pay off the loan all at once may be that he does not have that much free funds.)

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> For Amortization loans, users have extra spare money and hope to repay in advance. This means that the prepayment period should not be counted as a borrowing period, and interest should not be calculated. I believe this is common sense for any bank.
> 
> According to the [docs](https://docs.zivoe.com/user-docs/borrowers), the contract allows users to freely repay in advance, and the contract will calculate the interest payable by the user. Users have some idle funds that they want to repay in order not to pay interest on the funds, but the reality is that this cannot be the case. This is a loss for users.
> 
> For example, if the user calls the processPayment function twice in a row to make repayments, the repayment period for the second repayment should be 0, but the interest is still calculated according to the paymentInterval. This is unreasonable.
> 
> (The reason why the user does not pay off the loan all at once may be that he does not have that much free funds.)

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by panprog** [comment]
The fact that user wants to skip paying interest on payments paid earlier doesn't mean that he's allowed to. The loan agreement is to pay each interest based on payment interval irrelevant of when it's paid, so this works as intended. What Watson suggests is their view of the terms of the loan, which is different from the protocol's terms. So this should remain invalid.

**Comment by drynooo** [comment]
Users can make early repayments to avoid paying more interest by calling the [callLoan function](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L492). Therefore, early repayments through processPayment should have the same effect. Otherwise, it would violate the "flexibility to make early payments" mentioned in [the documentation](https://docs.zivoe.com/user-docs/borrowers).

> Make a Payment
Zivoe facilitates a hassle-free repayment process. Borrowers are expected to make payments as per the prearranged schedule and frequency. However, the flexibility to make early payments is offered to those who wish to do so.

I still have reservations.

**Comment by WangSecurity** [comment]
Agree with the lead judge that this is the intended design. The fact that it's possible to avoid paying more interest by closing the entire loan (`callLoan`) doesn't mean that it should be possible on every payment. I believe it's within the documentation of "the flexibility to make early payments is offered to those who wish to do so" that the users are able to close the entire loan upfront without paying the interest.

Hence, I believe it's intended design decision, therefore the report should remain invalid. Planning to reject the escalation.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Scorpiondeng](https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/266/#issuecomment-2105669718): rejected
