### ISSUE TITLE
Drynooo - Borrowers have the ability to influence the distribution of rewards between senior and junior

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#267]
Drynooo

medium

# Borrowers have the ability to influence the distribution of rewards between senior and junior

## Summary
Borrowers can [affect Defaults through the resolveDefault function](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L703), thereby [affecting the return value of adjustedSupplies](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeGlobals.sol#L129C54-L129C62). The value of adjustedSupplies will affect the [calculation of the earningsTrancheuse function](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeYDL.sol#L232). That is, it can affect the calculation[ ratio of senior and junior.](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeYDL.sol#L464-L465)

## Vulnerability Detail
Assumptions:
1. The borrower already has bad debts and he has the funds to repay the loan at this time. He needs to solve it through the resolveDefault function.
2. At this time, he has the ability to call the distributeYield function immediately after calling resolveDefault in the same transaction to control the reward distribution between junior and senior levels. He can make one of the rewards allocate more. (Although there are 6 averages, this process can also be repeated 6 times)
3. This ability allows him to choose a type of pledge to gain more benefits, or he can sell it to users who are already staking, thereby benefiting them.

## Impact
Borrowers have the ability to influence the distribution of rewards between senior and junior, thereby earning themselves more interest.

## Code Snippet
```solidity
    function resolveDefault(uint256 id, uint256 amount) external nonReentrant {
        require(
            loans[id].state == LoanState.Defaulted, 
            "OCC_Modular::resolveDefaut() loans[id].state != LoanState.Defaulted"
        );

        uint256 paymentAmount;

        if (amount >= loans[id].principalOwed) {
            paymentAmount = loans[id].principalOwed;
            loans[id].principalOwed = 0;
            loans[id].state = LoanState.Resolved;
        }
        else {
            paymentAmount = amount;
            loans[id].principalOwed -= paymentAmount;
        }

        emit DefaultResolved(id, paymentAmount, _msgSender(), loans[id].state == LoanState.Resolved);

        IERC20(stablecoin).safeTransferFrom(_msgSender(), owner(), paymentAmount);
        IZivoeGlobals_OCC(GBL).decreaseDefaults(IZivoeGlobals_OCC(GBL).standardize(paymentAmount, stablecoin));
    }
```
## Tool used

Manual Review

## Recommendation
It is recommended that the keeper call the distributeYield function in advance to prevent manipulation.

**Comment by pseudonaut** [comment]
Not relevant, or of concern
