### ISSUE TITLE
Bauer - Malicious users can deposit 0 assets to prolong the reward end time

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#270]
Bauer

high

# Malicious users can deposit 0 assets to prolong the reward end time

## Summary

The function `depositReward()` allows for depositing assets, including 0, to extend the end time of reward tokens. 

## Vulnerability Detail

The purpose of the `depositReward()` function is to deposit a reward into the contract for distribution. After updating the rewardRate of the reward token, the protocol updates `rewardData[_rewardsToken].lastUpdateTime = block.timestamp` and `rewardData[_rewardsToken].periodFinish = block.timestamp.add(rewardData[_rewardsToken].rewardsDuration)` with each successful call, effectively extending the reward period by rewardsDuration each time. However, malicious users can deposit 0 assets to prolong the reward end time, resulting in reduced rewards for users.
```solidity


        // Update vesting accounting for reward (if existing rewards being distributed, increase proportionally).
        if (block.timestamp >= rewardData[_rewardsToken].periodFinish) {
            rewardData[_rewardsToken].rewardRate = reward.div(rewardData[_rewardsToken].rewardsDuration);
        } else {
            uint256 remaining = rewardData[_rewardsToken].periodFinish.sub(block.timestamp);
            uint256 leftover = remaining.mul(rewardData[_rewardsToken].rewardRate);
            rewardData[_rewardsToken].rewardRate = reward.add(leftover).div(rewardData[_rewardsToken].rewardsDuration);
        }

        rewardData[_rewardsToken].lastUpdateTime = block.timestamp;
        rewardData[_rewardsToken].periodFinish = block.timestamp.add(rewardData[_rewardsToken].rewardsDuration);
        
```

## Impact
Prolong the reward end time, resulting in reduced rewards for users.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L228-L243
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L352-L366

## Tool used

Manual Review

## Recommendation

Duplicate of #11

**Comment by pseudonaut** [comment]
Valid, considering whitelists
