### ISSUE TITLE
Drynooo - Users can avoid part of the interest through Combine

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#272]
Drynooo

medium

# Users can avoid part of the interest through Combine

## Summary
When a user combines two loans, the previous interest will not be calculated. Directly merge into a [new loan](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L803-L806) according to the new time. Even if the user has not paid interest for a long time, this part of the interest will not be charged.

## Vulnerability Detail
If there is interest before the combine, it will not be settled, even if it is overdue interest. There will also be an interest exemption period of 2 to 9 days. This will cause the protocol to lose interest.
```solidity
        loans[loanCounter] = Loan(
            _msgSender(), notional, APR, APRLateFee, block.timestamp - block.timestamp % 7 days + 9 days + paymentInterval, 
            term, term, paymentInterval, block.timestamp - 1 days, gracePeriod, paymentSchedule, LoanState.Active
        );
```

## Impact
Users can avoid part of the interest through Combine

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L803-L806
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L450-L455

## Tool used

Manual Review

## Recommendation
It is recommended to settle the previous interest first and then combine it.

Duplicate of #95

**Comment by pseudonaut** [comment]
Known, not of concern
