### ISSUE TITLE
avik17 - H-1 : Inconsistent Precision Handling in increase and decrease defaults functions which can lead to incorrect accounting.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#275]
avik17

high

# H-1 : Inconsistent Precision Handling in increase and decrease defaults functions which can lead to incorrect accounting.

## Summary
The `decreaseDefaults` and `increaseDefaults` functions expect the input amount to be standardized to WEI (18 decimal places) before calling these functions.
## Vulnerability Detail
The `ZivoeGlobals.sol :: decreaseDefaults` and `ZivoeGlobals.sol :: increaseDefaults` functions expect the input amount to be standardized to WEI (18 decimal places) before calling these functions. However, there is no explicit check or requirement enforcing this. If the standardized function is not called before calling these functions, or if an incorrect amount is passed in, the system's default accounting may become inconsistent. If the input amount is not properly standardized to 18 decimals, the accounting of defaults in the system may become inaccurate.
## Impact
Incorrect default accounting could result in incorrect tranche token supplies, incorrect reward distributions, and an overall misrepresentation of the protocol's risk exposure and financial health.
## Code Snippet
[In line 161](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGlobals.sol#L157) in ZivoeGlobals.sol.
```solidity
function decreaseDefaults(uint256 amount) external {
        require(isLocker[_msgSender()], "ZivoeGlobals::decreaseDefaults() !isLocker[_msgSender()]");
        defaults = defaults.floorSub(amount);
        emit DefaultsDecreased(_msgSender(), amount, defaults);
    }
```
[In line 173](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGlobals.sol#L168) in ZivoeGlobals.sol.
```solidity
  function increaseDefaults(uint256 amount) external {
        require(isLocker[_msgSender()], "ZivoeGlobals::increaseDefaults() !isLocker[_msgSender()]");
        defaults += amount;
        emit DefaultsIncreased(_msgSender(), amount, defaults);
    }
```
## Tool used

Manual Review

## Recommendation
 Consider adding explicit checks or requirements to ensure that the input amount is properly standardized to WEI (18 decimals) before calling decreaseDefaults and increaseDefaults. Alternatively, you could move the standardization logic inside these functions to ensure consistency.

**Comment by pseudonaut** [comment]
This is already done in OCC_Modular, not valid
