### ISSUE TITLE
Drynooo - Users can make the protocol issue more rewards through flash loans. And these rewards can be claimed through slippage.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#280]
Drynooo

high

# Users can make the protocol issue more rewards through flash loans. And these rewards can be claimed through slippage.

## Summary
The income generated in uniswap can be collected through the forwardYield function, but attackers can use flash loans to manipulate the amount of rewards received to increase. And can profit from slippage in the process of removing liquidity.

## Vulnerability Detail
In the forwardYield function, [the basis is updated through the fetchBasis function](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L303), which represents the principal pledged by the protocol. [The excess over the principal is used to issue rewards.
](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L302)
But suppose:
1. An attacker can take away the pairAsset tokens in the pool through flash loans.
2. Call [forwardYield](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L287) during the flash loan process. At this time, since the flash loan has taken away the pairAsset tokens in the pool, the [pairAssetBalance will become very small](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L338), **thus [making the basis very small](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L341)**.
3. The attacker repays the flash loan.
4. The next time the forwardYield function is called, [**the rewards will increase significantly because the fetchBasis function returns to normal.**](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L313) This part of the reward even includes the principal of the agreement. This will allow users to receive more rewards. Moreover, the removeLiquidity function does not have slippage protection and is vulnerable to slippage attacks.

## Impact
Users can make the protocol issue more rewards through flash loans. And these rewards can be claimed through slippage.

## Code Snippet
```solidity
    function forwardYield() external {
        if (IZivoeGlobals_OCL_ZVE(GBL).isKeeper(_msgSender())) {
            require(
                block.timestamp > nextYieldDistribution - 12 hours, 
                "OCL_ZVE::forwardYield() block.timestamp <= nextYieldDistribution - 12 hours"
            );
        }
        else {
            require(
                block.timestamp > nextYieldDistribution, 
                "OCL_ZVE::forwardYield() block.timestamp <= nextYieldDistribution"
            );
        }

        (uint256 amount, uint256 lp) = fetchBasis();
        if (amount > basis) { _forwardYield(amount, lp); }
        (basis,) = fetchBasis();
        nextYieldDistribution += 30 days;
    }
```
## Tool used

Manual Review

## Recommendation
Call [the skim function of uniswap](https://github.com/Uniswap/v2-core/blob/ee547b17853e71ed4e0101ccfd52e70d5acded58/contracts/UniswapV2Pair.sol#L190-L195) to prevent flash loan attacks.
```diff
    function forwardYield() external {
        if (IZivoeGlobals_OCL_ZVE(GBL).isKeeper(_msgSender())) {
            require(
                block.timestamp > nextYieldDistribution - 12 hours, 
                "OCL_ZVE::forwardYield() block.timestamp <= nextYieldDistribution - 12 hours"
            );
        }
        else {
            require(
                block.timestamp > nextYieldDistribution, 
                "OCL_ZVE::forwardYield() block.timestamp <= nextYieldDistribution"
            );
        }

+       address pair = IFactory_OCL_ZVE(factory).getPair(pairAsset, ZVE);
+       IPair(pair).skim();
        (uint256 amount, uint256 lp) = fetchBasis();
        if (amount > basis) { _forwardYield(amount, lp); }
        (basis,) = fetchBasis();
        nextYieldDistribution += 30 days;
    }
```

Duplicate of #296

**Comment by pseudonaut** [comment]
Not relevant
