### ISSUE TITLE
DPS - OCC_Modular - USDC blacklist address will prevent a user from repaying his loan

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#286]
DPS

medium

# OCC_Modular - USDC blacklist address will prevent a user from repaying his loan

## Summary
If the stablecoin in OCC_Modular is set to USDC and a user gets blacklisted, it will prevent them from repaying their loan
## Vulnerability Detail
If a user has taken out a loan with the contract's stablecoin set to USDC, and he gets blacklisted, it will make it impossible for him to repay the loan
## Impact
This will cause their loan to get defaulted and start accruing fees without a way to resolve this by themselves

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L575
## Tool used

Manual Review

## Recommendation
Add a whitelist of stablecoins that a user can use to repay his loan. Don't rely only on one asset for a repayment.

**Comment by pseudonaut** [comment]
Not relevant
