### ISSUE TITLE
DPS - A user will be on big profit if he takes bullet loan and USDC depegs

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#287]
DPS

medium

# A user will be on big profit if he takes bullet loan and USDC depegs

## Summary
A user can take a bullet loan and return much less money than he took.

## Vulnerability Detail
If a user takes out a bullet loan for USDC that costs 1$ at the time and the asset depegs again as it did a few months ago, the user can just instantly repay the loan and return the whole principal and this way he will have to return much less money than he took
## Impact
This will make the loan cost nothing for the user and make it unprofitable for the protocol.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L492
## Tool used

Manual Review

## Recommendation
Use an oracle to track the price for the asset that you give so the users have to return the correct amount based on the price and not the count.

Duplicate of #105

**Comment by pseudonaut** [comment]
Not relevant
