### ISSUE TITLE
DPS - ZiveoRewards::getRewards() and ZivoeRewardsVesting::getRewards() can get DoSed for some users

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#288]
DPS

medium

# ZiveoRewards::getRewards() and ZivoeRewardsVesting::getRewards() can get DoSed for some users

## Summary
A blacklisted USDC address will prevent the user to claim his other rewards as well

## Vulnerability Detail
This functions send the user the assets that he has as a reward but if one of the assets is USDC and the user is blacklisted from it will cause him not to be able to claim the other ones as well.

## Impact
The rewards are sent by using a for loop

```solidity

 function getRewards() public updateReward(_msgSender()) {
        for (uint256 i = 0; i < rewardTokens.length; i++) { _getRewardAt(i); }
    }

```
If the user is blacklisted from USDC the whole transaction will revert and will prevent him from getting his other assets as well.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L281

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L484
## Tool used

Manual Review

## Recommendation
Consider adding a functionality where the user can claim a specific asset by his choice

Duplicate of #13

**Comment by pseudonaut** [comment]
Not relevant
