### ISSUE TITLE
cergyk - `OCY_Convex_A::pushToLocker` adds imbalanced liquidity to Curve pool which leads to paying unnecessary additional fees

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#299]
cergyk

medium

# `OCY_Convex_A::pushToLocker` adds imbalanced liquidity to Curve pool which leads to paying unnecessary additional fees

## Summary

`OCY_Convex_A::pushToLocker` is used to migrate specific amount of `FRAX` / `USDC` / `alUSD` from the DAO to a locker and allocate `FRAX` to `Curve BasePool` but by adding imbalanced liquidity to the `curveBasePool` protocol will pay unnecessary additional fees.

## Vulnerability Detail

When calling `OCY_Convex_A::pushToLocker` to migrate specific amount of `FRAX` / `USDC` / `alUSD` from the DAO to a locker it allocates a single sided amount to the curve pool/metapool (below FRAX is used as an example):

[OCY_Convex_A.sol#L117-L131](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_A.sol#L117-L131)
```solidity
    function pushToLocker(address asset, uint256 amount, bytes calldata data) external override onlyOwner {
        require(
            asset == FRAX || asset == USDC || asset == alUSD, 
            "OCY_Convex_A::pushToLocker() asset != FRAX && asset != USDC && asset != alUSD"
        );
        IERC20(asset).safeTransferFrom(owner(), address(this), amount);

        (uint _min_mint_amountBP, uint _min_mint_amountMP) = abi.decode(data, (uint, uint));

        if (asset == FRAX) {
            // Allocate FRAX to Curve BasePool
            IERC20(FRAX).safeIncreaseAllowance(curveBasePool, amount);
            uint256[2] memory _amounts;
            _amounts[0] = amount;
>>          IBasePool_OCY_Convex_A(curveBasePool).add_liquidity(_amounts, _min_mint_amountBP);
```

However, Curve base pool charges extra fees when adding imbalanced liquidity to the pool:

[StableSwap](https://etherscan.io/address/0xdcef968d416a41cdac0ed8702fac8128a64241a2#code#L321)
```vyper
    # to calculate fair user's share
    D2: uint256 = D1
    fees: uint256[N_COINS] = empty(uint256[N_COINS])
    mint_amount: uint256 = 0
    if token_supply > 0:
        # Only account for fees if we are not the first to deposit
        fee: uint256 = self.fee * N_COINS / (4 * (N_COINS - 1))
        admin_fee: uint256 = self.admin_fee
        for i in range(N_COINS):
            ideal_balance: uint256 = D1 * old_balances[i] / D0
            difference: uint256 = 0
            new_balance: uint256 = new_balances[i]
            if ideal_balance > new_balance:
>>              difference = ideal_balance - new_balance
            else:
>>              difference = new_balance - ideal_balance
            fees[i] = fee * difference / FEE_DENOMINATOR
            self.balances[i] = new_balance - (fees[i] * admin_fee / FEE_DENOMINATOR)
            new_balances[i] -= fees[i]
        D2 = self._get_D_mem(new_balances, amp)
        mint_amount = token_supply * (D2 - D0) / D0
```

These fees could be avoided by adding multiple tokens at once, in a somewhat balanced way (the fee is reduced proportionally to the balancedness).

## Impact

Extra unnecessary fees charged to the protocol, which can be easily avoided

## Code Snippet

- https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_A.sol#L117-L131
- https://etherscan.io/address/0xdcef968d416a41cdac0ed8702fac8128a64241a2#code#L321

## Tool used

Manual Review

## Recommendation

Enable balanced liquidity to be added to curve pools by implementing `pushToLockerMulti` for `OCY_Convex_A` and `OCY_Convex_C`

**Comment by pseudonaut** [comment]
So I don't believe this is an actual "issue" it's sub-optimal but this is what their protocol offers and has endpoints for, and what we decided to integrate with

This should be low at-best but possibly informational, because it's only an efficiency in capital for adding balanced liquidity vs. imbalanced liquidity (i.e. there's not an inherent issue in current implementation, it works as intended with external endpoints)
