### ISSUE TITLE
cergyk - ZivoeRewards::depositReward anybody can reset remaining rewards duration

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#303]
cergyk

medium

# ZivoeRewards::depositReward anybody can reset remaining rewards duration

## Summary

An attacker can spread remaining rewards over the whole `rewardDuration`  with amount == 0

## Vulnerability Detail

`ZivoeRewards::depositReward` and `ZivoeRewardsVesting::depositReward` are used to deposit a reward to these contracts for distribution.

The issue with the function is it is unpermissioned, but it impacts the distribution of existing rewards to users:
By depositing 1 wei of rewards, any user can spread existing rewards over the whole `rewardDuration` period. 

[ZivoeRewards.sol#L225-L249](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewards.sol#L225-L243)
```solidity
    /// @notice Deposits a reward to this contract for distribution.
    /// @param _rewardsToken The asset that's being distributed.
    /// @param reward The amount of the _rewardsToken to deposit.
    function depositReward(address _rewardsToken, uint256 reward) external updateReward(address(0)) nonReentrant {
        IERC20(_rewardsToken).safeTransferFrom(_msgSender(), address(this), reward);

        // Update vesting accounting for reward (if existing rewards being distributed, increase proportionally).
        if (block.timestamp >= rewardData[_rewardsToken].periodFinish) {
            rewardData[_rewardsToken].rewardRate = reward.div(rewardData[_rewardsToken].rewardsDuration);
        } else {
            uint256 remaining = rewardData[_rewardsToken].periodFinish.sub(block.timestamp);
            uint256 leftover = remaining.mul(rewardData[_rewardsToken].rewardRate);
            rewardData[_rewardsToken].rewardRate = reward.add(leftover).div(rewardData[_rewardsToken].rewardsDuration);
        }

        rewardData[_rewardsToken].lastUpdateTime = block.timestamp;
>>      rewardData[_rewardsToken].periodFinish = block.timestamp.add(rewardData[_rewardsToken].rewardsDuration);
        emit RewardDeposited(_rewardsToken, reward, _msgSender());
    }
```

## Impact

A malicious user can delay the whole distribution of rewards by a very long time by calling `depositReward` each time half of the rewardDuration has elapsed. This way the whole amount of rewards is never distributed, in a similar fashion as described in [Zeno's dichotomy paradox](https://en.wikipedia.org/wiki/Zeno%27s_paradoxes)

## Code Snippet

- https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewards.sol#L225-L24## Summary

## Tool used

Manual Review

## Recommendation

Add a minimum deposit amount to make this attack costly for the attacker:

```diff
    function depositReward(address _rewardsToken, uint256 reward) external updateReward(address(0)) nonReentrant {
+       require(IZivoeGlobals(GBL).standardize(reward, _rewardsToken) >= 0.1 ether, "reward < 0.1 ether"); 
        IERC20(_rewardsToken).safeTransferFrom(_msgSender(), address(this), reward);
```

Or make the function permissioned

Duplicate of #11

**Comment by pseudonaut** [comment]
Valid, looking into whitelists
