### ISSUE TITLE
phenom - potential arithmetic overflow or underflow due to improper handling of fixed-point arithmetic `standardize` function

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#305]
phenom

medium

# potential arithmetic overflow or underflow due to improper handling of fixed-point arithmetic `standardize` function

## Summary
The `standardize` function in the provided smart contract is vulnerable to potential arithmetic overflow or underflow due to improper handling of fixed-point arithmetic.

## Vulnerability Detail
The vulnerability arises from performing multiplication or division operations without proper handling of fixed-point arithmetic. Solidity does not handle fixed-point arithmetic automatically, so these operations can result in unexpected behavior, including arithmetic overflow or underflow.

## Impact
The impact of this vulnerability can vary depending on the input values and the assets involved. In some cases, it may result in incorrect standardized amounts, leading to financial losses or unexpected behavior in the application.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGlobals.sol#L142C1-L150C6
```solidity
function standardize(uint256 amount, address asset) external view returns (uint256 standardizedAmount) {
    standardizedAmount = amount;
    uint256 assetDecimals = IERC20Metadata(asset).decimals();
    if (assetDecimals < 18) { 
        standardizedAmount *= 10 ** (18 - assetDecimals); 
    } 
    else if (assetDecimals > 18) { 
        standardizedAmount /= 10 ** (assetDecimals - 18);
    }
}
```

## Tool used
Manual Review

## Recommendation
Properly handle fixed-point arithmetic by casting one of the operands to a `uint256` before performing multiplication or division operations. This will ensure correct handling of fixed-point arithmetic and mitigate the risk of arithmetic overflow or underflow. For example:

```solidity
function standardize(uint256 amount, address asset) external view returns (uint256 standardizedAmount) {
    standardizedAmount = amount;
    uint256 assetDecimals = IERC20Metadata(asset).decimals();
    if (assetDecimals < 18) { 
        standardizedAmount *= 10 ** (18 - assetDecimals); 
    } 
    else if (assetDecimals > 18) { 
        standardizedAmount /= 10 ** (assetDecimals - 18);
    }
}
```

**Comment by pseudonaut** [comment]
I need some help - it appears implementation and recommendation are the same. What is the difference?
