### ISSUE TITLE
phenom - Potential Miscalculation in ZivoeTranches due to standardize Function Behavior

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#306]
phenom

medium

# Potential Miscalculation in ZivoeTranches due to standardize Function Behavior

## Summary
The smart contract `ZivoeTranches` contains a potential vulnerability in its `standardize` function, which could lead to unexpected behavior in the `depositJunior` and `depositSenior` functions.

## Vulnerability Detail
The `standardize` function in the `IZivoeGlobals_ZivoeTranches` contract does not always return a value if the asset's decimals are exactly 18. This could result in the `depositJunior` and `depositSenior` functions receiving a value of 0, leading to incorrect calculations or unexpected behavior.

## Impact
If the `standardize` function returns a value of 0 due to the asset's decimals being exactly 18, it could potentially cause the `depositJunior` and `depositSenior` functions to proceed with incorrect calculations or fail unexpectedly.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGlobals.sol#L142C1-L150C6
```solidity
function standardize(uint256 amount, address asset) external view returns (uint256 standardizedAmount) {
    standardizedAmount = amount;
    if (IERC20Metadata(asset).decimals() < 18) { 
        standardizedAmount *= 10 ** (18 - IERC20Metadata(asset).decimals()); 
    } 
    else if (IERC20Metadata(asset).decimals() > 18) { 
        standardizedAmount /= 10 ** (IERC20Metadata(asset).decimals() - 18);
    }
    return standardizedAmount; // Add this line to ensure a return value
}
```

## Tool used
Manual Review

## Recommendation
It is recommended to modify the `standardize` function to ensure that it always returns a value, regardless of the asset's decimals. This can be achieved by adding a return statement at the end of the function to return the `standardizedAmount`.

**Comment by pseudonaut** [comment]
This occurs natively already, not valid
