### ISSUE TITLE
phenom - Title: Inaccurate Due Date Calculation in OCC Locker due to Friday Handling

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#308]
phenom

medium

# Title: Inaccurate Due Date Calculation in OCC Locker due to Friday Handling

## Summary

The vulnerability pertains to the calculation of the `paymentDueBy` timestamp within the `applyCombine` function.

## Vulnerability Detail

The vulnerability arises from the calculation of the `paymentDueBy` timestamp using the expression `block.timestamp - block.timestamp % 7 days + 9 days + paymentInterval`. This expression aims to set the `paymentDueBy` timestamp to the next Friday after the current block's timestamp, with a minimum lead-time of 9 days, plus the `paymentInterval`. However, there's a potential issue with this calculation when the current timestamp falls on a Friday. If the current timestamp is already a Friday, the expression will set the `paymentDueBy` timestamp to a date that's 9 days later than the current Friday, which might not align with the desired behavior.

## Impact

The impact of this vulnerability could lead to incorrect calculation of the `paymentDueBy` timestamp for newly created loans. If the current timestamp falls on a Friday, the calculation may result in a `paymentDueBy` timestamp that's 9 days later than expected, potentially causing issues with loan scheduling and payment processing.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L742
```solidity
uint256 fridayTimestamp = (block.timestamp + 1 days - (block.timestamp % (7 days))) % (7 days); // Calculate next Friday
uint256 nextFriday = fridayTimestamp + 9 days + paymentInterval; // Add 9 days and paymentInterval
```

## Tool used

Manual Review

## Recommendation

It's recommended to adjust the calculation of the `paymentDueBy` timestamp to ensure consistency and accuracy, particularly when the current timestamp falls on a Friday. By using the provided code snippet to calculate the next Friday and then adding the desired lead-time and payment interval, the `paymentDueBy` timestamp can be correctly determined, mitigating the vulnerability. Additionally, thorough testing should be conducted to verify the correctness of the fix and ensure proper loan scheduling and payment processing.

**Comment by pseudonaut** [comment]
Mathematically this issue raised has no validity
