### ISSUE TITLE
phenom - Integer Underflow Vulnerability in lpBurnable Calculation of _forwardYield Function

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#309]
phenom

medium

# Integer Underflow Vulnerability in lpBurnable Calculation of _forwardYield Function

## Summary

This report identifies a potential vulnerability in the `_forwardYield` function of a Solidity smart contract. The vulnerability is related to the calculation of the `lpBurnable` variable.

## Vulnerability Detail

The vulnerability arises from the calculation of `lpBurnable` using the expression `(amount - basis) * lp / amount * (BIPS - compoundingRateBIPS) / BIPS`. There's a risk of integer underflow or truncation if `basis` is greater than `amount`, potentially leading to unexpected behavior or incorrect results.

## Impact

The impact of this vulnerability could include incorrect calculation of `lpBurnable` and potentially incorrect behavior in the contract logic. Depending on the values of `amount`, `basis`, `lp`, `BIPS`, and `compoundingRateBIPS`, this vulnerability could result in integer underflow, leading to negative values or unexpected results.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L311
```solidity
uint256 lpBurnable;
if (amount > basis) {
    lpBurnable = (amount - basis) * lp * (BIPS - compoundingRateBIPS) / (amount * BIPS);
} else {
    lpBurnable = 0; // or handle the situation according to your logic
}
```

## Tool used

Manual Review

## Recommendation

It's recommended to carefully review and adjust the calculation of `lpBurnable` to prevent integer underflow or truncation. Ensure that appropriate checks are in place to handle scenarios where `basis` may be greater than `amount`, and consider using safe arithmetic operations or additional validation logic to mitigate the risk of unexpected behavior. Thorough testing should also be conducted to verify the correctness of the fix and ensure the integrity of the contract logic.

**Comment by pseudonaut** [comment]
This is literally checked right before the call
