### ISSUE TITLE
AMOW - Splitting deposits in `ZivoeTranches` is more profitable than depositing all at once

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#322]
AMOW

high

# Splitting deposits in `ZivoeTranches` is more profitable than depositing all at once

## Summary
Splitting a deposit into smaller ones can be more profitable when the `avgRatio` is kept at `lowerRatioIncentiveBIPS` and `upperRatioIncentiveBIPS` thresholds
## Vulnerability Detail
Depositing in either of the tranches rewards the user with incentives. Incentives are based on the supplies ratio between junior and senior tranche tokens (for simplicity we will use the default values which are subject to changes) which correspond to:  

lowerRatioIncentiveBIPS = 1000 (10%)  

upperRatioIncentiveBIPS = 3500 (35%)  

maxTrancheRatioBIPS = 4500 (45%)  

Whenever Junior:Senior average ratio is below 10%, users receive max rewards for depositing in the junior tranche, when it's between 10%-34% max reward multiplier decreases linearly until it passes the upper ratio and receives min rewards.
```solidity
        if (avgRatio <= lowerRatioIncentiveBIPS) {
            avgRate = maxZVEPerJTTMint;
        } else if (avgRatio >= upperRatioIncentiveBIPS) {
            avgRate = minZVEPerJTTMint;
        } else {
            avgRate = maxZVEPerJTTMint - diffRate * (avgRatio - lowerRatioIncentiveBIPS) / (upperRatioIncentiveBIPS - lowerRatioIncentiveBIPS);
        ...
        reward = avgRate * deposit / 1 ether;
        }
```
  
Imagine juniorSupp = 0, seniorSupp = 1000, J:S ratio = 0  

Bob is planning to deposit 300 tokens into the junior tranche.  
```solidity
        uint256 startRatio = juniorSupp * BIPS / seniorSupp; // 0
        uint256 finalRatio = (juniorSupp + deposit) * BIPS / seniorSupp; // 300/1000 = 3000 BIPS
        uint256 avgRatio = (startRatio + finalRatio) / 2; // 1500 BIPS
```
        
          
avgRatio at 1500 BIPS is within the 1000-3500 BIPS thresholds and triggers last else statement crafting a custom avgRate below the maximum.
```solidity
         else {
            avgRate = maxZVEPerJTTMint - diffRate * (avgRatio - lowerRatioIncentiveBIPS) / (upperRatioIncentiveBIPS - lowerRatioIncentiveBIPS);  }
```

However if Bob deposits a custom amount (200 tokens) that would put the `avgRatio = 1000 (lowerRatioIncentiveBIPS)`, he would trigger the first if-statement and reap maxZVEPerJTTMint rewards. Afterwards, Bob will deposit the other 100 tokens of the initial deposit multiplied by a custom avgRate below the max one.  
```solidity
        if (avgRatio <= lowerRatioIncentiveBIPS) {
            avgRate = maxZVEPerJTTMint;}
```

Bob's rewards become 200 * maxZVEPerJTTMint + 100 * customRate > 300 * customRate.  
Bob profits on behalf of the protocol and its' users.  
Similar logic can be applied whenever the avgRatio would surpass the upperRatioIncentiveBIPS so only a part of the deposit would receive minZVEPerJTTMint incentives while the initial one would have a custom, higher avgRate.  

Attack vector is just as relevant for [seniorDeposit](https://github.com/Zivoe/zivoe-core-foundry/blob/ad27cffdf96eaaa33274bfba0dda9b60e36d29a2/src/ZivoeTranches.sol#L236) too. 
## Impact
Protocol loss
## Code Snippet
```solidity
    function rewardZVEJuniorDeposit(uint256 deposit) public view returns (uint256 reward) {


        (uint256 seniorSupp, uint256 juniorSupp) = IZivoeGlobals_ZivoeTranches(GBL).adjustedSupplies();


        uint256 avgRate;    // The avg ZVE per stablecoin deposit reward, used for reward calculation.


        uint256 diffRate = maxZVEPerJTTMint - minZVEPerJTTMint;


        uint256 startRatio = juniorSupp * BIPS / seniorSupp;
        uint256 finalRatio = (juniorSupp + deposit) * BIPS / seniorSupp;
        uint256 avgRatio = (startRatio + finalRatio) / 2;


        if (avgRatio <= lowerRatioIncentiveBIPS) {
            avgRate = maxZVEPerJTTMint;
        } else if (avgRatio >= upperRatioIncentiveBIPS) {
            avgRate = minZVEPerJTTMint;
        } else {
            avgRate = maxZVEPerJTTMint - diffRate * (avgRatio - lowerRatioIncentiveBIPS) / (upperRatioIncentiveBIPS - lowerRatioIncentiveBIPS);
        }


        reward = avgRate * deposit / 1 ether;
        ...
    }
```
## Tool used

Manual Review

## Recommendation
Make incentives equal for everyone

Duplicate of #232

**Comment by pseudonaut** [comment]
Math doesn't seem valid, e.g. there is no different in output of rewards provided to validate the findings, only example inputs and assumption that the output is different

**Comment by pseudonaut** [comment]
Furthermore, of no concern

**Comment by deadrosesxyz** [comment]
Escalate

Should be a valid finding. There is a clearly shown loss of funds, which should not be seen as _design choice_. Impact would be especially high for whale deposits. Furthermore, here's a similar [finding](https://github.com/sherlock-audit/2024-03-woofi-swap-judging/issues/20) recently validated.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Should be a valid finding. There is a clearly shown loss of funds, which should not be seen as _design choice_. Impact would be especially high for whale deposits. Furthermore, here's a similar [finding](https://github.com/sherlock-audit/2024-03-woofi-swap-judging/issues/20) recently validated.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by armormadeofwoe** [comment]
In #232 there is a comment that issue is known while the README paragraph for known issues/acceptable risks is empty. Similar issue has been validated 2 months ago, as linked in the comment above. I respectfully insist on re-reviewing this.

**Comment by panprog** [comment]
I maintain the view that it's a design choice developers took to simplify the curve calculations. They might need to make user aware of this via UI or something, but other than that their choice is valid, so this issue is low.

**Comment by WangSecurity** [comment]
Can someone please clear [this](https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/322#issuecomment-2081169105) comment? The report doesn't do the calculations when Bob first deposits 200 and then 100, but claims that it's more than depositing 300 at once. Just to clarify what would be the loss in such example.

**Comment by panprog** [comment]
@WangSecurity 
I believe the developer didn't clearly understand the report in that comment. But in the "main" dup (#232) sponsor did understand. It makes sense to discuss / decide on the main issue #232 as it has 2 dups and also better description and both scenarios with calculations.

**Comment by WangSecurity** [comment]
Thank you for forwarding to this report. #232 nicely explains how it can be less rewards for the user if the ratio is below the lower bound and how at the upper bound the user is able to intentionally get more tokens. Hence, I believe this issue should be valid. Since #232 is the main report and explains the issue better, planning to accept the escalation and duplicate the issue with #232 as best and assign medium severity cause it requires for the ratio to be at the lower or upper bound.

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #232

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [deadrosesxyz](https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/322/#issuecomment-2105739576): accepted
