### ISSUE TITLE
AMOW - yieldTarget can be manipulated right before yield distribution to increase seniorProportion rewards.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#323]
AMOW

high

# yieldTarget can be manipulated right before yield distribution to increase seniorProportion rewards.

## Summary
Tranche token holders are incentivized and able to dodge `seniorProportionShortfall` rewards and have their rewards calculated with `seniorProportionBase`.
## Vulnerability Detail
When `ZivoeYDL.distributeYield` is called, the yield of the contract is gathered and split among protocol recipients, senior/junior holders and if any funds are left - residual recipients. Senior holders have their proportion calculated here
```solidity
    function seniorProportion(
        uint256 yD, uint256 yT, uint256 eSTT, uint256 eJTT, uint256 Y, uint256 Q, uint256 T
    ) external pure returns (uint256 sP) {
        // Shortfall of yield.
        if (yD < yT) { sP = seniorProportionShortfall(eSTT, eJTT, Q); } 
        // Excess yield and historical out-performance.
        else { sP = seniorProportionBase(yD, eSTT, Y, T); }
    }
```
Problem arises in the if-statement where the yieldDistributable (yD) is checked against the yieldTarget (yT).  
yT is calculated only when `distributeYield` is called and the output is used in seniorProportion calculations. Two of the variables used in yieldTarget formula are subject to governance changes.
```solidity
        @notice     Calculates amount of annual yield required to meet target rate for both tranches.
        @dev        (Y * T * (eSTT + eJTT * Q / BIPS) / BIPS) / 365
        @param      eSTT = ema-based supply of zSTT                  (units = WEI)
        @param      eJTT = ema-based supply of zJTT                  (units = WEI)
        @param      Y    = target annual yield for senior tranche   (units = BIPS) // can change through governance
        @param      Q    = multiple of Y                            (units = BIPS) // can change through governance
        @param      T    = # of days between distributions          (units = integer)
        @return     yT   = yield target for the senior and junior tranche combined.
        @dev        Precision of the return value, yT, is in WEI (10**18).
    */
    function yieldTarget(uint256 eSTT, uint256 eJTT, uint256 Y, uint256 Q, uint256 T) public pure returns (uint256 yT) {
        yT = (Y * T * (eSTT + eJTT * Q / BIPS) / BIPS) / 365;
    }
```
Whenever tranche token holders anticipate the yield target would not be met, proposals can be passed to reduce targetAPYBIPS and targetRatioBIPS, decreasing the yT enough so it would look as if yieldDistributable has reached the target yield and trigger `seniorProportionBase` instead of `seniorProportionShortfall`.  

Tranche token holders receive more rewards on the back of residual recipients (which after unlock() is invoked [are the same](https://github.com/Zivoe/zivoe-core-foundry/blob/ad27cffdf96eaaa33274bfba0dda9b60e36d29a2/src/ZivoeYDL.sol#L336-L352) as protocol recipients). Yield targets should be set before distribution period starts, not right at its' end.
## Impact
Loss of funds for the protocol
## Code Snippet
```solidity
    function seniorProportion(
        uint256 yD, uint256 yT, uint256 eSTT, uint256 eJTT, uint256 Y, uint256 Q, uint256 T
    ) external pure returns (uint256 sP) {
        // Shortfall of yield.
        if (yD < yT) { sP = seniorProportionShortfall(eSTT, eJTT, Q); } 
        // Excess yield and historical out-performance.
        else { sP = seniorProportionBase(yD, eSTT, Y, T); }
    }
```
## Tool used

Manual Review

## Recommendation
Make snapshot of next yieldTarget after each `ZivoeYDL.distributeYield()` call

**Comment by pseudonaut** [comment]
Not relevant
