### ISSUE TITLE
AMOW - Splitting ITO into 2 or more airdrops is more profitable

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#328]
AMOW

medium

# Splitting ITO into 2 or more airdrops is more profitable

## Summary
User can split their ITO into 2, claim the first airdrop, burn their zSTT and zJTT and get more vested tokens from the second airdrop claim
## Vulnerability Detail
Once ITO is over, users are able to call [`claimAirdrop()`](https://github.com/Zivoe/zivoe-core-foundry/blob/ad27cffdf96eaaa33274bfba0dda9b60e36d29a2/src/ZivoeITO.sol#L203) which transfers their senior and junior creditsOwned, calls `createVestingSchedule()` where each user receives a non-revokable vesting schedule for a portion of $ZVE awards equal to 5% of $ZVE total supply. 
```solidity
        IERC20(IZivoeGlobals_ITO(GBL).zJTT()).safeTransfer(depositor, juniorCreditsOwned);
        IERC20(IZivoeGlobals_ITO(GBL).zSTT()).safeTransfer(depositor, seniorCreditsOwned / 3);
```

```solidity 
        uint256 upper = seniorCreditsOwned + juniorCreditsOwned; // msg.sender's credits
        uint256 middle = IERC20(IZivoeGlobals_ITO(GBL).ZVE()).totalSupply() / 20; // 5% of $ZVE
        uint256 lower = IERC20(IZivoeGlobals_ITO(GBL).zSTT()).totalSupply() * 3 + ( // all users' credits
            IERC20(IZivoeGlobals_ITO(GBL).zJTT()).totalSupply() 
        );
        ...
        if (upper * middle / lower > 0) {
            ITO_IZivoeRewardsVesting(IZivoeGlobals_ITO(GBL).vestZVE()).createVestingSchedule(
                depositor, 0, 360, upper * middle / lower, false
            );
        }
```
After receiving one's first airdrop, they can burn their tranche tokens to decrease the totalSupply. If the totalSupply of zSTT and zJTT goes down, `uint256 lower` will decrease, vesting amount increases, making future calls of `claimAirdrop` more profitable for everyone. Protocol will end up paying more than the planned 5% of $ZVE totalSupply.  
Attack becomes more profitable in cases of user collusion or if a majority staker burns major share of zSTT and zJTT.
## Impact
Protocol loss
## Code Snippet
```solidity
        uint256 upper = seniorCreditsOwned + juniorCreditsOwned;
        uint256 middle = IERC20(IZivoeGlobals_ITO(GBL).ZVE()).totalSupply() / 20;
        uint256 lower = IERC20(IZivoeGlobals_ITO(GBL).zSTT()).totalSupply() * 3 + (
            IERC20(IZivoeGlobals_ITO(GBL).zJTT()).totalSupply()
        );


        emit AirdropClaimed(depositor, seniorCreditsOwned / 3, juniorCreditsOwned, upper * middle / lower);


        IERC20(IZivoeGlobals_ITO(GBL).zJTT()).safeTransfer(depositor, juniorCreditsOwned);
        IERC20(IZivoeGlobals_ITO(GBL).zSTT()).safeTransfer(depositor, seniorCreditsOwned / 3);


        if (upper * middle / lower > 0) {
            ITO_IZivoeRewardsVesting(IZivoeGlobals_ITO(GBL).vestZVE()).createVestingSchedule(
                depositor, 0, 360, upper * middle / lower, false
            )
        }
```
## Tool used

Manual Review

## Recommendation
Once the ITO ends, store ZVE, zJTT and zSTT totalsupplies into state variables and use them instead of dynamic current supplies.

Duplicate of #12

**Comment by pseudonaut** [comment]
Valid, need to snapshot at end
