### ISSUE TITLE
AMOW - `OCE_ZVE.forwardEmissions()` will forward freshly deposited balance alongside decayed one

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#331]
AMOW

medium

# `OCE_ZVE.forwardEmissions()` will forward freshly deposited balance alongside decayed one

## Summary
Freshly pushed funds into `OCE_ZVE.sol` locker can be prematurely forwarded with currently decaying ones through `forwardEmissions()` 
## Vulnerability Detail
[`forwardEmissions()`](https://github.com/Zivoe/zivoe-core-foundry/blob/ad27cffdf96eaaa33274bfba0dda9b60e36d29a2/src/lockers/OCE/OCE_ZVE.sol#L131) function catches the current ZVE balance of the OCE_ZVE locker and calls `_forwardEmissions` where it checks the decay rate and distributes the emissions. 
```solidity
    function forwardEmissions() external nonReentrant {
        uint zveBalance = IERC20(IZivoeGlobals_OCE_ZVE(GBL).ZVE()).balanceOf(address(this));
        _forwardEmissions(zveBalance - decay(zveBalance, block.timestamp - lastDistribution));
        lastDistribution = block.timestamp;
    }
```
If the function is called right after new funds are pushed into the locker, a portion of the fresh deposit will be immediately sent out despite not having decayed as the rest. It is profitable to wait for decay to accumulate and call the function right after new funds are pushed.
## Impact
Unexpected behaviour / Unfair distribution of rewards
## Code Snippet
```solidity
    function forwardEmissions() external nonReentrant {
        uint zveBalance = IERC20(IZivoeGlobals_OCE_ZVE(GBL).ZVE()).balanceOf(address(this));
        _forwardEmissions(zveBalance - decay(zveBalance, block.timestamp - lastDistribution));
        lastDistribution = block.timestamp;
    }
```
## Tool used

Manual Review

## Recommendation
Implement `forwardEmissions()` call within `pushToLocker()` so lastDistribution counter will reset and start a new decay.  

```solidity
    function pushToLocker(address asset, uint256 amount, bytes calldata data) external override onlyOwner {
        require(
            asset == IZivoeGlobals_OCE_ZVE(GBL).ZVE(), 
            "OCE_ZVE::pushToLocker() asset != IZivoeGlobals_OCE_ZVE(GBL).ZVE()"
        );
        forwardEmissions(); // <----- add this 
        IERC20(asset).safeTransferFrom(owner(), address(this), amount);
    }
```

Duplicate of #282

**Comment by pseudonaut** [comment]
Not relevant, likely will call forwardEmissions prior anyways,
