### ISSUE TITLE
0xmuxyz - If a staker would enter the blacklist of USDC or USDT that may be used as the `_rewardsToken`, the amount of the `_rewardsToken`, which was supposed to be transferred to the staker-blacklisted, will be stuck forever inside the ZivoeRewards contract

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#339]
0xmuxyz

medium

# If a staker would enter the blacklist of USDC or USDT that may be used as the `_rewardsToken`, the amount of the `_rewardsToken`, which was supposed to be transferred to the staker-blacklisted, will be stuck forever inside the ZivoeRewards contract

## Summary
Some ERC20 tokens has a **blacklist** feature (i.e. USDC, USDT, etc).

Within the ZivoeRewards#`_getRewardAt()`, if USDC or USDT would be used as the `_rewardsToken` and a staker has already entered the blacklist of these `_rewardsToken` (USDC or USDT) before the staker would call the ZivoeRewards#`fullWithdraw()` or directly call the ZivoeRewards#`getRewards()`, the TX of the ZivoeRewards#`fullWithdraw()` or the ZivoeRewards#`getRewards()` would be reverted - due to that transferring the `_rewardsToken` to the **staker-blacklisted** (`_msgSender()`) is reverted inside the ZivoeRewards#`_getRewardAt()`. 
 
As a result, the amount of the `_rewardToken`, which was supposed to be transferred to the **staker-blacklisted** (`_msgSender()`) will be remained inside the ZivoeRewards contract. 

Since there is **no** logic (function) to withdraw the amount of the `_rewardsToken`-remained inside the ZivoeReward contract, the remained-amount of the `_rewardToken` would be stuck forever inside the ZivoeRewards contract. 

## Vulnerability Detail

When a staker would withdraw the full amount of the staking token and receive the rewards, the staker would call the ZivoeRewards#`fullWithdraw()`.
Within the ZivoeRewards#`fullWithdraw()`, the ZivoeRewards#`withdraw()` and the ZivoeRewards#`getRewards()` would be called like this:
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L248
```solidity
    /// @notice Simultaneously calls withdraw() and getRewards() for convenience.
    function fullWithdraw() external {
        withdraw(_balances[_msgSender()]);
        getRewards(); ///<---------- @audit
    }
```

Within the ZivoeRewards#`getRewards()`, the ZivoeRewards#`_getRewardAt()` would be called in the for-loop like this:
(NOTE：A staker can **directly** call the  ZivoeRewards#`getRewards()` as well)
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L282
```solidity
    /// @notice Claim rewards for all possible _rewardTokens.
    function getRewards() public updateReward(_msgSender()) {
        for (uint256 i = 0; i < rewardTokens.length; i++) { _getRewardAt(i); } ///<---------- @audit
    }
```
    
Within the ZivoeRewards#`_getRewardAt()`, the amount (`reward`) of the `_rewardsToken` would be transferred to the staker (`msg.sender`) like this:
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L292
```solidity
    /// @notice Claim rewards for a specific _rewardToken.
    /// @param index The index to claim, corresponds to a given index of rewardToken[].
    function _getRewardAt(uint256 index) internal nonReentrant {
        address _rewardsToken = rewardTokens[index];
        uint256 reward = rewards[_msgSender()][_rewardsToken];
        if (reward > 0) {
            ...
            IERC20(_rewardsToken).safeTransfer(_msgSender(), reward);  ///<---------- @audit
            ...
        }
    }
```

However, within the ZivoeRewards#`_getRewardAt()`, if USDC or USDT would be used as the `_rewardsToken` and a staker has already entered the blacklist of these `_rewardsToken` (USDC or USDT) before the staker would call the ZivoeRewards#`fullWithdraw()` or directly call the ZivoeRewards#`getRewards()`, the TX of the ZivoeRewards#`fullWithdraw()` or the ZivoeRewards#`getRewards()` would be reverted - due to that transferring the `_rewardsToken` to the **staker-blacklisted** (`_msgSender()`) is reverted inside the ZivoeRewards#`_getRewardAt()`. 
 
As a result, the amount of the `_rewardToken`, which was supposed to be transferred to the **staker-blacklisted** (`_msgSender()`) will be remained inside the ZivoeRewards contract. 

Since there is **no** logic (function) to withdraw the amount of the `_rewardsToken`-remained inside the ZivoeReward contract, the remained-amount of the `_rewardToken` would be stuck forever inside the ZivoeRewards contract. 

## Impact
The amount of the `_rewardToken`, which was supposed to be transferred to the **staker-blacklisted** (`_msgSender()`) will be remained and stuck inside the ZivoeRewards contract. 

## Code Snippet
- https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L292

## Tool used
- Manual Review

## Recommendation
Within the ZivoeRewards contract, consider adding a function in order for an admin to withdraw the amount of the `_rewardToken`, which is stuck in the ZivoeRewards contract.

**Comment by pseudonaut** [comment]
Not relevant
