### ISSUE TITLE
0xmuxyz - The extended-payment due of the given loan `id` (`extensions[id]`) would not be considered in the validation of the OCC_Modular#`markDefault()`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#344]
0xmuxyz

medium

# The extended-payment due of the given loan `id` (`extensions[id]`) would not be considered in the validation of the OCC_Modular#`markDefault()`

## Summary
Within the OCC_Modular#`markDefault()`, the extended-payment due of the given loan `id` (`extensions[id]`) would **not** be considered in the validation. 

This allow an underwriter to mark the given loan `id` as the "default" state via the OCC_Modular#`markDefault()` - even if the  given loan `id` was approved to extend their payment due and the extended-payment due has **not** elapsed **yet**.

This lead to the contradicted-status between the **actual status** (**Not** defaulted yet) and the **marked-status**  (**Already** defaulted) would happen for the loan `id`, which was approved to extend their payment due.

## Vulnerability Detail

When an underwriter would mark a loan of a borrower as a "default" state, the underwriter would call the OCC_Modular#`markDefault()`. 
Within the OCC_Modular#`markDefault()`, it would be checked whether or not the current timestamp (`block.timestamp`) has elapsed the sum of the payment due and the grace period (`loans[id].paymentDueBy + loans[id].gracePeriod`).
Then, the `LoanState.Defaulted` would be stored into the state of the loan `id` (`loans[id].state`) like this:
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L608-L611
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L614
```solidity
    /// @notice Mark a loan insolvent if a payment hasn't been made beyond the corresponding grace period.
    /// @param  id The ID of the loan.
    function markDefault(uint256 id) external isUnderwriter {
        require(loans[id].state == LoanState.Active, "OCC_Modular::markDefault() loans[id].state != LoanState.Active");
        require( ///<----------------- @audit
            loans[id].paymentDueBy + loans[id].gracePeriod < block.timestamp, 
            "OCC_Modular::markDefault() loans[id].paymentDueBy + loans[id].gracePeriod >= block.timestamp"
        );
        ...
        loans[id].state = LoanState.Defaulted;  ///<----------------- @audit
        ...
    }
```

When a borrower would like make an extension request that ask an underwriter for extending the payment due of their loan (loan `id`), the borrower would call the OCC_Modular#`applyExtension()` with the loan `id` to be asked for extending the payment due.

Within the OCC_Modular#`applyExtension()`, the `extensions[id]` storage of a given loan `id`, which the extended-payment due will be stored, would be initialized like this:
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L854
```solidity
    /// @notice Applies an extension to a loan.
    /// @param  id The ID for the loan.
    function applyExtension(uint256 id) external {
        require(
            _msgSender() == loans[id].borrower, 
            "OCC_Modular::applyExtension() _msgSender() != loans[id].borrower"
        );
        require(extensions[id] > 0,  "OCC_Modular::applyExtension() extensions[id] == 0");
        ...
        
        loans[id].paymentsRemaining += extensions[id];
        loans[id].term += extensions[id];  
        extensions[id] = 0; ///<------------------------------ @audit - initialized
    }
```

Then, when a underwriter would approve an extension request from a borrower, the underwriter would call the OCC_Modular#`approveExtension()`.
Within the OCC_Modular#`approveExtension()`, a given `intervals` (The amount of intervals to approve for extension) would be stored into the `extensions[id]` storage like this:
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L926
```solidity
    /// @notice Approves an extension for a loan.
    /// @param  id The ID for the loan.
    /// @param  intervals The amount of intervals to approve for extension.
    function approveExtension(uint256 id, uint256 intervals) external isUnderwriter {
        ...
        extensions[id] = intervals; ///<------------------- @audit - i.e. 12, 24, etc.
    }
```

However, within the OCC_Modular#`markDefault()`, the extended-payment due of the given loan `id` (`extensions[id]`) would **not** be considered in the validation. 

This is problematic. Because, even if an loan `id`, which was approved (by an underwriter) to extend their payment due, has **not** elapsed the extended-payment due (`extensions[id]`), the underwriter can mark it as the **"default"** state (`LoanState.Defaulted`) to the given loan `id` via the OCC_Modular#`markDefault()`. 

SInce there is **no** way for the underwriter to resume it once the loan `id` would be marked as the **"default"** state (`LoanState.Defaulted`), the underwriter can **not** resume it.

## Impact

This lead to the contradicted-status between the **actual status** (**Not** defaulted yet) and the **marked-status**  (**Already** defaulted) would happen for the loan `id`, which was approved to extend their payment due.

## Code Snippet
- https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L606-L618

## Tool used
- Manual review

## Recommendation
Within the OCC_Modular#`markDefault()`, consider adding a validation in order to check whether or not the extended-payment due has **not** elapsed **yet** like this:
```diff
    /// @notice Mark a loan insolvent if a payment hasn't been made beyond the corresponding grace period.
    /// @param  id The ID of the loan.
    function markDefault(uint256 id) external isUnderwriter {
        require(loans[id].state == LoanState.Active, "OCC_Modular::markDefault() loans[id].state != LoanState.Active");
        require( 
            loans[id].paymentDueBy + loans[id].gracePeriod < block.timestamp,  
            "OCC_Modular::markDefault() loans[id].paymentDueBy + loans[id].gracePeriod >= block.timestamp"
        );
     
+       if (extensions[id] > 0) {
+            require( 
+                loans[id].paymentDueBy + loans[id].gracePeriod  + extensions[id] < block.timestamp, 
+                "The given loan id has not elapsed the extended-payment due yet"
+.           );
+       }
   
        ...
        loans[id].state = LoanState.Defaulted;  
        ...
    }
```

**Comment by pseudonaut** [comment]
Not relevant or desired functionality
