### ISSUE TITLE
0xmuxyz - Misaccounting of the `redemptionsQueuedSenior` and the `redemptionsQueuedJunior` in the OCR_Modular#`processRequest()` would happen - due to unnecessary increment

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#351]
0xmuxyz

high

# Misaccounting of the `redemptionsQueuedSenior` and the `redemptionsQueuedJunior` in the OCR_Modular#`processRequest()` would happen - due to unnecessary increment

## Summary
Within the OCR_Modular#`processRequest()` above, **only** the `redemptionsAllowedJunior` or the `redemptionsAllowedSenior` is supposed to be **decremented**.

However, within the OCR_Modular#`processRequest()` above, the `redemptionsQueuedSenior` or the `redemptionsQueuedJunior` would **also** be **incremented** at the same time.

This is problematic. Because both the `redemptionsQueuedSenior` and the `redemptionsQueuedJunior` are supposed to be reset after the OCR_Modular#`processRequest()` would be executed.

This lead to misaccounting of the `redemptionsQueuedSenior` and the `redemptionsQueuedJunior`. 

## Vulnerability Detail
When a depositor of a senior or junior tranche would like to redeem zSTT or zJTT for the stablecoin, the depositor need to take the following two redemption steps: 
- 1/ Calling the OCR_Modular#`createRequest()`
- 2/ Calling the OCR_Modular#`processRequest()` - after the sum of the current epoch and 14 days (`epoch + 14 days`) would elapse.

Within the OCR_Modular#`createRequest()`, the following updates would happen:
- if a request to be created for a senior tranche (`seniorElseJunior == true`), the `redemptionsQueuedSenior` would be incremented by adding a given `amount ` 
- if if a request to be created for a junior tranche (`seniorElseJunior == false`), the `redemptionsQueuedJunior` would be incremented by adding a given `amount ` 
   https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCR/OCR_Modular.sol#L220
   https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCR/OCR_Modular.sol#L224
```solidity
    /// @notice Creates a redemption request.
    /// @param  amount The amount to deposit for the request.
    /// @param  seniorElseJunior The tranche to deposit for (true = Senior, false = Junior).
    function createRequest(uint256 amount, bool seniorElseJunior) external _tickEpoch nonReentrant {
        ...
        requests[requestCounter] = Request(_msgSender(), amount, epoch + 14 days, seniorElseJunior); 
        if (seniorElseJunior) {
            redemptionsQueuedSenior += amount; ///<----------------- ＠audit
            ...
        }
        else {
            redemptionsQueuedJunior += amount; ///<----------------- ＠audit
            ...
        }
        requestCounter += 1; /// @audit info - This is also used as a "requestId"
    }
```
   
Within the OCR_Modular#`processRequest()`, the following updates would happen:
- if a request to be processed for a senior tranche (`requests[id].seniorElseJunior == true`), 
  - the `redemptionsAllowedSenior` would be decremented by subtracting the `requests[id].amount` 
  - the `redemptionsQueuedSenior` would be incremented by adding the `requests[id].amount` 
- if if a request to be processed for a junior tranche (`requests[id].seniorElseJunior == false`), 
  - the `redemptionsAllowedJunior` would be decremented by subtracting the `requests[id].amount` 
  - the `redemptionsQueuedJunior` would be incremented by adding the `requests[id].amount` 
    https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCR/OCR_Modular.sol#L285
    https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCR/OCR_Modular.sol#L287
    https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCR/OCR_Modular.sol#L293
    https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCR/OCR_Modular.sol#L295
```solidity
    /// @notice Processes a redemption request.
    /// @param  id The ID of the request to process.
    function processRequest(uint256 id) external _tickEpoch nonReentrant {
        ...
        requests[id].unlocks = epoch + 14 days;
        ....

        if (requests[id].seniorElseJunior) {
            ...
            redemptionsAllowedSenior -= requests[id].amount; ///<--------- ＠audit
            ...
            redemptionsQueuedSenior += requests[id].amount; ///<--------- ＠audit
        }
        else {
            ...
            redemptionsAllowedJunior -= requests[id].amount; ///<--------- ＠audit
            ...
            redemptionsQueuedJunior += requests[id].amount;  ///<--------- ＠audit
        }
        ...
```

Whenever the functions in the OCR_Modular contract would be called, the OCR_Modular#`tickEpoch()` would **also** be called via the OCR_Modular#`_tickEpoch()` modifier-implemented on these functions.

Within the OCR_Modular#`tickEpoch()`, if the current timestamp (`block.timestamp`) has already elapsed the current period (`epoch + 14 days`),
- the `redemptionsQueuedJunior` would be stored into the `redemptionsAllowedJunior`.
- the `redemptionsQueuedSenior` would be stored into the `redemptionsAllowedSenior`.

Then,
- the `redemptionsQueuedJunior` would be initialized by storing `0`.
- the `redemptionsQueuedSenior` would be initialized by storing `0`.

Then,
- a new epoch (`epoch += 14 day`) would be started.
   https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCR/OCR_Modular.sol#L311-L316
```solidity
    /// @notice Ticks the epoch.
    function tickEpoch() public {
        while (block.timestamp >= epoch + 14 days) { ///<--------- ＠audit
            epoch += 14 days; ///<--------- ＠audit
            redemptionsAllowedJunior += redemptionsQueuedJunior; ///<--------- ＠audit
            redemptionsAllowedSenior += redemptionsQueuedSenior; ///<--------- ＠audit
            redemptionsQueuedJunior = 0; ///<--------- ＠audit
            redemptionsQueuedSenior = 0; ///<--------- ＠audit
            ...
```

Within the OCR_Modular#`processRequest()` above, **only** the `redemptionsAllowedJunior` or the `redemptionsAllowedSenior` is supposed to be **decremented**.

However, within the OCR_Modular#`processRequest()` above, the `redemptionsQueuedSenior` or the `redemptionsQueuedJunior` would **also** be **incremented** at the same time.
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCR/OCR_Modular.sol#L287
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCR/OCR_Modular.sol#L295
```solidity
        if (requests[id].seniorElseJunior) {
            ...
            redemptionsAllowedSenior -= requests[id].amount;
            ...
            redemptionsQueuedSenior += requests[id].amount; ///<--------- ＠audit
        }
        else {
            ...
            redemptionsAllowedJunior -= requests[id].amount;
            ...
            redemptionsQueuedJunior += requests[id].amount;  ///<--------- ＠audit
        }
```
This is problematic. Because both the `redemptionsQueuedSenior` and the `redemptionsQueuedJunior` are supposed to be **reset** after the OCR_Modular#`processRequest()` would be executed.

## Impact
This lead to misaccounting of the `redemptionsQueuedSenior` and the `redemptionsQueuedJunior`. 

## Code Snippet
- https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCR/OCR_Modular.sol#L287
- https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCR/OCR_Modular.sol#L295

## Tool used
- Manual Review

## Recommendation
Within the OCR_Modular#`processRequest()`, consider removing the code that increment the `redemptionsQueuedSenior` or the `redemptionsQueuedJunior` like this:
```diff
    function processRequest(uint256 id) external _tickEpoch nonReentrant {
        ...
        requests[id].unlocks = epoch + 14 days;
        ...

        uint256 redeemAmount;

        if (requests[id].seniorElseJunior) {
            ...
            redemptionsAllowedSenior -= requests[id].amount; 
            ...
-           redemptionsQueuedSenior += requests[id].amount;
        }
        else {
            ...
            redemptionsAllowedJunior -= requests[id].amount;
            ...
-           redemptionsQueuedJunior += requests[id].amount;
        }
        ...
```

**Comment by pseudonaut** [comment]
OCR_Modular is out of scope
