### ISSUE TITLE
0xmuxyz - Lack of logic (function) to call the ZivoeTranches#`unlock()` in the ZivoeITO contract

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#355]
0xmuxyz

medium

# Lack of logic (function) to call the ZivoeTranches#`unlock()` in the ZivoeITO contract

## Summary
According to the [reply](https://discord.com/channels/812037309376495636/1226909446891110512/1227128551879348245) for the question in the discord, the ZivoeTranches contract is supposed to be unlocked after ITO is end like this:
> 1) No a depositor can only deposit into the ZivoeTranches contract after ITO has concluded and it has been unlocked.

However, within the ZivoeITO contract, there is **no** logic (function) to call the ZivoeTranches#`unlock()` in order to store the `true` into the `tranchesUnlocked` of the ZivoeTranches - after a ITO via the ZivoeITO contract would be `end`. 

This means that `true` will **never** be stored into the `tranchesUnlocked` of the ZivoeTranches contract even if the ITO  via the ZivoeITO contract would be end.

Hence, when a depositor would call the ZivoeTranches#`depositJunior()` or the ZivoeTranches#`depositSenior()` after the ITO is end via the ZivoeITO contract, the depositor's TX of the ZivoeTranches#`depositJunior()` or the ZivoeTranches#`depositSenior()` would be reverted at the following validations.
- https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L273
- https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L300

## Vulnerability Detail
Within the ZivoeTranches contract, the `tranchesUnlocked` would be defined like this:
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L83
```solidity
     bool public tranchesUnlocked;   /// @dev Prevents contract from supporting functionality until unlocked.
```

Within the ZivoeTranches#`depositJunior()` and the ZivoeTranches#`depositSenior()`, there is the validation to check whether or not the `tranchesUnlocked` is `true` like this:
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L273
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L300
```solidity
    function depositJunior(uint256 amount, address asset) public notPaused nonReentrant {
        ...
        require(tranchesUnlocked, "ZivoeTranches::depositJunior() !tranchesUnlocked"); ///<--------- @audit
```
```solidity
    function depositSenior(uint256 amount, address asset) public notPaused nonReentrant {
        ...
        require(tranchesUnlocked, "ZivoeTranches::depositSenior() !tranchesUnlocked"); ///<--------- @audit
```

Within the ZivoeTranches#`unlock()`, `true` would be stored into the `tranchesUnlocked()`.
(NOTE：This function would **only** be called by the ZivoeITO contract)
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L406
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L409
```solidity
    /// @notice Unlocks this contract for distributions, sets some initial variables.
    function unlock() external {
        require(
            _msgSender() == IZivoeGlobals_ZivoeTranches(GBL).ITO(), ///<--------- @audit
            "ZivoeTranches::unlock() _msgSender() != IZivoeGlobals_ZivoeTranches(GBL).ITO()"
        );
        tranchesUnlocked = true;  ///<--------- @audit
    }
```

According to the [reply](https://discord.com/channels/812037309376495636/1226909446891110512/1227128551879348245) for the question in the discord, the ZivoeTranches contract is supposed to be unlocked after ITO is end like this:
> 1) No a depositor can only deposit into the ZivoeTranches contract after ITO has concluded and it has been unlocked.

Based on above, within the ZivoeITO contract, some logic (function) to call the ZivoeTranches#`unlock()` in order to store the `true` into the `tranchesUnlocked` of the ZivoeTranches is supposed to be implemented.
And then, the logic (function) in the ZivoeITO contrac is supposed to be called - after a ITO via the ZivoeITO contract would be `end`.
(Because the ZivoeTranches#`unlock()` can **only** be called by the ZivoeITO contract)

However, within the ZivoeITO contract, there is **no** logic (function) to call the ZivoeTranches#`unlock()` in order to store the `true` into the `tranchesUnlocked` of the ZivoeTranches after a ITO via the ZivoeITO contract would be `end`. 

This means that `true` will **never** be stored into the `tranchesUnlocked` of the ZivoeTranches contract even if the ITO  via the ZivoeITO contract would be end.

## Impact
This is problematic because a depositor can **not** deposit stablecoin into the ZivoeTranches contract via the ZivoeTranches#`depositJunior()` or the ZivoeTranches#`depositSenior()` after the ITO via the ZivoeITO contract would be `end` - due to that the TX of the ZivoeTranches#`depositJunior()` or the ZivoeTranches#`depositSenior()` will be reverted at the following validation when the depositor would call the ZivoeTranches#`depositJunior()` or the ZivoeTranches#`depositSenior()`. 
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L273
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L300
```solidity
    function depositJunior(uint256 amount, address asset) public notPaused nonReentrant {
        ...
        require(tranchesUnlocked, "ZivoeTranches::depositJunior() !tranchesUnlocked"); ///<--------- @audit
```
```solidity
    function depositSenior(uint256 amount, address asset) public notPaused nonReentrant {
        ...
        require(tranchesUnlocked, "ZivoeTranches::depositSenior() !tranchesUnlocked"); ///<--------- @audit
```

## Code Snippet
- https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L409
- https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L273
- https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L300

## Tool used
- Manual Review

## Recommendation
Within the ZivoeITO contract, consider adding a logic (function) to call the ZivoeTranches#`unlock()` in order to store the `true` into the `tranchesUnlocked` of the ZivoeTranches - after a ITO via the ZivoeITO contract would be `end` like this:
```diff
/// File: ZivoeITO.sol

+   address public immutable zivoeTranches;   /// @dev The ZivoeTranches contract.
    ...

+   constructor (address _GBL, address[] memory _stables, address _zivoeTranches) {
-   constructor (address _GBL, address[] memory _stables) {
        GBL = _GBL;
        stables = _stables;
+       zivoeTranches = _zivoeTranches;
    }
    ...

+   function unlockZivoeTranches() public {
+       require(end != 0, "ZivoeITO::migrateDeposits() end == 0");
+       if (_msgSender() != IZivoeGlobals_ITO(GBL).ZVL()) {
+           require(block.timestamp > end, "ZivoeITO::migrateDeposits() block.timestamp <= end");
+       }
+
+       ITO_IZivoeTranches(zivoeTranches).unlock();
+   }
```

**Comment by pseudonaut** [comment]
Very confused on this one ... appears not valid, tranchesUnlocked value changes to true when desired in simulations/testing ... this says it doesn't?
