### ISSUE TITLE
Ironsidesec - `OCE_ZVE. forwardEmissions` lacks access control

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#356]
Ironsidesec

high

# `OCE_ZVE. forwardEmissions` lacks access control

## Summary
Issues happen on stZVE, stJTT, and stSTT contarcts. But the root cause is from  `OCE_ZVE` contract's [forwardEmissions](https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCE/OCE_ZVE.sol#L131)

This issue is not a duplicate of another issue where `(stZVE).depositReward` lacks access control, even if you fix `(stZVE).depositReward` to have access control to be callable only by ZVL || YDL || OCE_ZVE. You can still perform this attack. And the fix is needed in this contract.

root cause: missing access control to `forwardEmissions`
Impact : make reward emissions further slow by decreasing the reward rate.

## Vulnerability Detail

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCE/OCE_ZVE.sol#L131

```solidity


File: 2024-03-zivoe\zivoe-core-foundry\src\lockers\OCE\OCE_ZVE.sol


133:     function forwardEmissions() external nonReentrant {
134:         uint zveBalance = IERC20(IZivoeGlobals_OCE_ZVE(GBL).ZVE()).balanceOf(address(this));
135:         _forwardEmissions(zveBalance - decay(zveBalance, block.timestamp - lastDistribution));
136:         lastDistribution = block.timestamp;
137:     }
138:
139:     /// @notice This handles the accounting for forwarding ZVE to lockers privately.
140:     /// @param amount The amount of $ZVE to distribute.
141:     function _forwardEmissions(uint256 amount) private {
142:         require(amount >= 100 ether, "OCE_ZVE::_forwardEmissions amount < 100 ether");
143:
144:         uint amountZero = amount * distributionRatioBIPS[0] / BIPS;
145:         uint amountOne = amount * distributionRatioBIPS[1] / BIPS;
146:         uint amountTwo = amount * distributionRatioBIPS[2] / BIPS;
147:         address ZVE = IZivoeGlobals_OCE_ZVE(GBL).ZVE();
148:         address stZVE = IZivoeGlobals_OCE_ZVE(GBL).stZVE();
149:         address stSTT = IZivoeGlobals_OCE_ZVE(GBL).stSTT();
150:         address stJTT = IZivoeGlobals_OCE_ZVE(GBL).stJTT();
151:
152:         emit EmissionsForwarded(amountZero, amountOne, amountTwo);
153:        
154:         IERC20(ZVE).safeIncreaseAllowance(stZVE, amountZero);
155:         IERC20(ZVE).safeIncreaseAllowance(stSTT, amountOne);
156:         IERC20(ZVE).safeIncreaseAllowance(stJTT, amountTwo);
157:  >>>    IZivoeRewards_OCE_ZVE(stZVE).depositReward(ZVE, amountZero);
158:  >>>    IZivoeRewards_OCE_ZVE(stSTT).depositReward(ZVE, amountOne);
159:  >>>    IZivoeRewards_OCE_ZVE(stJTT).depositReward(ZVE, amountTwo);
160:     }





```
`reward rate = reward balance / reward duration.`

Attack path: 1
1. Currently, `block.timestamp  <  rewardData[_rewardsToken].periodFinish`, meaning for a 30-day reward period, they deposited 30 * 1000 reward tokens, meaning  1000 reward tokens per day. Currently, we are at the 20th day, and it is left out 10 days * 1000 tokens.

2. Now call [forwardEmissions](https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCE/OCE_ZVE.sol#L131) which will deposit 100 token / 3 into stZVE, stJTT, stSTT contracts, 33 per contract. Once it deposits, the reward rate of 1000 tokens per day will change to (1000 * 10 + 33) / 30 days = 334.33 tokens per day.

So this sudden decrease of reward rate will make the stakers exit by calling withdraw, and it is due to open access control. This issue is not a duplicate of another issue where `(stZVE).depositReward` lacks access control, even if you fix `(stZVE).depositReward` to have access control to be callable only by ZVL || YDL || OCE_ZVE. You can still perform this attack. And the fix is needed in this contract.

This is an issue, deflating reward rates, so stakers might exit seeing the reward APRs.

## Impact
Stakers will leave the stZVE, stJTT, stSTT contracts due to lagged reward rates.

Reward emissions can be made very slow by increasing the reward duration. This is an issue, deflating reward rates, so stakers might exit seeing the reward APRs. Rewards are made 1/3 rd slower by elongating it to 30 days.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCE/OCE_ZVE.sol#L131

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCE/OCE_ZVE.sol#L155-L157

## Tool used

Manual Review

## Recommendation

Add access control, `forwardEmissions` to only callable by ZVL contract.

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCE/OCE_ZVE.sol#L131

```diff
    function forwardEmissions() external nonReentrant {
+       require( _msgSender() == IZivoeGlobals_ZivoeRewards(GBL).ZVL(),"_msgSender() != ZVL ");


        uint zveBalance = IERC20(IZivoeGlobals_OCE_ZVE(GBL).ZVE()).balanceOf(address(this));
        _forwardEmissions(zveBalance - decay(zveBalance, block.timestamp - lastDistribution));
        lastDistribution = block.timestamp;
    }
```

Duplicate of #11

**Comment by pseudonaut** [comment]
Valid, needs whitelist
