### ISSUE TITLE
amar - Signature replay attack in `castVoteWithReasonAndParamsBySig()` to use up more votes than intended

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#362]
amar

high

# Signature replay attack in `castVoteWithReasonAndParamsBySig()` to use up more votes than intended

## Summary
Signatures can be replayed
## Vulnerability Detail
The `ZivoeGovernorV2` contract is responsible for the governance functionality in the protocol like proposals and voting, and inherits from OZ's `Governor.sol`. Users can provide a signature to allow someone else to [vote on their behalf](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/4e5b11919e91b18b6683b6f49a1b4fdede579969/contracts/governance/Governor.sol#L474-L489) using the `castVoteWithReasonAndParamsBySig()` function:

```solidity
    address voter = ECDSA.recover(
        _hashTypedDataV4(
            keccak256(
                abi.encode(
                    EXTENDED_BALLOT_TYPEHASH,
                    proposalId,
                    support,
                    keccak256(bytes(reason)),
                    keccak256(params)
                )
            )
        ),
        v,
        r,
        s
    );
```

As we can see above, the signature provided does not include a nonce. Due to the lack of a nonce, the function can be called multiple times with the same signature. If a user provides a signature to use a portion of their votes, an attacker can repeatedly call `castVotesWithReasonAndParamsBySig()` with the same signature to use up more votes than the user originally intended.
## Impact
Due to the lack of signature replay protection in `castVoteWithReasonAndParamsBySig()`, an attacker can repeatedly call the function with the same signature to user up more votes than the user originally intended.
## Code Snippet
```solidity
    address voter = ECDSA.recover(
        _hashTypedDataV4(
            keccak256(
                abi.encode(
                    EXTENDED_BALLOT_TYPEHASH,
                    proposalId,
                    support,
                    keccak256(bytes(reason)),
                    keccak256(params)
                )
            )
        ),
        v,
        r,
        s
    );
```
## Tool used
Manual Review

## Recommendation
Use an updated version of OZ's Governor where the issue is mitigated.

**Comment by pseudonaut** [comment]
Interesting, which version is this patched in?
