### ISSUE TITLE
redbeans - Assests deposited in ``ZivoeITO`` could  stuck in the contract if called before the ITO.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#367]
redbeans

medium

# Assests deposited in ``ZivoeITO`` could  stuck in the contract if called before the ITO.

## Summary
The ``migrateDeposits`` migrates the deposits stored in the contract to the DAO. if  it is called before ``end`` funds will get stuck.
 
 
## Vulnerability Detail
The ``migrateDeposits()`` is supposed to be called after the end and it can be called only once. In the comments migrated returns true when ITO concludes. This function is callable by anyone but owner can call before the end .
probable scenarios
The owner calls before ``block.timestamp > end`` migrated will be set to be true
User deposits assest in the tranche
ITO ends at the time of calling migrateDeposits() it will revert
Which causes funds to get stucked.
```solidity
bool public migrated;//false

    /// @dev Triggers (true) when ITO concludes and assets migrate to ZivoeDAO.

```
```solidity
  function migrateDeposits() external {
        require(end != 0, "ZivoeITO::migrateDeposits() end == 0");
        if (_msgSender() != IZivoeGlobals_ITO(GBL).ZVL()) {
            require(block.timestamp > end, "ZivoeITO::migrateDeposits() block.timestamp <= end");
        }
        require(!migrated, "ZivoeITO::migrateDeposits() migrated");
        migrated = true;

        emit DepositsMigrated(
            IERC20(stables[0]).balanceOf(address(this)),
            IERC20(stables[1]).balanceOf(address(this)),
            IERC20(stables[2]).balanceOf(address(this)),
            IERC20(stables[3]).balanceOf(address(this))
        );

        for (uint256 i = 0; i < stables.length; i++) {
            IERC20(stables[i]).safeTransfer(IZivoeGlobals_ITO(GBL).DAO(), IERC20(stables[i]).balanceOf(address(this)));
        }

        ITO_IZivoeYDL(IZivoeGlobals_ITO(GBL).YDL()).unlock();
        ITO_IZivoeTranches(IZivoeGlobals_ITO(GBL).ZVT()).unlock();
    }
```

## Impact
loss of fund of users
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L313-L335

## Tool used

Manual Review

## Recommendation
migrateDeposits() should be only called when ITO concludes.

**Comment by pseudonaut** [comment]
Not valid
