### ISSUE TITLE
SilverChariot - `OCL_ZVE` actions can be DOS-ed via sandwiching

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#369]
SilverChariot

medium

# `OCL_ZVE` actions can be DOS-ed via sandwiching

## Summary
[OCL_ZVE](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol) is called by the DAO after a governance proposal vote succeeds and a timelock period passes. A malicious user can sandwich the Uniswap/Sushiswap calls to make the transaction revert because of slippage. A new proposal and a new timelock period will have to pass before the given action can be executed again.

## Vulnerability Detail
The locker uses [`addLiquidity`](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L198-L206) and [`removeLiquidity`](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L233-L236). When adding liquidity, only 10% slippage can be tolerated, otherwise the tx wil revert.

```solidity
            (balPairAsset * 9) / 10,
            (balZVE * 9) / 10, 
```

An attacker can take advantage of that and sandwich the transaction to manipulate the pool's slippage to be more than 10% of the contract balance. The locker transaction will then revert and as said above, a new period of voting + timelock will have to pass before executing the action again. The attacker can then sandwich the new transaction again, resulting in a continuous DOS of the locker.
## Impact
Medium, since it's a DOS and the attacker would have to pay for swap fees.

## Code Snippet
```solidity
        (uint256 depositedPairAsset, uint256 depositedZVE, uint256 minted) = IRouter_OCL_ZVE(router).addLiquidity(
            pairAsset, 
            ZVE, 
            balPairAsset,
            balZVE, 
            (balPairAsset * 9) / 10,
            (balZVE * 9) / 10, 
            address(this), block.timestamp + 14 days
        );
```

```solidity
            (uint256 claimedPairAsset, uint256 claimedZVE) = IRouter_OCL_ZVE(router).removeLiquidity(
                pairAsset, ZVE, preBalLPToken, 
                amountAMin, amountBMin, address(this), block.timestamp + 14 days
            );
```

## Tool used

Manual Review

## Recommendation
It's hard to give a recommendation for fixing this issue. A transaction retrying mechanism may be helpful, but it has to be carefully considered.

**Comment by pseudonaut** [comment]
Protectable via flash-bots, not relevant
