### ISSUE TITLE
Ironsidesec - Interest and late payments are not charged when combining the loans.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#375]
Ironsidesec

high

# Interest and late payments are not charged when combining the loans.

## Summary
**Impact**: loss of interest and late fee yield to stakers.
**Root cause** : This can only be solved by enforcing payments when the combination is approved, because different loans are at different payment intervals and some might be on near-due terms.

The IMAPCT depends on
1. How many loans will you combine, and
2. How many of these have payment intervals > 7 days terms. If a 14-day or 28-day loan is combined with another loan in mid way of term, then there is a loss of interest yield.
3. If any of those loans hit a grace period, or at least half time into that payment interval, for example, on a 28-day interval, if the loan is on the 20th day, then that interval loan is just lost.

The underwriter has the power to check and assign if the payments are paid or if the loan is in grace period. But since the offer can be alive for 3 days from `approveCombine`, the borrower can wait and use all the time to avoid paying fees for the interval and any late fees and just combine the principal for a new loan.
These edge cases are discussed below.

## Vulnerability Detail

**applyCombine** : https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L742-L808

**approveCombine** : https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L877-L905

**Attack path :**
1. A borrower has loan A ( 6 months - 15 % APR for 1000$ bullet loan with 14 day interval payment ), And currently loan A sits at 92 th day (3 months), and 6 payments are made. So no late fees till now, and next due is on 98 th end day. And borrower wants to take another bullet loan for 5k$ at same APR.
2. So the underwriter seeing the proper credit, approves a combine loan for (6k$ at 15% APR) for an agreed-upon time period.
3. So there's still 3 days to accept the offer before calling `applyCombine`. As soon as the underwriter calls `approveCombine` to approve a combination of loans, the borrower backruns and calls `applyCombine` which will combine the loan, and the interest payment of loan A will be lost. And it is a loss for stakers. Because Imagine if the loan A was big amount and one interval's payment would be worth a lot.
4. Also, if there were multiple loans which are near the due payment dates, the loss of yield would be high. And the impact would be higher if the borrower instead of backrunning the applycombine, he would wait for 3 days to hit the grace period in those 3 days offer expiry, then there is also a loss of late fees charge. 
5. So just force a pending payment when `applyCombine` is called.

## Impact

Loss of interest and late fee yield to stakers. So medium.

The IMAPCT depends on
1. How many loans will you combine, and
2. How many of these have payment intervals > 7 days terms. If a 14-day or 28-day loan is combined with another loan in mid-term, then there is a loss of interest yield.
3. If any of those loans hit a grace period, or at least half time into that payment interval, for example, on a 28-day interval, if the loan is on the 20th day, then that interval loan is just lost.

## Code Snippet

**applyCombine** : https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L742-L808

**approveCombine** : https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L877-L905

## Tool used

Manual Review

## Recommendation

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L742-L808

```diff
function applyCombine(uint256 id) external {


        ***


        uint256 notional;
        uint256 APR;
       
        for (uint256 i = 0; i < combinations[id].loans.length; i++) {
            uint256 loanID = combinations[id].loans[i];
+           makePayment(loanID);



            require(
                _msgSender() == loans[loanID].borrower,
                "OCC_Modular::applyCombine() _msgSender() != loans[loanID].borrower"
            );
            require(
                loans[loanID].state == LoanState.Active,
                "OCC_Modular::applyCombine() loans[loanID].state != LoanState.Active"
            );
            notional += loans[loanID].principalOwed;
            APR += loans[loanID].principalOwed * loans[loanID].APR;
            loans[loanID].principalOwed = 0;
            loans[loanID].paymentDueBy = 0;
            loans[loanID].paymentsRemaining = 0;
            loans[loanID].state = LoanState.Combined;
        }



        APR = APR / notional;
        uint256 term = combinations[id].term;
       
        ***
    }
```

Duplicate of #95

**Comment by pseudonaut** [comment]
Known, not of concern
