### ISSUE TITLE
amar - Any user can grief rewards distribution `rewardRate` variable

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#376]
amar

high

# Any user can grief rewards distribution `rewardRate` variable

## Summary
Any user can grief the rewards distribution `rewardRate` variable
## Vulnerability Detail
Let's take a closer look at how the `rewardRate` variable is [calculated](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewards.sol#L228-L238) in the `ZivoeRewards.sol` contract when any arbitrary user deposits rewards:

```solidity
    else {
        uint256 remaining = rewardData[_rewardsToken].periodFinish.sub(block.timestamp);
        uint256 leftover = remaining.mul(rewardData[_rewardsToken].rewardRate);
@>      rewardData[_rewardsToken].rewardRate = reward.add(leftover).div(rewardData[_rewardsToken].rewardsDuration);
    }
```

This is an issue since anyone can arbitrarily deposit rewards, and the function lacks any input validation for the amount. Any user can just deposit dust amounts of 1 wei and with each deposit, the `remainingReward + 1 wei` will be divided by the default rewards duration. By spamming this a user can dillute it further and further, griefing the rewards rate for users. 
## Impact
Dillution of reward rate for all users by an attacker.
## Code Snippet
```solidity
    else {
        uint256 remaining = rewardData[_rewardsToken].periodFinish.sub(block.timestamp);
        uint256 leftover = remaining.mul(rewardData[_rewardsToken].rewardRate);
@>      rewardData[_rewardsToken].rewardRate = reward.add(leftover).div(rewardData[_rewardsToken].rewardsDuration);
    }
```
## Tool used
Manual Review

## Recommendation
Access control on the function

Duplicate of #11

**Comment by pseudonaut** [comment]
Valid, considering whitelists
