### ISSUE TITLE
amar - When a user's vesting is revoked the `vestingTokenAllocated` is zero'd out but the remaining vesting amount is stuck in the contract

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#377]
amar

high

# When a user's vesting is revoked the `vestingTokenAllocated` is zero'd out but the remaining vesting amount is stuck in the contract

## Summary
The remaining vesting tokens allocated for the vesting schedule are not accrued to any other varaible, nor pulled to the treasury so they are stuck
## Vulnerability Detail
Let's take a look at what happens when a user's [vesting schedule is revoked](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L439-L449):

```solidity
    uint256 amount = amountWithdrawable(account);
    uint256 vestingAmount = vestingScheduleOf[account].totalVesting;

    vestingTokenAllocated -= amount;
    ...
    vestingTokenAllocated -= (vestingAmount - vestingScheduleOf[account].totalWithdrawn);
```

Essentially, the `vestingTokenAllocated` variable which is the user's vesting schedule allocated amount, is decremented by the amount that is paid out to the user at the time of revocation. After that, it is zero'd out by subtracting `vestingTokenAllocated -= (vestingAmount - vestingScheduleOf[account].totalWithdrawn)` where `vestingAmount` is the total vesting for the schedule of the user since the start. This is done to set the `vestingTokenAllocated` to zero after revoking the user's schedule.

The issue is that although the remaining token allocation for the user's vesting schedule is set to 0, the tokens have already been allocated prior to this and are in the contract. Since later in the function flow they are not incremented to another variable, nor transferred to a treasury or something of the sort, records of them are wiped off variables, whilst they still remain in the contract - stuck.
## Impact
Remaining allocated vesting tokens are stuck in the contract when a user's vesting schedule is revoked.
## Code Snippet
```solidity
    uint256 amount = amountWithdrawable(account);
    uint256 vestingAmount = vestingScheduleOf[account].totalVesting;

    vestingTokenAllocated -= amount;
    ...
    vestingTokenAllocated -= (vestingAmount - vestingScheduleOf[account].totalWithdrawn);
```
## Tool used
Manual Review

## Recommendation
Transfer to treasury or perhaps distribute to other vesting recipients.

**Comment by pseudonaut** [comment]
Intended, for future vesting to others
