### ISSUE TITLE
flacko - Tokens will be stuck in ZivoeRewards contracts because of precision loss when calculating reward rate

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#386]
flacko

medium

# Tokens will be stuck in ZivoeRewards contracts because of precision loss when calculating reward rate

## Summary
Due to precision loss when calculating the `rewardRate` in the rewards and vesting contracts, reward tokens will accumulate and be left stuck.

## Vulnerability Detail
When rewards are deposited to an instance of **ZivoeRewards** or **ZivoeRewardsVesting** via `depositRewards()`, the `rewardRate` for the deposited `_rewardsToken` will be either calculated for the first time or recalculated if there have already been deposited rewards for that token and their `periodFinish` hasn't elapsed yet. In any case though, there'll be a precision loss when dividing the rewards by the duration:

```solidity
        if (block.timestamp >= rewardData[_rewardsToken].periodFinish) {
→           rewardData[_rewardsToken].rewardRate = reward.div(rewardData[_rewardsToken].rewardsDuration);
        } else {
            uint256 remaining = rewardData[_rewardsToken].periodFinish.sub(block.timestamp);
            uint256 leftover = remaining.mul(rewardData[_rewardsToken].rewardRate);
→           rewardData[_rewardsToken].rewardRate = reward.add(leftover).div(rewardData[_rewardsToken].rewardsDuration);
        }
```

The two contracts in question have no means of handling that dust amount accumulated over time and it will essentially remain stuck.
## Impact
Let's consider the following two examples:
1. The current period for a `_rewardsToken` has finished / has never started
    `reward` = 1000e18
    `rewardsDuration` = 30 days = 2952000 seconds
    `rewardRate` = 385802469135802
    Running back the check: `rewardRate` * `rewardsDuration` = 999999999999998784000. We get 1216000 difference because of the precision loss.
2. The current period for a `_rewardsToken` has not finished yet
    `reward` = 1000e18
    `rewardsDuration` = 30 days = 2952000 seconds
    `rewardRate` = 385802469135802 (using the former `rewardRate`)
    
    `remaining` = 15 days (half of `rewardsDuration` have passed) 
    `leftover` = `remaining` * `rewardRate` = 499999999999999392000
    `rewardRate` = (`reward` + `lefover`) / `rewardsDuration` = (1000e18 + 499999999999999392000) / 29520000 = 1499999999999999392000 / 2952000 = 578703703703703
    Running back the check: `rewardRate` * `rewardsDuration` = 1499999999999998176000.
    `leftover` + `reward` = 499999999999999392000 + 1000e18 = 1499999999999999392000
    The difference of 1216000 is still there.

In the above calculations, `reward` is still quite the round number. If it was just 1 ether worth of reward token less - 999e18 - the difference lost because of precision loss would grow to 1728000. Now this might not seem like much, but considering there will be 3 instances of **ZivoeRewards** and one instance of **ZivoeRewardsVesting** that makes 4 contracts accumulating stuck assets + every different `_rewardsToken` will suffer precision loss when calculating the reward rate for it. Another factor that will make matters worse is the less decimals of precision a reward token has, the bigger the precision loss hence the larger the amount of stuck tokens that'll accumulate.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L232-L238
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L356-L362

## Tool used
Manual Review

## Recommendation
Implement a `skim`-like function that allows for the dust accumulated in these contracts instances to be transferred to the DAO for example, or deposit the dust amount 'virtually' to the contract itself so it can be distributed when enough of it accumulates.

Duplicate of #129

**Comment by pseudonaut** [comment]
Dust is ok
