### ISSUE TITLE
t0x1c - Protocol supports rebasing token OUSD but calculates basis & yield incorrectly in `OCY_OUSD.sol`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#387]
t0x1c

medium

# Protocol supports rebasing token OUSD but calculates basis & yield incorrectly in `OCY_OUSD.sol`

## Summary
The balance of rebasing token OUSD can change dynamically but the protocol uses a stored value of `basis` to calculate distributable yield, which can be outdated and can give incorrect results.

## Vulnerability Detail
Consider the scenario:
- Current `basis` and balance is 100.
- Additional yield of 10 accrues. Balance = 110.
- A positive rebase of OUSD happens as a result of which balances of all holders are reduced by 10.
- `forwardYield()` is called. It [calculates `amountOUSD`](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_OUSD.sol#L146-L147) to be equal to the current balance i.e. 100.
- Since `amountOUSD > basis` is `false`, no yield is distributed.

In the inverse case of negative rebasing, the protocol ends up forwarding higher than expected yield.

## Impact
Possible loss of yield.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_OUSD.sol#L146-L147

## Tool used
Manual Review

## Recommendation
OUSD rebasing events will need to be tracked and `basis` updated accordingly.

**Comment by pseudonaut** [comment]
The example issue supplied does not seem to have a relevant issue - it is tracking the nature of what's present?
