### ISSUE TITLE
0xGreyWolf - In `ZivoeTranches::depositSenior()` and `ZivoeTranches::depositJunior()`, the liquidity capital can be reused to accumulate `ZVE` rewards

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#389]
0xGreyWolf

high

# In `ZivoeTranches::depositSenior()` and `ZivoeTranches::depositJunior()`, the liquidity capital can be reused to accumulate `ZVE` rewards

## Summary
When a liquidity provider deposits liquidity in `depositSenior()`, he/she receives `zSTT` as a receipt of the deposit amount itself plus `ZVE` as an incentive / rewards.
- [`depositSenior()`](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeTranches.sol#L295-L315)
    ```solidity
    /// @notice Deposit stablecoins into the senior tranche.
    /// @dev    Mints Zivoe Senior Tranche ($zSTT) tokens in 1:1 ratio.
    /// @param  amount The amount to deposit.
    /// @param  asset The asset (stablecoin) to deposit.
    function depositSenior(uint256 amount, address asset) public notPaused nonReentrant {
        require(
            IZivoeGlobals_ZivoeTranches(GBL).stablecoinWhitelist(asset), 
            "ZivoeTranches::depositSenior() !IZivoeGlobals_ZivoeTranches(GBL).stablecoinWhitelist(asset)"
        );
        require(tranchesUnlocked, "ZivoeTranches::depositSenior() !tranchesUnlocked");

        address depositor = _msgSender();

        IERC20(asset).safeTransferFrom(depositor, IZivoeGlobals_ZivoeTranches(GBL).DAO(), amount);
        
        uint256 convertedAmount = IZivoeGlobals_ZivoeTranches(GBL).standardize(amount, asset);

    @>  uint256 incentives = rewardZVESeniorDeposit(convertedAmount); // @audit - This line calculates ZVE incentives / rewards

        emit SeniorDeposit(depositor, asset, amount, incentives);

        // Ordering important, transfer ZVE rewards prior to minting zJTT() due to totalSupply() changes.
    @>  IERC20(IZivoeGlobals_ZivoeTranches(GBL).ZVE()).safeTransfer(depositor, incentives); // @audit - This line transfers ZVE incentives to the depositor
        IERC20Mintable_ZivoeTranches(IZivoeGlobals_ZivoeTranches(GBL).zSTT()).mint(depositor, convertedAmount); 
    }
    ```
    - [`rewardZVESeniorDeposit()`](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeTranches.sol#L236-L262)
        ```solidity
        function rewardZVESeniorDeposit(uint256 deposit) public view returns (uint256 reward) {...}
        ```
`zSTT` can be sold to the secondary markets (as stated in the discord server) and retrieve back the original deposited stablecoin amount.

- [`information via discord server`](https://discord.com/channels/812037309376495636/1226909446891110512/1228042241394868345)
    ```solidity
    johnnyq — 04/12/2024 2:01 AM
    OCR_Modular is not in scope
    Tranche tokens would have liquidity on secondary markets, i.e. zJTT/USDC , zSTT/USDC
    ```

Since the liquidity provider can retrieve back his/her original capital, he/she can deposit it again in `depositSenior()` and will receive the same amount of `ZVE` incentives / rewards "again". This attack principle also applies to the function `depositJunior()`.

## Vulnerability Detail
Let's illustrate the issue with the following scenario:
1. Eve (the attacker) deposits 1000 USDC, receives 1000 `zSTT` and receives X amount of `ZVE` as incentives / rewards.
2. Eve swaps 1000 `zSTT` to USDC on secondary market hence receiving her original capital 1000 USDC.
3. Eve deposits again using the same capital (1000 USDC) via `depositSenior()` and receives another X amount of `ZVE`.
4. At this point, Eve has 2X `ZVE` already, twice as much as she rightfully should own.
5. Eve repeats the process making her `ZVE` incentives / rewards 3X, 4X, nX, etc., with the same amount of capital.

## Impact
`ZVE` is the governance token and earns fees on all revenue generated by the protocol.  Since the attacker can receive `ZVE` multiple times with the same amount of capital:
- the attacker can inflate his/her earnings at the expense of the honest liquidity providers and the protocol itself 
- the attacker has the potential to dominate the governance rights and steer the protocol direction in his/her favor 

## Tool used
Manual Review

## Recommendation
There must be some restrictions in `ZVE` incentives releases on liquidity deposits. `ZVE` should not be received upon liquidity deposit. There should be a required "holding period" for `zSTT` or `zJTT` before `ZVE` can be claimed.

**Comment by pseudonaut** [comment]
Intended
