### ISSUE TITLE
Ironsidesec - Combined amortized loans will  pay more interest rather than paying  separately without combining

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#392]
Ironsidesec

medium

# Combined amortized loans will  pay more interest rather than paying  separately without combining

## Summary
The amortized loans should not be combined, because if they are combined, they have to pay more interest than if they held those loans separately and paid interest separately instead of combining.

Its about 5 - 10 % cheaper to not combine, but it will depend on APR, principal, term, interval period.

## Vulnerability Detail

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L877-L905

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L742

The loan APR and interest calculation can be played with using the below formula. Use the remix IDE or chisel tool from Foundry.

```solidity


    function loop(uint initialPrincipal, uint  interestRate, uint totalTerms)  public pure returns (uint ) {
        uint remainingTerms = totalTerms;
        uint principalOwed = initialPrincipal;
        uint interestPaid;


        for(uint i = 0; i < totalTerms; i++) {


            interestPaid += (principalOwed * interestRate / 10000 ) * 28 days / 365 days;
            principalOwed -= principalOwed / remainingTerms;


            remainingTerms--;
        }


        return interestPaid;
    }
```
example call `loop(5000 $, 5000 (50% apr), 4)`; meaning four terms. The function assumes the payment interval is 28 days.

**Flow with combining**

Its January 1, 2024,
1. Loan A with $5000 at 50% amortized loan starts with a 28 day intervals for 8 term (8 months loan)
2. three months passed so its April 1, the interest paid is, $ 503 in 3 months.
3. Now the borrower want to take 1000$ loan B at 25% with a 28 day intervals for 5 term (5 months loan), so the underwriter combines the loan.
4. And a new loan will be created which will try to create a new nominal principal and new APR, so
new principal = 1000 + 3750 (not 5k because its amortized 3x) = 4750, and new APR will be = (1000 * 0.25 + 3750 * 0.50) / (4750) = 44.73 %
5. And after 5 payments to this combined loan, the interest paid will be, $ 486, so totally these 2 loans will generate 503 + 486 = `$989`

**Flow without combining**

Its jan 1 2024,
1. Loan A  with $5000 at 50% amortized loan starts with a 28 day intervals for 8 term (8 months loan)
2. three months passed so its April 1, the interest paid is, $ 503 in 3 months.
3. Now the borrower want to take 1000$ loan B at 25% with a 28 day intervals for 5 term (5 months loan), but combination was not approved by borrower even if the underwriter approves.
4. so the Loan A will generate $856 interest yield  after the whole 8 months. And loan B will generate $ 55 so total at `$913` interest if not combined.

So with combined = $989
and without combined = $913

so here the borrower will simply choose to have loans without combining them. And even if underwriter `approveCombine` the borrower will reject it by not calling `applyCombine`.

This issue exists for amortized loans, and bullet loans are safe and correctly accouted.

## Impact

Amortized loans that combine will chanrge more interest than uncombined loan A nad loan B.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L877-L905

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L742

## Tool used

Manual Review

## Recommendation
The APR and notional calculation being onchain makes it difficult to calculate, So instead, the new APR and new principle amount should be calculated offchain by the underwriter, and then call `approveCombine` with the input parameter. So that borrower will call `applyCombine` if he's okay with the new combined loan.

Or, don't allow amortized loans to combine.

**Comment by pseudonaut** [comment]
Not relevant
