### ISSUE TITLE
cergyk - ZivoeYDL::unlock stJTT and stSTT are not set as protocol or residual recipients and will miss on yield distribution

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#397]
cergyk

medium

# ZivoeYDL::unlock stJTT and stSTT are not set as protocol or residual recipients and will miss on yield distribution

## Summary
During ZivoeYDL::unlock after initial tranche offering, the protocol recipients and residual recipients are set. However stJTT and stSTT are not set, and will not receive rewards which are intended for them.

## Vulnerability Detail
We can see that Zivoe intended `stJTT` and `stSTT` to be recipients of yield because they are handled as a special case during the iteration over `protocolRecipients` and `residualRecipients`:

[ZivoeYDL.sol#L244-L248](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L244-L248)
```solidity
if (_recipient == IZivoeGlobals_YDL(GBL).stSTT() || _recipient == IZivoeGlobals_YDL(GBL).stJTT()) {
    IERC20(distributedAsset).safeIncreaseAllowance(_recipient, _protocol[i]);
    IZivoeRewards_YDL(_recipient).depositReward(distributedAsset, _protocol[i]);
    emit YieldDistributedSingle(distributedAsset, _recipient, _protocol[i]);
}
```

[ZivoeYDL.sol#L283-L287](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L283-L287)
```solidity
if (_recipient == IZivoeGlobals_YDL(GBL).stSTT() ||_recipient == IZivoeGlobals_YDL(GBL).stJTT()) {
    IERC20(distributedAsset).safeIncreaseAllowance(_recipient, _residual[i]);
    IZivoeRewards_YDL(_recipient).depositReward(distributedAsset, _residual[i]);
    emit YieldDistributedSingle(distributedAsset, _recipient, _protocol[i]);
}
```

However as we can see in `ZivoeYDL::unlock` only stZVE and ZVL are set as recipients after ITO:

```solidity
    address[] memory protocolRecipientAcc = new address[](2);
    uint256[] memory protocolRecipientAmt = new uint256[](2);

    protocolRecipientAcc[0] = address(IZivoeGlobals_YDL(GBL).stZVE());
    protocolRecipientAmt[0] = 6666;
    protocolRecipientAcc[1] = address(IZivoeGlobals_YDL(GBL).ZVL());
    protocolRecipientAmt[1] = 3334;

    protocolRecipients = Recipients(protocolRecipientAcc, protocolRecipientAmt);

    address[] memory residualRecipientAcc = new address[](2);
    uint256[] memory residualRecipientAmt = new uint256[](2);

    residualRecipientAcc[0] = address(IZivoeGlobals_YDL(GBL).stZVE());
    residualRecipientAmt[0] = 6666;
    residualRecipientAcc[1] = address(IZivoeGlobals_YDL(GBL).ZVL());
    residualRecipientAmt[1] = 3334;

    residualRecipients = Recipients(residualRecipientAcc, residualRecipientAmt);
```

## Impact

stSTT and stJTT tokens miss on yield which is due to them

## Tool used

Manual Review

## Recommendation

Initialise stJTT and stSTT during unlock as `protocolRecipients` and `residualRecipients`

**Comment by pseudonaut** [comment]
Not valid, it's distributed after protocol earnings and prior to residual earnings
