### ISSUE TITLE
pivanov - [ZivoeGlobals.sol] - Lack of Input Validation in Whitelist Management Functions

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#4]
pivanov

medium

# [ZivoeGlobals.sol] - Lack of Input Validation in Whitelist Management Functions

## Summary
The `ZivoeGlobals` contract lacks necessary input validation checks for addresses being added to various whitelists, potentially allowing for zero addresses to be set, which could lead to operational failures or vulnerabilities within the system.

## Vulnerability Detail
Functions responsible for updating the status of keepers, lockers, and stablecoins do not validate the input address, permitting the zero address **(0x0)** to be added to these critical whitelists. This omission could result in operational disruptions or vulnerabilities, as interactions with a zero address could lead to unexpected behaviors or token losses.

## Impact
Allowing the zero address to be added to keeper, locker, or stablecoin whitelists undermines the contract's security and reliability. It may lead to failed transactions or unintended loss of funds when these lists are used to validate interactions or transactions within the Zivoe ecosystem.

## Code Snippet
See the related code segment [here](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGlobals.sol#L226-L229)
```solidity
function updateIsKeeper(address keeper, bool status) external onlyZVL {
    isKeeper[keeper] = status;
    emit UpdatedKeeperStatus(keeper, status);
}
```
Similar issues are present in `[updateIsLocker](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGlobals.sol#L235-L238)` and `[updateStablecoinWhitelist](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGlobals.sol#L244-L247)`

## Tool used
Manual Review

## Recommendation
Introduce stringent input validation to reject zero addresses and ensure only valid addresses can be added to or modified within the system's whitelists. This can be achieved by adding a require statement to check for non-zero addresses at the beginning of each affected function.

### Code Snippets for Recommendation
```solidity
function updateIsKeeper(address keeper, bool status) external onlyZVL {
    require(keeper != address(0), "ZivoeGlobals: keeper cannot be the zero address");
    isKeeper[keeper] = status;
    emit UpdatedKeeperStatus(keeper, status);
}
```

```solidity
function updateIsLocker(address locker, bool status) external onlyZVL {
    require(locker != address(0), "ZivoeGlobals: locker cannot be the zero address");
    isLocker[locker] = status;
    emit UpdatedLockerStatus(locker, status);
}
```

```solidity
function updateStablecoinWhitelist(address stablecoin, bool allowed) external onlyZVL {
    require(stablecoin != address(0), "ZivoeGlobals: stablecoin cannot be the zero address");
    stablecoinWhitelist[stablecoin] = allowed;
    emit UpdatedStablecoinWhitelist(stablecoin, allowed);
}
```

Implementing these changes will significantly enhance the contract's robustness by ensuring that only valid addresses can be whitelisted, thereby reducing the risk of operational errors or vulnerabilities.

**Comment by pseudonaut** [comment]
Not relevant
