### ISSUE TITLE
0x73696d616f - Inability to collateralize by minting new tranch tokens in `ZivoeTranches` if adjusted supplies go to `0` due to division by 0

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#401]
0x73696d616f

medium

# Inability to collateralize by minting new tranch tokens in `ZivoeTranches` if adjusted supplies go to `0` due to division by 0

## Summary

Junior and senior tranche tokens are minted to users who deposit collateral into the `DAO`, which can then use it to generate yield or cover any loss in the short term. However, if the adjusted supply of both junior and senior tranche tokens reach 0, it's no longer possible to mint new tranch tokens and collateralize the system back.

## Vulnerability Detail

In [ZivoeTranches::depositJunior()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L268) and [ZivoeTranches::depositSenior()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L295), users receive junior and senior tranche tokens, respectively, by transferring collateral to the `DAO` at a 1:1 ratio. This is how liquidity/collateral enters the system, although initially through `ZivoeITO`. If the adjusted supply ever reaches `0` due to defaults, it's expected that users, through `ZVE` incentives, refill the collateral back of the system. However, due to an unhandled division by 0 error, if the adjust supplies reaches 0, it's no longer possible to collateralize the system back. Thus, the system would be stuck in this state where no collateral is provided from users for an undetermined period, leading to less yield generation due to having less collateral available and a possible sustained decrease of the `ema` adjusted supplies of the tranche tokens, aggravating further the yield loss of the tranches.

The division by 0 error is present in `startRatio` [ZivoeTranches::rewardZVESeniorDeposit()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L236) and [ZivoeTranches::rewardZVEJuniorDeposit()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L203), when `seniorSupp == 0`.

Note that it is expected that more collateral is available than tranche tokens, due to yield generation, which means that over time it gets more and more likely (as the amount of collateral compared to tranche tokens tends to increase) for this to happen. For example, after accumulating yield for 5 years at 10%, the collateral could be `1.1^5 = 1.61` times the tranche tokens, making it more likely that `defaults` reach the supply of junior and tranche tokens. The only way to overcome this scenario would be decreasing defaults by gathering collateral from other places. However, note that the colleral gathered would need to be bigger than the current `defaults - totalSupply`, possibly a significant amount.

Add the following test to `Test_ZivoeTranches.sol` confirming that minting is impossible when the adjusted supplies are 0.
```solidity
function test_POC_ZivoeTranches_0supply_breaks_minting() public {
    simulateITO(100_000_000 ether, 100_000_000 ether, 100_000_000 * USD, 100_000_000 * USD);

    vm.startPrank(address(ZVT));
    GBL.increaseDefaults(zJTT.totalSupply());
    GBL.increaseDefaults(zSTT.totalSupply());
    vm.stopPrank();

    mint("DAI", address(sam), 10_000_000_000 ether);
    assert(sam.try_approveToken(address(DAI), address(ZVT), 10_000_000_000 ether));
    vm.startPrank(address(sam));
    vm.expectRevert("ZivoeTranches::depositJunior() !isJuniorOpen(amount, asset)");
    ZVT.depositJunior(10_000_000_000 ether, address(DAI));
    vm.expectRevert(stdError.divisionError);
    ZVT.depositSenior(10_000_000_000 ether, address(DAI));
    vm.stopPrank();
}
```

## Impact

Inability to accrue collateral for undetermined time, leading to significant yield loss due to not allocating more capital. Additionally, tranches would take even bigger losses as their supplies could be 0 for a sustained period of time, possibly decreasing the `ema` supplies if a `ZivoeYDL::distributeYield()` call is made in the meantime.

## Code Snippet

[ZivoeTranches::rewardZVEJuniorDeposit()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L203)
```solidity
function rewardZVEJuniorDeposit(uint256 deposit) public view returns (uint256 reward) {
    ...
    uint256 startRatio = juniorSupp * BIPS / seniorSupp;
    ...
}
```

[ZivoeTranches::rewardZVESeniorDeposit()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L236) 
```solidity
function rewardZVESeniorDeposit(uint256 deposit) public view returns (uint256 reward) {
    ...
    uint256 startRatio = juniorSupp * BIPS / seniorSupp;
    ...
}
```

## Tool used

Manual Review

Vscode

Foundry

## Recommendation

This edge case should be easy to handled due to the fact that when the adjusted supply of senior tranche tokens is 0, so it the supply of junior tranche tokens. Note that junior tranche tokens should respect the invariant that `convertedAmount + juniorSupp <= seniorSupp * maxTrancheRatioBIPS / BIPS;`, thus, if the supply of senior tokens is `0`, users should be rewarded for minting senior tranche tokens, otherwise there might not be enough incentives to mint tranche tokens (junior can not be minted when both supplies are 0). I am stating this because a simple solution would be adding `1` to the denominator `seniorSupp`, but this would make `avgRate = minZVEPerJTTMint;` for senior deposits, disincentivizing users. Due to this, a better fix would be adding `+1` to the numerator and denominator of `startRatio` and `finalRatio`, which would give a bigger incentive to mint senior tranche tokens when the adjusted supply is `0`.

Duplicate of #37

**Comment by pseudonaut** [comment]
It's not expected to re-collateralize the system through deposits, rather handle defaults off-chain, as of now if seniorSupp == 0 this is desired to revert
