### ISSUE TITLE
aitor - Mismatch between emit on `ZivoeITO.migrateDeposits()` and the array

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#403]
aitor

medium

# Mismatch between emit on `ZivoeITO.migrateDeposits()` and the array

## Summary

Contract: `ZivoeITO`

Function: `migrateDeposits()`

There is a mismatch in the contract with respect to the array of the stables. The emit within the function is set to 4 elements, but the array itself has undefined length.

Any error with the value during the deploy will lead to a malfunction.

## Vulnerability Detail

We set stable at 3 elements:

```solidity
 address[] public stables;

stables.push(address(USDC));
stables.push(address(USDT));
stables.push(address(DAI));
```

Running the function will ends in an error:

```terminal
[FAIL. Reason: panic: array out-of-bounds access (0x32)] test_migrateDeposits() (gas: 91896)
[PASS] test_zivoeITODepositJunior() (gas: 165)
Suite result: FAILED. 3 passed; 1 failed; 0 skipped; finished in 4.31ms (578.88µs CPU time)

Ran 1 test suite in 132.87ms (4.31ms CPU time): 3 tests passed, 1 failed, 0 skipped (4 total tests)

Failing tests:
Encountered 1 failing test in test/PhaseZeroTest.t.sol:PhaseZeroTest
[FAIL. Reason: panic: array out-of-bounds access (0x32)] test_migrateDeposits() (gas: 91896)

Encountered a total of 1 failing tests, 3 tests succeeded

```

## Impact

This is  MEDIUM Risk vulnerability, funds are not in risk but an issue that dev team should address.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L322

## Tool used

Manual Review

## Recommendation

There is 2 ways to proceed:

1. Set the array to 4 elements:
   `address[4] public stables;`

2. Modify the emit emiting the address and the balance and implement into the function like:

```solidity
for (uint256 i = 0; i < stables.length; i++) {
    emit DepositsMigrated(address(stables[i], IERC20(stables[i]).balanceOf(address(this)));}
}

```

```terminal
[PASS] test_migrateDeposits() (gas: 481890)
[PASS] test_zivoeITODepositJunior() (gas: 165)
Suite result: ok. 4 passed; 0 failed; 0 skipped; finished in 4.69ms (809.00µs CPU time)

Ran 1 test suite in 144.88ms (4.69ms CPU time): 4 tests passed, 0 failed, 0 skipped (4 total tests)
➜  zivoe-core-foundry git:(main) ✗
```

**Comment by pseudonaut** [comment]
Assumed deployment is perfect
