### ISSUE TITLE
Dliteofficial - Precision Error during principal repayment calculation in `OCC_Modular::amountOwed()` will cause ZIVOE to lose funds to borrowers.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#410]
Dliteofficial

medium

# Precision Error during principal repayment calculation in `OCC_Modular::amountOwed()` will cause ZIVOE to lose funds to borrowers.

## Vulnerability Detail

There are two types of loans on Zivoe, bullet loans, which are interest-only loans that allow the borrower to pay back the principal at the end of the loan term. On the flip side are amortized loans, which allow users to pay both the payment and interest proportionally every month.

When a user takes an amortized loan, which the `loans[id].principalOwed % loans[id].paymentsRemaining != 0`, precision error sets in, and a few tokens are scraped off the amount paid back as principal owed.

This vulnerability also arises when loan extensions happen. When a loan extension is applied and accepted, it can cause a loan with this `loans[id].principalOwed % loans[id].paymentsRemaining == 0` to become `loans[id].principalOwed % loans[id].paymentsRemaining != 0`, causing precision error and loss of tokens on Zivoe's part.

## Impact

Loss of funds to Zivoe during principal repayment.

## Code Snippet

[`OCC_Modular::amountOwed()`](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L440C1-L457C6)

```solidity
    function amountOwed(uint256 id) public view returns (
        uint256 principal, uint256 interest, uint256 lateFee, uint256 total
    ) {
        if (loans[id].paymentSchedule == 0) {
            if (loans[id].paymentsRemaining == 1) { principal = loans[id].principalOwed; }
        }
>>>>    else { principal = loans[id].principalOwed / loans[id].paymentsRemaining; }

        if (block.timestamp > loans[id].paymentDueBy && loans[id].state == LoanState.Active) {
            lateFee = loans[id].principalOwed * (block.timestamp - loans[id].paymentDueBy) *
                loans[id].APRLateFee / (86400 * 365 * BIPS);
        }
        interest = loans[id].principalOwed * loans[id].paymentInterval * loans[id].APR / (86400 * 365 * BIPS);
        total = principal + interest + lateFee;
    }
```

## Tool used

Manual Review

## Recommendation
Review Principal Repayment calculation.

**Comment by pseudonaut** [comment]
Dust is ok
