### ISSUE TITLE
SUPERMAN_I4G - Spillage of Funds or Reward Tokens Due To Rounding

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#412]
SUPERMAN_I4G

high

# Spillage of Funds or Reward Tokens Due To Rounding

## Summary
The ```depositReward``` function present in the ```ZivoeRewards.sol``` (and ```ZivoeRewardsVesting.sol```) contract is responsible for initiating rewards or yield distribution upon a successful call. This function transfers the reward amount (for a specific reward token) into the contract, and calculates the ```rewardRate``` for the reward token. However each time ```rewardRate``` is calculated, certain portion of the rewards or funds will always spill-out due to rounding. 

## Vulnerability Detail
Whenever the ```depositReward``` function (in both ```ZivoeRewards.sol``` and ```ZivoeRewardsVesting.sol```) is called, we expect the reward token transfered into the contract for distribution per a ```rewardRate```. This ```rewardRate``` is just the number of tokens users or stakers can acrrue for their stakes per second and that's calculated in the ```depositReward``` function.

For every transfered rewards token, the ```rewardRate``` is calculated as:
 ```rewardData[_rewardsToken].rewardRate = reward.div(rewardData[_rewardsToken].rewardsDuration)``` 
 > (i.e the transfered reward amount divide by the reward duration)

OR

 ```rewardData[_rewardsToken].rewardRate = reward.add(leftover).div(rewardData[_rewardsToken].rewardsDuration)``` 
 > (i.e if reward distribution is still ongoing then add the transfered reward amount to the the calculated leftover amount divide by the reward duration). 

 However this calculation is not ideal as this only opens pathway for spillage of rewards each time the ```rewardRate``` is calculated. For example:
 * Alice calls ```depositReward``` function and transfers 100 reward tokens (to be distributed for 60 seconds)
 * ```reward``` = 100 & ```rewardDuration``` = 60 therefore, ```rewardRate``` = ```reward.div(rewardDuration)```  (i.e 100 divided by 60). ```rewardRate = 1``` (i.e. 1 token per second).
 * However, if the calculated ```rewardRate = 1``` then only 60 reward tokens will be distributed since the duration is 60 seconds after all. Therefore, 40 reward tokens spill-out in the calculation (in other words undistributed and lost or stuck in the contract).
 * This occurs because each time ```rewardRate``` is calculated, the value will always round down. (i.e. if the value is calculated as ```1.66666667``` then solidity will round down and return ```value == 1```).

 > For more context play with this simple code below on Remix as this issue is quite an easy one to understand. Enjoy! 
```javascript
 // SPDX-License-Identifier: BUSL-1.1
pragma solidity ^0.8.0;
import "@openzeppelin/contracts/utils/math/SafeMath.sol";

contract test {
    using SafeMath for uint256;
    function getRewardRate() external view returns (uint256) {
        uint256 rewardAmount = 100; //100 tokens
        uint256 duration = 60; //60 seconds
        return rewardAmount.div(duration);
    }

    function getSpilledToken() external view returns (uint256) {
        uint256 rewardAmount = 100; //100 tokens
        uint256 duration = 60; //60 seconds
        return rewardAmount.mod(duration);
    }
}
```

 

## Impact
* Loss of Funds

> PS: High Severity since this is a definite loss of funds without external limitations.

## Code Snippet
```diff
    function depositReward(address _rewardsToken, uint256 reward) external updateReward(address(0)) nonReentrant {
        IERC20(_rewardsToken).safeTransferFrom(_msgSender(), address(this), reward);

        // Update vesting accounting for reward (if existing rewards being distributed, increase proportionally).
        if (block.timestamp >= rewardData[_rewardsToken].periodFinish) {
            //@audit some rewards will always spill out due to rounding
-            rewardData[_rewardsToken].rewardRate = reward.div(rewardData[_rewardsToken].rewardsDuration);
        } else {
            uint256 remaining = rewardData[_rewardsToken].periodFinish.sub(block.timestamp);
            uint256 leftover = remaining.mul(rewardData[_rewardsToken].rewardRate);
-            rewardData[_rewardsToken].rewardRate = reward.add(leftover).div(rewardData[_rewardsToken].rewardsDuration);
        }
        rewardData[_rewardsToken].lastUpdateTime = block.timestamp;
        rewardData[_rewardsToken].periodFinish = block.timestamp.add(rewardData[_rewardsToken].rewardsDuration);
        emit RewardDeposited(_rewardsToken, reward, _msgSender());
    }
```
## Tool used
Manual Review

## Recommendation
There are two common ways to mitigate this, either by introducing a multiplier or getting the spillout amount and always adding to the leftover in the next reward cycle. Although the first is more ideal and mostly adopted by popular protocols implementing similar mechanism. See some examples below.
* Unistaker (by Uniswap): 
https://github.com/code-423n4/2024-02-uniswap-foundation/blob/95a31342c30c6f97e8e036b1f523141420b574b7/src/UniStaker.sol#L134
https://github.com/code-423n4/2024-02-uniswap-foundation/blob/95a31342c30c6f97e8e036b1f523141420b574b7/src/UniStaker.sol#L578
* SpoolStaking (by SpoolFi): 
https://github.com/SpoolFi/spool-staking-and-voting/blob/51d3c3d14acce9e5604b1f88ed3a8e3cdc051461/contracts/SpoolStaking.sol#L45
https://github.com/SpoolFi/spool-staking-and-voting/blob/51d3c3d14acce9e5604b1f88ed3a8e3cdc051461/contracts/SpoolStaking.sol#L387

Duplicate of #129

**Comment by pseudonaut** [comment]
This is dust on a minute scale, not relevant
