### ISSUE TITLE
flacko - Adding liquidity to Curve pools while imbalanced will be penalized resulting in less LP tokens

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#419]
flacko

medium

# Adding liquidity to Curve pools while imbalanced will be penalized resulting in less LP tokens

## Summary
Liquidity provisions to Curve pools that are part of transactions pushing assets to the Convex lockers (`pushToLocker()`) will result in receiving less LP tokens when the Curve base or meta pools are imbalanced and thus result in suboptimal returns from Convex pools.
## Vulnerability Detail
In Curve pools (both base and meta pools), there are penalties/bonuses when adding liquidity. If a liquidity deposit helps the pool in reaching that desired balance between assets, a deposit bonus will be given. On the other hand, if a deposit deviates the pool from the desired balance, a deposit penalty will be imposed (receive fewer tokens).

Snippet shown for the Curve base pool that **OCY_Convex_A** adds liquidity to ([link](https://www.codeslaw.app/contracts/ethereum/0xB30dA2376F63De30b42dC055C93fa474F31330A5)):

```python
def add_liquidity(
    _amounts: uint256[N_COINS],
    _min_mint_amount: uint256,
    _receiver: address = msg.sender
) -> uint256:
    ...
    # We need to recalculate the invariant accounting for fees
    # to calculate fair user's share
    fees: uint256[N_COINS] = empty(uint256[N_COINS])
    mint_amount: uint256 = 0
    if total_supply > 0:
        # Only account for fees if we are not the first to deposit
        base_fee: uint256 = self.fee * N_COINS / (4 * (N_COINS - 1))
        for i in range(N_COINS):
            ideal_balance: uint256 = D1 * old_balances[i] / D0
            difference: uint256 = 0
            new_balance: uint256 = new_balances[i]
            if ideal_balance > new_balance:
                difference = ideal_balance - new_balance
            else:
                difference = new_balance - ideal_balance
            fees[i] = base_fee * difference / FEE_DENOMINATOR
            self.balances[i] = new_balance - (fees[i] * ADMIN_FEE / FEE_DENOMINATOR)
            new_balances[i] -= fees[i]
→       D2: uint256 = self.get_D_mem(rates, new_balances, amp)
→       mint_amount = total_supply * (D2 - D0) / D0
    else:
        self.balances = new_balances
        mint_amount = D1  # Take the dust if there was any
    ...
```

Now, pushing assets to the Convex lockers happens with proposals by the DAO which are executed by a timelock after a 12 hour delay. Even if a '`pushToLocker()` to a Convex locker' proposal is made at a time when the Curve pools are in good shape (balanced), there's no guarantee that any of the pools used across the lockers wouldn't be imbalanced and anyone can process a proposal that passed both voting and the timelock delay causing the liquidity provision transaction to execute in unfavourable conditions.

## Impact
Adding liquidity to a Curve pool (either base or meta pool) is at risk of receiving less LP tokens due to executing a `pushToLocker()` proposal in time when one of the Curve pools that are to be used is imbalanced and thus yielding sub-optimal returns. 

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_A.sol#L117-L169
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_C.sol#L110-L141

## Tool used
Manual Review

## Recommendation
Not sure much can be done here due to the nature of the delayed manner in which the `pushToLocker()` functions are called because of governance and the timelock. Ideally these can be made callable in a strictly permissioned manner but that'd be in direct contradiction with the DAO-oriented approach the whole protocol has embraced on.

**Comment by pseudonaut** [comment]
Could consider supporting this, may require additional dev elsewhere

**Comment by flackoon** [comment]
Escalate

Curve pools can stay imbalanced for prolonged periods of time which can hardly be tackled with execution timing once the deposit amount is specified (in the proposal) and can't be changed, which means the executor of the proposal has to wait for the Curve pool to balance itself which means missing on LP yield. Alongside that, the locker calls `add_liquidity()` with a single token which further emphasises the chance of bringing the pool to an imbalanced state and incurring the penalty. Also, there is no indication in the code or the README that the sponsor is aware of this peculiarity of Curve pools, hence I believe this report is wrongly excluded and insist it is upgraded to High severity because of the direct loss of funds as in these two reports that were deemed valid:

https://github.com/sherlock-audit/2023-10-notional-judging/issues/82
https://github.com/sherlock-audit/2023-02-notional-judging/issues/9

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Curve pools can stay imbalanced for prolonged periods of time which can hardly be tackled with execution timing once the deposit amount is specified (in the proposal) and can't be changed, which means the executor of the proposal has to wait for the Curve pool to balance itself which means missing on LP yield. Alongside that, the locker calls `add_liquidity()` with a single token which further emphasises the chance of bringing the pool to an imbalanced state and incurring the penalty. Also, there is no indication in the code or the README that the sponsor is aware of this peculiarity of Curve pools, hence I believe this report is wrongly excluded and insist it is upgraded to High severity because of the direct loss of funds as in these two reports that were deemed valid:
> 
> https://github.com/sherlock-audit/2023-10-notional-judging/issues/82
> https://github.com/sherlock-audit/2023-02-notional-judging/issues/9

You've deleted an escalation for this issue.

**Comment by panprog** [comment]
I maintain my view that it's informational issue. We can also say that admin is trusted to not deposit in the pools if it's connected with a large loss due to imbalance, or that admin weights these risks and does this in expectations of higher profits than imbalance losses.
