### ISSUE TITLE
dian.ivanov - Incorrect event parameter in `distributeYield` function in `ZivoeYDL` contract

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#423]
dian.ivanov

medium

# Incorrect event parameter in `distributeYield` function in `ZivoeYDL` contract

## Summary
The `distributeYield` function in the `ZivoeYDL` contract emits an event with an incorrect parameter when distributing residual earnings. This misalignment between the event parameter and the actual distribution could lead to confusion and inaccuracies in tracking transactions.

## Vulnerability Detail
During the distribution of residual earnings, the `YieldDistributedSingle` event is triggered with the wrong parameter `_protocol[i]` instead of the correct value `_residual[i]`. This occurs in a loop where residual earnings are processed, potentially causing incorrect data to be logged, misleading stakeholders about the actual transactions executed.

## Impact
The issue affects the logging of transactions and not the actual transfer of assets. However, inaccurate event logs can lead to misinterpretation of transaction outcomes, affecting audits, monitoring, and trust in the system's reporting accuracy.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L285C1-L286C93 :

```solidity
    function distributeYield() external nonReentrant {
        ...
        for (uint256 i = 0; i < residualRecipients.recipients.length; i++) {
            if (_residual[i] > 0) {
                address _recipient = residualRecipients.recipients[i];
                if (_recipient == IZivoeGlobals_YDL(GBL).stSTT() ||_recipient == IZivoeGlobals_YDL(GBL).stJTT()) {
                    IERC20(distributedAsset).safeIncreaseAllowance(_recipient, _residual[i]);
                    IZivoeRewards_YDL(_recipient).depositReward(distributedAsset, _residual[i]);
                    emit YieldDistributedSingle(distributedAsset, _recipient, _protocol[i]);
                }
                ...
    }
```

## Tool used

Manual Review

## Recommendation
Correct the parameter in the `YieldDistributedSingle` event emission to reflect the actual value distributed in the transaction. This adjustment ensures the accuracy of logged data and enhances the transparency and reliability of the system:

```diff solidity
    function distributeYield() external nonReentrant {
        ...
        for (uint256 i = 0; i < residualRecipients.recipients.length; i++) {
            if (_residual[i] > 0) {
                address _recipient = residualRecipients.recipients[i];
                if (_recipient == IZivoeGlobals_YDL(GBL).stSTT() ||_recipient == IZivoeGlobals_YDL(GBL).stJTT()) {
                    IERC20(distributedAsset).safeIncreaseAllowance(_recipient, _residual[i]);
                    IZivoeRewards_YDL(_recipient).depositReward(distributedAsset, _residual[i]);
-                   emit YieldDistributedSingle(distributedAsset, _recipient, _protocol[i]);
+                   emit YieldDistributedSingle(distributedAsset, _recipient, _residual[i]);
                }
                ...
    }

**Comment by pseudonaut** [comment]
Valid

**Comment by BiasedMerc** [comment]
I believe this issue should be invalid, as the Impact outlined only mentions incorrect events being emmited. According to sherlock rules this should be not be a valid issue:
[Issue validity](https://docs.sherlock.xyz/audits/judging/judging#v.-how-to-identify-a-medium-issue)

> Incorrect Event values: Incorrectly calculated/wrong values in emitted events are not considered valid medium or high.

This issue does not outline any other impacts from the outlined incorrect code. Issue #15 outlines a specific scenario under which the function will revert and lead to functionality being broken. However this issue does not outline any of the needed scenarios or even acknowledge that a revert is possible due to the incorrect code, and only mentions incorrect data being emmited.

**Comment by midori-fuse** [comment]
Escalate

Agree with the above comment. Delegating escalation

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Agree with the above comment. Delegating escalation

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by panprog** [comment]
I think the revert impact is more or less obvious, but yes, this issue doesn't mention any other impact other than incorrect emit value, which is invalid by Sherlock rules. I'm used for such obvious impacts to not prevent the issue being a dup, but the rules do seems to indicate the escalation is valid and this issue should be low, so tend to agree with the escalation.

**Comment by dianiivanov** [comment]
@midori-fuse  @panprog  @BiasedMerc 
I appreciate the insights and feedback on my finding. I'd like to highlight that both my submission and the validated issue identified by @BiasedMerc propose identical technical fix—correcting the parameter in the emit YieldDistributedSingle event from _protocol[i] to _residual[i]. This correction is crucial not only for accurate event logging but also implicitly addresses the potential for function reverts.
The proposed fix, although framed differently in terms of impact, serves the same essential purpose—ensuring the contract functions correctly under all conditions.
Given the technical overlap and the importance of the recommended fix for the proper protocol functioning, Could we reconsider the validity of this finding ?

**Comment by BiasedMerc** [comment]
> @midori-fuse @panprog @BiasedMerc I appreciate the insights and feedback on my finding. I'd like to highlight that both my submission and the validated issue identified by @BiasedMerc propose identical technical fix—correcting the parameter in the emit YieldDistributedSingle event from _protocol[i] to _residual[i]. This correction is crucial not only for accurate event logging but also implicitly addresses the potential for function reverts. The proposed fix, although framed differently in terms of impact, serves the same essential purpose—ensuring the contract functions correctly under all conditions. Given the technical overlap and the importance of the recommended fix for the proper protocol functioning, Could we reconsider the validity of this finding ?

Reports should be judged individually, and when overviewing your report standalone it would not be considered medium or high, as outlined in the Sherlock rules:

>Incorrect Event values: Incorrectly calculated/wrong values in emitted events are not considered valid medium or high.

It's important to follow the rules to ensure that all Wardens are clear on what issues are valid and not, and in this instance this would not classify as valid under the current rules.

**Comment by dianiivanov** [comment]
@BiasedMerc, I appreciate your perspective and understand the rule regarding incorrect event values. However, the essence of our findings isn't just about event accuracy but also about the potential for function reverts, which we both address with our proposed fix. Although my initial report highlighted the event logging issue, the technical solution we both recommend—correcting the parameter from _protocol[i] to _residual[i]—implicitly resolves a potential revert scenario. This overlap in solutions underscores the fix's critical nature for ensuring the contract's robust functionality.

I agree that adherence to the competition rules is crucial. My argument for reconsideration is based not solely on the event logging issue but on the broader impact our shared fix would have on the contract's operation, security and reliability.

I would be happy to hear thoughts from @midori-fuse, @panprog and the others.

**Comment by BiasedMerc** [comment]
> @BiasedMerc, I appreciate your perspective and understand the rule regarding incorrect event values. However, the essence of our findings isn't just about event accuracy but also about the potential for function reverts, which we both address with our proposed fix. Although my initial report highlighted the event logging issue, the technical solution we both recommend—correcting the parameter from _protocol[i] to _residual[i]—implicitly resolves a potential revert scenario. This overlap in solutions underscores the fix's critical nature for ensuring the contract's robust functionality.
> 
> I agree that adherence to the competition rules is crucial. My argument for reconsideration is based not solely on the event logging issue but on the broader impact our shared fix would have on the contract's operation, security and reliability.
> 
> I would be happy to hear thoughts from @midori-fuse, @panprog and the others.

I understand and don't want to argue, but let me just point out one last aspect.

An issue should be evaluated standalone, then marked as duplicate with other valid findings. 
The finding in question when evaluated standalone would be "excluded" due to the outlined Sherlock rule.
Therefore it cannot then be marked as a duplicate of any other "valid" medium or high issue afterwards.

Thanks, and also awaiting inputs from the others.

**Comment by dianiivanov** [comment]
> > @BiasedMerc, I appreciate your perspective and understand the rule regarding incorrect event values. However, the essence of our findings isn't just about event accuracy but also about the potential for function reverts, which we both address with our proposed fix. Although my initial report highlighted the event logging issue, the technical solution we both recommend—correcting the parameter from _protocol[i] to _residual[i]—implicitly resolves a potential revert scenario. This overlap in solutions underscores the fix's critical nature for ensuring the contract's robust functionality.
> > I agree that adherence to the competition rules is crucial. My argument for reconsideration is based not solely on the event logging issue but on the broader impact our shared fix would have on the contract's operation, security and reliability.
> > I would be happy to hear thoughts from @midori-fuse, @panprog and the others.
> 
> I understand and don't want to argue, but let me just point out one last aspect.
> 
> An issue should be evaluated standalone, then marked as duplicate with other valid findings. The finding in question when evaluated standalone would be "excluded" due to the outlined Sherlock rule. Therefore it cannot then be marked as a duplicate of any other "valid" medium or high issue afterwards.
> 
> Thanks, and also awaiting inputs from the others.

Thank you for your continued engagement on this topic. I'd like to emphasize that I am steering away from any notion of arguing.

**Comment by midori-fuse** [comment]
A category of issue that is invalid by [Sherlock rules](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid) is that:

> **Incorrect Event values**: Incorrectly calculated/wrong values in emitted events are not considered valid medium or high.

Therefore "incorrect event parameter" by itself is invalid.

However, the main submission describes a case where the tx reverts due to out-of-bound access. Any OOB access anywhere will cause a revert, this much is well-known. And since the tx reverts, the event is never emitted, which separates the main submission from the above rule (both by wording of "emitted" event, as well as the rule's itself intention).

The "incorrect event emission" is not an issue, the "OOB array access" is. I believe this is the least that has to be shown in order to justify having identified the issue.

**Comment by WangSecurity** [comment]
While this report and the main one are similar, this one doesn't mention the revert of `distributeYield` and doesn't mention that the arrays can be of different length. Hence, I agree this report is insufficient of being a duplicate. Planning to accept the escalation and de-duplicate the report.

**Comment by Evert0x** [comment]
Result:
Unique
Invalid

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [midori-fuse](https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/423/#issuecomment-2105924406): accepted
