### ISSUE TITLE
0x73696d616f - `keeper` may inadvertently frontrun a `borrower` `OCC_Modular::makePayment()` with a `OCC_Modular::processPayment()` call

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#429]
0x73696d616f

medium

# `keeper` may inadvertently frontrun a `borrower` `OCC_Modular::makePayment()` with a `OCC_Modular::processPayment()` call

## Summary

`OCC_Modular::makePayment()` and `OCC_Modular::processPayment()` may be triggable at the same time for 2 different loans, the borrower intends to repay 1 of them, but the keeper frontruns and repays the wrong one.

## Vulnerability Detail

`OCC_Modular::processPayment()` may be used by keepers to pull funds from the `borrower`, likely with the purpose of saving gas from the `borrower` and improve `UX`. However, there may be concurrency issues if a `borrower` has 2 loans ongoing with the same `OCC_Modular` and payment is due on both. If a borrower approves `stablecoin` to the `OCC_Modular` wishing to make a payment for one of the loans, and has enough funds to repay both loans, a keeper may view the approval and repay one of the loans that the borrower did not intend to pay. This could be harmful for the borrower as the loan that it wished to repay could be at the last payment and would be closed or could be late and accruing fees, but the keeper repaid the other loan instead and the borrower does not have funds available to repay the intended one.

Add this test to `Test_OCC_Modular.sol` for a full example of the scenario. Here the borrower has 2 loans, the first one was late, it approves `OCC_Modular`, but the keeper frontruns it and repays the second one, making the payment fail.

```solidity
function test_POC_Borrower_Frontrunned_By_keeper() public {
    uint96 random = 10_000e18 + 1001;
    bool choice = true; // bullet

    // first loan to be payed and will be accumulating late fees
    (uint256 _loanID_DAI1,,,) = simulateITO_and_createOffers_and_acceptOffers(random, choice);
    (,, uint256[10] memory _preInfo) = OCC_Modular_DAI.loanInfo(_loanID_DAI1);

    hevm.warp(block.timestamp + _preInfo[3] + _preInfo[5] + 1);

    // second loan will not be accumulating late fees yet
    uint256 _loanID_DAI2 = createRandomOffer(random, choice, DAI);
    assert(tim.try_acceptOffer(address(OCC_Modular_DAI), _loanID_DAI2));

    hevm.warp(block.timestamp + _preInfo[3] + _preInfo[5] - 11 hours);

    // Tim only has interestOwed + lateFee balance
    (, uint256 interestOwed, uint256 lateFee,) = OCC_Modular_DAI.amountOwed(_loanID_DAI1);
    deal(address(DAI), address(tim), interestOwed + lateFee);

    vm.prank(address(tim));
    IERC20(DAI).approve(address(OCC_Modular_DAI), type(uint256).max / 1e18);

    // underwriter frontruns tim due to approval and transaction time
    // repaying _loanID_DAI2 instead
    vm.prank(address(roy));
    OCC_Modular_DAI.processPayment(_loanID_DAI2);

    // tim tries to make payment but does not have the funds
    // _loanID_DAI1 continues to accrue funds
    assert(!tim.try_makePayment(address(OCC_Modular_DAI), _loanID_DAI1));
}
```

## Impact

Extra late fees accrued for the borrower or not closing a loan that was expected to be closed. This could also be impactful offchain as the borrower could argue it was tricked.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L575
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L636

## Tool used

Manual Review

Vscode

Foundry

## Recommendation

Preferably the keeper should send a borrower signature confirming that the payment of a certain loan id should be processed.

**Comment by pseudonaut** [comment]
Not relevant

**Comment by 0x73696d616f** [comment]
Escalate

Where is it said that keepers are intended to optimize loan payment?
Even if the keeper is trusted it has no way of knowing it is frontrunning the borrower.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Where is it said that keepers are intended to optimize loan payment?
> Even if the keeper is trusted it has no way of knowing it is frontrunning the borrower.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by panprog** [comment]
I believe this specific keeper is intended to be user-initiated and as such even if it frontruns user transaction, it's user mistake.

**Comment by 0x73696d616f** [comment]
> I believe this specific keeper is intended to be user-initiated and as such even if it frontruns user transaction, it's user mistake.

Just mentioning that this is not stated anywhere nor the code implies as such.

**Comment by 0x73696d616f** [comment]
Also, there are other functions that would incur in concurrency issues, [callLoan()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L492), [resolveDefault()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L682) and [supplyInterest()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L709).

**Comment by WangSecurity** [comment]
I don't really understand is it actually possible that the keeper pays out the wrong loan?

My main concern is that in your report, the keeper's behaviour seems wrong and if they're used to make a payment for the borrower (i.e. `processPayment`), then it seems like it always should be the correct loan. Do keepers actually work in a way that you approve the token and they instantly make a repayment? Can you please clarify where this assumption comes from that the keeper just repays any loan as soon as you approve the OCC_Modular and not in a way to submit the transactions that the user wants it to be?

**Comment by 0x73696d616f** [comment]
> I don't really understand is it actually possible that the keeper pays out the wrong loan?

The wrong loan according to the intended action of the borrower.

> Do keepers actually work in a way that you approve the token and they instantly make a repayment? Can you please clarify where this assumption comes from that the keeper just repays any loan as soon as you approve the OCC_Modular and not in a way to submit the transactions that the user wants it to be?

There is no documentation for how the keeper works. But a keeper is expected to fulfill the obligations as long as the state allows it to do (in this case, having the borrower's approval). This is how chainlink keepers work, for example.

The issue is that the keeper may, without malicious intent, frontrun the borrower.

I don't see any form of repayment or similar to the keeper so there is no reason to believe it is user initiated. Also, the borrower has to approve `OCC_Modular`, which makes it even less likely to be user initiated, as the borrower still has to spend gas and do 1 transaction.

**Comment by WangSecurity** [comment]
I see that indeed this path sounds possible, but this issue heavily depends on the off-chain mechanism (keeper) working incorrectly, i.e. paying not the loan the user wanted to repay, which is out of smart contracts scope. Moreover, the README says the keepers will help submit transaction to smart contracts, hence, I believe it's safe to assume that it will indeed help the user, rather than harm them.

 Planning to reject the escalation and leave the issue as it is.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x73696d616f](https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/429/#issuecomment-2105657125): rejected
