### ISSUE TITLE
Hajime - deduction of amount from zero `redemptionsQueuedSenior`  `redemptionsQueuedJunior`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#43]
Hajime

high

# deduction of amount from zero `redemptionsQueuedSenior`  `redemptionsQueuedJunior`

## Summary
from being reset to zero  `redemptionsQueuedSenior`, `redemptionsQueuedJunior` subtract amount
 
## Vulnerability Detail
before executing the `destroyRequest()` function, a modifier is called in which `redemptionsQueuedJunior` and `redemptionsQueuedSenior`, which are storage variables, are reset to zero.   In `destroysRequest()` If unlocks > epoch, the amount is deducted from `redemptionsQueuedSenior` and `redemptionsQueuedJunior`, despite the fact that they were reset to zero before.

## Impact
deduction from zeroed values of variables `redemptionsQueuedSenior`, `redemptionsQueuedJunior`

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCR/OCR_Modular.sol#L242
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCR/OCR_Modular.sol#L247
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCR/OCR_Modular.sol#L315-L316

## Tool used

Manual Review

## Recommendation
add an intermediate variable to reset

**Comment by pseudonaut** [comment]
OCR_Modular not in scope
