### ISSUE TITLE
den_sosnovskyi - `ZivoeITO::claimAirdrop` calculate `uint256 middle` value by dividing by 20, but should divide by 2

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#431]
den_sosnovskyi

medium

# `ZivoeITO::claimAirdrop` calculate `uint256 middle` value by dividing by 20, but should divide by 2

## Summary
`ZivoeITO::claimAirdrop` function calculates `middle` value from `IERC20().totalSupply()` value by dividing it by 20, but should divide by 2. 

## Vulnerability Detail
`ZivoeITO::claimAirdrop` function calculates `upper`, `lower` and `middle` values to calculate proportion of $ZVE awarded based on $pZVE credits. `middle` values should be half of the `IERC20(IZivoeGlobals_ITO(GBL).ZVE()).totalSupply()`. In order to receive this half, it should be divided by 2, but in the code it is divided by 20.

## Impact
Becaues `middle` value is not correct, the smaller amount would be vested via `createVestingSchedule` function, than should be

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L225C9-L225C82
```solidity
uint256 middle = IERC20(IZivoeGlobals_ITO(GBL).ZVE()).totalSupply() / 20;
```

## Tool used

Manual Review

## Recommendation
Change 20 to 2:
```diff
- uint256 middle = IERC20(IZivoeGlobals_ITO(GBL).ZVE()).totalSupply() / 20;
+ uint256 middle = IERC20(IZivoeGlobals_ITO(GBL).ZVE()).totalSupply() / 2;
```

**Comment by pseudonaut** [comment]
Should be 20, not valid, represents 5% of supply
