### ISSUE TITLE
den_sosnovskyi - `OCC_Modular::resolveDefault` does not return possible token leftovers to `msg.sender`, so `msg.sender` can lose tokens

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#436]
den_sosnovskyi

medium

# `OCC_Modular::resolveDefault` does not return possible token leftovers to `msg.sender`, so `msg.sender` can lose tokens

## Summary
`OCC_Modular::resolveDefault`  accepts the amount from `msg.sender` and can truncate to `loans[id].principalOwed` value. Everything truncated is stuck in the contract.

## Vulnerability Detail
In `OCC_Modular::resolveDefault` function a user can send an amount higher than `loans[id].principalOwed`. In this case `amount` value is truncated to `loans[id].principalOwed`. All truncated amount should be returned back to `msg.sender`, but it does not. So if user send more than `loans[id].principalOwed`, he/she loses leftovers, cause it is stuck in the contract.

## Impact
User can forever lose tokens send to the `OCC_Modular::resolveDefault`

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L690-L694

## Tool used

Manual Review

## Recommendation
Send back leftovers to the msg.sender at the end of the function
```diff
+        if(amount > paymentAmount){
+            IERC20(stablecoin).safeTransfer(_msgSender(), amount - paymentAmount);
+       }
```

**Comment by pseudonaut** [comment]
It was never sent in first place ...not valid
