### ISSUE TITLE
araj - `updateDistributedAsset` can cause loss of funds to stakers

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#44]
araj

medium

# `updateDistributedAsset` can cause loss of funds to stakers

## Summary
Stakers will loss accumulated yield of previous `distributedAsset` while changing `distributedAsset` in `ZivoeYDL::updateDistributedAsset`

## Vulnerability Detail
`ZivoeYDL` stores all the `yield` generated over a period of `30 days` and `distribute` it to all the parties(ZVE stakers, zSTT/zJTT stakers, ZVL) through `ZivoeYDL::distributeYield()`
```solidity
 function distributeYield() external nonReentrant {
               // Code......
}
```
Now the problem is, when `distributedAsset` is changed via `governance` then the yield generated in previous `distributedAsset` is not distributed to stakers, which is lost for stakers as `distributeYield()` is only distributing the yield generated in current `distributedAsset`
```solidity
 function distributeYield() external nonReentrant {
            // Code.....
      
            if (_recipient == IZivoeGlobals_YDL(GBL).stSTT() ||_recipient == IZivoeGlobals_YDL(GBL).stJTT()) {
             @>  IERC20(distributedAsset).safeIncreaseAllowance(_recipient, _protocol[i]);
                         
                       // Code...
             @>  IERC20(distributedAsset).safeIncreaseAllowance(IZivoeGlobals_YDL(GBL).stZVE(), stZVEAllocation);
             @>  IERC20(distributedAsset).safeIncreaseAllowance(IZivoeGlobals_YDL(GBL).vestZVE(),vestZVEAllocation);
             @>  IZivoeRewards_YDL(IZivoeGlobals_YDL(GBL).stZVE()).depositReward(distributedAsset, stZVEAllocation);
             @>  IZivoeRewards_YDL(IZivoeGlobals_YDL(GBL).vestZVE()).depositReward(distributedAsset, vestZVEAllocation);
                emit YieldDistributedSingle(distributedAsset, IZivoeGlobals_YDL(GBL).stZVE(), stZVEAllocation);
                emit YieldDistributedSingle(distributedAsset, IZivoeGlobals_YDL(GBL).vestZVE(), vestZVEAllocation);
            }
            else {
            @>  IERC20(distributedAsset).safeTransfer(_recipient, _protocol[i]);
                emit YieldDistributedSingle(distributedAsset, _recipient, _protocol[i]);
            }
        }

                        //Code...
             @>  IZivoeRewards_YDL(IZivoeGlobals_YDL(GBL).stSTT()).depositReward(distributedAsset, _seniorTranche);
             @>  IZivoeRewards_YDL(IZivoeGlobals_YDL(GBL).stJTT()).depositReward(distributedAsset, _juniorTranche);

                          //Code....
             @>  IERC20(distributedAsset).safeIncreaseAllowance(_recipient, _residual[i]);
             @>  IZivoeRewards_YDL(_recipient).depositReward(distributedAsset, _residual[i]);

                }
                              //Code.....
               @> IERC20(distributedAsset).safeIncreaseAllowance(IZivoeGlobals_YDL(GBL).stZVE(), stZVEAllocation);
               @> IERC20(distributedAsset).safeIncreaseAllowance(IZivoeGlobals_YDL(GBL).vestZVE(), vestZVEAllocation);
               @> IZivoeRewards_YDL(IZivoeGlobals_YDL(GBL).stZVE()).depositReward(distributedAsset, stZVEAllocation);
               @> IZivoeRewards_YDL(IZivoeGlobals_YDL(GBL).vestZVE()).depositReward(distributedAsset, vestZVEAllocation);
       
                else {
               @> ERC20(distributedAsset).safeTransfer(_recipient, _residual[i]);
    }
```
//Here is how it works:-
1. initial `distributedAsset` is DAI
2. 100k yield `generated` in DAI within first 29 days(or before)
3. `distributedAsset` is changed to USDC via governance
4. Now, on `30th day` yield will be distributed to all parties which is accumulated in `USDC` not DAI
5. That DAI(100k) is `lost` for staker as this will not be distributed to them

## Impact
Stakers will loss on yield, everytime `distributedAsset` is changed

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L213C1-L310C6
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L356C2-L371C6

## Tool used
Manual Review

## Recommendation
Distribute the yield generated in previous `distributedAsset` before calling `updateDistributedAsset`

**Comment by pseudonaut** [comment]
Intended
