### ISSUE TITLE
den_sosnovskyi - `OCL_ZVE::pushToLockerMulti` can often revert because allowance often will not be reset to zero because of the depositing slippage

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#440]
den_sosnovskyi

medium

# `OCL_ZVE::pushToLockerMulti` can often revert because allowance often will not be reset to zero because of the depositing slippage

## Summary
`OCL_ZVE::pushToLockerMulti` automatically expect router allowance to be reset to zero after adding liquidity to Uniswap. But it is often not true, because of the slippage while deposition to Uniswap, SushiSwap or other similar protocols

## Vulnerability Detail
`OCL_ZVE::pushToLockerMulti` allow router to spend some amount of `pairAsset` and `ZVE`. After depositing the contract requires these allowances to be zero, otherwise it reverts. The problem is that deposit to Uniswap to other similar protocols expect desired amount, and minimum amount, and very often the actual amount deposited is not desired, but something between desired and minimum. That's why this allowance check inside `OCL_ZVE::pushToLockerMulti` will revert often

Same issues:
1. `OCT_DAO::convertAndForward` function
2. `OCY_Convex_A::pushToLocker` function
3. `OCY_Convex_C::pushToLocker` function

## Impact
`OCL_ZVE::pushToLockerMulti` will revert often

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L208
```solidity
        assert(IERC20(pairAsset).allowance(address(this), router) == 0);
        assert(IERC20(ZVE).allowance(address(this), router) == 0);
```

## Tool used

Manual Review

## Recommendation
Before check for zero allowance, reset this allowance to zero manually

Duplicate of #18

**Comment by MarsWhiteHacker** [comment]
Escalate
It is a valid issue, but there is another valid issue, https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/609, that I described in this opened issue as well:
```
Same issues:

OCT_DAO::convertAndForward function
OCY_Convex_A::pushToLocker function
OCY_Convex_C::pushToLocker function
```

So can this issue be counted as two valid issue?

**Comment by sherlock-admin3** [comment]
> Escalate
> It is a valid issue, but there is another valid issue, https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/609, that I described in this opened issue as well:
> ```
> Same issues:
> 
> OCT_DAO::convertAndForward function
> OCY_Convex_A::pushToLocker function
> OCY_Convex_C::pushToLocker function
> ```
> 
> So can this issue be counted as two valid issue?

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by panprog** [comment]
An issue can not be a dup of more than 1 issue, so no, this can not count as dup to 2 issues. I also don't think all of these issues can count as 1 group, because the reasons of if (or why) the allowance can remain non-0 is different for all of them.
Even if all issues are united under 1 group, there will be no substantial ranking changes due to high amount of dups in all groups.

**Comment by WangSecurity** [comment]
Lead Judge is correct, the one report can be counted as a duplicate for only one issue and for one reward. Since this report is primarily focuses on `pushToLockerMulti`, then I believe it's fair to keep it as a duplicate of #18. Planning to reject the escalation and leave the issue as it is.

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #18

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [MarsWhiteHacker](https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/440/#issuecomment-2105661506): rejected
