### ISSUE TITLE
den_sosnovskyi - In `ZivoeSwapper::handle_validation_0502b1c5` assetIn should be token0 when `zeroForOne_0` is true, but is if written vice versa

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#445]
den_sosnovskyi

medium

# In `ZivoeSwapper::handle_validation_0502b1c5` assetIn should be token0 when `zeroForOne_0` is true, but is if written vice versa

## Summary
In `ZivoeSwapper::handle_validation_0502b1c5` function when we have `zeroForOne_0` set to true, assetIn should be token0, and assetOut - token1, but in the code thay have vice versa checks, which will revert

## Vulnerability Detail
In `ZivoeSwapper::handle_validation_0502b1c5` function we can have `zeroForOne_0` true or false. If it is true, it means we want to swap token0 for token1. So we should require that assetIn == token0(). In the code they do opposite check when `zeroForOne_0` is true - `require(IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[0])))).token1() == assetIn,`
This will always revert if data argument is correctly set. 

## Impact
`ZivoeSwapper::handle_validation_0502b1c5` will always revert with correctly encoded data argument

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/Utility/ZivoeSwapper.sol#L134
```solidity
            require(IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[0])))).token1() == assetIn,
```

## Tool used

Manual Review

## Recommendation
Change token order:
```diff
        if (zeroForOne_0) {
            //@audit-q: is it correct order of token index in comparison to handle_validation_e449022e function
-            require(IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[0])))).token1() == assetIn,
+            require(IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[0])))).token0() == assetIn,
            "ZivoeSwapper::handle_validation_0502b1c5() IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[0])))).token1() != assetIn");
        }
        else {
-            require(IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[0])))).token0() == assetIn,
+            require(IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[0])))).token1() == assetIn,
            "ZivoeSwapper::handle_validation_0502b1c5() IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[0])))).token0() != assetIn");
        }
        if (zeroForOne_DLENGTH) {
-            require(IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[_d.length - 1])))).token0() == assetOut,
+            require(IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[_d.length - 1])))).token1() == assetOut,
            "ZivoeSwapper::handle_validation_0502b1c5() IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[_d.length - 1])))).token0() != assetOut");
        }
        else {
-            require(IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[_d.length - 1])))).token1() == assetOut,
+            require(IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[_d.length - 1])))).token0() == assetOut,
            "ZivoeSwapper::handle_validation_0502b1c5() IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[_d.length - 1])))).token1() != assetOut");
        }
```

**Comment by pseudonaut** [comment]
In my tests this was the proper format, have you confirmed and validated what you're suggesting?
