### ISSUE TITLE
ether_sky - Users who stake STT and JTT tokens can rewards for non-staked users.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#446]
ether_sky

medium

# Users who stake STT and JTT tokens can rewards for non-staked users.

## Summary
Users who wish to earn `rewards` must stake `STT` and `JTT` tokens.
However, the `reward calculation` is based on the `total supply` of `STT` and `JTT` tokens, which includes both `staked` and `non-staked` tokens.
## Vulnerability Detail
When users deposit `stable coins` into the `tranche`, they receive tranche tokens `STT` and `JTT`.
```solidity
function depositSenior(uint256 amount, address asset) public notPaused nonReentrant {
    address depositor = _msgSender();

    IERC20(asset).safeTransferFrom(depositor, IZivoeGlobals_ZivoeTranches(GBL).DAO(), amount);
    
    uint256 convertedAmount = IZivoeGlobals_ZivoeTranches(GBL).standardize(amount, asset);

    uint256 incentives = rewardZVESeniorDeposit(convertedAmount);
    // Ordering important, transfer ZVE rewards prior to minting zJTT() due to totalSupply() changes.
    IERC20(IZivoeGlobals_ZivoeTranches(GBL).ZVE()).safeTransfer(depositor, incentives);
    IERC20Mintable_ZivoeTranches(IZivoeGlobals_ZivoeTranches(GBL).zSTT()).mint(depositor, convertedAmount); // @audit, here
}
```
To earn `rewards` from these tokens, they need to stake them.
```solidity
function stake(uint256 amount) external nonReentrant updateReward(_msgSender()) {
    require(amount > 0, "ZivoeRewards::stake() amount == 0");

    _totalSupply = _totalSupply.add(amount);
    _writeCheckpoint(_totalSupplyCheckpoints, _add, amount);
    _writeCheckpoint(_checkpoints[_msgSender()], _add, amount);
    _balances[_msgSender()] = _balances[_msgSender()].add(amount);
    stakingToken.safeTransferFrom(_msgSender(), address(this), amount);
    emit Staked(_msgSender(), amount);
}
```
However, the current reward calculation is based on the `total supply` of `STT` and `JTT` tokens, regardless of whether they are `staked` or not.
```solidity
function distributeYield() external nonReentrant {
    (uint256 aSTT, uint256 aJTT) = IZivoeGlobals_YDL(GBL).adjustedSupplies(); // @audit, here
    emaSTT = MATH.ema(emaSTT, aSTT, retrospectiveDistributions.min(distributionCounter));
    emaJTT = MATH.ema(emaJTT, aJTT, retrospectiveDistributions.min(distributionCounter));
}
```

For instance, if the current `total supply` of `STT` is `10,000` and only `2,000` are `staked`, the `rewards` associated with the entire `10,000` `total supply` are assigned to the users who `staked` the `2,000` `STT`.
In other words, `stakers` can potentially receive rewards `5` times the amount they actually `staked`.

I am not sure if this is an intentional design choice.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeTranches.sol#L314
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewards.sol#L253-L262
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeYDL.sol#L238-L239
## Tool used

Manual Review

**Comment by pseudonaut** [comment]
Intended
