### ISSUE TITLE
cu5t0mPe0 - The contract may be DOS

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#450]
cu5t0mPe0

high

# The contract may be DOS

## Summary

When DAO added a receiver, it did not check the upper limit, which resulted in exceeding the maximum gas of the block and achieving the effect of DoS.

## Vulnerability Detail

The relevant code for DAO to update the receiver for the YDL module is implemented as follows:

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeYDL.sol#L392-L416

The code only checks whether `recipients.length` is greater than 0, but does not check the upper limit of `recipients.length`.

In the function `distributeYield`, the array recipients will be traversed and the amount will be sent.

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeYDL.sol#L213-L310

When dos have already occurred, the DAO needs at least 7 days to issue proposals again, so important features will be dos

## Impact

Loan users may be unable to repay their loans and lose more money.

Most locker and other contracts will be DOSed for more than 7 days

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeYDL.sol#L392-L416

## Tool used

Manual Review

## Recommendation

Relevant code to check the upper limit of recipients should be added.

**Comment by pseudonaut** [comment]
Not of concern
