### ISSUE TITLE
Ironsidesec - 1 wei donation attack on `ZivoeSwapper` swap actions

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#451]
Ironsidesec

medium

# 1 wei donation attack on `ZivoeSwapper` swap actions

## Summary
Swap actions can be made to revert by donating 1 wei to contracts that inherit `ZivoeSwapper`. 
Root cause: strict equality at https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/Utility/ZivoeSwapper.sol#L88
Impact : swap actions revert

## Vulnerability Detail

OCT_YDL and OCT_DAO uses `ZivoeSwapper.convertAsset` to swap tokens from A to B.

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCT/OCT_YDL.sol#L105

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/Utility/ZivoeSwapper.sol#L166

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/Utility/ZivoeSwapper.sol#L88

```solidity

File: 2024-03-zivoe\zivoe-core-foundry\src\lockers\OCT\OCT_YDL.sol

97:     function convertAndForward(address asset, bytes calldata data) external nonReentrant {
98:         require(
99:             IZivoeGlobals_OCT_YDL(GBL).isKeeper(_msgSender()),
100:             "OCT_YDL::convertAndForward !isKeeper(_msgSender())"
101:         );
102:         address distributedAsset = IZivoeYDL_OCT_YDL(IZivoeGlobals_OCT_YDL(GBL).YDL()).distributedAsset();
103:  >>>    uint256 amountFrom = IERC20(asset).balanceOf(address(this));
104:         IERC20(asset).safeIncreaseAllowance(router1INCH_V5, amountFrom);
105:  >>>    convertAsset(asset, distributedAsset, amountFrom, data); 
106:        
107:         assert(IERC20(asset).allowance(address(this), router1INCH_V5) == 0);
108:         uint balDistributedAsset = IERC20(distributedAsset).balanceOf(address(this));
109:         emit AssetConvertedForwarded(asset, distributedAsset, amountFrom, balDistributedAsset);
110:         IERC20(distributedAsset).safeTransfer(IZivoeGlobals_OCT_YDL(GBL).YDL(), balDistributedAsset);
111:     }


File: 2024-03-zivoe\zivoe-core-foundry\src\lockers\Utility\ZivoeSwapper.sol

171:     function convertAsset(
172:         address assetIn,
173:   >>>   address assetOut,
174:         uint256 amountIn,
175:         bytes calldata data
176:     ) internal {
177:         // Handle validation.
178:         bytes4 sig = bytes4(data[:4]);
179:         if (sig == bytes4(keccak256("swap(address,(address,address,address,address,uint256,uint256,uint256),bytes,bytes)"))) {
180:             handle_validation_12aa3caf(data, assetIn, assetOut, amountIn);
181:         }

             ***
        }


File: 2024-03-zivoe\zivoe-core-foundry\src\lockers\Utility\ZivoeSwapper.sol

73:     function handle_validation_12aa3caf(bytes calldata data, address assetIn, address assetOut, uint256 amountIn) internal view {
74:         (, SwapDescription memory _b,) = abi.decode(data[4:], (address, SwapDescription, bytes));
75:         require(address(_b.srcToken) == assetIn, "ZivoeSwapper::handle_validation_12aa3caf() address(_b.srcToken) != assetIn");
76:         require(address(_b.dstToken) == assetOut, "ZivoeSwapper::handle_validation_12aa3caf() address(_b.dstToken) != assetOut");
77:         
78:   >>>   require(_b.amount == amountIn, "ZivoeSwapper::handle_validation_12aa3caf() _b.amount != amountIn");
79:         require(_b.dstReceiver == address(this), "ZivoeSwapper::handle_validation_12aa3caf() _b.dstReceiver != address(this)");
80:     }

```

**Attack path :**

1. Keeper calls L97 above, `OCT_YDL.convertAndForward` or `OCT_DAO.convertAndForward` with params `address asset, bytes calldata data`
2. Then it will call L171 of `ZivoeSwapper.convertAsset` which will internally call L73 `handle_validation_12aa3caf`
3. Focus on line 78 from `ZivoeSwapper` above, it is validating if the `_b.amount == amountIn`
4. _b.amount cannot be manipulated because it is coming from the input parameter `data`, but `amountIn` can be manipulated because, look at Line 103 & 105 from `OCT_YDL`, it is calculated from that contract's balance.
5. Someone can donate 1 wei, and this whole swap action will revert, because before donating, the keeper will see the contract's balance A and that will be his `_b.amount`, but after submitting onchain, someone donates and balance becomes A + 1 wei. so `_b.amount < amountIn` happens.

The frontrun is possible and team did not mention about using private mempool for keeper on readme or natspec comments or docs. So the keeper will definitely get frontran.

https://github.com/sherlock-audit/2024-03-zivoe#q-are-there-any-off-chain-mechanisms-or-off-chain-procedures-for-the-protocol-keeper-bots-input-validation-expectations-etc

```md
Q: Are there any off-chain mechanisms or off-chain procedures for the protocol (keeper bots, input validation expectations, etc)?
Keepers will handle conversions in the OCT_ lockers (via 1INCHv5 APIs and submitting tx's to smart contracts) For minting tranche tokens (or participating in ITO, minting tokens there) we have front-end mechanisms to validate input


```
This issue not only exists on swap(), but will happens on all unoswap, uniswapv3, and orderRFQ too.

## Impact
Revert to DOS for the swap actions.  And yield conversions are very important actions, so this is medium.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCT/OCT_YDL.sol#L105

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/Utility/ZivoeSwapper.sol#L166

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/Utility/ZivoeSwapper.sol#L88

## Tool used

Manual Review

## Recommendation

Use private mempool like flashbots RPC. or don't do a strict equality check at 

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/Utility/ZivoeSwapper.sol#L88

**Comment by pseudonaut** [comment]
We're already going to be running tx's through flash-bots
