### ISSUE TITLE
Ironsidesec - Many uniswap v2 and v3 swap actions of `ZivoeSwapper` will revert due to wrong `token0 and token1` validation

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#453]
Ironsidesec

high

# Many uniswap v2 and v3 swap actions of `ZivoeSwapper` will revert due to wrong `token0 and token1` validation

## Summary
Impact: many routes of pairs involving `USDC, DAI, USDT, FRAX, CVX, CRV` of both uniswap v2 and uniswap v3 will revert. So, instead, we must take another route with a lower price, resulting in a loss of yield to stakeholders.
root cause : due to wrong `token0 and token1 / assetin - assetout` validation

## Vulnerability Detail

**Note**: this issue occurs in both uni v2 and v3 swaps. And the swapping route's pairs length doesn't matter if 1 or > 1

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCT/OCT_YDL.sol#L105

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/Utility/ZivoeSwapper.sol#L133-L147

```solidity

File: 2024-03-zivoe\zivoe-core-foundry\src\lockers\OCT\OCT_YDL.sol

97:     function convertAndForward(address asset, bytes calldata data) external nonReentrant {
98:         require(
99:             IZivoeGlobals_OCT_YDL(GBL).isKeeper(_msgSender()),
100:             "OCT_YDL::convertAndForward !isKeeper(_msgSender())"
101:         );
102:         address distributedAsset = IZivoeYDL_OCT_YDL(IZivoeGlobals_OCT_YDL(GBL).YDL()).distributedAsset();
103:         uint256 amountFrom = IERC20(asset).balanceOf(address(this));
104:         IERC20(asset).safeIncreaseAllowance(router1INCH_V5, amountFrom);
105:   >>>   convertAsset(asset, distributedAsset, amountFrom, data);
107:         assert(IERC20(asset).allowance(address(this), router1INCH_V5) == 0);
108:         uint balDistributedAsset = IERC20(distributedAsset).balanceOf(address(this));
109:         emit AssetConvertedForwarded(asset, distributedAsset, amountFrom, balDistributedAsset);
110:         IERC20(distributedAsset).safeTransfer(IZivoeGlobals_OCT_YDL(GBL).YDL(), balDistributedAsset);
111:     }



File: 2024-03-zivoe\zivoe-core-foundry\src\lockers\Utility\ZivoeSwapper.sol

    /// @dev "0502b1c5": "unoswap(address,uint256,uint256,uint256[])" for uniswapV2 pools

111:     function handle_validation_0502b1c5(bytes calldata data, address assetIn, address assetOut, uint256 amountIn) internal view {
112:         (address _a, uint256 _b,, uint256[] memory _d) = abi.decode(data[4:], (address, uint256, uint256, uint256[]));
113:         require(_a == assetIn, "ZivoeSwapper::handle_validation_0502b1c5() _a != assetIn");
114:         require(_b == amountIn, "ZivoeSwapper::handle_validation_0502b1c5() _b != amountIn");
115:         bool zeroForOne_0;
116:         bool zeroForOne_DLENGTH;
117:         uint256 info_0 = _d[0];
118:         uint256 info_DLENGTH = _d[_d.length - 1];
119:         assembly {
120:             zeroForOne_0 := and(info_0, _REVERSE_MASK)
121:             zeroForOne_DLENGTH := and(info_DLENGTH, _REVERSE_MASK)
122:         }
123:
124:            
125:         if (zeroForOne_0) {
126:             require(IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[0])))).token1() == assetIn,
127:             "ZivoeSwapper::handle_validation_0502b1c5() IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[0])))).token1() != assetIn");
128:         }
129:         else {
130:             require(IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[0])))).token0() == assetIn,
131:             "ZivoeSwapper::handle_validation_0502b1c5() IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[0])))).token0() != assetIn");
132:         }
133:         if (zeroForOne_DLENGTH) {
134:             require(IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[_d.length - 1])))).token0() == assetOut,
135:             "ZivoeSwapper::handle_validation_0502b1c5() IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[_d.length - 1])))).token0() != assetOut");
136:         }
137:         else {
138:             require(IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[_d.length - 1])))).token1() == assetOut,
139:             "ZivoeSwapper::handle_validation_0502b1c5() IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[_d.length - 1])))).token1() != assetOut");
140:         }
141:     }

```

**Issue path:**

1. So, ZIVOE uses DAI as the distributing token in YDL. But some rewards were earned from external staking in USDC. And they are currently stored in OXT_YDL yet to be swapped into DAI and sent to YDL
2. So, keeoer will call `OCT_YDL.convertAndForward` with params `address asset, bytes calldata data`, then it will call  `ZivoeSwapper.convertAsset` which will internally call `handle_validation_0502b1c5` to validate the token 0 and token 1  and the pairs array used in `data` param.
3. The pair to swap from USDC to DAI is [0xAE461cA67B15dc8dc81CE7615e0320dA1A9aB8D5](https://etherscan.io/address/0xAE461cA67B15dc8dc81CE7615e0320dA1A9aB8D5), So in L112 above `_d` array will be [uint256(uint160(address(0xAE461cA67B15dc8dc81CE7615e0320dA1A9aB8D5)))]
4. now `zeroForOne_0` will always be false because and(pair, _REVERSE_MASK) = and(0x000000000000000000000000ae461ca67b15dc8dc81ce7615e0320da1a9ab8d5,0x8000000000000000000000000000000000000000000000000000000000000000) = false
5. It will always be false, same for `zeroForOne_DLENGTH` calculation both are false always.
6. If both are false, then line 130 will trigger, and it will revert in this case because look at line 105 above, it will convert from `asset => distributedAsset`, so its always `USDC => DAI`, so `assetIn` in L130 will be USDC and it is validated with `uinV2pair.token0`, but the token0 in that pair is DAI. So this line will revert.

7. so the revert line 130 above be like `require(DAI == USDC)`. click to see the `token0` being `DAI` https://etherscan.io/address/0xAE461cA67B15dc8dc81CE7615e0320dA1A9aB8D5#readContract#F15
8. uniswap v3, also does the same validation leading to reverts, becasue the pair creation is same in v2 and v3 depending on token 0 > or < token 1.

## Impact
Many routes of uniswap v2 and v3 involving `USDC, DAI, USDT, FRAX,, CVX, CRV`, will revert due to wrong `token0` and `token1` validation.  So, instead, we must take another route with a lower price, resulting in a loss of yield to stakeholders. so `High`.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCT/OCT_YDL.sol#L105

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/Utility/ZivoeSwapper.sol#L133-L147

## Tool used

Manual Review

## Recommendation

Remove the token0 and token1 validations because keeper is trusted, and validate the 1 inch data offchain.
Or, on each uniswap pair, compare if token 0 < or > token 1 and then validate.

**Comment by pseudonaut** [comment]
In my test-cases this worked properly ... I validated this multiple times and believe it to be the proper format
