### ISSUE TITLE
stackbuster23 - Looping Over an Array of unbounded size would lead to denial of service.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#464]
stackbuster23

medium

# Looping Over an Array of unbounded size would lead to denial of service.

## Summary

Looping Over an Array of unbounded size would lead to denial of service.

## Vulnerability Details

The ZiveoRewardVesting and ZiveoReward contracts both have and use a state variable rewardTokens, which is an array of address type (`address[] public rewardTokens`), for storing ERC20 token addresses in the contracts storage. Tokens addresses can be added to the rewardTokens array through the addReward function
(`function addReward(address _rewardsToken, uint256 _rewardsDuration) external`) which pushes token addresses unto the rewardTokens array with no upper bound on the length of the array. More so, the modifier updateReward which modifies and updates the state mapping rewardData (`mapping(address => Reward) public rewardData;`), does have to loop over the rewardTokens array to update there respective informations in the rewardData mapping.  If at some point there are now a large number of reward token addresses, iterating over them will become very costly and causes the block to reach its gas limit. This will disrupt functions where this modifier is used, leaving the contract's functionalities such as depositing Rewards, revoking Vesting Schedule, users getting there rewards, impede ability to stake and also would disrupt the withdrawals of staking tokens by users of the protocol in a state of DoS.

## Impact

The impact is High, as the contract will be in a state of DoS, without a way for anyone to withdraw their staking token, claim rewards, stake and cancel vestiing schedule. Likelihood is low as it requires a pretty large number od reward token addresses added.

## Code Snippet

    The modifier applicable to both the ZiveoRewardVesting and ZiveoReward contracts.

```solidity

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewards.sol#L123-L125

```
Modifier Used in The following Functions:

```solidity

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewards.sol#L228-L229


https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewards.sol#L253

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewards.sol#L270

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewards.sol#L270

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewards.sol#L299

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L352

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L473

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L501

```

## Tool used

Manual Review

## Recommendation

Limit the numbers of reward tokens that would be added to the array, protocol could decide on the maximum numbers of reward tokens that would not be too gas intensive, standing as the upper limit. Moreover, informations could be updated for individual tokens instead of always having to iterate over the rewardTokens array.

**Comment by pseudonaut** [comment]
It's already capped, not valid
