### ISSUE TITLE
JigglypuffAndPikachu - Basis Can Be Manipulated Via Uniswap Pool Manipulation

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#467]
JigglypuffAndPikachu

medium

# Basis Can Be Manipulated Via Uniswap Pool Manipulation

## Summary

The `basis` can be manipulated by frontrunning `forwardYield()` with a swap through the Uniswap pool. There is actually a nuance where this frontrunning would lose money if the `forwardYield()` call removes liquidity, but we can avoid this by _reducing_ the USDC in the pool rather than increasing it. 

## Vulnerability Detail

For this description, we'll let USDC be the base asset.

`basis` is a record of the USDC of the liquidity position in the `USDC/ZVE` pool. When `forwardYield` is called, an attacker can frontrun the call by _decreasing_ the `USDC` and increasing `ZVE` in the pool to reduce the basis. This low basis would make a future call to `forwardYield()` forward far more yield than there would be if the price was unmanipulated.

It may seem counterintuitive to _decrease_ the basis - why do that when increasing it would immediately increase the yield forwarded?

The problem with increasing the basis is that when `amount > basis`, [liquidity is removed](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L316-L318).

 That means that when the sandwich attacker tries to swap back/rebalance the pool after `forwardYield()`, they are swapping back through a larger amount of liquidity, and hence lose money, which makes it an invalid/unprofitable attack path.

## Impact

Basis can be manipulated to unfairly increase the rewards distributed.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L302-L303

## Tool used

Manual Review

## Recommendation

Use a TWAP of the USDC reserves in the Uniswap pool rather than the current reserves.

Duplicate of #296

**Comment by pseudonaut** [comment]
Mitigated via flash-bots call, not of concern
