### ISSUE TITLE
saidam017 - Governor's proposal cancel mechanism is not implemented and could potentially cause issues.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#473]
saidam017

medium

# Governor's proposal cancel mechanism is not implemented and could potentially cause issues.

## Summary

`ZivoeGovernorV2` has an internal `_cancel` function that cancels proposals that are currently not active or not yet executed. However, this function is not exposed to any public/external function and cannot be called, potentially causing issues in the future.

## Vulnerability Detail

In `ZivoeGovernorV2`, it can be observed that there is an internal `_cancel` function that is not exposed to any public/external interfaces, including inside all inherited contracts.

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGovernorV2.sol#L134-L141

```solidity
    function _cancel(
        address[] memory targets, 
        uint256[] memory values, 
        bytes[] memory calldatas, 
        bytes32 descriptionHash
    ) internal override(Governor, ZivoeGTC) returns (uint256) {
        return ZivoeGTC._cancel(targets, values, calldatas, descriptionHash);
    }
```

## Impact

In some cases, canceling a proposal might be needed when the proposer sees that their proposal has become outdated or no longer aligns with the goals or interests of the DAO. It also helps prevent spam or low-quality proposals, especially in cases where the proposer's delegated voting power drops below the proposal threshold.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGovernorV2.sol#L134-L141

## Tool used

Manual Review

## Recommendation

Implement an external/public cancel function and define the circumstances under which the proposal can be canceled.

**Comment by pseudonaut** [comment]
Not valid, managed by canceller role in another contract
