### ISSUE TITLE
BiasedMerc - OLC_ZVE will revert if USDC amount transfered is below 10 USDC, which can cause issues with providing liquidity

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#48]
BiasedMerc

medium

# OLC_ZVE will revert if USDC amount transfered is below 10 USDC, which can cause issues with providing liquidity

## Summary

`OLC_ZVE::pushToLockerMulti()` checks that any amount of tokens being sent is greater than `10 * 10**6`. When the token provided is USDC, this is equal to 10 USDC, whilst this minimum amount will be much lower for other tokens utilised by the protocol. Meaning if the DAO wants to transfer any amount lower than 10 USDC, the call will revert.

## Vulnerability Detail

The Zivoe protocol is intending to use multiple stablecoins, but in this issue we will just focus on USDC and FRAX for comparison.

`USDC` has 6 decimals, whilst `FRAX` has 18. Meaning that:
`1 USDC = 1,000,000`
`1 FRAX = 1,000,000,000,000,000,000`

[OCL_ZVE::pushToLockerMulti()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L172-L184)
```solidity
    function pushToLockerMulti(
        address[] calldata assets, uint256[] calldata amounts, bytes[] calldata data
    ) external override onlyOwner nonReentrant {
        address ZVE = IZivoeGlobals_OCL_ZVE(GBL).ZVE();
        require(
            assets[0] == pairAsset && assets[1] == ZVE,
            "OCL_ZVE::pushToLockerMulti() assets[0] != pairAsset || assets[1] != ZVE"
        );

        for (uint256 i = 0; i < 2; i++) {
            require(amounts[i] >= 10 * 10**6, "OCL_ZVE::pushToLockerMulti() amounts[i] < 10 * 10**6");
            IERC20(assets[i]).safeTransferFrom(owner(), address(this), amounts[i]);
        }
```
`pushToLockerMulti` allows the DAO to add liquidity to UniswapV2 through the `OLC_ZVE` locker. When transfering the tokens, a for loop is used to checks that the amounts of tokens is:
`amounts[i] >= 10 * 10**6`

However this check is done not considering that different tokens have different decimals, meaning the minimum amount is different for `USDC` and `FRAX`, using the minimum provided in the require statement of `10000000`:
`10000000` of `USDC` = `10000000 / 10 * 6 = 10 USDC`
`10000000` of `FRAX` = `10000000 / 10 * 18 = 0.00000000001 FRAX`

The minimum transfer requirements for different assets are inconsistant, which can cause DAO calls to the locker to fail if this behaviour is undocumented and unexpected. 

Also if a pool is heavily imbalanced due to swaps, then this could mean that appropriate liquidity cannot be added. Considering that the `OCL_ZVE` locker could have left over USDC from a previous call (due to how liquidity to UniswapV2 is added, meanining leftover tokens are expected in the locker), then the actual amount the DAO needs to send to the locker could be small, as they would be wanting to utilise the rest of the leftover funds to add liquidity to the router.

[OCL_ZVE.sol#L192-L206](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L192-L206)
```solidity
        uint balPairAsset = IERC20(pairAsset).balanceOf(address(this));
        uint balZVE = IERC20(ZVE).balanceOf(address(this));
        IERC20(pairAsset).safeIncreaseAllowance(router, balPairAsset);
        IERC20(ZVE).safeIncreaseAllowance(router, balZVE);

        // Prevent volatility of greater than 10% in pool relative to amounts present.
        (uint256 depositedPairAsset, uint256 depositedZVE, uint256 minted) = IRouter_OCL_ZVE(router).addLiquidity(
            pairAsset, 
            ZVE, 
            balPairAsset,
            balZVE, 
            (balPairAsset * 9) / 10,
            (balZVE * 9) / 10, 
            address(this), block.timestamp + 14 days
        );
```
`balPairAsset` is the current balance of the locker, rather than the passed `amounts` value passed by the DAO. Meaning if there are `2500` USDC left in the contract from a previous large liquidity provision call, then the DAO could only want to pass in `1 USDC` and `2500 ZVE` to add liquidity to the LP proportionally, however this call will fail. 

## Impact

DAO calls to `pushToLockerMulti` will revert if the locker's stablecoin is `USDC` and less than `10 USDC` is provided as one of the amounts to transfer. As outlined in the final paragraph of the explanation, this can lead to issues with providing liquidity to the UniswapV2 router.

## Code Snippet

[OCL_ZVE::pushToLockerMulti()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L172-L184)
[OCL_ZVE.sol#L192-L206](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L192-L206)

## Tool used

Manual Review

## Recommendation

Remove the amount check, as decimal amounts do not matter in this context, as the only place where the `amounts[i]` is used is within the `safeTransferFrom()`, which will be calling the contract of the token which will have the appropriate decimal scaling. The operations later in the function use `balanceOf()` for amounts to be sent to LPs.

**Comment by pseudonaut** [comment]
Intended
