### ISSUE TITLE
BoRonGod - malicious user can force OCY_OUSD to lose compound interest from rebase.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#483]
BoRonGod

medium

# malicious user can force OCY_OUSD to lose compound interest from rebase.

## Summary

Due to no access control, malicious user can force OCY_OUSD to lose compound interest from rebase.

## Vulnerability Detail

According to [Origin doc](https://docs.oeth.com/guides/integration-guide-for-exchanges#:~:text=Any%20smart%20contract,are%20always%20earning.):

> Any smart contract that is holding oTokens needs to manually opt-in to receive the yield by calling rebaseOptIn(). This is due to the [elastic supply](https://docs.oeth.com/core-concepts/elastic-supply) and the [rebasing nature of oTokens](https://docs.oeth.com/core-concepts/elastic-supply/rebasing-and-smart-contracts). Many exchanges sweep customer funds into a multi-sig wallet for cold storage. If you do this, you'll want to make sure that you opt-in to rebasing so that you are always earning.

Although function `rebase()` is called to make sure `OCY_OUSD` can earn yield, other contracts in protocol cannot rebase OUSD.

So, since OUSD compounds once a day, a malicious user can call `forwardYield()` daily to push new yield to `OCT_YDL`, making this part of OUSD no longer able to participate in rebasing.

Currently, OUSD serves a 30-day APY of 11.32%, which means they have a APR of 1+365*(1.1132)^(1/365) = 1.10725. Users lose 10% of their yield because of the attacker.

So, protocol would suffer a loss at APY-APR from this attack.

## Impact

malicious user can force OCY_OUSD to lose compound interest from rebase.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_OUSD.sol#L145

## Tool used

Manual Review

## Recommendation

make `OCT_YDL` rebase for `OUSD`, or add a access control on `forwardYield`.

**Comment by pseudonaut** [comment]
It'll be handled quickly in OCT_YDL and this is intended as is

**Comment by Albort-J** [comment]
invalid

**Comment by RealLTDingZhen** [comment]
escalate

I believe this is a issue when Zivoe becomes one of the major holders of OUSD. Other OUSD holders can call `forwardYield()` daily to get more rebase yield(eat into yield of Zivoe), causing Zivoe lose 10% of their APY yield because of the attack, and the yield goes into other OUSD holders. Since the pull/push functions are controlled by DAO, `forwardYield` should be considered to have an access control.

**Comment by sherlock-admin3** [comment]
> escalate
> 
> I believe this is a issue when Zivoe becomes one of the major holders of OUSD. Other OUSD holders can call `forwardYield()` daily to get more rebase yield(eat into yield of Zivoe), causing Zivoe lose 10% of their APY yield because of the attack, and the yield goes into other OUSD holders. Since the pull/push functions are controlled by DAO, `forwardYield` should be considered to have an access control.

You've deleted an escalation for this issue.

**Comment by panprog** [comment]
This is intended.
