### ISSUE TITLE
rbserver - Calling `depositJunior` and `depositSenior` functions revert when `block.timestamp == end` is true at which ITO is not concluded

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#490]
rbserver

medium

# Calling `depositJunior` and `depositSenior` functions revert when `block.timestamp == end` is true at which ITO is not concluded

## Summary
Calling the `depositJunior` and `depositSenior` functions revert when `block.timestamp == end` is true at which the ITO is not finished. This contradicts the protocol's specification that should allow users to deposit stablecoins for minting Zivoe Junior and/or Senior Tranche tokens before the ITO is concluded.

## Vulnerability Detail
The `claimAirdrop` and `migrateDeposits` functions shown in the Code Snippet section can only be called by someone who is not ZVL when `block.timestamp > end` is true. Since the protocol's specification requires these functions to only be callable by someone who is not ZVL when the ITO is concluded, the ITO is considered finished when `block.timestamp > end` is true, which also indicates that it is not finished when `block.timestamp <= end` is true. However, when `block.timestamp == end` is true at which the ITO is not yet finished, calling the `depositJunior` and `depositSenior` functions shown in the Code Snippet section revert because they require `block.timestamp < end` to be true.

## Impact
For the users who deposited stablecoins for minting Zivoe Junior and/or Senior Tranche tokens, their `depositJunior` and `depositSenior` transactions can be executed in the block whose `block.timestamp` equals `end`. However, these users' `depositJunior` and `depositSenior` transactions revert, which forces them to miss the opportunities for minting Zivoe Junior and/or Senior Tranche tokens even though the ITO is not finished. This is against the protocol's specification, which should allow users to deposit stablecoins for minting Zivoe Junior and/or Senior Tranche tokens before the ITO is concluded.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L203-L242
```solidity
    function claimAirdrop(address depositor) external returns (
        uint256 zSTTClaimed, uint256 zJTTClaimed, uint256 ZVEVested
    ) {
        require(end != 0, "ZivoeITO::claimAirdrop() end == 0");
        require(block.timestamp > end || migrated, "ZivoeITO::claimAirdrop() block.timestamp <= end && !migrated");
        ...
    }
```

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L313-L335
```solidity
    function migrateDeposits() external {
        require(end != 0, "ZivoeITO::migrateDeposits() end == 0");
        if (_msgSender() != IZivoeGlobals_ITO(GBL).ZVL()) {
            require(block.timestamp > end, "ZivoeITO::migrateDeposits() block.timestamp <= end");
        }
        ...
    }
```

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L248-L271
```solidity
    function depositJunior(uint256 amount, address asset) public {
        require(block.timestamp < end, "ZivoeITO::depositJunior() block.timestamp >= end");
        ...
    }
```

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L277-L298
```solidity
    function depositSenior(uint256 amount, address asset) public {
        require(block.timestamp < end, "ZivoeITO::depositSenior() block.timestamp >= end");
        ...
    }
```

## Tool used
Manual Review

## Recommendation
The `depositJunior` and `depositSenior` functions can be updated to require `block.timestamp <= end` instead of `block.timestamp < end` to be true. Alternatively, if `end` is considered as the timestamp at which the ITO is concluded, the `claimAirdrop` and `migrateDeposits` functions can be updated to require `block.timestamp >= end` instead of `block.timestamp > end` to be true.

**Comment by pseudonaut** [comment]
The issue is in a single block? If so, not relevant or of concern
