### ISSUE TITLE
Nihavent - [M-#] Incorrect computation of `M` in `ZivoeMath::ema()` function results in over-weighting base-value `bV` instead of current-value `cV`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#491]
Nihavent

medium

# [M-#] Incorrect computation of `M` in `ZivoeMath::ema()` function results in over-weighting base-value `bV` instead of current-value `cV`

## Summary

According to the docs (https://docs.zivoe.com/user-docs/yield-distribution/mathematics#ema), the `ZivoeMath::ema()` function "Conceptually we are exponentially weighting the current value relative to the prior value, to give greater weighting to the most recent value."

Due to the calculation of `M` in `ZivoeMath::ema()`, greater weight is given to the recent value (`cV`) for `N` <= 2 which equates to the first two times `ZivoeYDL::distributeYield()` is called. For the remainder of the life of the protocol (`N` > 2), greater weight will be given to the prior value (`bV`).

## Vulnerability Detail

In the `ZivoeMath::ema()`, `M` can take a range of values between 0 and WAD. When this value is 0, 100% weighting is given to the prior value and 0% weighting to the current value. When this value is WAD, 0% weighting is given to the prior value and 100% weighting to the current value.

As stated in the documentation, it is intended to give greater weighting to the current value, implying that `M` should be > 0.5*WAD for the majority of the life of the protocol. However, with the current calculation of `M`:

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeMath.sol#L37

```javascript
  uint256 M = (WAD * 2).floorDiv(N + 1);
```
The protocol will give greater weighting to the prior value, as shown in the table below:

| N           | M           | Weight of current value Cv | Weight of prior value Pv |
| ----------- | ----------- | -------------------------- | ------------------------ |
| 1           | 1           | 100%                       | 0
| 2           | 0.667       | 66.7%                      | 33.3%
| 3           | 0.5         | 50%                        | 50%
| 4           | 0.4         | 40%                        | 60%
| 5           | 0.333       | 33.3%                      | 66.6%
| >=6         | 0.286       | 28.6%                      | 71.4%

## Impact

The `ZivoeYDL::emaSTT` and `ZivoeYDL::emaJTT` state variables are calculated incorrectly and as a result, each Tranche's EMA value is extremely slow to respond to changes in the size of their respective tranche.

Consider the example provided in the docs (https://docs.zivoe.com/user-docs/yield-distribution) with an indefinite continuation where the size of the Senior Tranche does not change after 24,000,000:

| Month | Adjust Supply of zSTT | Senior EMA |
|-------|------------------------|------------|
| 1     | 10,000,000             | 9,333,333  |
| 2     | 12,000,000             | 10,666,666 |
| 3     | 14,000,000             | 11,999,999 |
| 4     | 16,000,000             | 13,333,332 |
| 5     | 18,000,000             | 14,666,665 |
| 6     | 20,000,000             | 16,190,474 |
| 7     | 22,000,000             | 17,850,338 |
| 8     | 24,000,000             | 19,607,384 |
| 9     | 24,000,000             | 20,862,417 |
| 10    | 24,000,000             | 21,758,869 |
| 11    | 24,000,000             | 22,399,192 |
| 12    | 24,000,000             | 22,856,566 |
| 13    | 24,000,000             | 23,183,261 |
| 14    | 24,000,000             | 23,416,615 |
| 15    | 24,000,000             | 23,583,297 |
| 16    | 24,000,000             | 23,702,355 |
| 17    | 24,000,000             | 23,787,396 |
| 18    | 24,000,000             | 23,848,140 |
| 19    | 24,000,000             | 23,891,529 |
| 20    | 24,000,000             | 23,922,520 |

Etc..

Assuming adjusted supply of `zSTT` does not change, it will take ~49 months for Senior EMA to catch up to the tranche size!

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeMath.sol#L35-L39

```javascript

    function ema(uint256 bV, uint256 cV, uint256 N) external pure returns (uint256 eV) {
        assert(N != 0);
        uint256 M = (WAD * 2).floorDiv(N + 1);
        eV = ((M * cV) + (WAD - M) * bV).floorDiv(WAD);
    }

```

## Tool used

Manual Review

## Recommendation

Update the calculation of `M`, so in the limit, it stabalizes somewhere in the range 0.5*WAD < `M` < 1. The exact calculation of `M` used will be a commercial decision.

**Comment by pseudonaut** [comment]
This seems reasonable and intended
