### ISSUE TITLE
ether_sky - The inconsistency of whitelisted stablecoins in `ZivoeITO` and `ZivoeGlobals`.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#500]
ether_sky

medium

# The inconsistency of whitelisted stablecoins in `ZivoeITO` and `ZivoeGlobals`.

## Vulnerability Detail
Users can deposit `whitelisted stable coins` into `tranches` through `ITO`.
There are `4` possible `whitelisted stable coins`.
```solidity
function depositJunior(uint256 amount, address asset) public {
    require(block.timestamp < end, "ZivoeITO::depositJunior() block.timestamp >= end");
    require(!migrated, "ZivoeITO::depositJunior() migrated");
    require(
        asset == stables[0] || asset == stables[1] || asset == stables[2] || asset == stables[3],  // @audit, here
        "ZivoeITO::depositJunior() asset != stables[0-3]"
    );
}
```
After `migration`, users directly deposit `stable coins` into the `tranches`.
```solidity
function depositJunior(uint256 amount, address asset) public notPaused nonReentrant {
    require(
        IZivoeGlobals_ZivoeTranches(GBL).stablecoinWhitelist(asset),  // @audit, here
        "ZivoeTranches::depositJunior() !IZivoeGlobals_ZivoeTranches(GBL).stablecoinWhitelist(asset)"
    );
}
```
However, in `ZivoeGlobals`, only `3 stable coins` are listed as `whitelisted`.
```solidity
function initializeGlobals(
    address[] calldata globals,
    address[] calldata stablecoins
) external onlyOwner {
    require(DAO == address(0), "ZivoeGlobals::initializeGlobals() DAO != address(0)");

    stablecoinWhitelist[stablecoins[0]] = true; // DAI
    stablecoinWhitelist[stablecoins[1]] = true; // USDC
    stablecoinWhitelist[stablecoins[2]] = true; // USDT
}
```
This inconsistency leads me to consider two possible cases:
- One important `stable coin` is missing from `ZivoeGlobals`.
- One `stable coin` should not be `whitelisted` in `ITO`.

Of course, the `ZVL` can address this by adding the missing `stable coin` to the `whitelisted` list in `ZivoeGlobals`, but this is a `fix`.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeITO.sol#L251-L254
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeTranches.sol#L270
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeGlobals.sol#L202-L204
## Tool used

Manual Review

## Recommendation
We need to synchronize these.

**Comment by pseudonaut** [comment]
Intended
