### ISSUE TITLE
ether_sky - When defaults remain unresolved, no one will deposit into `Junior Tranches`.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#504]
ether_sky

medium

# When defaults remain unresolved, no one will deposit into `Junior Tranches`.

## Vulnerability Detail
When `defaults` occur, they first affect the `Junior Tranche`, leading to an absolute decrease in `JTT token's price`.
However, new `deposit` don't take this into account.
A user depositing `1,000` `stable coins` will receive `1,000` `JTT` tokens.
```solidity
function depositJunior(uint256 amount, address asset) public notPaused nonReentrant {
    require(
        IZivoeGlobals_ZivoeTranches(GBL).stablecoinWhitelist(asset), 
        "ZivoeTranches::depositJunior() !IZivoeGlobals_ZivoeTranches(GBL).stablecoinWhitelist(asset)"
    );
    require(tranchesUnlocked, "ZivoeTranches::depositJunior() !tranchesUnlocked");

    address depositor = _msgSender();

    IERC20(asset).safeTransferFrom(depositor, IZivoeGlobals_ZivoeTranches(GBL).DAO(), amount);
    
    uint256 convertedAmount = IZivoeGlobals_ZivoeTranches(GBL).standardize(amount, asset);

    require(isJuniorOpen(amount, asset),"ZivoeTranches::depositJunior() !isJuniorOpen(amount, asset)");

    uint256 incentives = rewardZVEJuniorDeposit(convertedAmount);
    emit JuniorDeposit(depositor, asset, amount, incentives);

    // Ordering important, transfer ZVE rewards prior to minting zJTT() due to totalSupply() changes.
    IERC20(IZivoeGlobals_ZivoeTranches(GBL).ZVE()).safeTransfer(depositor, incentives);
    IERC20Mintable_ZivoeTranches(IZivoeGlobals_ZivoeTranches(GBL).zJTT()).mint(depositor, convertedAmount); // @audit, here
}
```
It's obvious that no one would take such action, anticipating immediate `loss`.

While users could purchase `JTT` tokens in the secondary `market` during this period, protocol liquidity won't increase until `defaults` are `resolved`.
Moreover, there is no guarantee that `defaults` will always be promptly `resolved`.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeTranches.sol#L288
## Tool used

Manual Review

## Recommendation

Duplicate of #211

**Comment by pseudonaut** [comment]
Intended
