### ISSUE TITLE
NoOne - M-1 Reentrancy Vulnerability in depositStablecoin Function

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#505]
NoOne

medium

# M-1 Reentrancy Vulnerability in depositStablecoin Function

## Summary
The vulnerability arises due to the interaction with the IERC20 contract's `transferFrom `function, which may allow reentrant calls.
## Vulnerability Detail

   `IERC20(stablecoin).transferFrom(_msgSender(), treasury, amount);`

## Impact
The `depositStablecoin` function in the provided code is vulnerable to reentrancy attacks. Reentrancy attacks can allow an attacker to repeatedly call back into the `depositStablecoin` function before the state is updated, potentially causing unexpected behavior and loss of funds.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/misc/Presale.sol#L147

```solidity

function depositStablecoin(address stablecoin, uint256 amount) public {
        require(
            block.timestamp > presaleStart,
            "Presale::depositStablecoin() block.timestamp <= presaleStart"
        );
        require(
            block.timestamp < presaleStart + presaleDuration,
            "Presale::depositStablecoin() block.timestamp >= presaleStart + presaleDuration"
        );
        require(
            stablecoinWhitelist[stablecoin],
            "Presale::depositStablecoin() !stablecoinWhitelist[stablecoin]"
        );

        // Enforce minimum 10
        uint checkAmount = standardize(stablecoin, amount);
        require(
            checkAmount >= 10 ether,
            "Presale::depositStablecoin() checkAmount < 10 ether"
        );

        IERC20(stablecoin).transferFrom(_msgSender(), treasury, amount);

        // Points awarded is equivalent to amount deposited, converted to 10**18 precision (wei).
        uint256 pointsAwarded = pointsAwardedStablecoin(stablecoin, amount);
        points[_msgSender()] += pointsAwarded;
        emit StablecoinDeposited(
            _msgSender(),
            stablecoin,
            amount,
            pointsAwarded
        );
    }
```
## Tool used
Foundry

## Recommendation
 Implement a reentrancy guard within the `depositStablecoin` function to prevent multiple reentrant calls. This guard should be placed before any state changes occur and released after all state changes have been made.

**Comment by pseudonaut** [comment]
Not in scope contract
