### ISSUE TITLE
NoOne - M-2 Use safeTransferFrom() instead of transferFrom() for outgoing ERC20 transfers

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#508]
NoOne

medium

# M-2 Use safeTransferFrom() instead of transferFrom() for outgoing ERC20 transfers

## Summary
It is recommended to use `safeTransferFrom()` instead of `transferFrom()` when transferring `ERC20`s out of the vault.
## Vulnerability Detail
Some tokens (like USDT) don't correctly implement the EIP20 standard and their `transfer/ transferFrom` function return void instead of a success boolean. Calling these functions with the correct EIP20 function signatures will always revert. The `transferFrom()` method is used instead of `safeTransferFrom()`, which I assume is a gas-saving measure. I however argue that this isn’t recommended because: 

[OpenZeppelin’s documentation](https://docs.openzeppelin.com/contracts/4.x/api/token/erc721#IERC721-transferFrom-address-address-uint256-) discourages the use of `transferFrom()`; use `safeTransferFrom()` whenever possible
The recipient could have logic in the onERC721Received() function, which is only triggered in the safeTransferFrom() function and not in transferFrom(). A notable example of such contracts is the Sudoswap pair:
## Impact
Tokens that don't actually perform the transfer and return false are still counted as a correct transfer and tokens that don't correctly implement the latest EIP20 spec, like USDT, will be unusable in the protocol as they revert the transaction because of the missing return value.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/misc/Presale.sol#L159
## Tool used

Manual Review

## Recommendation
Recommend using OpenZeppelin's SafeERC20 versions with the safeTransfer and safeTransferFrom functions that handle the return value check as well as non-standard-compliant tokens.

**Comment by pseudonaut** [comment]
Not in scope, also pretty sure we use safeTransfer everywhere else
