### ISSUE TITLE
Maniacs - Ineffective deadline used across different OCL locker functions

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#510]
Maniacs

medium

# Ineffective deadline used across different OCL locker functions

## Summary
Protocol uses ineffective deadline inside the OCL locker contract and this can cause transactions to be unexpectedly executed.

## Vulnerability Detail
The deadline parameter that the protocol passes is ineffective since the block.timestamp is relative to the block in which the transaction is executed.

Link to a similar issue: https://github.com/sherlock-audit/2023-04-blueberry-judging/issues/145#issuecomment-1595155228

## Impact
The transaction can stay in the mempool for an infinite amount of time and still be valid for execution. During this execution, however, conditions might have changed and result in an unfavorable outcome or unexpected execution.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L233-L235

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L268-L270

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L316-L318

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L198-L206

## Tool used

Manual Review

## Recommendation
Use a deadline coming from a function input parameter.

Duplicate of #144

**Comment by pseudonaut** [comment]
Valid, but not of concern
