### ISSUE TITLE
0xblackskull - Missing check for previous trigger in ZivoeYDL::unlock

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#512]
0xblackskull

medium

# Missing check for previous trigger in ZivoeYDL::unlock

## Summary
The `ZivoeYDL::unlock` function in the contract lacks a check to verify whether the unlocking process has been previously triggered. This oversight may result in overriding `lastDistribution` variable

## Vulnerability Detail
The `ZivoeYDL::unlock` function is intended to unlock the contract for distributions and initialize certain values. However, it does not include a check to determine whether the unlocking process has already been triggered. As a result, if the function is called multiple times, it will execute the initialization logic repeatedly, potentially leading to inconsistencies in contract state like ``lastDistribution`` .

## Impact
The absence of a check for the previous trigger in the `unlock` function poses a moderate risk to the stability and integrity of the contract. Repeated calls to the function may result in unnecessary execution of initialization logic and potential inconsistencies in contract state.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L327

## Tool used

Manual Review

## Recommendation
Add `require` check for is `unlocked`
```solidity
  require(
            _msgSender() == IZivoeGlobals_YDL(GBL).ITO(),
            "ZivoeYDL::unlock() _msgSender() != IZivoeGlobals_YDL(GBL).ITO()"
        );
+ require(!unlocked);
```

**Comment by pseudonaut** [comment]
Not valid, not needed
