### ISSUE TITLE
BoRonGod - DAO actions can eat into yields of users and vice versa

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#513]
BoRonGod

high

# DAO actions can eat into yields of users and vice versa

## Summary

Currently some DAO actions in `OCY_Convex_C` and `OCL_ZVE` may eat into yield of users and vice versa.

## Vulnerability Detail

In OCY_Convex_C, `pullFromLocker` and `pullFromLockerPartial` do not forward extraReward from convex, which eat into yields of users. (currently extra rewards contains PYUSD)

    function pullFromLocker(address asset, bytes calldata data) external override onlyOwner {
        require(asset == convexPoolToken, "OCY_Convex_C::pullFromLocker() asset != convexPoolToken");
        
        claimRewards(false);
        ...

In OCL_ZVE, `pullFromLocker` and `pullFromLockerPartial` do not cache token balances, but send all tokens to DAO, which eat into yields of users. 

In OCL_ZVE, `pushToLocker` will leave some token in contract, such token would soon be claimed as yield in `forwardYield()`. Such 

    //function pushToLocker
        (uint256 depositedPairAsset, uint256 depositedZVE, uint256 minted) = IRouter_OCL_ZVE(router).addLiquidity(
            pairAsset, 
            ZVE, 
            balPairAsset,
            balZVE, 
            (balPairAsset * 9) / 10,
            (balZVE * 9) / 10, 
            address(this), 
            block.timestamp + 14 days
        );

## Impact

Calculations of APY/APR of the protocol would be not precise, users or DAO may also suffer loss.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_C.sol#L149

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L203

## Tool used

Manual Review

## Recommendation

Specify exact values to get from theses contracts.

**Comment by pseudonaut** [comment]
Intended
