### ISSUE TITLE
Maniacs - Supply Interest in OCC locker is underdeveloped

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#514]
Maniacs

high

# Supply Interest in OCC locker is underdeveloped

## Summary
The development of [`supplyInterest()`](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L709) is not finished.

## Vulnerability Detail
The function is used by borrowers to repay their outstanding interest after their defaulted loan has been resolved. The problem is that the function is not finished and when users use it they will just donate their tokens to the OCC locker without affecting the protocol accounting.

## Impact
Users can be miss led that they can use this function to repay their outstanding interest but in reality they will donate their tokens without any internal protocol accounting being updated.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L709-L722

## Tool used

Manual Review

## Recommendation
Finish the development of [`supplyInterest()`](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L709)

**Comment by pseudonaut** [comment]
Not valid, requires certain state of loan to be called
