### ISSUE TITLE
cergyk - ZivoeYDL::distributeYield emaSTT is easily manipulatable through deposit/redemptions

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#517]
cergyk

medium

# ZivoeYDL::distributeYield emaSTT is easily manipulatable through deposit/redemptions

## Summary
Senior tranche tokens (STT) can be minted and redeemed against stablecoins. By using this capability a malicious user can artificially inflate STT supply in one block and increase STT proportion of yield artificially.

### Senior proportion

First let's see that `seniorProportion` of yield distributed by `ZivoeYDL`, and computed in `ZivoeMath` is always proportional to emaSTT:

`ZivoeMath::seniorProportionShortfall`:

as seen in natspec comment:
```solidity
//             WAD                         
// --------------------------------  *  RAY
//             Q * eJTT * WAD / BIPS       
// WAD  +   ---------------------
//                   eSTT
```

Which becomes in analytical form:
```solidity
//        emaSTT
// --------------------
//   emaSTT + Q x emaJTT
```

`ZivoeMath::seniorProportionBase`:

as seen in natspec comment:
```solidity
//   Y  * eSTT * T
// ----------------- *  RAY
//     (365) * yD
```

The distribution is done according to computed proportions:
[ZivoeYDL.sol#L464-L465](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L464-L465)
```solidity
    senior = (distributionYield * _seniorProportion) / RAY;
    junior = (distributionYield * juniorProportion) / RAY;
```

### emaSTT

Senior tranche token ema is computed when `OCE_ZVE::distributeYield` is called (unpermissioned) every 30 days

Let's see how ema for STT is computed:
[ZivoeYDL.sol#L237-L239](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L237-L239)
```solidity
    (uint256 aSTT, uint256 aJTT) = IZivoeGlobals_YDL(GBL).adjustedSupplies();
    emaSTT = MATH.ema(emaSTT, aSTT, retrospectiveDistributions.min(distributionCounter));
    emaJTT = MATH.ema(emaJTT, aJTT, retrospectiveDistributions.min(distributionCounter));
```

[ZivoeMath.sol#L35-L39](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeMath.sol#L35-L39)
```solidity
function ema(uint256 bV, uint256 cV, uint256 N) external pure returns (uint256 eV) {
    assert(N != 0);
    uint256 M = (WAD * 2).floorDiv(N + 1);
    eV = ((M * cV) + (WAD - M) * bV).floorDiv(WAD);
}
```

since `retrospectiveDistributions == 6`, historical ema value accounts for 5/7 of the new value and current totalSupply value for STT accounts for 2/7.

### Scenario

Which brings us to the manipulation itself:

- Attacker has a big amount: `1M` of STT , asks for a redeem and waits until the redemption can be claimed
- In one transaction:
    - Attacker uses a flash loan to mint the same of amount of STT as before `1M`, the total supply is increased by this amount
    - Attacker calls `distributeYield` with the inflated totalSupply, ema is increased by at least `1M * 2/7 ~= 285 000`
    - Attacker claims the redemption pays back the flash-loan, and is in the same situation as before requesting redemption (`1M` balance of STT).

Yield proportion of STT has been considerably increased for that yield distribution period

## Impact
A malicious user with a large balance of STT can manipulate proportion of yield dedicated to senior tranche tokens 

## Tool used

Manual Review

## Recommendation
Please consider using EMA on the ratio of `STT/JTT` to compute the proportion, which would be harder to manipulate than the totalSupply of the token, which has a higher variance

**Comment by pseudonaut** [comment]
Redemptions not in scope

**Comment by CergyK** [comment]
Escalate

Although the issue mentions redemptions, the root cause does not stem from it.

The issue outlines a wrong design in the averaging used to `smooth` supply values of STT and JTT. The averages are in turn used to compute allocations for participants.

The mistake here is to use moving averages on supplies of STT or JTT, instead of using moving averages on `(STT/(STT+JTT))` which is the ratio used to compute the allocations.

This issue is similar to [Ubiquity #56](https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/56).

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Although the issue mentions redemptions, the root cause does not stem from it.
> 
> The issue outlines a wrong design in the averaging used to 'smooth' the proportion of STT compared to JTT. The averages are in turn used to compute allocations for participants.
> 
> The mistake here is to use moving averages on supplies of STT or JTT, instead of using moving averages on `(STT/(STT+JTT))` which is the ratio used to compute the allocations.
> 
> This issue is similar in nature to [Ubiquity #56](https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/56).  
> 
>  

You've deleted an escalation for this issue.

**Comment by panprog** [comment]
Since the redemption is out of scope, there is no impact in this finding, so this is either informational or low. User trying to abuse this without redemption will simply deposit more into senior tranche and that's it. No damage from this.
