### ISSUE TITLE
BoRonGod - rewardPerTokenStored can be inflated by the first depositor and rewards can be stolen

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#518]
BoRonGod

high

# rewardPerTokenStored can be inflated by the first depositor and rewards can be stolen

## Summary

The first user who calls BaseRewardPool's stake() function with 1 wei can inflate the `rewardPerTokenStored`. And the same user can call withdraw and drain the rewards.

## Vulnerability Detail

When a user call stake() with 1 wei(NOT USDC or USDT, a coin with 18 decimals would work), it updates the _totalSupply as 1 wei and the rewards through updateReward modifier. This modifier calls rewardPerToken() to assign the return to rewardPerTokenStored and assigns it to the account via userRewardPerTokenPaid[account] = rewardPerTokenStored; rewardPerToken() formula is as below;

    /// @notice Cumulative amount of rewards distributed per LP token.
    /// @param _rewardsToken The asset that's being distributed.
    /// @return amount The cumulative amount of rewards distributed per LP token.
    function rewardPerToken(address _rewardsToken) public view returns (uint256 amount) {
        if (_totalSupply == 0) { return rewardData[_rewardsToken].rewardPerTokenStored; }
        return rewardData[_rewardsToken].rewardPerTokenStored.add(
            lastTimeRewardApplicable(_rewardsToken).sub(
                rewardData[_rewardsToken].lastUpdateTime
            ).mul(rewardData[_rewardsToken].rewardRate).mul(1e18).div(_totalSupply)
        );
    }

Since it depends on the denominator as totalSupply(), the whole multiplying will be divided by 1 wei which will inflate the rewardPerTokenStored astronomically. And there is no obstacle for the user to withdraw it in the withdraw function.

## Impact

rewardPerTokenStored can be inflated, makes the whole contract not work properly.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L196

## Tool used

Manual Review

## Recommendation

Deposit 1e18 wei into the contract when deploying it, and make sure _totalSupply dont go to 0 within lifecircle.

**Comment by pseudonaut** [comment]
I don't think it will inflate anything, mathematically appears it is handled appropriately
