### ISSUE TITLE
Maniacs - ZivoeSwapper is missing a slippage validation checks

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#521]
Maniacs

high

# ZivoeSwapper is missing a slippage validation checks

## Summary
[`convertAsset()`](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/Utility/ZivoeSwapper.sol#L166-L191) uses 1inch router perform a swap between 2 assets but a slippage check validation is missing for some of the function scenarios.

## Vulnerability Detail
[`convertAsset()`](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/Utility/ZivoeSwapper.sol#L166-L191) uses bytes input parameter to allow the caller to use 1 out of the 4 1inch swap functions:

Link to the 1inch router [`contract`](https://etherscan.deth.net/address/0x1111111254EEB25477B68fb85Ed929f73A960582#readContract)
- swap()
- uniswapV3Swap()
- unoswap()
- fillOrderRFQ()

The protocol does checks for `assetIn`, `assetOut`, `amountIn` and `amountOut` in order to validate if the correct values are presented in the bytes input parameter.

Some 1inch functions have built in slippage checks and if min amount values are not provided they will revert. 

`swap()`:
```solidity
function swap(
        IAggregationExecutor executor,
        SwapDescription calldata desc,
        bytes calldata permit,
        bytes calldata data
    )
        external
        payable
        returns (
            uint256 returnAmount,
            uint256 spentAmount
        )
    {
@>      if (desc.minReturnAmount == 0) revert ZeroMinReturn();
    ...
}
```

but for [`uniswapV3Swap() and unoswap()`](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/Utility/ZivoeSwapper.sol#L177-L180) there aren't such built-in checks and the swap it will not revert if minReturn value is not provided in the bytes input parameter by the caller.

## Impact
The caller of the swap can get sandwiched and lose his funds.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/Utility/ZivoeSwapper.sol#L166-L191

## Tool used

Manual Review

## Recommendation
Add validation checks for each 1inch swap function that is going to be used for the minimum return value of the swap in order to avoid sandwich attacks.

**Comment by pseudonaut** [comment]
These are done with flash-bots, not relevant
