### ISSUE TITLE
saidam017 - Push tokens to `OCL_ZVE` not returning back the unused tokens

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#523]
saidam017

medium

# Push tokens to `OCL_ZVE` not returning back the unused tokens

## Summary

When the DAO decides to push tokens to `OCL_ZVE`, it will provide the token to the liquidity pool to obtain liquidity tokens. However, it doesn't return the unused tokens to the DAO contract, causing the assets to remain in `OCL_ZVE`, rendering them unproductive.

## Vulnerability Detail

When the DAO pushes tokens to `OCL_ZVE` by triggering `pushToLockerMulti`, it calls `router.addLiquidity` and provides the required parameters to push the tokens to the liquidity pool and mint liquidity tokens.

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L172-L215

```solidity
    function pushToLockerMulti(
        address[] calldata assets, uint256[] calldata amounts, bytes[] calldata data
    ) external override onlyOwner nonReentrant {
        address ZVE = IZivoeGlobals_OCL_ZVE(GBL).ZVE();
        require(
            assets[0] == pairAsset && assets[1] == ZVE,
            "OCL_ZVE::pushToLockerMulti() assets[0] != pairAsset || assets[1] != ZVE"
        );

        for (uint256 i = 0; i < 2; i++) {
            require(amounts[i] >= 10 * 10**6, "OCL_ZVE::pushToLockerMulti() amounts[i] < 10 * 10**6");
            IERC20(assets[i]).safeTransferFrom(owner(), address(this), amounts[i]);
        }

        if (nextYieldDistribution == 0) { nextYieldDistribution = block.timestamp + 30 days; }

        uint256 preBasis;
        if (basis != 0) { (preBasis,) = fetchBasis(); }

        // Router addLiquidity() endpoint.
        uint balPairAsset = IERC20(pairAsset).balanceOf(address(this));
        uint balZVE = IERC20(ZVE).balanceOf(address(this));
        IERC20(pairAsset).safeIncreaseAllowance(router, balPairAsset);
        IERC20(ZVE).safeIncreaseAllowance(router, balZVE);

        // Prevent volatility of greater than 10% in pool relative to amounts present.
>>>     (uint256 depositedPairAsset, uint256 depositedZVE, uint256 minted) = IRouter_OCL_ZVE(router).addLiquidity(
            pairAsset, 
            ZVE, 
            balPairAsset,
            balZVE, 
            (balPairAsset * 9) / 10,
            (balZVE * 9) / 10, 
            address(this), block.timestamp + 14 days
        );
        emit LiquidityTokensMinted(minted, depositedZVE, depositedPairAsset);
        assert(IERC20(pairAsset).allowance(address(this), router) == 0);
        assert(IERC20(ZVE).allowance(address(this), router) == 0);

        // Increase basis by difference.
        (uint256 postBasis,) = fetchBasis();
        require(postBasis > preBasis, "OCL_ZVE::pushToLockerMulti() postBasis <= preBasis");
        basis += postBasis - preBasis;
    }
```

However, the actual `pairAsset` (`depositedPairAsset`) and `ZVE`  (`depositedZVE`) deposited could change and not the same with `balPairAsset` and `balZVE` due to a larger change in the true market price before the transaction is confirmed. And the unused tokens are not directly returned back to DAO contract.

docs reference : [here](https://docs.uniswap.org/contracts/v2/guides/smart-contract-integration/providing-liquidity)

## Impact

Not directly returning unused assets will causing the assets to remain in `OCL_ZVE` and rendering them unproductive.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L172-L215

## Tool used

Manual Review

## Recommendation

Return the unused assets directly to the DAO.

Duplicate of #18

**Comment by pseudonaut** [comment]
It actually reverts, need to handle this properly, valid but suggestion should be to modify assert statements
