### ISSUE TITLE
0xvj - Unvested tokens should not be considered for votes in governance

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#524]
0xvj

medium

# Unvested tokens should not be considered for votes in governance

## Summary
Incorrect votes count for governance due to unvested ZVE tokens being considered for votes 

## Vulnerability Detail
In `ZivoeGovernorV2.sol._getVotes`, the votes for a user are calculated based on the `vestZVE` and `stZVE` balances. But current votes should not consider `vestZVE` balance. User will posses the tokens only after the vesting is complete. So voting power of a user must not depend on unvested balance. 

Initially the ZVE is allocated for Early Contributors (30%) and Team & Advisors (30%). Just after the vesting period has started, those tokens are being considered for votes count. This would give an upperhand for Early Contributors and  Team & Advisors which makes governance centralised

## Impact
Additional upperhand in goverance for Early Contributors and Team & Advisors. And incorrect voting count.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGovernorV2.sol#L150

## Tool used

Manual Review

## Recommendation
Only consider staked ZVE for votes count

**Comment by pseudonaut** [comment]
Intended
