### ISSUE TITLE
Maniacs - Protocol calculates Uniswap/Sushiswap yield incorrectly

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#527]
Maniacs

high

# Protocol calculates Uniswap/Sushiswap yield incorrectly

## Summary
OCL locker is responsible for providing liquidity to Uniswap/Sushiswap ZVE/other token pools and part of the generated yield is taken out and transferred to the yield or converter locker contract. The [`_forwardYield()`](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L311) uses an incorrect approach to determine the generated yield from the provided liquidity and based on that burns LP tokens and takes out the underlying assets from the pool.

## Vulnerability Detail
Liquidity providers on UniswapV2 become profitable by collecting trading fees and rely on the conditions that affect the impermanent loss.

In more detail you can check: https://docs.uniswap.org/contracts/v2/concepts/advanced-topics/understanding-returns

Currently, yield is collected not based on the profitability of the position but based on the price of the ZVE in terms of the pairing token.

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L302

If for example, we provide liquidity:
100 DAI
100 ZVE

and after some time the ratio of the pool changes (the price of the pool changes) to:
120 DAI
80 ZVE

then ```if (amount > basis) { _forwardYield(amount, lp); }``` will pass because in this moment:
`amount` == 120e18
`basis` == 100e18
and the difference is going to be 20e18

The protocol will take 50% of 20e18 thinking that this is yield when in reality it is not. Then it will distribute this amount as yield to the ZivoeYDL contract.

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L313

## Impact
The protocol takes out incorrect liquidity from the pool thinking it is profit when in reality is principal (the amount the protocol has put in), then it takes the principal and distributes it as yield, giving it away to stakers.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L287-L305
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L311-L330

## Tool used

Manual Review

## Recommendation
Change how yield is calculated by taking into consideration the generated trading fees and impermanent loss.

**Comment by pseudonaut** [comment]
Intended
