### ISSUE TITLE
mazi.xyz - Critical access control vulnerability in `ZivoeTrancheToken::burn` function

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#529]
mazi.xyz

high

# Critical access control vulnerability in `ZivoeTrancheToken::burn` function

## Summary

The lack of access control in the `ZivoeTrancheToken::burn` function may result in the loss of zSTT/zJTT, impacting the internal accounting of a user's tranche token balance and the standardized amount of stablecoin deposited.

## Vulnerability Detail

The absence of access control in ZivoeTrancheToken::burn may result in users losing their $zJTT and/or $zSTT tokens. This loss affects internal accounting, leading to an incorrect ratio between the user's stablecoin deposit and Tranche token ($zJTT or $zSTT) balance.

<details>

<summary>Code</summary>

```solidity
    // @audit-info missing access control
    function burn(uint256 amount) external {
        _burn(_msgSender(), amount);
    }
```

</details>

## Impact

The disruption caused by the accidental burn of a tranche token can cause the following:

- reduction in Airdrop allocation received by the user.
- reduction $ZVE incentives transferred upon depositing into any tranche after the Initial Token Offering (ITO).

## Code Snippet

[Code Snippet](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTrancheToken.sol#L72)

## Tool used

Manual Review

## Recommendation

```diff
-   function burn(uint256 amount) external {
+   function burn(uint256 amount) external isMinterRole {
        _burn(_msgSender(), amount);
    }
```

**OR**

```diff
    ...
+   mapping(address => bool) private _isBurner;
+   modifier isBurnerRole() {
+       require(_isBurner[_msgSender()], "ZivoeTrancheToken::isBurnerRole() !_isBurner[_msgSender()]");
+       _;
+   }
    ...
-   function burn(uint256 amount) external {
+   function burn(uint256 amount) external isBurnerRole {
        _burn(_msgSender(), amount);
    }
```

**Comment by pseudonaut** [comment]
ZivoeITO will be updated to snapshot values to handle this
