### ISSUE TITLE
pseudoArtist - Precision loss will lead to less LP token burned while forwarding yeild in  `OCL_ZVE::_forwardYield`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#53]
pseudoArtist

high

# Precision loss will lead to less LP token burned while forwarding yeild in  `OCL_ZVE::_forwardYield`

## Summary
Precision loss will lead to less LP token being burnt in [OCL_ZVE::_forwardYield](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L313)
## Vulnerability Detail
[forwardYield](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L287-L305) function forwards the yeild in excess of  the basis, i.e 
```solidity
if (amount > basis) _forwardYield(amount, lp);
```
if the amount is greater than basis it calls the internal [_forwardYield](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L311-L330) function to forward the yield to the YDL in the form of pairAsset, however while doing so it calculates the [LP tokens to burn](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L313), This calculation results in precision loss because of division before multiplication and hence it will lead to less LP token being burnt instead of more.
## Impact
The incorrect calculation of LP tokens to burn due to division before multiplication will lead to less LP token burning.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L302
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L313
## Tool used

Manual Review

## Recommendation
```solidity
- uint256 lpBurnable = (amount - basis) * lp / amount * (BIPS - compoundingRateBIPS) / BIPS;
+ uint256 lpBurnable = (amount - basis) * lp * (BIPS - compoundingRateBIPS) / amount  / BIPS;
```

**Comment by pseudonaut** [comment]
Valid
