### ISSUE TITLE
KupiaSec - If protocol contributors participate in the ITO stage, they will not receive the `$ZVE` that they were entitled to as rewards for their contributions to the protocol.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#532]
KupiaSec

high

# If protocol contributors participate in the ITO stage, they will not receive the `$ZVE` that they were entitled to as rewards for their contributions to the protocol.

## Summary

After the `Initial Tranche Offering (ITO)` stage, when ITO participants claim the airdrop, a vesting schedule of `$ZVE` is created. In the [ZivoeRewardsVesting.createVestingSchedule()](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L381-L404) function, once the `vestingScheduleSet[account]` variable is set to `true`, it can never be switched back to `false`.

So any team members, advisors, or early contributors who participated in the ITO stage can receive `$ZVE` as rewards for their ITO participation. However, they cannot receive the additional `$ZVE` that they were entitled to as rewards for their prior contributions to the protocol since the `ZVL` is unable to create a vesting schedule twice for the same account.

## Vulnerability Detail

After the ITO stage, when ITO participants claim the airdrop, a vesting schedule of `$ZVE` is created at [L236](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeITO.sol#L236-L238).
```solidity
File: ZivoeITO.sol
203:     function claimAirdrop(address depositor) external returns (
204:         uint256 zSTTClaimed, uint256 zJTTClaimed, uint256 ZVEVested
205:     ) {
            [...]
235:         if (upper * middle / lower > 0) {
236:             ITO_IZivoeRewardsVesting(IZivoeGlobals_ITO(GBL).vestZVE()).createVestingSchedule(
237:                 depositor, 0, 360, upper * middle / lower, false
238:             );
239:         }
240:         
241:         return (seniorCreditsOwned / 3, juniorCreditsOwned, upper * middle / lower);
242:     }
```
When ITO creates a vesting schedule of `$ZVE` for an account by calling the `createVestingSchedule()` function, it first checks if the `vestingScheduleSet[account]` variable is `false`.

```solidity
File: ZivoeRewardsVesting.sol
388:    require(
389:        !vestingScheduleSet[account], //@audit-info If vestingScheduleSet[account] is true, it reverts.
390:        "ZivoeRewardsVesting::createVestingSchedule() vestingScheduleSet[account]"
391:    );
```
Then, if several conditions are satisfied, it sets the `vestingScheduleSet[account]` variable  to `true` at [L404](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L404). 
```solidity
File: ZivoeRewardsVesting.sol
404:    vestingScheduleSet[account] = true
```
Finally, ZVL or ITO creates a vesting schedule.

However, when ZVL is going to create a vesting schedule again for the same account, as `vestingScheduleSet[account]` was set as `true` before, it reverts.

#### Example
Let Alice is one of the advisors. 
- She deposited `$DAI` in the ITO stage by calling [ZivoeITO.depositSenior()](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeITO.sol#L277-L298).
- After the ITO stage, he claims the airdrop by calling [ZivoeITO.claimAirdrop()](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeITO.sol#L203-L242) and a vesting schedule is created for her. 
- Later, ZVL is going to create a vesting schedule for her since she contributed to the protocol as an advisor. So ZVL calls [ZivoeRewardsVesting.createVestingSchedule()](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L381-L404) to create a vesting schedule.
- Unfortunately, this function reverts and Alice is unable to receive `$ZVE` entitled to him.

## Impact

Here's a breakdown of the potential impacts of this issue:

- Team members, advisors, and early contributors who are entitled to a portion of the 60% `$ZVE` via a vesting schedule can't receive that allocation if they participate in the ITO stage.
- ZVL can't create a vesting schedule for individuals who received `$ZVE` via a vesting schedule before.

## Tool used

Manual Review

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L388-L391

## Recommendation

To solve this issue, it's necessary to revise multiple sections of the `ZivoeRewardsVesting.sol` contract. We recommend reimplementing the code to enable ZVL to create multiple vesting schedules for the same account.

**Comment by KupiaSecAdmin** [comment]
Escalate

Let's assume that the protocol team intend to create vesting schedule
only once per account as Panprog commented. Now, `ZivoeRewardsVesting.sol`, the reward vesting contract is implemented that intend, so even `ZVL` can't create vesting schedule twice per account.

In this case, there are some arise under the assumption above.

According to Zivoe Documentation(https://docs.zivoe.com/user-docs/zivoe-token-zve), the distribution of `$ZVE` is as follows:
- 35% - Zivoe DAO
- 5% - Initial Tranche Offering (“ITO”): The airdrop is subject to a 1-year linear vesting schedule.
- 30% - Team, Advisors, & Future Incentives: These tokens are reserved for team members, advisors, and future members of the Zivoe Development Company. This rewards the team responsible for launching the  Zivoe protocol and incentivizes continued development.
- 30% - Early Contributors: This ZVE is set aside for investors and early contributors that helped fund Zivoe and its development. This portion will also be subject to a 4-year vesting schedule.

As explained above, the protocol team distribute 60% of $ZVE to team, advisors, future memebers of the Zivoe Development Company and early contributors by creating a vesting schedule. They can create a vesting schedule for them before or after ITO stage. In both case, there is a serious problem.

1. In case of creating a vesting schedule for them before ITO stage.

	- The protocol team create a vesting schedule for team, advisors and early contributors before ITO stage.
	Then, if some of team, advisors and early contributors participates in ITO stage by depositing stable coins, they can't claim their airdrop. That's because the implemented logic of `ZivoeRewardsVesting` contract doesn't allow to create a vesting schedule twice per account. 
	
		<b>Unfortunately, although they contributed to ITO, they won't get a a portion of 5% as reward.</b>

	- As the future member of the Zivoe Development Company are unknown at that time, the protocol team can't create a vesting schedule for them.	Then, if some of them participate in ITO stage, they receive a portion of 5% as reward via vesting schedule.
	
		Later, they become the member of the Zivoe Development Company. However, they won't get a portion of 60%, reward for their contribution to the protocol.
	
		<b>Unfortunately, although they contribute to the protocol as the member of the Zivoe Development Company, they won't get a portion of 30% as reward.</b>

2. In the case of creating a vesting schedule for them after ITO stage.
	
	There is no reason that team, advisors, future member of the Zivoe Development Company and early contributors can't participate in ITO stage.

	If some of them participate in ITO stage, `ZivoeITO` contract will automatically create a vesting schedule for them to distribute a portion of 5% as reward. Then, when the protocol team is going to distribute a portion of 60% to them, creating a schedule will be reverted.

	<b>Unfortunately, although they contributed to the protocol, they won't get a portion of 60% that is entitled to them.</b>

As revealed above, in both case, some contributors will get smaller amount of `$ZVE` than they are entitled to.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Let's assume that the protocol team intend to create vesting schedule
> only once per account as Panprog commented. Now, `ZivoeRewardsVesting.sol`, the reward vesting contract is implemented that intend, so even `ZVL` can't create vesting schedule twice per account.
> 
> In this case, there are some arise under the assumption above.
> 
> According to Zivoe Documentation(https://docs.zivoe.com/user-docs/zivoe-token-zve), the distribution of `$ZVE` is as follows:
> - 35% - Zivoe DAO
> - 5% - Initial Tranche Offering (“ITO”): The airdrop is subject to a 1-year linear vesting schedule.
> - 30% - Team, Advisors, & Future Incentives: These tokens are reserved for team members, advisors, and future members of the Zivoe Development Company. This rewards the team responsible for launching the  Zivoe protocol and incentivizes continued development.
> - 30% - Early Contributors: This ZVE is set aside for investors and early contributors that helped fund Zivoe and its development. This portion will also be subject to a 4-year vesting schedule.
> 
> As explained above, the protocol team distribute 60% of $ZVE to team, advisors, future memebers of the Zivoe Development Company and early contributors by creating a vesting schedule. They can create a vesting schedule for them before or after ITO stage. In both case, there is a serious problem.
> 
> 1. In case of creating a vesting schedule for them before ITO stage.
> 
> 	- The protocol team create a vesting schedule for team, advisors and early contributors before ITO stage.
> 	Then, if some of team, advisors and early contributors participates in ITO stage by depositing stable coins, they can't claim their airdrop. That's because the implemented logic of `ZivoeRewardsVesting` contract doesn't allow to create a vesting schedule twice per account. 
> 	
> 		<b>Unfortunately, although they contributed to ITO, they won't get a a portion of 5% as reward.</b>
> 
> 	- As the future member of the Zivoe Development Company are unknown at that time, the protocol team can't create a vesting schedule for them.	Then, if some of them participate in ITO stage, they receive a portion of 5% as reward via vesting schedule.
> 	
> 		Later, they become the member of the Zivoe Development Company. However, they won't get a portion of 60%, reward for their contribution to the protocol.
> 	
> 		<b>Unfortunately, although they contribute to the protocol as the member of the Zivoe Development Company, they won't get a portion of 30% as reward.</b>
> 
> 2. In the case of creating a vesting schedule for them after ITO stage.
> 	
> 	There is no reason that team, advisors, future member of the Zivoe Development Company and early contributors can't participate in ITO stage.
> 
> 	If some of them participate in ITO stage, `ZivoeITO` contract will automatically create a vesting schedule for them to distribute a portion of 5% as reward. Then, when the protocol team is going to distribute a portion of 60% to them, creating a schedule will be reverted.
> 
> 	<b>Unfortunately, although they contributed to the protocol, they won't get a portion of 60% that is entitled to them.</b>
> 
> As revealed above, in both case, some contributors will get smaller amount of `$ZVE` than they are entitled to.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by panprog** [comment]
I see no issue here. Each person can have multiple accounts, the restriction of one vesting schedule is only per account, not per user.

**Comment by WangSecurity** [comment]
Firstly, I agree that's the design to allow only on vesting schedule per account. Secondly, the advisor/team member/ early contributor can make a second account to receive funds (I believe if they're the team member/advisor or early contributor then they can contact the team about it). So I believe the user can still have two vesting schedules, but on the different addresses.

Hence, planning to reject the escalation and leave the issue as it is.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [KupiaSecAdmin](https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/532/#issuecomment-2106186674): rejected
