### ISSUE TITLE
0xvj - Outdated slippages being used while adding and removing liquidity from uniswap

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#545]
0xvj

high

# Outdated slippages being used while adding and removing liquidity from uniswap

## Summary
The slippage values for adding and removing liquidity are being set while creating the governance proposals. This will result in incorrect slippage protection for these actions, because by the time those transactions execute on lockers those slippage values will already become outdated.

## Vulnerability Detail
Slippage values for adding and removing liquidity are added while creating governance proposal for that actions.

```solidity
    function pullFromLocker(address asset, bytes calldata data) external override onlyOwner nonReentrant {
        ...
        (uint amountAMin, uint amountBMin) = abi.decode(data, (uint, uint));
        ....
        // Router removeLiquidity() endpoint.
        (uint256 claimedPairAsset, uint256 claimedZVE) = IRouter_OCL_ZVE(router).removeLiquidity(
            pairAsset, ZVE, preBalLPToken, 
            amountAMin, amountBMin, address(this), block.timestamp + 14 days
        );
        ...
    }
```

But there will be a delay(timelock delay  + voting duration ) till the proposals are executed. As per docs the total time before execution is 24 hours (timelockDelay(12) + votingDuration(12)). During this period if the prices of assets change, the slippage value which was calculated on prices before 24 hours is not correct while execution.

So to avoid reverting of transaction due to slippage protection , slippage should  higher which is also not ideal because setting higher slippage will cause loss to the protocol if an MEV bot performs sandwich attacks.

## Impact
If the price changes are huge, the incorrect slippage value might result in losses or transaction being reverted

## Code Snippet
Many instances are effected by the same issue in the codeabse
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L233
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L268
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_A.sol#L131
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_A.sol#L184
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_A.sol#L220C11-L220C115
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_C.sol#L117
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_C.sol#L156
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_C.sol#L183

## Tool used

Manual Review

## Recommendation
Implement a 2-step way to enable configuring slippage values at the time of execution time.

Duplicate of #146

**Comment by pseudonaut** [comment]
Intended
