### ISSUE TITLE
sakshamguruji - Unaprove Calls Can Be Frontrun With Apply Calls

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#550]
sakshamguruji

medium

# Unaprove Calls Can Be Frontrun With Apply Calls

## Summary

The underwriter can unapprove a certain borrower for combine/refinance/conversion/extension but these can be frontrun by the borrower with a apply call.

** PS: This is also applicable for `cancelOffer` frontrunning , where a cancelOffer call by an underwriter can be front ran by the borrower by a `acceptOffer()` call. **

## Vulnerability Detail

1.) The underwriter has approved a certain borrower to combine his loans into one.

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L877

2.) Due to some  reasons , it was decided to unapprove the combine and the underwriter calls `unapproveCombine()`

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L939

```solidity
function unapproveCombine(uint256 id) external isUnderwriter {
        emit CombineUnapproved(id);
        combinations[id].valid = false;
    }
```

3.) But this call can be frontrun by the borrower with a applyCombine() call and successfully combines the loan

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L742

## Impact

Unapprove calls by the underwriter can be frontrun making the mechanism useless and combining malicious loans.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L939

## Tool used

Manual Review

## Recommendation

Have a locking period during which a apply call cannot be accepted , during this period the underwriter can successfully unapprove.

**Comment by pseudonaut** [comment]
Not of concern
