### ISSUE TITLE
0xvj - Depeg of whitelisted stablecoins can result in incorrect accounting

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#557]
0xvj

high

# Depeg of whitelisted stablecoins can result in incorrect accounting

## Summary
The is no pausing mechanism during depeg events. If any stablecoin depegs, operations using the coin will result in incorrect accounting and losses for protocol

## Vulnerability Detail
The are two scenarios where the issue arises

1. During an ITO, If any of the allowed stable coins are de-pegged, than there is no way to remove(disallow) the de-pegged stable coin or pause the deposits. An attacker can buy the de-pegged coins for lower price in the market and deposit them to get equal share for tranche credits compared to other high value stable coins resulting in more profit for the attacker

2. If any of the borrowed loans are repaid while the OCC_Modular's stable coin is a de-pegged, malicious users can be able to repay the loans at very low costs which causes loss to the protocol.

## Impact
Incorrect accounting and loss of funds for protocol

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L248
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L277
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L575

## Tool used

Manual Review

## Recommendation
Implement a functionality to disable stablecoins in ITO. 
Implement emergency pausing for repayments

Duplicate of #105

**Comment by pseudonaut** [comment]
Not of concern
