### ISSUE TITLE
pseudoArtist - `ZivoeMaths.sol :: juniorProportion` has no logic for  return value when `sP > RAY`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#56]
pseudoArtist

medium

# `ZivoeMaths.sol :: juniorProportion` has no logic for  return value when `sP > RAY`

## Summary
No logic to handle the case when `sP > RAY` in the [juniorProportion](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeMath.sol#L53C5-L54C6)
## Vulnerability Detail
[juniorProportion](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeMath.sol#L53C5-L54C6) Calculate the amount (in RAY precision) that the junior tranche should receive for the current distribution period. The returned value is dependent upon what proportion of yield the senior tranche, sP, has been attributed already,

The DOCS mention that : [If the input parameter sP (”senior proportion”) is greater than RAY (indicating the senior tranche should receive 100% or more of the distributable yield) we return the default value of jP, 0](https://docs.zivoe.com/user-docs/yield-distribution/mathematics#juniorproportion).

The `juniorProportion` function returns `jP` when `sP <= RAY` in the if block but there is no return value for the case where `sP > RAY` this means when senior tranche receives 100% of the distributable yield the junior proportion calculation is flawed and doesn't return 0.

```solidity
function juniorProportion(uint256 eSTT, uint256 eJTT, uint256 sP, uint256 Q) external pure returns (uint256 jP) {
        if (sP <= RAY) jP = (Q * eJTT * sP / BIPS).floorDiv(eSTT).min(RAY - sP);
    }
```
## Impact
This could lead to wrong calculations or no return values in case where `sP > RAY` and when senior tranche receives 100% of the distributable yield.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeMath.sol#L53C5-L54C6

## Tool used

Manual Review

## Recommendation
Just add else block to return 0 when `sP > RAY`

**Comment by pseudonaut** [comment]
Natively 0 is returned, intended
