### ISSUE TITLE
Ironsidesec - `_creditBalances[OCY_OUSD]`  of `OUSD` can be manipulated

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#562]
Ironsidesec

medium

# `_creditBalances[OCY_OUSD]`  of `OUSD` can be manipulated

## Summary
Impact : `_creditBalances` can be manipulated by changing `nonRebasingCreditsPerToken` of OCY_OUSD by donation.
Root cause : open access to rebase opt in and an ability to optin any time needed.

## Vulnerability Detail

From line 457 of OUSD.sol from https://etherscan.deth.net/address/0x2A8e1E676Ec238d8A992307B495b45B3fEAa5e86

```solidity

ousd.sol

452:     /**
453:      * @dev Is an account using rebasing accounting or non-rebasing accounting?
454:      *      Also, ensure contracts are non-rebasing if they have not opted in.
455:      * @param _account Address of the account.
456:      */
457:     function _isNonRebasingAccount(address _account) internal returns (bool) {
458:         bool isContract = Address.isContract(_account);
459:         if (isContract && rebaseState[_account] == RebaseOptions.NotSet) {
460:             _ensureRebasingMigration(_account);
461:         }
462:         return nonRebasingCreditsPerToken[_account] > 0;
463:     }
464: 
465:     /**
466:      * @dev Ensures internal account for rebasing and non-rebasing credits and
467:      *      supply is updated following deployment of frozen yield change.
468:      */
469:     function _ensureRebasingMigration(address _account) internal {
470:         if (nonRebasingCreditsPerToken[_account] == 0) {
471:             if (_creditBalances[_account] == 0) {
472:                 // Since there is no existing balance, we can directly set to
473:                 // high resolution, and do not have to do any other bookkeeping
474:                 nonRebasingCreditsPerToken[_account] = 1e27;
475:             } else {
476:                 // Migrate an existing account:
477: 
478:                 // Set fixed credits per token for this account
479:                 nonRebasingCreditsPerToken[_account] = _rebasingCreditsPerToken;
480:                 // Update non rebasing supply
481:                 nonRebasingSupply = nonRebasingSupply.add(balanceOf(_account));
482:                 // Update credit tallies
483:                 _rebasingCredits = _rebasingCredits.sub(
484:                     _creditBalances[_account]
485:                 );
486:             }
487:         }
488:     }
489: 
490:     /**
491:      * @dev Add a contract address to the non-rebasing exception list. The
492:      * address's balance will be part of rebases and the account will be exposed
493:      * to upside and downside.
494:      */
495:     function rebaseOptIn() public nonReentrant {
496:         require(_isNonRebasingAccount(msg.sender), "Account has not opted out");
497: 
498:         // Convert balance into the same amount at the current exchange rate
499:         uint256 newCreditBalance = _creditBalances[msg.sender]
500:             .mul(_rebasingCreditsPerToken)
501:             .div(_creditsPerToken(msg.sender));
502: 
503:         // Decreasing non rebasing supply
504:         nonRebasingSupply = nonRebasingSupply.sub(balanceOf(msg.sender));
505: 
506:         _creditBalances[msg.sender] = newCreditBalance;
507: 
508:         // Increase rebasing credits, totalSupply remains unchanged so no
509:         // adjustment necessary
510:         _rebasingCredits = _rebasingCredits.add(_creditBalances[msg.sender]);
511: 
512:         rebaseState[msg.sender] = RebaseOptions.OptIn;
513: 
514:         // Delete any fixed credits per token
515:         delete nonRebasingCreditsPerToken[msg.sender];
516:     }


440:     function _creditsPerToken(address _account)
441:         internal
442:         view
443:         returns (uint256)
444:     {
445:         if (nonRebasingCreditsPerToken[_account] != 0) {
446:             return nonRebasingCreditsPerToken[_account];
447:         } else {
448:             return _rebasingCreditsPerToken;
449:         }
450:     }


```

The creadit balance can be manipulated due to due to line 501 above.

Anyone can call `OCY_OUSD.rebase` and it will change `nonRebasingCreditsPerToken` which can change `_creditBalances` and `_rebasingCredits`

But anyone with the contarct address can change `nonRebasingCreditsPerToken` by transfering 1 wei, which wil trigger at this line 474 because `_isNonRebasingAccount` is internally called everytime there's a transfer.

Since `OCY_OUSD.rebase` changed `_creditBalances` based on `nonRebasingCreditsPerToken`, which can be manipulated by sending 1 wei OUSD as soon as `OCY_OUSD` is deployed. And it will change `nonRebasingCreditsPerToken` in line  474, or if you want to change at line 479, then do another 1 wei transfer. And then calling `OCY_OUSD.rebase` will yield different values of `_creditBalances` and `_rebasingCredits`.

So, if the protocol want to transfer OUSD from DAO to this locker `OCY_OUSD`, and wait to call rebase opt in, then the `_creditBalances` manipulation will cause big % in change.

## Impact
`_creditBalances` can be manipulated by changing `nonRebasingCreditsPerToken` of OCY_OUSD by donation.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCY/OCY_OUSD.sol#L128

 line 457 of OUSD.sol from https://etherscan.deth.net/address/0x2A8e1E676Ec238d8A992307B495b45B3fEAa5e86
 
## Tool used

Manual Review

## Recommendation

Optin to rebase on either `constructor` or `pushToLocker` itself.

**Comment by pseudonaut** [comment]
optInRebase will be called immediately upon deployment of contract, not prior to ownership
