### ISSUE TITLE
Audinarey - Missing slippage protection when `forwardYield()` yield is called can lead to losses

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#568]
Audinarey

high

# Missing slippage protection when `forwardYield()` yield is called can lead to losses

## Summary
During yield forwarding the amount of LP to retrive for forwarding is removed from the pool to retrieve the pair asset to forward and also the $ZVE for the said LP portion burned.

However, [`forwardYield()`](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L316-L318) function can be frontrun and receive a worse price than expected when the transaction is initially submitted . 
```solidity
        (uint256 claimedPairAsset, uint256 claimedZVE) = IRouter_OCL_ZVE(router).removeLiquidity(
            pairAsset, ZVE, lpBurnable, 0, 0, address(this), block.timestamp + 14 days
        );
```

There's no protection at all (to ensure the asset recieved are within a tolerable range compared to the amount of lp tokens to burn), no minimum return amount and a long deadline of `14 days` for the trade transaction to be valid which means the trade can be delayed by miners or users congesting the network, as well as being sandwich attacked 

## Vulnerability Detail
- frontrunner sees the transaction in the mempool with missing slippage and a 14 day expiry
- frontrunner takes a flashloan to unbalance the pool and then manipulate the reserves of the pool in order to make `pairAsset` appear more valuable than it really is so the user receives less `pairAsset` than what the `lpBurnable` is worth.

## Impact
This can ultimately lead to loss of the yield (`pairAsset) being claimed for forwarding.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L316-L318

## Tool used

Manual Review

## Recommendation
Add some sort of protection for the user such that they receive their desired amounts. 
- Add a minimum return amount for all  liquidity removals to all Router functions (in this case repalce with 0 values that are within +/-X% deviation from `(amount - basis)`).
- Reduce the deadline from 14 days

Duplicate of #146

**Comment by Audinarey** [comment]
Escalate

This is a duplicate of #298
