### ISSUE TITLE
lemonmon - Annual percentage rate rounding issue in favor of the borrower when combining loans in the function `OCC_Modular.applyCombine()`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#576]
lemonmon

medium

# Annual percentage rate rounding issue in favor of the borrower when combining loans in the function `OCC_Modular.applyCombine()`

## Summary

Due to a rounding issue, the annual percentage rate `APR` may be rounded down in favor of the borrower when loans are combined.

## Vulnerability Detail

When `OCC_Modular.applyCombine()` is called to combine multiple loans into a single loan, the `APR` (annualized percentage rate charged on the outstanding principal) is calculated rounding down in favor of the borrower, since `APR` is divided by `notional` (line 781 OCC_Modular.sol) which may round down. The rounded down `APR` is then applied to the newly created combined `Loan` (line 804 OCC_Modular.sol).

Note that `APR` is in `BIPS` where `10_000` equals `100%`. Rounding down thus may result in 0.01% precision loss:

`10_000` = `100%`. Rounding down by `1` = `0.01%` precision loss. So the annual percentage rate `APR` may be reduced by `0.01%` each time a loan is combined.

## Impact

Whenever a loan is combined the combined loan's `APR` may be rounded down by 0.01% in favor of the borrower. Thus this may introduce a loss for the lender.

The issue may get worse when the process of combining loans is repeatedly done multiple times, since per combination there may be a 0.01% loss of `APR` which may add up to a significant loss for the lender.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L781

## Tool used

Manual Review

## Recommendation

Consider rounding up the annualized percentage rate `APR` on line 781 in OCC_Modular.sol in favor of the lender.

**Comment by Albort-J** [comment]
low/info
