### ISSUE TITLE
novaman33 - Arbitrage opportunity in depositSenior and depositJunior

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#58]
novaman33

high

# Arbitrage opportunity in depositSenior and depositJunior

## Summary
A reward given per deposit in `ZivoeTranches.sol` creates an arbitrage opportunity for users.
## Vulnerability Detail
Anyone can call depositSenior and depositJunior and earn a reward for the deposit. Despite there are no withdraw functions, "Tranche tokens would have liquidity on secondary markets, i.e. zJTT/USDC , zSTT/USDC" as stated by the sponsor. This creates the opportunity for users to deposit, claim their rewards and then sell on secondary markets.
## Impact
It creates an arbitrage opportunity - High.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeTranches.sol#L283
## Tool used

Manual Review

## Recommendation
Enforce limits on the amounts that are being given as incentive.

**Comment by pseudonaut** [comment]
Intended
