### ISSUE TITLE
recursiveEth - Title: Inconsistency in Supported Stablecoins Across ZivoeITO and ZivoeTranches Contracts

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#585]
recursiveEth

medium

# Title: Inconsistency in Supported Stablecoins Across ZivoeITO and ZivoeTranches Contracts

## Summary

There is an inconsistency in the supported stablecoins between the ZivoeITO and ZivoeTranches contracts. While ZivoeITO supports deposits of DAI, USDC, USDT, and FRAX tokens, ZivoeTranches only supports deposits of DAI, USDC, and USDT. As a result, users who have deposited FRAX tokens in ZivoeITO won't be able to deposit them in ZivoeTranches due to the lack of FRAX token support, leading to a temporary denial-of-service (DOS) situation for these users.

## Vulnerability Detail

The vulnerability arises from the discrepancy in the supported stablecoins between the two contracts. ZivoeITO allows deposits of FRAX tokens, but ZivoeTranches does not support FRAX, causing users who have deposited FRAX in ZivoeITO to face a temporary DOS when attempting to deposit FRAX in ZivoeTranches.

## Impact

The impact of this inconsistency is that users who have deposited FRAX tokens in ZivoeITO may experience frustration and confusion when they attempt to deposit the same tokens in ZivoeTranches but are unable to do so due to the lack of support. This could result in a negative user experience and potential loss of trust in the protocol.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L281

```javascript

    function initializeGlobals(
        address[] calldata globals,
        address[] calldata stablecoins
    ) external onlyOwner {
        require(
            DAO == address(0),
            "ZivoeGlobals::initializeGlobals() DAO != address(0)"
        );

        emit TransferredZVL(globals[10]);

        DAO = globals[0];
        ITO = globals[1];
        stJTT = globals[2];
        stSTT = globals[3];
        stZVE = globals[4];
        vestZVE = globals[5];
        YDL = globals[6];
        zJTT = globals[7];
        zSTT = globals[8];
        ZVE = globals[9];
        ZVL = globals[10];
        GOV = globals[11];
        TLC = globals[12];
        ZVT = globals[13];

        stablecoinWhitelist[stablecoins[0]] = true; // DAI
        stablecoinWhitelist[stablecoins[1]] = true; // USDC
        stablecoinWhitelist[stablecoins[2]] = true; // USDT
    }
```

while depositing into senior or junior they check upto the 4th position in array whether the stablecoint matches the deployed asset

```javascript
require(asset == stables[0] ||
  asset == stables[1] ||
  asset == stables[2] ||
  asset == stables[3], "ZivoeITO::depositSenior() asset != stables[0-3]");
```

## Tool used

Manual Review

## Recommendation

Ensure consistency in the supported stablecoins across all relevant contracts within the protocol. If FRAX tokens are supported in ZivoeITO, consider adding support for FRAX in ZivoeTranches as well, by addition of FRAX at the time of deployment.

**Comment by pseudonaut** [comment]
Not of concern
