### ISSUE TITLE
lemonmon - Usage of a hardcoded list of stable coins that can't be changed inside `ZivoeITO` may cause issues during the Initial Tranche Offering period

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#588]
lemonmon

medium

# Usage of a hardcoded list of stable coins that can't be changed inside `ZivoeITO` may cause issues during the Initial Tranche Offering period

## Summary

The system uses a hardcoded list of stable coins that are accepted to be depositted by LPs during the ITO (initial tranche offering) which may introduce issues, because the list of accepted stable coins can't be adjusted or changed.

## Vulnerability Detail

The contract `ZivoeITO` that is used for the initial tranche offering is not using a whitelisting mechanism for its allowed stablecoins that can be depositted. It just uses a `stables` state variable that is a hardcoded array of stablecoin addresses. Thus when depositting to a tranche for example via `ZivoeITO.depositJunior()` or via `ZivoeITO.depositSenior()`, the system just checks whether the asset depositted is one of the four stable coin assets (line 251-253 and line 280-282 ZivoeITO.sol).

The issue is that the `stables` state variable can't be changed, so during the ITO the 4 accepted stable coins can't be changed. So if a depeg happens during ITO, it may introduce a loss for the protocol since users may deposit a depeged stable coin to the senior or junior tranche.

In comparison `ZivoeTranches.sol` uses a whitelist to determine whether a stable coin is accepted to be depositted into the senior or junior tranche when `ZivoeTranches.depositJunior()` or `ZivoeTranches.depositSenior()` is called by a liquidity provider. See line 296-297 and line 269-270 in ZivoeTranches.sol.

## Impact

There is a "4x" risk of a potential depeg that may happen during ITO, since there are 4 stable coins accepted to be depositted for the ITO. If one of these stable coins depegs during ITO, other liquidity providers may suffer a critical loss:

1. Multiple liquidity providers deposit stablecoins that did not depeg.

1. Then a depeg of one of the 4 stable coins happens.

1. Other liquidity providers then deposit big amounts of the depegged stablecoin which may introduce a critical loss on the liquidity providers who didn't deposit a depegged stable coin before.

I report this as a medium, due to the combination of Low probability of a depeg during the ITO (30 day period) + Critical impact on other liquidity providers. So Low + Critical = Medium.

Furthermore, the risk of a depeg happening to a stable coin that is accepted during ITO may lower the incentive for liquidity providers to participate during the ITO.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeITO.sol#L251-L253

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeITO.sol#L280-L283

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeTranches.sol#L269-L272

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeTranches.sol#L296-L299

## Tool used

Manual Review

## Recommendation

Consider using a whitelist mechanism for the accepted stable coins in ZivoeITO.sol in the same way as it is already implemented into ZivoeTranches.sol to be able to mitigate a depeg of one of the accepted stable coins for the ITO by being able to remove a depegged stable coin from the whitelist.

**Comment by pseudonaut** [comment]
Not ideal, intended
