### ISSUE TITLE
araj - `ZivoeRewards::depositReward` can revert while depositing reward through `ZivoeYDL::distributeYield`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#59]
araj

medium

# `ZivoeRewards::depositReward` can revert while depositing reward through `ZivoeYDL::distributeYield`

## Summary
`ZivoeRewards::depositReward()` can revert while depositing reward through `ZivoeYDL::distributeYield()`  if rewardToken is not added in `ZivoeRewards` or can't be added due to `max limit` of 10 tokens.

## Vulnerability Detail
`ZivoeYDL::distributeYield()` is depositing `distributedAsset` to `ZivoeRewards`(stJTT/stSTT/stZVE) contract. `ZivoeRewards::depositReward()` is calculating `rewardRate` based on `rewardsDuration` of that token.
```solidity
function depositReward(address _rewardsToken, uint256 reward) external updateReward(address(0)) nonReentrant {
        IERC20(_rewardsToken).safeTransferFrom(_msgSender(), address(this), reward);

        // Update vesting accounting for reward (if existing rewards being distributed, increase proportionally).
        if (block.timestamp >= rewardData[_rewardsToken].periodFinish) {
       @>     rewardData[_rewardsToken].rewardRate = reward.div(rewardData[_rewardsToken].rewardsDuration);
        } else {
            uint256 remaining = rewardData[_rewardsToken].periodFinish.sub(block.timestamp);
            uint256 leftover = remaining.mul(rewardData[_rewardsToken].rewardRate);
            rewardData[_rewardsToken].rewardRate = reward.add(leftover).div(rewardData[_rewardsToken].rewardsDuration);
        }
    }
```
Now, the problem is `rewardsDuration` is set in `Zivoe::addReward()`. If distributedAsset is not added then `rewardsDuration` is 0, which will `revert` the `ZivoeYDL::distributeYield()` transaction with divide by 0 error.

Also there is a `limit` of adding only 10 rewardToken & there is `no way` to `remove` any rewardToken and add a new one. Now, this also a problem as `distributedAsset` in `Zivoe::YDL` is set via `governance` not by `ZVL`, so if rewardToken is reached 10 tokens limit and `governance` sets a token which is not in rewardToken list, then whole `ZivoeYDL::distributeYield()` will revert as there is no way to `remove` any rewardToken and add a new one.
```solidity
    function addReward(address _rewardsToken, uint256 _rewardsDuration) external {
        require(
            _msgSender() == IZivoeGlobals_ZivoeRewards(GBL).ZVL(), 
            "_msgSender() != IZivoeGlobals_ZivoeRewards(GBL).ZVL()")
        ;
        require(_rewardsDuration > 0, "ZivoeRewards::addReward() _rewardsDuration == 0");
        require(
            rewardData[_rewardsToken].rewardsDuration == 0, 
            "ZivoeRewards::addReward() rewardData[_rewardsToken].rewardsDuration != 0"
        );
      @>  require(rewardTokens.length < 10, "ZivoeRewards::addReward() rewardTokens.length >= 10");

        rewardTokens.push(_rewardsToken);
       @> rewardData[_rewardsToken].rewardsDuration = _rewardsDuration;
        emit RewardAdded(_rewardsToken);
    }
```

## Impact
`ZivoeYDL::distributeYield()` will revert if any of the two above situation occures 

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L228C2-L243C6
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L208C1-L223C6

## Tool used
Manual Review

## Recommendation
There are couple of ideas
1. Check if `distributedAsset` is added or not before `depositReward`
2. Either completely remove the 10 token limit or make a function to remove and add a new token

**Comment by pseudonaut** [comment]
Intended and managed by ZVL, assumed trusted
