### ISSUE TITLE
recursiveEth - Title: Incorrect Event Emission for Last Payment in `OCC_Modoular:makePayment` and `OCC_Modular:processPayment`.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#594]
recursiveEth

medium

# Title: Incorrect Event Emission for Last Payment in `OCC_Modoular:makePayment` and `OCC_Modular:processPayment`.

## Summary

The processPayment and makePayment functions allow users to make payments for active loans. However, there's a discrepancy in the event emission related to the next payment due date, which does not accurately reflect whether the payment was the last one. This can lead to incorrect event emissions and miscommunication of payment statuses.

## Vulnerability Detail

As the protcol is dependent on events for updated data reagarding loans. The vulnerability arises from emitting the PaymentMade event without accurately determining whether the payment being made is the last one. The nextPaymentDue value is calculated as loans[id].paymentDueBy + loans[id].paymentInterval, which is not correct if the payment being made is the last one. This discrepancy can mislead off-chain operations that rely on these events.

## Impact

Incorrect event emissions can lead to misinterpretation of payment statuses by off-chain systems or users. This could result in incorrect reporting, inaccurate financial records

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L652
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L580

```javascript
 emit PaymentMade(
            id,
            loans[id].borrower,
            principalOwed + interestOwed + lateFee,
            principalOwed,
            interestOwed,
            lateFee,
            loans[id].paymentDueBy + loans[id].paymentInterval
        );

```

## Tool used

Manual Review

## Recommendation

accurately determine whether the payment being made is the last one for the loan. This can be done by checking the remaining payments or comparing the current payment count to the total number of payments or whether its bullet or Amortization.

```javascript
 if (loans[id].paymentsRemaining == 1) {
            loans[id].state = LoanState.Repaid;
            loans[id].paymentDueBy = 0;
        } else {
            loans[id].paymentDueBy += loans[id].paymentInterval;
        }
```
they can check loans[id].paymentDueBy by above method.

**Comment by pseudonaut** [comment]
Interesting. It's valid but not of concern, we have subgraphs in place and handle data according to current system already fine so not interested in updating
