### ISSUE TITLE
krikolkk - Forwarding yield from `OCL_ZVE` can remove and forward a significant portion of the LP

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#595]
krikolkk

high

# Forwarding yield from `OCL_ZVE` can remove and forward a significant portion of the LP

## Summary

[The function](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L311) `_forwardYield` is supposed to collect trading fees generated on an AMM by removing liquidity from the pair and forward it to respective lockers. However, the amount of LP removed is based on the amount of the asset that the `ZVE` token is paired with. This means that the increase in the price of the `ZVE` token can result in a significant amount of LP being removed and forwarded.

## Vulnerability Detail

The function is called [here](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L302), and the `amount` parameter is calculated [here](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L341). This `amount` is referred to as `basis` throughout the contract, and previous `basis` is used to calculate the amount of LP to be removed. Assuming that the `OCL_ZVE` contract is the sole holder of the LP tokens, it is simply the `pairAsset` balance of the AMM pool.

To illustrate the impact of the issue, refer to the following table:

| asset increase | pair asset balance | pool total supply | lp | lp burnable | % of LP |
| -------------- | ------------------ | ----------------- | ----- | ----------- | ------- |
| 1x | 1E+24 | 1E+18 | 1E+18 | 0 | 0,00% |
| 1,5x | 1,5E+24 | 1E+18 | 1E+18 | 1,66667E+17 | 16,67% |
| 2x | 2E+24 | 1E+18 | 1E+18 | 2,5E+17 | 25,00% |
| 4x | 4E+24 | 1E+18 | 1E+18 | 3,75E+17 | 37,50% |
| 8x | 8E+24 | 1E+18 | 1E+18 | 4,375E+17 | 43,75% |
| 16x | 1,6E+25 | 1E+18 | 1E+18 | 4,6875E+17 | 46,88% |
| 32x | 3,2E+25 | 1E+18 | 1E+18 | 4,84375E+17 | 48,44% |
| 64x | 6,4E+25 | 1E+18 | 1E+18 | 4,92188E+17 | 49,22% |
| 128x | 1,28E+26 | 1E+18 | 1E+18 | 4,96094E+17 | 49,61% |

- **asset increase**: how much the asset balance of the pool was increased
- **pair asset balance**: the asset balance of the pool
- **pool total supply**: the total amount of LP tokens
- **lp**: the total amount of LP tokens
- **lp burnable**: LP tokens that will be burned when forwarding yield
- **% of LP**: proportion of total LP to be burned

We can see that just a 1.5x increase in the asset balance (which might be a 2.25x increase in the price of the `ZVE` token) will remove 16.67% of the LP from the pool.

## Impact

The contract will remove a significant portion of LP and forward it as a yield.

## Code Snippet

This test added to [Test_OCL_ZVE](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-testing/src/TESTS_Lockers/Test_OCL_ZVE.sol) illustrates that after the amount of pair asset in the LP increases by 50%, the `_forwardYield` function removes ~16.67% of the LP and distributes it as yield.

```Solidity
function test_forwardYieldTooMuchLPRemoved() public {
        uint256 amountA = 1_000_000 * USD;
        uint256 amountB = 1_000_000 * USD;

        assert(zvl.try_updateIsKeeper(address(GBL), address(bob), true));

        // push
        pushToLockerInitial_Sushi(amountA, amountB, 0);

        address pair = IUniswapV2Factory(OCL_ZVE_SUSHI_DAI.factory()).getPair(
            DAI,
            address(ZVE)
        );

        uint256 balance0 = IERC20(pair).balanceOf(address(OCL_ZVE_SUSHI_DAI));

        // swap so asset increases 1.5x
        buyZVE_Sushi(amountA / 2, DAI);

        hevm.warp(
            OCL_ZVE_SUSHI_DAI.nextYieldDistribution() - 12 hours + 1 seconds
        );
        assert(bob.try_forwardYield(address(OCL_ZVE_SUSHI_DAI)));
        uint256 balance2 = IERC20(pair).balanceOf(address(OCL_ZVE_SUSHI_DAI));

        // new amount of LP tokens held is ~83% of the original LP tokens held
        assertLt(balance2, (balance0 * 84) / 100);
    }
```

## Tool used

Foundry, Manual review, Spreadsheets

## Recommendation

Consider tracking the `basis` parameter on Uniswap's / Sushiswap's `kLast()` function instead of the amount of the pair asset inside the contract. This will better illustrate the tokens gained by the AMM's tax.

**Comment by coreggon11** [comment]
Escalate

So if somebody (maybe a user who is getting these rewards) took a flashloan, bought a large amount of ZVE, forwarded the yield (removing 40% of LP) and then returned the funds, while the pool is now 50% less liquid and an excessive amount of LP is forwarded to stakers, that is not an issue?
