### ISSUE TITLE
lemonmon - Principal amount owed is rounded down in favor of the loan borrower inside the function `OCC_Modular.amountOwed()`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#598]
lemonmon

medium

# Principal amount owed is rounded down in favor of the loan borrower inside the function `OCC_Modular.amountOwed()`

## Summary

When calculating the principal amount owed for an amortizing loan, the calculation is rounding down in favor of the borrower.

## Vulnerability Detail

Inside `OCC_Modular.amountOwed()` the amount of principal owed is calculated on line 448 (OCC_Modular.sol). There due to the division by `loans[id].paymentsRemaining` the calculated amount of `principal` owed may be rounded down.

`OCC_Modular.amountOwed()` is used to determine `principalOwed` (line 500 and line 578 in OCC_Modular.sol) when paying off a loan or making a payment on a loan.

## Impact

The system may round down the amount of principal owed in favor of the loan borrower which may cause a loss for the loan lender.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L448

## Tool used

Manual Review

## Recommendation

Consider adjusting the calculation line 448 (OCC_Modular.sol) so that the amount of principal owed is rounded in favor of the lender.

**Comment by pseudonaut** [comment]
Not of concern
