### ISSUE TITLE
recursiveEth - Title: Potential Loss of Excess Tokens in Loan Default Resolution

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#599]
recursiveEth

medium

# Title: Potential Loss of Excess Tokens in Loan Default Resolution

## Summary

The resolveDefault function is designed to resolve defaulted loans by allowing users to make full or partial payments. However, there's a potential issue where if a user sends more tokens than the remaining principal owed on the loan, the excess tokens are sent to the protocol owner instead of being returned to the user. This could lead to a loss of tokens for users

## Vulnerability Detail

The vulnerability lies in the logic of the resolveDefault function, where if the amount sent by the user is greater than or equal to the remaining principal owed on the loan, all the excess tokens are transferred to the protocol owner, rather than sending those toke back to user.

## Impact

The impact of this vulnerability is potential loss of tokens for users who inadvertently send more tokens than necessary to resolve their defaulted loans.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L682

```javascript
if (amount >= loans[id].principalOwed) {
  paymentAmount = loans[id].principalOwed;
  loans[id].principalOwed = 0;
  loans[id].state = LoanState.Resolved;
} else {
  paymentAmount = amount;
  loans[id].principalOwed -= paymentAmount;
}
```

## Tool used

Manual Review

## Recommendation

Return Excess Tokens: Modify the logic of the resolveDefault function to return any excess tokens back to the user if they send more than the remaining principal owed on the loan. This ensures that users do not lose tokens unnecessarily and promotes a fair and transparent resolution process.

**Comment by pseudonaut** [comment]
Mathematically this doesn't seem valid and is handled in logic perfectly as is
