### ISSUE TITLE
pivanov - [ZivoeLocker.sol] - Insufficient Validation in Asset Transfer Functions

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#6]
pivanov

medium

# [ZivoeLocker.sol] - Insufficient Validation in Asset Transfer Functions

## Summary
The `ZivoeLocker` abstract contract lacks necessary validation checks in its asset transfer functions, potentially leading to unauthorized asset manipulation.

## Vulnerability Detail
The asset transfer methods in the `ZivoeLocker` contract (e.g., `pushToLocker`, `pullFromLocker`, etc.) lack checks to ensure that the caller (besides being the owner) is authorized to initiate such transfers for the specific assets. This could potentially allow unauthorized transfers of assets if the contract implementation does not properly override these functions to include such validations.

## Impact
If the derived contracts from ZivoeLocker do not implement additional checks or override these methods with proper validations, it could lead to scenarios where assets are transferred without proper authorization, risking asset loss or mismanagement.

## Code Snippet
See the related code segment for `pushToLocker` function [here](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeLocker.sol#L73-L76)
```solidity
function pushToLocker(address asset, uint256 amount, bytes calldata data) external virtual onlyOwner {
    require(canPush(), "ZivoeLocker::pushToLocker() !canPush()");
    IERC20(asset).safeTransferFrom(owner(), address(this), amount);
}
```
Similar issues are present in:
- `pullFromLocker`
- `pushToLockerMulti`
- `pullFromLockerMulti`
- `pullFromLockerPartial`
- `pushToLockerERC721`
- `pullFromLockerERC721`
- `pushToLockerMultiERC721`
- `pullFromLockerMultiERC721`
- `pushToLockerERC1155`
- `pullFromLockerERC1155`

## Tool used
Manual Review

## Recommendation
Implement strict validation mechanisms in the abstract ZivoeLocker contract to ensure that only authorized entities can initiate asset transfers. This could include:

- Validating the assets against a whitelist for ERC20, ERC721, and ERC1155 tokens before proceeding with transfers.
- Ensuring derived contracts override these functions with appropriate authorization checks specific to the asset being transferred.

### Code Snippets for Recommendation
Adding asset validation for `ERC20` transfers in `pushToLocker`:
```solidity
function pushToLocker(address asset, uint256 amount, bytes calldata data) external virtual onlyOwner {
    require(canPush(), "ZivoeLocker::pushToLocker() !canPush()");
    require(isAuthorizedAsset(asset), "ZivoeLocker::pushToLocker() unauthorized asset");
    IERC20(asset).safeTransferFrom(owner(), address(this), amount);
}

// Example validation function to be implemented
function isAuthorizedAsset(address asset) public view returns (bool) {
    // Validation logic to ensure the asset is authorized for transfer
    return true; // Placeholder return
}
```

Such a pattern ensures that all asset transfers through `ZivoeLocker` derived contracts are thoroughly validated, thereby enhancing the security posture against unauthorized asset manipulation.

**Comment by pseudonaut** [comment]
Not valid, redundant
