### ISSUE TITLE
Quanta - Severe dust in rewards of `ZivoeRewards` and `ZivoeRewardsVesting`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#601]
Quanta

medium

# Severe dust in rewards of `ZivoeRewards` and `ZivoeRewardsVesting`

## Summary

The reward rate calculations in [ZivoeRewards.sol#L233](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L233) can lead to an excesive dust and permanent loss of funds.

## Vulnerability Detail

In the contracts, when `depositReward` is called, new rewards are sent to the contract. Subsequently, the contract calculates the `rewardRate` by dividing the deposited amount. However, an issue arises when dealing with lower amounts, especially with tokens having lower decimal precision, such as stablecoins with 6 decimals. Over longer durations, this division operation results in a loss of precision. The total precision loss can be quantified as the product of the dust per second and the duration in seconds.

## Impact

In addition to the precision loss, another consequence of this calculation is that a portion of the funds might not be properly vested and could become trapped within the contract indefinitely. This occurs due to rounding errors, especially pronounced when dealing with lower amounts and longer durations. Consequently, the affected funds may remain inaccessible within the contract, posing a risk to the overall functionality and fairness of the system

## Code Snippet

```solidity 
 function depositReward(address _rewardsToken, uint256 reward) external updateReward(address(0)) nonReentrant {
        IERC20(_rewardsToken).safeTransferFrom(_msgSender(), address(this), reward);

        // Update vesting accounting for reward (if existing rewards being distributed, increase proportionally).
        if (block.timestamp >= rewardData[_rewardsToken].periodFinish) {
            // dust = loss of precission per second * duration

            // 1000 USDC = 1000 * 10 ** 6 deposit
            // duration of 31536000: 1 year

            // 1000e6 / 31536000 = 31.709791983764585 => 31 
            // 0.709791983764585 * 31536000 = 22075200 = 22 USDC of dust
            rewardData[_rewardsToken].rewardRate = reward.div(rewardData[_rewardsToken].rewardsDuration);
        } else {
```

## Tool used

Manual Review

## Recommendation

Use 30 decimals of precision in the `rewardRate` value just like other staking contracts do :

```solidity
rewardData[_rewardsToken].rewardRate = reward.mult(PRECISION).div(rewardData[_rewardsToken].rewardsDuration)
```

Duplicate of #129

**Comment by pseudonaut** [comment]
Valid, considering higher precision implementation
