### ISSUE TITLE
Audinarey - Zivoe does not consider enforcing refinancing when APR is reviewd upward

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#617]
Audinarey

medium

# Zivoe does not consider enforcing refinancing when APR is reviewd upward

## Summary

When `APR` goes up and ZVL approves a refinancing of a loan position for a user, the user can decide not to implement leading to loss for the protocol as the increased `APR` is applied to the position and as such continues to underpay interest.

## Vulnerability Detail

- Borrower takes out a loan of 100_00)DAI at 15% `APR` for 12 term of 28 `paymentPeriod`s each
- `APR` increases to 20% after 3 term have elapsed, [[Underwriter approves](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L932-L935)](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L932-L935) refinancing
- user does not [[apply refinanced](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L859-L869)](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L859-L869) `APR` and continues to service the loan at 15% `APR thereby underpaying the protocol

## Impact

This can ultimately lead to loss of funds for the protocol as borrowers will keep underpaying interest even when `APR` has been reviewed upward.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L932-L935

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L859-L869

## Tool used

Manual Review

## Recommendation

Consider force applying refinancing when the `APR` is reviewed upward

**Comment by pseudonaut** [comment]
Intended
