### ISSUE TITLE
saidam017 - Incorrect token validation from zero for one direction flag inside `ZivoeSwapper` when utilizing `unoswap` function

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#619]
saidam017

medium

# Incorrect token validation from zero for one direction flag inside `ZivoeSwapper` when utilizing `unoswap` function

## Summary

When use `unoswap` function for swapping assets via 1Inch, the token validation check is incorrect, causing the function will not work properly.

## Vulnerability Detail

It can be observed that inside the `unoswap` function validation, it will first get the `zeroForOne_0` and `zeroForOne_DLENGTH` flags, then check `assetIn` and `assetOut` against `token1`/`token0` inside the pool.

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/Utility/ZivoeSwapper.sol#L121-L149

```solidity
    function handle_validation_0502b1c5(bytes calldata data, address assetIn, address assetOut, uint256 amountIn) internal view {
        (address _a, uint256 _b,, uint256[] memory _d) = abi.decode(data[4:], (address, uint256, uint256, uint256[]));
        require(_a == assetIn, "ZivoeSwapper::handle_validation_0502b1c5() _a != assetIn");
        require(_b == amountIn, "ZivoeSwapper::handle_validation_0502b1c5() _b != amountIn");
        bool zeroForOne_0;
        bool zeroForOne_DLENGTH;
        uint256 info_0 = _d[0];
        uint256 info_DLENGTH = _d[_d.length - 1];
        assembly {
>>>         zeroForOne_0 := and(info_0, _REVERSE_MASK)
>>>         zeroForOne_DLENGTH := and(info_DLENGTH, _REVERSE_MASK)
        }
        if (zeroForOne_0) {
         require(IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[0])))).token1() == assetIn,
            "ZivoeSwapper::handle_validation_0502b1c5() IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[0])))).token1() != assetIn");
        }
        else {
            require(IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[0])))).token0() == assetIn,
            "ZivoeSwapper::handle_validation_0502b1c5() IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[0])))).token0() != assetIn");
        }
        if (zeroForOne_DLENGTH) {
            require(IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[_d.length - 1])))).token0() == assetOut,
            "ZivoeSwapper::handle_validation_0502b1c5() IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[_d.length - 1])))).token0() != assetOut");
        }
        else {
            require(IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[_d.length - 1])))).token1() == assetOut,
            "ZivoeSwapper::handle_validation_0502b1c5() IUniswapV2Pool_ZivoeSwapper(address(uint160(uint256(_d[_d.length - 1])))).token1() != assetOut");
        }
    }
```

`zeroForOne` is a flag that determine the direction of the swap, `true` for `token0` to `token1`, and  `false` for `token1` to `token0`. It can be observed that currently, the validation for not correct for both `assetIn` and `assetOut`. when `zeroForOne_0` is true, `assetIn` should be equal to `token0` and when `zeroForOne_0` is false, `assetIn` should be equal to `token1`. While for `assetOut`, when `zeroForOne_DLENGTH` is true, means `assetOut` should be equal to `token1` and when false, `assetOut` should be equal to `token0`.

## Impact

This will cause operation that need to interact with 1INCH and use `unoswap` function will revert and not work properly.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/Utility/ZivoeSwapper.sol#L121-L149

## Tool used

Manual Review

## Recommendation

Adjust and fix the token validation according to `zeroForOne` flag.

**Comment by pseudonaut** [comment]
Has this been verified as valid via founry-rs tests with properly generated data from 1INCHv5? I've tested this multiple times and this appears to be proper formatting
