### ISSUE TITLE
Shield - If a whitelisted stable coin depegs during the `ITO` period, it would result in uneven ZVE vesting

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#621]
Shield

medium

# If a whitelisted stable coin depegs during the `ITO` period, it would result in uneven ZVE vesting

## Summary

If a whitelisted stable coin depegs during the `ITO` period, it would result in uneven ZVE vesting.

## Vulnerability Detail

The `ZvoeITO.claimAirdrop` function is used to claim $zSTT, $zJTT, and begin a vesting schedule for $ZVE. 

The amount of `$zSTT`, `$zJTT` and vesting amount of `$ZVE` are decided based on the `seniorCreditsOwned` and `juniorCreditsOwned` amounts of the particular account.

These credit amounts are calculated inside the `depositJunior` and `depositSenior` functions as shown below:

```solidity
        uint256 standardizedAmount = IZivoeGlobals_ITO(GBL).standardize(amount, asset); //@audit-info - get the standardized amount

        juniorCredits[caller] += standardizedAmount; 
```

`depositJunior` and `depositSenior` functions can be called during the `ITO` period which is `30 days`. The issue here is that if any of the stable coins depegs during these 30 days users can take advantage of this and mint more `$zSTT`, `$zJTT` tokens and vest more `$ZVE` tokens. 

For example assume `USDC depegs to $0.9`. In that case the users can mint more `$zSTT`, `$zJTT` tokens for a `$1000 worth of USDC` than possible when `USDC was at $1`.

## Impact

The above vulnerability will result in leaking value from the previous depositors of the stable coins (USDC) (When the coins were properly pegged) to the protocol. 

## Code Snippet

```solidity
        // Calculate proportion of $ZVE awarded based on $pZVE credits.
        uint256 upper = seniorCreditsOwned + juniorCreditsOwned;
        uint256 middle = IERC20(IZivoeGlobals_ITO(GBL).ZVE()).totalSupply() / 20;
        uint256 lower = IERC20(IZivoeGlobals_ITO(GBL).zSTT()).totalSupply() * 3 + (
            IERC20(IZivoeGlobals_ITO(GBL).zJTT()).totalSupply()
        );

        emit AirdropClaimed(depositor, seniorCreditsOwned / 3, juniorCreditsOwned, upper * middle / lower);

        IERC20(IZivoeGlobals_ITO(GBL).zJTT()).safeTransfer(depositor, juniorCreditsOwned);
        IERC20(IZivoeGlobals_ITO(GBL).zSTT()).safeTransfer(depositor, seniorCreditsOwned / 3);
```

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L223-L233

```solidity
        uint256 standardizedAmount = IZivoeGlobals_ITO(GBL).standardize(amount, asset);

        juniorCredits[caller] += standardizedAmount;

        emit JuniorDeposit(caller, asset, amount, standardizedAmount, standardizedAmount);

        IERC20(asset).safeTransferFrom(caller, address(this), amount);
        IERC20Mintable_ITO(IZivoeGlobals_ITO(GBL).zJTT()).mint(address(this), standardizedAmount);
```

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L263-L270

```solidity
        uint256 standardizedAmount = IZivoeGlobals_ITO(GBL).standardize(amount, asset);

        seniorCredits[caller] += standardizedAmount * 3;

        emit SeniorDeposit(caller, asset, amount, standardizedAmount * 3, standardizedAmount);

        IERC20(asset).safeTransferFrom(caller, address(this), amount);
        IERC20Mintable_ITO(IZivoeGlobals_ITO(GBL).zSTT()).mint(address(this), standardizedAmount);
```

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L290-L297

## Tool used
Manual Review and VSCode

## Recommendation

Hence it is recommended to have an external oracle to check the prices against, of the whitelisted stable coins, and restrict the deposits if any of the stable coins are depegged more than a percentage threshold.

Duplicate of #105

**Comment by pseudonaut** [comment]
Not of concern
