### ISSUE TITLE
Quanta - `DestroyRequest` can be frontrun

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#628]
Quanta

medium

# `DestroyRequest` can be frontrun

## Summary
A malicious actor could frontrun `destroyRequest` by calling [processRequest](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCR/OCR_Modular.sol#L255) and lead to an undesired behaviour

## Vulnerability Detail

In the OCR_Modular contract, the `processRequest` function lacks access controls, allowing any user to call it. Conversely, the `destroyRequest` function can only be called by the request creator. This design introduces a potential vulnerability: if a user attempts to destroy a request after the 14-day period has elapsed, their transaction could be front-run by calling `processRequest`. As a result, instead of destroying the request as intended, the front-runner could effectively process the request, leading to unintended consequences for the user." 

## Code Snippet

```solidity
function processRequest(uint256 id) external _tickEpoch nonReentrant {
        // no sender checks
        require(requests[id].amount > 0, "OCR_Modular::processRequest() requests[id].amount == 0");
        require(requests[id].unlocks <= epoch, "OCR_Modular::processRequest() requests[id].unlocks > epoch");
   //...
```

## Tool used

Manual Review

## Recommendation

Only allow the request account to process the request just like in `destroyRequest`: 
```solidity
function processRequest(uint256 id) external _tickEpoch nonReentrant {
        // check sender
        require(
            requests[id].account == _msgSender(),
             "OCR_Modular::processRequest() requests[id].account != _msgSender()"
        );
        require(requests[id].amount > 0, "OCR_Modular::processRequest() requests[id].amount == 0");
        require(requests[id].unlocks <= epoch, "OCR_Modular::processRequest() requests[id].unlocks > epoch");
   //...
```

**Comment by pseudonaut** [comment]
OCR_Modular not in scope unfortunately
