### ISSUE TITLE
Pheonix - Denial Of Service in `distributeYield()` function causes yield to be stuck for residuals.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#635]
Pheonix

medium

# Denial Of Service in `distributeYield()` function causes yield to be stuck for residuals.

## Summary
Yield distribution will not work if any one of the recipient is blacklisted address in USDC token contract.

## Vulnerability Detail
`distributeYield()` function is responsible for distributing the outstanding yield to an array of  recipients mainly , ZVE stakers, and the Zivoe Development Company.

There are 2 kinds of recipients 
1. Protocol Recipients
2. Residual Recipients 

Yield will be a stablecoin ( can be DAI , USDT , USDC ) that will be distributed via YDL

After calculating the amount that is to be distributed to both the recipients, this function runs 2 `for` loops, one for protocol and the other for residual.
The problem arises if one of the residual or protocol recipients is a blacklisted address from USDC token contract.
In that case, any of the for loop will be in a state of DOS.

```solidity
        for (uint256 i = 0; i < residualRecipients.recipients.length; i++) {
            if (_residual[i] > 0) {
                address _recipient = residualRecipients.recipients[i];
                if (_recipient == IZivoeGlobals_YDL(GBL).stSTT() ||_recipient == IZivoeGlobals_YDL(GBL).stJTT()) {
                    IERC20(distributedAsset).safeIncreaseAllowance(_recipient, _residual[i]);
                    IZivoeRewards_YDL(_recipient).depositReward(distributedAsset, _residual[i]);
                    emit YieldDistributedSingle(distributedAsset, _recipient, _protocol[i]);
                }
                else if (_recipient == IZivoeGlobals_YDL(GBL).stZVE()) {
                    uint256 splitBIPS = (
                        IERC20(IZivoeGlobals_YDL(GBL).stZVE()).totalSupply() * BIPS
                    ) / (
                        IERC20(IZivoeGlobals_YDL(GBL).stZVE()).totalSupply() + 
                        IERC20(IZivoeGlobals_YDL(GBL).vestZVE()).totalSupply()
                    );
                    uint stZVEAllocation = _residual[i] * splitBIPS / BIPS;
                    uint vestZVEAllocation = _residual[i] * (BIPS - splitBIPS) / BIPS;
                    IERC20(distributedAsset).safeIncreaseAllowance(IZivoeGlobals_YDL(GBL).stZVE(), stZVEAllocation);
                    IERC20(distributedAsset).safeIncreaseAllowance(IZivoeGlobals_YDL(GBL).vestZVE(), vestZVEAllocation);
                    IZivoeRewards_YDL(IZivoeGlobals_YDL(GBL).stZVE()).depositReward(distributedAsset, stZVEAllocation);
                    IZivoeRewards_YDL(IZivoeGlobals_YDL(GBL).vestZVE()).depositReward(distributedAsset, vestZVEAllocation);
                    emit YieldDistributedSingle(distributedAsset, IZivoeGlobals_YDL(GBL).stZVE(), stZVEAllocation);
                    emit YieldDistributedSingle(distributedAsset, IZivoeGlobals_YDL(GBL).vestZVE(), vestZVEAllocation);
                }
                else {
                    IERC20(distributedAsset).safeTransfer(_recipient, _residual[i]);
                    emit YieldDistributedSingle(distributedAsset, _recipient, _residual[i]);
                }
            }
        }
    }
 ```

The above for loop will be in a suspended state ( if residual is blacklisted ) and the amount will be stuck.
Although this can be mitigated by calling `updateRecipients()` function, but the problem is that this function is only callable by TLC which is governance based.
That means for any update to happen , this has to go through a voting scenario.

## Impact
Rewards for all the recipients will be stuck.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeYDL.sol#L213-L310

## Tool used

Manual Review

## Recommendation
This can be mitigated by using try/catch statement such that other recipients will not be affected for the sake of a single blacklisted user.

**Comment by pseudonaut** [comment]
Not of concern
