### ISSUE TITLE
lemonmon - The `ZivoeYDL` ema calculation is incorrect due to uninitialized `distributionCounter`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#638]
lemonmon

medium

# The `ZivoeYDL` ema calculation is incorrect due to uninitialized `distributionCounter`

## Summary

The `ZivoeYDL` uses ema calculation for the adjusted supply of the tranche tokens to determine the yield distribution between parties. But due to uninitialized `distributionCounter`, the ema calculation will fail to use the first value set by `unlock` function. It opens up the possibility to manipulate the distribution, especially for the first couple of times.

## Vulnerability Detail

The `ZivoeMath:ema` function takes the varibale `N`, the Number of steps to average over.

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeMath.sol#L35-L39

As the unit test suggests, the N should be initialized to be 1, then should be incremented before the `ema` is called.

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-testing/src/TESTS_Math/Test_ZivoeMath_ema.sol#L16-L39

But in the `ZivoeYDL`, `distributionCounter` was initialized to be zero by default,

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L101

Then the `distributionCounter` was incremented before the calling the `MATH.ema`:

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L238-L239

So, the first time when the `distributeYield` is called, the `distributionCounter` will be zero, then incremented to be one before the `MATH.ema` call.

If the `ema` function is called with `N` as 1, the `M` will be `WAD`. then the `bV` (the base value) will not be accounted. Basically, the result will be `cV` itself. In the case of the `distributeYield`, the result will be the new adjusted supply. The ema set in the `unlock` will be basically not taken into account.

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeMath.sol#L35-L39

```solidity
    function ema(uint256 bV, uint256 cV, uint256 N) external pure returns (uint256 eV) {
        assert(N != 0);
        uint256 M = (WAD * 2).floorDiv(N + 1);
        eV = ((M * cV) + (WAD - M) * bV).floorDiv(WAD);
    }
```

This opens up a possibility to manipulate the ema value. Especially the first time when the yield is distributed, it will store the raw value of the adjustedSupply of the Tranche token, then it will be used for the next distribution

## Impact

The ema value is not properly calculated, for the multiple times in the beginning. It may skew the yield distribution between parties.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeMath.sol#L35-L39

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-testing/src/TESTS_Math/Test_ZivoeMath_ema.sol#L16-L39
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L101
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L238-L239
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeMath.sol#L35-L39

## Tool used

Manual Review

## Recommendation

Initialize the `distributionCounter` to 1 in the constructor

Duplicate of #201

**Comment by pseudonaut** [comment]
Valid, need to do this
