### ISSUE TITLE
lemonmon - Outdated openzeppelin `safeIncreaseAllowance` does not counter the USDT's approval issue.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#640]
lemonmon

medium

# Outdated openzeppelin `safeIncreaseAllowance` does not counter the USDT's approval issue.

## Summary

The Openzeppelin's safeERC20, specifically `safeIncreaseAllowance` is used to counter the issue with USDT's approval; revert on approval from non-zero allowance to non-zero allowance.

However, version used in Zivoe is v4.8, which does not help for that matter.

## Vulnerability Detail

USDT has an unique behavior, where is approval is done from non-zero allowance to non-zero allowance it would revert.

Zivoe is using the `safeIncreaseAllowance` to counter this issue, as it was stated in the contest page.

It is true, for the newer version of openzeppelin (for example, v5.0.2). It uses `forceApprove`, which will approve to zero first then approve to the newer value.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/4032b42694ff6599b17ffde65b2b64d7fc8a38f8/contracts/token/ERC20/utils/SafeERC20.sol#L76-L83

But Zivoe is using older version (v4.8.0), which will simply approve to the new allowance.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/4e5b11919e91b18b6683b6f49a1b4fdede579969/contracts/token/ERC20/utils/SafeERC20.sol#L61-L68

```solidity
    function safeIncreaseAllowance(
        IERC20 token,
        address spender,
        uint256 value
    ) internal {
        uint256 newAllowance = token.allowance(address(this), spender) + value;
        _callOptionalReturn(token, abi.encodeWithSelector(token.approve.selector, spender, newAllowance));
    }
```

Therefore, if the existing allowance should be non-zero on USDT, all the functions using the `safeIncreaseAllowance` will revert.

## Impact

Functions using `safeIncreaseAllowance` may fail in the used token is USDT (or any token which reverts on non-zero to non-zero approval)

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeDAO.sol#L293

## Tool used

Manual Review

## Recommendation

Consider updating the Openzeppelin version.

**Comment by pseudonaut** [comment]
Need to inspect and determine if actually valid
