### ISSUE TITLE
BoRonGod - Current system will suffer significant losses during stablecoin depeg

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#642]
BoRonGod

medium

# Current system will suffer significant losses during stablecoin depeg

## Summary

Current system 

## Vulnerability Detail

Here is a game-theory issue about governance system:

Current Zivoe protocol assumes that all tokens entering OCY and OCL have extremely stable prices, as the slippage parameters specified during addliquidity/swap are passed in when creating the proposal. If there is a significant price fluctuation, the transaction cannot be completed because parameters such as slippage cannot be changed when proposal is waiting in Timelock. 

Consider the USDC depeg in 2023:

1. USDC dropped to 0.95$ 
2. Zivoe protocol identified such price drop, and decide to sell some USDC to balance risks. When initializing proposals, a slippage of 5% is passed in.
3. After 1days in Timelock, USDC dropped to 0.83$, the proposal cannot be executed.

OR:

1. USDC dropped to 0.95$ .
2. Zivoe protocol identified such price drop, and decide to sell some USDC to balance risks. When initializing proposals, a slippage of 20% is passed in.
3. After 1days in Timelock, the executed tx is sandwiched by a arbitrageur.

For depeg like UST, such mechanism would make Zivoe suffer significant losses because tx cannot be executed on time.

And, since external integrates are RESTRICTED, the depeg scenero should be considered possible and valid.

## Impact

When depeg happens, Zivoe administrators will have to bear huge slippage to pull from lockers because they have to guess the token price after timelock.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L317

## Tool used

Manual Review

## Recommendation

Consider add an Emergency withdrawal mechanism or an Emergency proposal type to handle such issue.

Duplicate of #105

**Comment by pseudonaut** [comment]
Not of concern
