### ISSUE TITLE
Shield - A user can let the last payment of his loan `default` to avoid paying `lateFee and interestOwed`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#643]
Shield

high

# A user can let the last payment of his loan `default` to avoid paying `lateFee and interestOwed`

## Summary

A user can let the last payment of his loan `default` to avoid paying `lateFee and interestOwed`

## Vulnerability Detail

In the `OCC_Modular.resolveDefault` function, if the `loans[id].principalOwed` is totally repaid for a `defaulted loan` the state of the loan is updated to the `LoanState.Resolved`. And after that the `underwriter` can call the  `OCC_Modular.markRepaid` function to change the state back to `loans[id].state = LoanState.Repaid`.

So when the loan is in the `LoanState.Repaid` state it is considered to be in the fully settled state.

But the issue is when the `OCC_Modular.resolveDefault` is called only the `loans[id].principalOwed` is repaid back to the `DAO` and it does not account for the `lateFee or the interestOwed`. This is in contrast to how the loan is repaid in the `OCC_Modular.makePayment` and `OCC_Modular.callLoan` functions. Because when these two functions are called to repay a `loanPayment` it accounts for the `lateFee` and the `interestOwed` and the `payer` has to `repay` the `principal + lateFee + intereseOwed`.

## Impact

As a result of the above vulnerability, a user can let his `loan` default (last payment of his loan) and  avoid paying the `lateFee` rather than calling the `OCC_Modular.makePayment` or `OCC_Modular.callLoan` function where he has to pay the `lateFee` if the payment is delayed. This will result in lost funds to the `IZivoeGlobals_OCC(GBL).YDL()` or `OCT_YDL` contracts accordingly. (Because usually late fees and owed interest are paid to these contracts).

## Code Snippet

```solidity
        uint256 paymentAmount;

        if (amount >= loans[id].principalOwed) {
            paymentAmount = loans[id].principalOwed;
            loans[id].principalOwed = 0;
            loans[id].state = LoanState.Resolved;
        }
        else {
            paymentAmount = amount;
            loans[id].principalOwed -= paymentAmount;
        }

        emit DefaultResolved(id, paymentAmount, _msgSender(), loans[id].state == LoanState.Resolved);

        IERC20(stablecoin).safeTransferFrom(_msgSender(), owner(), paymentAmount);
        IZivoeGlobals_OCC(GBL).decreaseDefaults(IZivoeGlobals_OCC(GBL).standardize(paymentAmount, stablecoin));
```

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L688-L703

```solidity
        (uint256 principalOwed, uint256 interestOwed, uint256 lateFee,) = amountOwed(id);

        emit PaymentMade(
            id, _msgSender(), principalOwed + interestOwed + lateFee, principalOwed,
            interestOwed, lateFee, loans[id].paymentDueBy + loans[id].paymentInterval
        );

        // Transfer interest + lateFee to YDL if in same format, otherwise keep here for 1INCH forwarding.
        if (stablecoin == IZivoeYDL_OCC(IZivoeGlobals_OCC(GBL).YDL()).distributedAsset()) {
            IERC20(stablecoin).safeTransferFrom(_msgSender(), IZivoeGlobals_OCC(GBL).YDL(), interestOwed + lateFee);
        }
        else {
            IERC20(stablecoin).safeTransferFrom(_msgSender(), OCT_YDL, interestOwed + lateFee);
        }
```

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L578-L591

```solidity
        uint256 principalOwed = loans[id].principalOwed;
        (, uint256 interestOwed, uint256 lateFee,) = amountOwed(id);

        emit LoanCalled(id, principalOwed + interestOwed + lateFee, principalOwed, interestOwed, lateFee);

        // Transfer interest to YDL if in same format, otherwise keep here for 1INCH forwarding.
        if (stablecoin == IZivoeYDL_OCC(IZivoeGlobals_OCC(GBL).YDL()).distributedAsset()) {
            IERC20(stablecoin).safeTransferFrom(_msgSender(), IZivoeGlobals_OCC(GBL).YDL(), interestOwed + lateFee);
        }
        else {
            IERC20(stablecoin).safeTransferFrom(_msgSender(), OCT_YDL, interestOwed + lateFee);
        }
```

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L499-L510

## Tool used
Manual Review and VSCode

## Recommendation

Hence it is recommended to compute the `lateFee` and the `interestOwed` for the `defaulted loan payment` when the `OCC_Modular.resolveDefault` function is called and charge that payment from the payer (msg.sender) and transfer it to the `IZivoeGlobals_OCC(GBL).YDL()` contract or the `OCT_YDL` contract accordingly.

**Comment by pseudonaut** [comment]
Not of concern

**Comment by 0x73696d616f** [comment]
escalate

This is intended by the protocol, the linked function, [resolveDefault()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L688-L703), is to be called by the admins of the protocol to reduce defaults. Fees are supposed to be handled through [supplyInterest()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L709).

If a user decides to later pay the principal back, it will do the protocol a favor as it was already going to spend the funds to reduce the default anyway.

**Comment by sherlock-admin3** [comment]
> escalate
> 
> This is intended by the protocol, the linked function, [resolveDefault()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L688-L703), is to be called by the admins of the protocol to reduce defaults. Fees are supposed to be handled through [supplyInterest()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L709).
> 
> If a user decides to later pay the principal back, it will do the protocol a favor as it was already going to spend the funds to reduce the default anyway.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by panprog** [comment]
I agree with the escalation. From the [docs](https://docs.zivoe.com/user-docs/borrowers/how-do-defaults-work#resolving-defaults):
> All loans issued by the protocol will be collateralized off-chain by consumer loans placed into an SPV. In the event of a default by the lender that originated these consumer loans Zivoe will take possession of the SPV. Upon taking possession, a designated third-party service provider will service the loans within the SPV, and the portfolio will be wound down, ensuring that the protocol receives the accrued interest and principal owed to it.

So while on-chain it looks valid, the off-chain process is that borrower loses collateral in case of default (similar to liquidations in the other protocols), so this can not be used to avoid paying fees.

This issue should be made invalid.

**Comment by viraj124** [comment]
@panprog we don't have the escalation power but we have audited just the on chain part of the code and acc to that this issue should be valid, the validity of the issue should be dominated by the on chain side of the code where a simple check addition can prevent any chance of this scenario happening

**Comment by viraj124** [comment]
> I agree with the escalation. From the [docs](https://docs.zivoe.com/user-docs/borrowers/how-do-defaults-work#resolving-defaults):
> 
> > All loans issued by the protocol will be collateralized off-chain by consumer loans placed into an SPV. In the event of a default by the lender that originated these consumer loans Zivoe will take possession of the SPV. Upon taking possession, a designated third-party service provider will service the loans within the SPV, and the portfolio will be wound down, ensuring that the protocol receives the accrued interest and principal owed to it.
> 
> So while on-chain it looks valid, the off-chain process is that borrower loses collateral in case of default (similar to liquidations in the other protocols), so this can not be used to avoid paying fees.
> 
> This issue should be made invalid.

@panprog we don't have the escalation power but we have audited just the on chain part of the code and acc to that this issue should be valid, the validity of the issue should be dominated by the on chain side of the code where a simple check addition can prevent any chance of this scenario happening

**Comment by viraj124** [comment]
> escalate
> 
> This is intended by the protocol, the linked function, [resolveDefault()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L688-L703), is to be called by the admins of the protocol to reduce defaults. Fees are supposed to be handled through [supplyInterest()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L709).
> 
> If a user decides to later pay the principal back, it will do the protocol a favor as it was already going to spend the funds to reduce the default anyway.

responded above this should be a valid issue just in terms of the on chain functionality and can be easily fixed like mentioned in the issue and above comment

**Comment by panprog** [comment]
@viraj124 
We can not take into account only on-chain part of the protocol, the protocol logic includes off-chain actions, meaning that on-chain default can not be viewed as if borrower can simply resume paying the loan, on-chain actions are tightly connected with off-chain logic, and here the logic is such that in case of default borrower loses off-chain collateral and no longer needs to pay out the loan - the on-chain loan + possible interest and late fees are paid by the entity which takes posession of the borrower's collateral. So exactly as said in the escalation, `resolveDefault` can be called by anybody, but the expected callers are admins / liquidator, not the borrower, meaning this can not be seen as if borrower reduces fees.

**Comment by WangSecurity** [comment]
Agree with the Lead Judge. While we indeed audit only the on-chain part, we have to take off-chain into consideration as well. [This](https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/643#issuecomment-2106150197) information was known in the docs throughout the contest, hence, I believe it's an intended design.

Planning to accept the escalation and invalidate the report.

**Comment by 0x73696d616f** [comment]
@WangSecurity think you mean change the issue from medium to non reward?
> Planning to accept the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
@0x73696d616f yep, thank you for notifying

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x73696d616f](https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/643/#issuecomment-2105661897): accepted
