### ISSUE TITLE
supercool - When someone creates a vesting schedule and creates it with revocable opition!their is bug with how the `vesting.totalVested`is changed accruing in `revokeVestingSchedule`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#646]
supercool

high

# When someone creates a vesting schedule and creates it with revocable opition!their is bug with how the `vesting.totalVested`is changed accruing in `revokeVestingSchedule`

## Summary
The user has a choice about how they want to their vesting schedule. It can be revocable or you have to wait until withdraw gives the user some tokens. Furthermore when someone/user calls `revokeVestingSchedule()` and changes `vesting.totalVested` it will be assigned to `vestingtotalWithdrawn`.Lastly, below we will continue to see how this bug works in depth and how impacts users and the protocol!
## Vulnerability Details
As we said in the summary the user makes a vesting schedule and then someone/user calls `revokeVestingSchedule`.In practice, a specific state that can create a loss of funds is below!
When the state of the schedule returns 0 tokens to the user someone/user will call the function and make `totalWithdraw+=0` and `totalVesting=0`.
```solidity
        vestingScheduleOf[account].totalWithdrawn += amount;
        vestingScheduleOf[account].totalVesting = vestingScheduleOf[account].totalWithdrawn;
```
Switching totalVesting is good when the schedule is somewhat used but when the schedule is new it creates an issue. In conclusion when the user wants to get the tokens vested `totalVesting-totalWithdraw` will be zero not letting the user get their tokens back or any reward!
## Impact
Even though `revokeVestingSchedule` is supposed to end the vesting and give only `amount` as described it should not allow when the vesting is created to allow zero tokens returned. There should never be a state that allows the user enabled by an attacker or user to not get any tokens back with their schedule its a loss of funds because of the fact their investment will return 0 and it wasted time returning not even a single token. Lastly in this bad state, there is no reason to allow the user/someone to call this function and receive zero tokens!
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L445C23-L445C93
## Recommendation
A simple and quick fix is to add a zero revert statement when the user tries to revoke 

Duplicate of #31

**Comment by pseudonaut** [comment]
Valid, there are accounting issues in this revoke function, need to inspect and determine further

**Comment by superc00l** [comment]
Escalate
This bug report has to do with accounting issues about `totalVesting` and `totalWithdraw` and its implications on certain states. Furthermore, it should be rediscussed even if it's designated that it's invalid it should at least not be grouped with #31!

**Comment by sherlock-admin3** [comment]
> Escalate
> This bug report has to do with accounting issues about `totalVesting` and `totalWithdraw` and its implications on certain states. Furthermore, it should be rediscussed even if it's designated that it's invalid it should at least not be grouped with #31!

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by panprog** [comment]
The description is really hard to understand, so I'm not even sure what it talks about, but it might actually be invalid and by design.
