### ISSUE TITLE
BoRonGod - Convex admin can adjust fee rate to harm Zivoe and its users

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#648]
BoRonGod

medium

# Convex admin can adjust fee rate to harm Zivoe and its users

## Summary

Convex admin can adjust fee rates to harm Zivoe and its users, causing the protocol to suffer serious losses.

## Vulnerability Detail

Per the contest page, the admins of the protocols that Napier integrates with are considered "RESTRICTED". This means that any issue related to FRAX's admin action that could negatively affect Napier protocol/users will be considered valid in this audit contest.

Q: Are the admins of the protocols your contracts integrate with (if any) TRUSTED or RESTRICTED?
RESTRICTED

Following is one of the ways that Convex admin can harm Zivoe and its users.

According to Convex [Booster.sol](https://github.com/convex-eth/platform/blob/46888db798227cb49902816db29e664ff9df60e7/contracts/contracts/Booster.sol#L145-L161): 

    function setFees(uint256 _lockFees, uint256 _stakerFees, uint256 _callerFees, uint256 _platform) external{
        require(msg.sender==feeManager, "!auth");

        uint256 total = _lockFees.add(_stakerFees).add(_callerFees).add(_platform);
        require(total <= MaxFees, ">MaxFees");

        //values must be within certain ranges     
        if(_lockFees >= 1000 && _lockFees <= 1500
            && _stakerFees >= 300 && _stakerFees <= 600
            && _callerFees >= 10 && _callerFees <= 100
            && _platform <= 200){
            lockIncentive = _lockFees;
            stakerIncentive = _stakerFees;
            earmarkIncentive = _callerFees;
            platformFee = _platform;
        }

Convex admin can set the fee to 20%. The fee will consume most of the yield, leaving very little or nothing for Zivoe's OCY_Convex.

## Impact

Loss of assets for the protocols.

## Code Snippet

https://github.com/convex-eth/platform/blob/46888db798227cb49902816db29e664ff9df60e7/contracts/contracts/Booster.sol#L145

## Tool used

Manual Review

## Recommendation

Ensure that the protocol team and its users are aware of the risks of such an event and develop a contingency plan to manage it.

Duplicate of #657

**Comment by pseudonaut** [comment]
Not of concern
