### ISSUE TITLE
jasonxiale - `ZivoeRewardsVesting.depositReward` and `ZivoeRewards.depositReward` lack of permission check and parameter check.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#650]
jasonxiale

high

# `ZivoeRewardsVesting.depositReward` and `ZivoeRewards.depositReward` lack of permission check and parameter check.

## Summary
`ZivoeRewardsVesting.depositReward` and `ZivoeRewards.depositReward` don't validate the caller, and the parameters. A malicious user can call these two function with malicious parameter, which can affect the rewards `rewardRate`, thus can affect the depositors' rewards.

## Vulnerability Detail
Take `ZivoeRewardsVesting.depositReward` as an example, in [ZivoeRewardsVesting.depositReward](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L352-L367), __the function doesn't validate the caller, and `reward` parameter, so a malicious user can call this function with ZERO as `reward`.__

During the call, the `leftover` will be equal to `remaining` in [ZivoeRewardsVesting.sol#L359-L360](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L359-L360), so the `rewardData[_rewardsToken].rewardRate` will be smaller than expected because `leftover` is divided by `rewardData[_rewardsToken].rewardsDuration` in [ZivoeRewardsVesting.sol#L361](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L361)
```solidity
352     function depositReward(address _rewardsToken, uint256 reward) external updateReward(address(0)) nonReentrant {
353         IERC20(_rewardsToken).safeTransferFrom(_msgSender(), address(this), reward);
354 
355         // Update vesting accounting for reward (if existing rewards being distributed, increase proportionally).
356         if (block.timestamp >= rewardData[_rewardsToken].periodFinish) {
357             rewardData[_rewardsToken].rewardRate = reward.div(rewardData[_rewardsToken].rewardsDuration);
358         } else {
359             uint256 remaining = rewardData[_rewardsToken].periodFinish.sub(block.timestamp);
360             uint256 leftover = remaining.mul(rewardData[_rewardsToken].rewardRate);
361             rewardData[_rewardsToken].rewardRate = reward.add(leftover).div(rewardData[_rewardsToken].rewardsDuration);
362         }
363 
364         rewardData[_rewardsToken].lastUpdateTime = block.timestamp;
365         rewardData[_rewardsToken].periodFinish = block.timestamp.add(rewardData[_rewardsToken].rewardsDuration);
366         emit RewardDeposited(_rewardsToken, reward, _msgSender());
367     }
```

## Impact
A malicious user can call these two function with malicious parameter, which can affect the rewards `rewardRate`, thus can affect the depositors' rewards.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L352-L367
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewards.sol#L228-L243

## Tool used

Manual Review

## Recommendation
Verify the caller, and check if `rewards` is larger than a predefined threshold

Duplicate of #11

**Comment by pseudonaut** [comment]
Valid, considering adding whitelists
