### ISSUE TITLE
Topmark - Precision Loss in Division Operation During Asset Decimal Conversion

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#653]
Topmark

medium

# Precision Loss in Division Operation During Asset Decimal Conversion

## Summary
The standardize(...) function in the ZivoeGlobals.sol contract  is designed to adjust the amount of an asset based on its decimal places. However, there is a problem related to precision loss during division when the asset’s decimal places exceed 18.
## Vulnerability Detail
In the code noted by the pointer in code snippet below, if the asset’s decimal places are greater than 18, the standardizedAmount is divided by a power of 10 to the excess decimal increase e.g 21 - 18 = 3 for a 21 decimal asset. This division operation can lead to precision loss if the standardizedAmount is not evenly divisible by the divisor. The loss of precision means that the standardizedAmount may be slightly less than the actual value it should represent.
```solidity
 function standardize(uint256 amount, address asset) external view returns (uint256 standardizedAmount) {
        standardizedAmount = amount;
        if (IERC20Metadata(asset).decimals() < 18) { 
            standardizedAmount *= 10 ** (18 - IERC20Metadata(asset).decimals()); 
        } 
        else if (IERC20Metadata(asset).decimals() > 18) { 
>>>            standardizedAmount /= 10 ** (IERC20Metadata(asset).decimals() - 18);   ❌
        }
    }
```
## Impact
The impact of this vulnerability is potentially significant in a financial context in the protocol. Even a small precision loss, when compounded over many transactions, can lead to a noticeable loss of funds. This could negatively affect the balance of users and the overall integrity of the financial system built around this code.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeGlobals.sol#L148
## Tool used

Manual Review

## Recommendation
Protocol should put necessary variables in place to handle accumulated value lost as a result of precision loss so that they are not completely lost

**Comment by Albort-J** [comment]
Invalid
