### ISSUE TITLE
0brxce - depositReward can be called by any one with any asset leading to lost/locked funds

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#654]
0brxce

medium

# depositReward can be called by any one with any asset leading to lost/locked funds

## Summary
depositRewards is designed to receive tokens which should be distributed as rewards but since it's an external function with no permissioning, there's the potential for users to lose funds and have them locked in the respective rewards contract.

## Vulnerability Detail
The addReward function which adds an asset as a reward in the rewards contract is a privileged function requiring the _msgSender() to be the Zivoe Laboratory. depositReward receives such assets and uses them when the time comes for reward distribution, yet it doesn't have the same privilege of validating who the msgSender() is or ensuring that the _rewardsToken is a valid reward token.

## Impact
Anyone who calls this function on any ZivoeRewards or ZivoeRewardsVesting contract will lose that amount of the respective token

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L352-L367
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L228-L243

## Tool used

Manual Review

## Recommendation
Check the _rewardsToken is valid by checking the rewardToken array.
Create a permissioned list of accepted depositors.

Duplicate of #11

**Comment by pseudonaut** [comment]
Valid, need to add whitelists
