### ISSUE TITLE
Ironsidesec - Wasted new reward tokens are emitted to old stakers because new reward tokens are calculated based on same  `_balance` but convex has separate `_balance` calculations.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#655]
Ironsidesec

medium

# Wasted new reward tokens are emitted to old stakers because new reward tokens are calculated based on same  `_balance` but convex has separate `_balance` calculations.

## Summary
Convex also has the feature that they will make new rewards eligible only for the amount they staked after the new rewards are added. And it works correctly for them  because their system if multiple reward contracts per staking contract. There will be a staking contract A which will have a default reward. If there's a new reward token to be added, it will deploy a new reward contract, and if anyone stakes, it will change the balance on both this staking contract A and that new reward contract.
example : L 879 of https://etherscan.deth.net/address/0xc583e81bB36A1F620A804D8AF642B63b0ceEb5c0 and L 855 of https://etherscan.deth.net/address/0x6dF312B6367F53e4b7875738d32DE7925A72a1CF

## Vulnerability Detail

Issue 1: Wasted new reward tokens emitted to old stakers because new reward tokens are calculated based on the same  `_balance`
The issue is even if ZIVOE drops off that old stakers doesnt deserve new rewards, still hold a % of total supply of that staking token, because their staking balance  > 0. So the `rewardpertoken` will also be shared to these old stakers. And because they shouldn't  claim, these rewards are just emitted wrongly, causing a loss to these latest stakers

Issue 2: New rewards cannot be distributed to old stakers proportionately, because their `accountrewardpertoken == 0` for the new reward token
The team wants to distribute the new reward tokens to old stakers also beacuse they also share a balance of staked token. But their `accountrewardpertoken == 0` for the new reward token. So, they cannot be eligible for rewards until they call stake atleast once after new rewards are added. So this mechanism is wrong.

But ZIVOE wants to share the rewards with current staker too. And its not possible with current reward mechanism calculation because `accountrewardpertoken == 0`
for the new reward token.

## Impact
Either
Wasted new reward tokens emitted to old stakers because new reward tokens are calculated based on the same `_balance`.
or
Current stakers cannot be eligible for new rewards, which is against the intention of ZIVOE. So change the reward mechanism.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/ZivoeRewards.sol#L130

## Tool used

Manual Review

## Recommendation
Change the reward, reward rate mechanism to also eligible for new reward tokens for current stakers.

**Comment by pseudonaut** [comment]
Intended
