### ISSUE TITLE
BiasedMerc - ZivoeRewards has a hardcap of 10 rewards tokens, with no way to remove unused tokens

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#66]
BiasedMerc

medium

# ZivoeRewards has a hardcap of 10 rewards tokens, with no way to remove unused tokens

## Summary

`ZivoeRewards` allows up to 10 rewards tokens to be utilised for distributing rewards, however the contract has no way to remove reward tokens. This can result in the contract being locked from adding new tokens in the future, leading to the protocol being unable to operate as intended and having to deploy a new rewards contract.

## Vulnerability Detail

For tokens to be utilised for reward discribution they need to be first added through `addReward`:

[ZivoeRewards::addReward()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L208-L223)
```solidity
    function addReward(address _rewardsToken, uint256 _rewardsDuration) external {
        require(
            _msgSender() == IZivoeGlobals_ZivoeRewards(GBL).ZVL(), 
            "_msgSender() != IZivoeGlobals_ZivoeRewards(GBL).ZVL()")
        ;
        require(_rewardsDuration > 0, "ZivoeRewards::addReward() _rewardsDuration == 0");
        require(
            rewardData[_rewardsToken].rewardsDuration == 0, 
            "ZivoeRewards::addReward() rewardData[_rewardsToken].rewardsDuration != 0"
        );
        require(rewardTokens.length < 10, "ZivoeRewards::addReward() rewardTokens.length >= 10");

        rewardTokens.push(_rewardsToken);
        rewardData[_rewardsToken].rewardsDuration = _rewardsDuration;
        emit RewardAdded(_rewardsToken);
    }
```
The important aspect for this issue is the check:
`require(rewardTokens.length < 10, "ZivoeRewards::addReward() rewardTokens.length >= 10");`
Which ensures that only 10 `rewardTokens` can be utilised. However it is possible that the protocol may want to stop utilising certain tokens, and move rewards to different tokens. However currently the rewards contract has no way to remove tokens from `rewardTokens`.

## Impact

If over time the protocol cycles through different rewards tokens, then once they get to 10 `rewardTokens` they will be unable to add any new reward tokens. Leading to the use of outdated or less than ideal tokens, due to no function that allows `ZVL` to remove unused tokens from `rewardTokens` to be replaced by newer reward tokens.

## Code Snippet

[ZivoeRewards::addReward()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L208-L223)

## Tool used

Manual Review

## Recommendation

Add a function only callable by `IZivoeGlobals_ZivoeRewards(GBL).ZVL()` that removes unused tokens from `rewardTokens` freeing up space for new tokens to be added.

**Comment by pseudonaut** [comment]
Intended
