### ISSUE TITLE
BiasedMerc - OCL_ZVE: Improper use of Deadline when adding liquidity using UniswapV2 router

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#68]
BiasedMerc

medium

# OCL_ZVE: Improper use of Deadline when adding liquidity using UniswapV2 router

## Summary

`OCL_ZVE` allows the DAO to add liquidity to an LP through the UniswapV2 router, using `addLiquidity`. `addLiquidity` contains a `Deadline` parameter for a timeframe within which the call is valid. However `pushToLockerMulti` uses `block.timestamp + 14 days` as the `Deadline` meaning it is essentially useless, as `block.timestamp` will be determined in the same block as the call to `addLiquidity`. The DAO has no control over the deadline.

## Vulnerability Detail

Calls to `UniswapV2Router02::addLiqudity()` are protected by a `deadline` parameter to limit the execution of delayed/ old transactions. Functions that modify liquidity of the pool check this parameter against the current block timestamp in order to discard expired interactions:

[UniswapV2Router02::addLiquidity](https://github.com/Uniswap/v2-periphery/blob/master/contracts/UniswapV2Router02.sol#L61-L70)
```solidity
    function addLiquidity(
        address tokenA,
        address tokenB,
        uint amountADesired,
        uint amountBDesired,
        uint amountAMin,
        uint amountBMin,
        address to,
        uint deadline
    ) external virtual override ensure(deadline) returns (uint amountA, uint amountB, uint liquidity) {
```
The modifier `ensure(deadline)`:

[UniswapV2Router02::ensure](https://github.com/Uniswap/v2-periphery/blob/master/contracts/UniswapV2Router02.sol#L18-L21)
```solidity
    modifier ensure(uint deadline) {
        require(deadline >= block.timestamp, 'UniswapV2Router: EXPIRED');
        _;
    }
```
The deadline provided by the caller is checked to be larger or equal to the current block timestamp. The implemention of the `deadline` in `OCL_ZVE::pushToLockerMulti()`:

[OCL_ZVE.sol#L198-L206](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L198-L206)
```solidity
        (uint256 depositedPairAsset, uint256 depositedZVE, uint256 minted) = IRouter_OCL_ZVE(router).addLiquidity(
            pairAsset, 
            ZVE, 
            balPairAsset,
            balZVE, 
            (balPairAsset * 9) / 10,
            (balZVE * 9) / 10, 
            address(this), block.timestamp + 14 days
        );
```
The last parameter is the deadline, it is the current blocktimestamp with 14 days added. Firstly the addition of 14 days has no effect, as the timestamp will be the same as the timestamp within `addLiquidity`. Secondly, the DAO should have control of the deadline when sending a transaction to the locker.

## Impact

Using `block.timestamp + 14 days` is effectively bypassing the security check. As the `block.timestamp` will be determined once the transaction gets mined, the check will always pass.

Failing to provide a proper deadline value enables pending transactions to be maliciously executed at a later point. Transactions providing too little gas will have their execution delayed, and can be picked by malicious actors or MEV bots to be executed at a later point when they can profit from it, whilst negatively affecting the transaction sender (which is the Zivoe DAO).

## Code Snippet

[UniswapV2Router02::addLiquidity](https://github.com/Uniswap/v2-periphery/blob/master/contracts/UniswapV2Router02.sol#L61-L70)
[UniswapV2Router02::ensure](https://github.com/Uniswap/v2-periphery/blob/master/contracts/UniswapV2Router02.sol#L18-L21)
[OCL_ZVE.sol#L198-L206](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L198-L206)

## Tool used

Manual Review

## Recommendation

Allow the DAO to provide the deadline parameter to ensure the transaction is executed within a reasonable timeframe.

Duplicate of #144

**Comment by pseudonaut** [comment]
Interesting, I suppose this is valid however we're not overly conerned with the period - it was primarily provided to ensure we didn't revert on their end
