### ISSUE TITLE
pivanov - [ZivoeRewards.sol] - Unbounded Loops in Reward Claiming Mechanism

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#7]
pivanov

medium

# [ZivoeRewards.sol] - Unbounded Loops in Reward Claiming Mechanism

## Summary
The `ZivoeRewards` contract allows for multiple reward tokens to be added and managed within a single staking mechanism. However, functions that iterate over these reward tokens, such as `getRewards` and the `updateReward` modifier, do not limit the number of iterations. This lack of bounding could lead to gas limit issues, making these functions fail due to excessive gas consumption when there are many reward tokens.

## Vulnerability Detail
The contract iterates over all reward tokens in several functions to calculate and update rewards. While this design supports flexibility in reward management, it inherently introduces a scalability issue. As the number of reward tokens grows, the gas required to execute these iterations could exceed block gas limits, effectively making key functions such as claiming rewards or staking/unstaking operations infeasible.

## Impact
This unbounded loop issue could severely impact the usability and functionality of the `ZivoeRewards` contract. Users might be unable to claim their rewards or perform staking operations if the gas required exceeds the block gas limit. This could freeze the rewards mechanism and erode user trust in the system.

## Code Snippet
See the related code segment for `getRewards` function [here](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L281-L283)
```solidity
function getRewards() public updateReward(_msgSender()) {
    for (uint256 i = 0; i < rewardTokens.length; i++) { _getRewardAt(i); }
}
```

And from the `updateReward ` modifier [here](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L123C5-L134)
```solidity
modifier updateReward(address account) {
    for (uint256 i; i < rewardTokens.length; i++) {
        address token = rewardTokens[i];
        rewardData[token].rewardPerTokenStored = rewardPerToken(token);
        rewardData[token].lastUpdateTime = lastTimeRewardApplicable(token);
        if (account != address(0)) {
            rewards[account][token] = earned(account, token);
            accountRewardPerTokenPaid[account][token] = rewardData[token].rewardPerTokenStored;
        }
    }
    _;
}
```

## Tool used
Manual Review

## Recommendation
To mitigate this issue, consider implementing one of the following strategies:

- **Pagination**: Introduce a mechanism to process reward tokens in batches. This approach would allow operations to be executed within acceptable gas limits by limiting the number of reward tokens processed in a single transaction.
- **Limiting Reward Tokens**: Enforce a maximum number of reward tokens that can be managed by the contract. This direct approach limits flexibility but ensures that the contract remains operable.
- **Gas Estimation Checks**: Before performing operations that iterate over reward tokens, estimate the gas cost and compare it against a predefined threshold or the current block gas limit to prevent transactions that would fail.

Implementing such mechanisms requires careful consideration to balance flexibility, usability, and gas efficiency.

**Comment by pseudonaut** [comment]
Not valid, there is upper-bound of 10 maximum assets in addReward()
