### ISSUE TITLE
nikhil840096 - Unexpected Behavior in Token Transfer Due to Non-Standard Stablecoin Implementation. `Presale.sol:depositStablecoin`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#71]
nikhil840096

high

# Unexpected Behavior in Token Transfer Due to Non-Standard Stablecoin Implementation. `Presale.sol:depositStablecoin`

## Summary

This report details a critical vulnerability in the provided code snippet `IERC20(stablecoin).transferFrom(_msgSender(), treasury, amount);` from Presale.sol:depositStablecoin . The vulnerability stems from a potential mismatch between the ERC-20 standard and the specific implementation of the `transferFrom` function  used in stablecoins such as USDT in this case.

## Discrepancy in ERC-20 `transferFrom` Implementation with USDT

The protocol documentation specifies USDT as the stablecoin. However, a critical incompatibility exists between the `transferFrom` functions of the ERC-20 standard and the USDT implementation.

**ERC-20 `transferFrom` (Defined in `IERC20` interface):**

- Takes three arguments: `from` address, `to` address, `value` (amount)
- **Returns a boolean value:** `true` on successful transfer, `false` on failure

**USDT `transferFrom` (As per documentation):**

- Takes three arguments: `_from` address, `_to` address, `_value` (amount)
- **Does not return a boolean value**

This mismatch introduces a significant vulnerability:

* **Transaction Failures:** Without proper error handling, potential failures within USDT's `transferFrom` function could go undetected, leading to transaction failures.

While this vulnerability falls outside the pre-defined scope of the audit, I consider it essential to bring it to your attention due to its potential security implications.

## Impact

Since the code cannot explicitly verify the transfer's success, potential errors or malicious actions within the transferFrom function could go undetected.

* **Transaction Failures:** Without proper error handling, potential failures within USDT's `transferFrom` function could go undetected, leading to transaction failures.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/misc/Presale.sol#L159

## Tool used

Manual Review

## Recommendation

Use `safeTransferFrom` .

**Comment by pseudonaut** [comment]
Outside of scope, thanks for noticing though

**Comment by Nikhil8400** [comment]
I understand the initial classification of my finding as out of scope due to its suggestion regarding the use of safetransferfrom, I would like to draw your attention toward this finding which was a similar finding to this one, for a out of scope file but it has been considered [Link of the finding](https://solodit.xyz/issues/m-03-use-a-safe-transfer-helper-library-for-erc20-transfers-code4rena-juicebox-juicebox-v2-contest-git). Therefore, I respectfully request reconsideration of my finding in light of this information. Thank you for your attention to this matter.
