### ISSUE TITLE
dimulski - Portion of ZVE votes are assigned to addresses that can't vote, but are still counted towards the voting threshold

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#72]
dimulski

medium

# Portion of ZVE votes are assigned to addresses that can't vote, but are still counted towards the voting threshold

## Summary
The **Zivoe protocol** implements the ``OCL_ZVE.sol`` locker contract. The purpose of this contract is to create pools on Uniswap V2 and/or Sushi swap, and provide liquidity into them, as a way to generate yield. The pools consists of the ``ZVE`` token, and another token (most probably a whitelisted stablecoin by the protocol).  The ``ZivoeGovernorV2.sol`` contract is used for creating proposal, and allowing users to vote on them. For a proposal to be successful a quorum has to be reached, and the votes for the proposal has to be more than the votes against the proposal. 

In order to check if a quorum is reached first the ``_quorumReached()`` function from the openzeppelin  ``GovernorCountingSimple.sol`` contract is called:

```solidity
function _quorumReached(uint256 proposalId) internal view virtual override returns (bool) {
        ProposalVote storage proposalVote = _proposalVotes[proposalId];

        return quorum(proposalSnapshot(proposalId)) <= proposalVote.forVotes + proposalVote.abstainVotes;
}
```
As can be seen from the above code snippet only the ``forVotes`` and ``abstainVotes`` are compared against the required quorum. ``againtsVotes`` are not taken into account.
The ``_quorumReached()`` function in turn calls the ``quorum()`` function from the openzeppelin ``GovernorVotesQuorumFraction.sol`` contract:
```solidity
function quorum(uint256 blockNumber) public view virtual override returns (uint256) {
        return (token.getPastTotalSupply(blockNumber) * quorumNumerator(blockNumber)) / quorumDenominator();
}
```
which basicaly multiplies all the ZVE tokens  by a ``quorumNumerator`` that was set by the governance for that block, and then divides it by a ``quorumDenominator``. The ``ZivoeToken.sol`` contract mints **25_000_000 e18** tokens on creation, and the only way the supply of ``ZVE`` tokens can decrease and in turn the overall vote supply is by burning them.
```solidity
constructor(string memory name_, string memory symbol_, address init) ERC20(name_, symbol_) ERC20Permit(name_) {
        _mint(init, 25000000 ether);
}
```
However in the ``OCL_ZVE.sol`` contract the [pushToLockerMulti()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L172-L215) function transfers an amount of ``ZVE`` tokens to a pool, thus transferring part of the voting rights to an address which can't vote, as the pool implementation doesn't have the logic to vote on proposals or delegate to somebody else. The ``OCE_ZVE.sol`` contract purpose is to facilitate an exponential decay emission schedule for ``ZVE``, however the DAO again deposits ``ZVE`` tokens to an address which can't vote. When emissions are distributed to the appropriate ``ZivoeRewards.sol`` instances again the votes will be owned by an address which can't vote, until users claim their rewards.   Depending on the ``quorumNumerator`` for a block, and the ``ZVE`` tokens held by addresses that can't vote, and the possibility of users providing ``ZVE`` tokens as liquidity themselves on the Uniswap and/or Sushiswap pools, it is fairly possible that a scenario where a proposal with mostly for and against votes doesn't meet the quorum criteria occurs, even if the for votes are more than the against votes. In a case where 35% of the total ``ZVE`` supply is supplied as liquidity for different pools by the protocol, and the ``quorumNumerator`` is set to 70, no proposal can pass thus making the protocol obsolete.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L172-L215
## Tool used
Manual Review

## Recommendation
Consider overwriting the ``_quorumReached()`` function to take into account the ``againtsVotes`` as well, additionally you can consider implementing a mechanism where ``ZVE`` tokens that will be deposited to a pool, delegate their votes to the ``ZVL`` multisig.

**Comment by pseudonaut** [comment]
Intended, contracts shouldn't vote, only EOAs
