### ISSUE TITLE
dimulski - ZivoeTranches.sol contract is missing a redeeming mechanism

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#77]
dimulski

medium

# ZivoeTranches.sol contract is missing a redeeming mechanism

## Summary
The ``ZivoeTranches.sol`` contract supports deposits of whitelisted stablecoins via [depositJunior()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L268-L289) and [depositSenior](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L295-L315) functions. However there is no mechanism that allows users who deposited to redeem their tranche tokens back to stablecoins and withdraw them from the system. This severely limits the functionality of the protocol, especially the ``ZivoeTranches.sol`` contract, and deters potential users from depositing, as they can't redeem even a part of their initial deposit back, if they decide to. 

## Impact
Missing a redemption mechanism in the ``ZivoeTranches.sol`` contract severely limits the functionality of the protocol, especially the ``ZivoeTranches.sol`` contract, and deters potential users from depositing, as they can't get even a part of their initial deposit back, if they decide to. 

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L268-L289
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeTranches.sol#L295-L315

## Tool used
Manual Review

## Recommendation
Implement the redemption mechanism that you have described in your docs.

**Comment by pseudonaut** [comment]
Not relevant
