### ISSUE TITLE
pseudoArtist - Wrong calculation of ema in `ZivoeMaths.sol` will lead to wrong updates of the Weighted Moving average of Tranche Size.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#80]
pseudoArtist

high

# Wrong calculation of ema in `ZivoeMaths.sol` will lead to wrong updates of the Weighted Moving average of Tranche Size.

## Summary
The protocol is calculating [ema](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeMath.sol#L35-L39) according to the [Wikipedia](https://en.wikipedia.org/wiki/Exponential_smoothing) as mentioned in the docs however the implemention doesn't hold the invariant `0 < α < 1`
## Vulnerability Detail
EMA will not be working as exponential moving average as the invariant `0 < α < 1` doesn't holds, Now let's look at this how it fails to hold the invariant : 

The [EMA](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeMath.sol#L35-L39) function is calculated as follow : 

```solidity
function ema(uint256 bV, uint256 cV, uint256 N) external pure returns (uint256 eV) {
        assert(N != 0);
        uint256 M = (WAD * 2).floorDiv(N + 1);
        eV = ((M * cV) + (WAD - M) * bV).floorDiv(WAD);
    }
```

however the smoothing factor is represented as :
```solidity
uint256 M = (WAD * 2).floorDiv(N + 1);
```   

## OR

```solidity
α = 2 / ( N + 1 )
```   
Now according to the definition `0 < α < 1` the value of `α` should always be strictly greater that `0` and strictly less than `1` which is logical and true since it is exponential moving average and also the average value always is less than the greatest number and greater than the smallest number, but let's take
 `N = 1` then  : 
 α = 2 / ( 1 + 1 )
 α = 2 / 2 
 α = 1
 When we take `N = 1` the value of `α = 1` which should never become true since this is an invariant and should always hold the condition that  `0 < α < 1`.
 
 I consider this issue to be of HIGH severity as In [ZivoeYDL.sol :: distributeYield()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L238-L239) the distribution of yeild is done and the Weighted moving average for senior tranche size, a.k.a. `zSTT.totalSupply()` and  Weighted moving average for junior tranche size, a.k.a. `zJTT.totalSupply()` is updated [HERE](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L238-L239) and this could impact wrong updates in the total supply of the tranche tokens in some cases.
 
## Impact
The actual implemention of EMA is wrongly implemented and it will lead to wrong updates in the Weighted moving average for tranche size.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L238-L239

```solidity
 emaSTT = MATH.ema(emaSTT, aSTT, retrospectiveDistributions.min(distributionCounter));
 emaJTT = MATH.ema(emaJTT, aJTT, retrospectiveDistributions.min(distributionCounter));
``` 
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeMath.sol

```solidity
function ema(uint256 bV, uint256 cV, uint256 N) external pure returns (uint256 eV) {
        assert(N != 0);
        uint256 M = (WAD * 2).floorDiv(N + 1);
        eV = ((M * cV) + (WAD - M) * bV).floorDiv(WAD);
    }
```           
## Tool used

Manual Review

## Recommendation
This can be easily rectified by changing 

```solidity
- α = 2 / ( N + 1 )
+ α = 1 / ( N + 1 )
```    
Even with the smallest value of  N i.e. 1 the value of α becomes `1 / 2` i.e.  less than 1 and with the increasing value of N, `α ` always satisfies the required condition `0 < α < 1`

Duplicate of #201

**Comment by pseudonaut** [comment]
Actually with exponential smoothing it can be less than or equal to , `<=` and in our system we start with `N==1` so it will always be 1 or less with our chosen smoothing fator
