### ISSUE TITLE
SilverChariot - Arbitrary address can sabotage loans combination

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#81]
SilverChariot

medium

# Arbitrary address can sabotage loans combination

## Summary
Before combining loans there is a require that checks if the loans that you want to combine are active. Any arbitrary address can make this check fail and prevent the borrower from combining his loans.

## Vulnerability Detail
After the protocol call `approveCombine`, the borrower is allowed to call `applyCombine` and combine two or more loans. There is a require that checks if each of the loans is active. 
```js
require(loans[loanID].state == LoanState.Active, "OCC_Modular::applyCombine() loans[loanID].state != LoanState.Active");
```
However, any arbitrary address can front-run `applyCombine` and repay one of the loans the borrower wants to combine which would make the loan status repaid and later when `applyCombine` is executed, the require check for that loan will fail, and make the whole transaction revert meaning the borrower is unable to combine his loans. 

## Impact
A borrower is unable to combine his loans. 

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCC/OCC_Modular.sol#L769-L772

## Tool used

Manual Review

**Comment by pseudonaut** [comment]
Not relevant, it's not malicious and is slightly funny but user would be literally giving free money to the protocol and the borrower/underwriter could coordinate to combine remainder of loans again
