### ISSUE TITLE
SilverChariot - First call of `ZivoeYDL.distributeYield()` will distribute yield incorrectly

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#85]
SilverChariot

high

# First call of `ZivoeYDL.distributeYield()` will distribute yield incorrectly

## Summary
[ZivoeYDL.distributeYield()](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeYDL.sol#L213-L269) distributes a montly yield. Since `lastDistribution` is set to `block.timestamp + 30 days` when unlocking the contract, the first yield distribution will use the yield for 2 months, but the calculations will be made as if only 1 month has passed.

## Vulnerability Detail
When the contract is [unlocked](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeYDL.sol#L328), it sets 
```solidity
        lastDistribution = block.timestamp + 30 days;
```

Then [distributeYield](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeYDL.sol#L215-L218) can be called only if `daysBetweenDistribution` (which is set to 30 days) have passed since `lastDistribution`.

```solidity
        require(
            block.timestamp >= lastDistribution + daysBetweenDistributions * 86400, 
            "ZivoeYDL::distributeYield() block.timestamp < lastDistribution + daysBetweenDistributions * 86400"
        );
```

Therefore, the first distribution can be executed after at least 60 days since the unlocking have passed. However, the whole distribution process calculates its values for a single month, using `daysBetweenDistributions`.

```solidity
        uint256 _seniorProportion = MATH.seniorProportion(
            IZivoeGlobals_YDL(GBL).standardize(yD, distributedAsset),
            MATH.yieldTarget(emaSTT, emaJTT, targetAPYBIPS, targetRatioBIPS, daysBetweenDistributions),
            emaSTT, emaJTT, targetAPYBIPS, targetRatioBIPS, daysBetweenDistributions
        );
```

The `targetYield` will be calculated for only 1 month, which will completely mess up the whole distribution process. Let's look at the following example: 

|Senior supply| Junior Supply | target APY | junior multiplier | 
| ----------- | ----------- | ------------- | ---------- |
| 20 000 | 4 000 | 10% | 2.2 |

The senior yield per month should be 10% / 12 = 0.83%
The junior yield per month is $0.0083 * 2.2 = 1.83$%

The senior yield in stablecoin for one month is `166 DAI`.
The junior yield in stablecoin for one month is `73 DAI`.

When distributing for a first time, the yield should be around `332 DAI` and `146 DAI`, since 2 months has passed.  In the test below we can see that when the yield is `800 DAI` the contract distributes only `166 DAI` to the senior and `73 DAI` to the junior. The rest is send to the residual addresses.

## Impact
Wrong yield distribution depending on the yield accumulation. The contract will calculate the yield target as much smaller value than it has to be and will take wrong decisions based on that.

## Code Snippet
Paste the following test in [Test_ZivoeYDL.sol](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-testing/src/TESTS_Core/Test_ZivoeYDL.sol) and import `console`.

```solidity
   function test_first_distribution() public {
       simulateITO_byTranche_optionalStake(20_000 ether, true);

       uint256 YDLUnlockTimestamp = block.timestamp;
       hevm.warp(YDL.lastDistribution() + YDL.daysBetweenDistributions() * 86400);

       address[] memory recipients = new address[](1);
       uint256[] memory proportions = new uint256[](1);
       recipients[0] = address(0xb0b);
       proportions[0] = 10000;

       hevm.prank(GBL.TLC());
       YDL.updateRecipients(recipients, proportions, false);

       // 60 days have passed since unlocking
       assertEq((block.timestamp - YDLUnlockTimestamp) / 86400, YDL.daysBetweenDistributions() * 2);

       mint("DAI", address(YDL), 800 ether);

       uint256 seniorTrancheBefore = IERC20(DAI).balanceOf(address(stSTT));
       uint256 juniorTrancheBefore = IERC20(DAI).balanceOf(address(stJTT));
       uint256 residualBefore = IERC20(DAI).balanceOf(address(0xb0b));

       YDL.distributeYield();

       uint256 seniorTrancheAfter = IERC20(DAI).balanceOf(address(stSTT));
       uint256 juniorTrancheAfter = IERC20(DAI).balanceOf(address(stJTT));
       uint256 residualAfter = IERC20(DAI).balanceOf(address(0xb0b));

       console.log('senior difference: ', seniorTrancheAfter - seniorTrancheBefore);
       console.log('junior difference: ', juniorTrancheAfter - juniorTrancheBefore);
       console.log('residual difference: ', residualAfter - residualBefore);
    }
```
The logs: 

```solidity
  senior difference:  164383561643835616438
  junior difference:  72328767123287671232
  residual difference:  403287671232876712330
```
From the 800 DAI that accrued in the contract, the senior and junior staking contracts received only around 236 DAI. The residuals got around 403 DAI.

## Tool used

Foundry

## Recommendation
Do not add 30 days to the `lastDistribution` variable when unlocking.

```diff
    function unlock() external {
      ...
-     lastDistribution = block.timestamp + 30 days;
+     lastDistribution = block.timestamp;
      ...
      }
```

**Comment by pseudonaut** [comment]
60 days is intended for first distribution

**Comment by ZdravkoHr** [comment]
@WangSecurity, can you please reevaluate the validity of this finding. It has the same type of impact as #347 which was accepted.

In fact, the impact is even greater because the delay here will always be 30 days at least and no keeper down time is needed. Thanks!

**Comment by WangSecurity** [comment]
I agree that this one is indeed expected behaviour for the first distribution. #347 explains the problem for every other distribution, while this one is about the first one which is exapcted to behave in that way.

**Comment by ZdravkoHr** [comment]
@WangSecurity, but why is losing rewards for a whole month acceptable in this issue, while losing rewards for much smaller time is not in #347. I am not saying they must be duplicates, but that both these families show the same impact

**Comment by WangSecurity** [comment]
The reason is that for the first distribution, it's intended to distribute over 30 days, instead of 60 and the protocol works as expected. While in #347 it's shows how there can be a loss in other distributions where it's intended to be 30 days and should be so. I'm not saying that losing the rewards for a month is a accepable, I'm saying that it's the intended behaviour in this case for the first distribution.

**Comment by ZdravkoHr** [comment]
@WangSecurity, I guess you unintentionaly replaced `30` and `60` in your first sentence?

If understand that the protocol intends to distribute the first yield after 60 days and not 30.

However, as explained in the `Vulnerability Section`, the code will distribute the whole yield from day 0 to day 60 as if only 30 days have passed and the tranches will receive much less than they deserve.

That's why I am saying there is a loss of yield for one month.

**Comment by WangSecurity** [comment]
Yeah, I understand what you mean, but I believe the intention here is indeed to not just distribute after 60 days, but also distribute it as only 30 days have passed. I agree that it's a strange behaviour, but I believe it's intended to work in that way and I see report more as a recommendation to be honest.
