### ISSUE TITLE
pseudoArtist - `ZivoeRewards.sol::getRewards()`  Blacklisted users will miss out on Rewards even after staking properly.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#86]
pseudoArtist

high

# `ZivoeRewards.sol::getRewards()`  Blacklisted users will miss out on Rewards even after staking properly.

## Summary
A user who is a blacklisted address for the reward tokens won't be able to claim rewards even after staking correctly.
## Vulnerability Detail
`ZivoeRewards.sol` Contract is used to stake and claim reward for the staked tokens, and as per sponsors comment in the discord public chat it has been confirmed that reward tokens can be any of the following (ZVE , DAI , USDC), The USDC has a `blacklist()` function where a particular address can be blacklisted and won't be able to hold USDC.
Currently there are [223 blacklisted USDC addresses](https://dune.com/phabc/usdc-banned-addresses).

Now let's see how this can be a cause of concern:

1. User calls [stake()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L253-L262) and stakes certain amount of tokens.

2. User accumulates the reward tokens such as USDC.

3. User calls [getRewards()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L281-L283) which further calls internal function [_getRewardAt](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L287C14-L295).

4. The function transfers `reward` to `msg.sender` and if the `msg.sender` is a blacklisted address he won't be able to receive his rewards in that case since `IERC20(_rewardsToken).safeTransfer(_msgSender(), reward);` this `safeTransfer` will revert in that case

## Impact
Loss of reward tokens for user.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L287C14-L295

```solidity
function _getRewardAt(uint256 index) internal nonReentrant {
        address _rewardsToken = rewardTokens[index];
        uint256 reward = rewards[_msgSender()][_rewardsToken];
        if (reward > 0) {
            rewards[_msgSender()][_rewardsToken] = 0;
@>            IERC20(_rewardsToken).safeTransfer(_msgSender(), reward);
            emit RewardDistributed(_msgSender(), _rewardsToken, reward);
        }
    }
```    
## Tool used

Manual Review

## Recommendation
Add a check while staking if msg.sender is already a blacklisted address for the reward token or not, however this will work only for `stake()` function but won't work for `stakeFor()` function since in that case reward reciever will be a different address.

**Comment by panprog** [comment]
Escalate

This is a dup of #13 , just missed it due to absence of clear wording that the impact is in the *other* rewards, not in the blacklisted reward itself.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This is a dup of #13 , just missed it due to absence of clear wording that the impact is in the *other* rewards, not in the blacklisted reward itself.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Depends on #13 escalation. If #13 remains invalid, then planning to accept this escalation. If #13 ends up invalid, will reject this escalation, cause it doesn't effect the rewards distribution.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [panprog](https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/86/#issuecomment-2105660834): rejected
