### ISSUE TITLE
alzaf - Unchecked transferFrom

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#87]
alzaf

high

# Unchecked transferFrom

## Summary

Unchecked transferFrom

## Vulnerability Detail

The return value of an external transferFrom call is not checked

## Impact

Deposit will not revert if the transfer fails, and an attacker can call deposit for free

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/misc/Presale.sol#L159

## Tool used

Manual Review

## Recommendation

Use SafeERC20, or ensure that the transfer/transferFrom return value is checked.

**Comment by pseudonaut** [comment]
Contract out of scope
