### ISSUE TITLE
pseudoArtist - 'ZivoeITO.sol:DepositJunior & depositSenior' won't be able to accept more than 4 stablecoins in the future for deposit

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#90]
pseudoArtist

medium

# 'ZivoeITO.sol:DepositJunior & depositSenior' won't be able to accept more than 4 stablecoins in the future for deposit

## Summary
Both [DepositJunior()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L248C14-L271) & [depositSenior()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L277-L298) are used to deposit stablecoins mint Zivoe Junior Tranche ($zJTT) tokens and Zivoe Senior Tranche ($zJTT) and increase airdrop credits. but due to hardcoded require condition if more than 4 stablecoins are ever used for depositing in ITO the function will not accept coins at index 4 onward in the `stables[]` array.
## Vulnerability Detail
I will take the example of [depositJunior()](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L248-L271) function to show how it will be a problem if ever protocol tries to put more than 4 stablecoins in the array.

Just look at this [require](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L251C8-L254C11) condition check :

```solidity
 require(
            asset == stables[0] || asset == stables[1] || asset == stables[2] || asset == stables[3],
            "ZivoeITO::depositJunior() asset != stables[0-3]"
        );
```
It checks if the assets to be deposited are already present in the stables[] array at index 0,1,2,3 only and if they are not present the function will revert in that case, however the problem arises with the nature of hardcoded index, if ever protocol decides to add more stablecoins for depositing the depositJunior and depositSenior function will not work for those stablecoins which are at index 4 and  onwards, in that case it will just revert.        
## Impact
Two main function of the ITO [depositJunior](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L248-L271) and [depositSenior](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L277-L298) will not work as intended.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L251C8-L254C11
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeITO.sol#L280-L283

```solidity
 require(
            asset == stables[0] || asset == stables[1] || asset == stables[2] || asset == stables[3],
            "ZivoeITO::depositJunior() asset != stables[0-3]"
        );
```        
## Tool used

Manual Review and Remix

## Recommendation
add this logic and replace the old one :

```solidity
-   require(
-            asset == stables[0] || asset == stables[1] || asset == stables[2] || asset == stables[3],
-            "ZivoeITO::depositJunior() asset != stables[0-3]"
-        );

+        bool found = false;
+        for (uint i = 0; i < stables.length; i++) {
+       if (asset == stables[i]) {
+        found = true;
+        break;
+    }
+        }
+ require(found, "ZivoeITO::depositJunior() asset not found in stables array");
```

**Comment by pseudonaut** [comment]
Intended
