### ISSUE TITLE
zarkk01 - There is no way to remove a `rewardToken` from the `rewardTokens` array which size is limited

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#93]
zarkk01

medium

# There is no way to remove a `rewardToken` from the `rewardTokens` array which size is limited

## Summary
In the `ZivoeRewards` contract, `ZVL` role can add a `rewardToken` to the `rewardTokens` array easily calling `addReward()` function. But this function sets a limit to the size of the `rewardTokens` array as 10. If protocol changes his mind or something disasterous happens in the token and should be removed from the array, there is no way to do that.

## Vulnerability Detail
Users in `ZivoeRewards` contract, while they are staking their $ZVE, $zSTT or $zJTT, they take rewards in the form of `rewardTokens`. These rewardTokens are added to the `rewardTokens` array in the `addReward()` function. From this point, everyone can deposit funds to the contract so these funds to be distributed to stakers as long as this funds are in a token which appears in the `rewardTokens` array. But if the protocol decides to remove a token from the `rewardTokens` array for a lot of reasons, there is no way to do that.

## Impact
Unwanted tokens can remain for ever in the `rewardTokens` array and since the `rewardTokens` array is limited to 10, they "take seats" of other tokens which can be more beneficial for the users. This can result in a loss of income for the users and a decrease in the efficiency of the protocol but also can conclude on : 
1. `distributeYield()` function of `ZivoeYDL` contract to `depositRewards` in unwanted tokens.
2. Users to deposit funds without knowing the issue with this `rewardToken`

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewards.sol#L208

## Tool used
Manual Review

## Recommendation
A "back-door" of changing minds and remove a `rewardToken` from the array and let the protocol to be more flexible is needed. Consider adding a `removeReward()` function to the `ZivoeRewards` contract which will remove a `rewardToken` from the `rewardTokens` array. This function should be limited to the `ZVL` role and should be able to remove a `rewardToken` from the array. With changes made to `distributeYield()` function of `ZivoeYDL`, here is a possible implementation of the function in `ZivoeRewards` :
```solidity
function removeReward(address _token) external {
        require(
            _msgSender() == IZivoeGlobals_ZivoeRewards(GBL).ZVL(), 
            "_msgSender() != IZivoeGlobals_ZivoeRewards(GBL).ZVL()")
        ;
        require(rewardTokens.length > 0, "No reward tokens to remove")

        if (IERC20(_token).balanceOf(address(this)) > 0) {
            IERC20(_token).transfer(IZivoeGlobals_ZivoeRewards(GBL)DAO(), IERC20(_token).balanceOf(address(this)));
        }

        uint256 index = 42;
        for (uint256 i = 0; i < rewardTokens.length; i++) {
            if (rewardTokens[i] == _token) {
                index = i;
                break;
            }
        }

        require(index < rewardTokens.length, "Token not found in rewardTokens array");
        rewardTokens[index] = rewardTokens[rewardTokens.length - 1];
        rewardTokens.pop();
    }
```

**Comment by pseudonaut** [comment]
Intended
