### ISSUE TITLE
Timenov - Attacker can cause revert or decrease rewards.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#94]
Timenov

high

# Attacker can cause revert or decrease rewards.

## Summary
In `ZivoeRewards` and `ZivoeRewardsVesting` users can stake a token and after time receive rewards. Rewards are added by trusted entity and after that anyone can deposit rewards. However there are certain conditions that will allow an attacker to take advantage of the current implementation and cause unsuspected reverts or decrease of rewards rate.

## Vulnerability Detail
Scenarios that attacker can use: 

#### Scenario 1 (underflow revert)

1. Contracts are running fine and users stake their tokens.
2. Attacker can be the first to deposit reward by frontrunning or wait time to pass so that `block.timestamp >= rewardData[_rewardsToken].periodFinish` is true and calls `depositReward` with 0 as reward.

```solidity
    function depositReward(address _rewardsToken, uint256 reward) external updateReward(address(0)) nonReentrant {
        IERC20(_rewardsToken).safeTransferFrom(_msgSender(), address(this), reward);

        // Update vesting accounting for reward (if existing rewards being distributed, increase proportionally).
        if (block.timestamp >= rewardData[_rewardsToken].periodFinish) {
            rewardData[_rewardsToken].rewardRate = reward.div(rewardData[_rewardsToken].rewardsDuration); // @audit 0 / anyNumber = 0
        } else {
            uint256 remaining = rewardData[_rewardsToken].periodFinish.sub(block.timestamp);
            uint256 leftover = remaining.mul(rewardData[_rewardsToken].rewardRate);
            rewardData[_rewardsToken].rewardRate = reward.add(leftover).div(rewardData[_rewardsToken].rewardsDuration);
        }

        rewardData[_rewardsToken].lastUpdateTime = block.timestamp;
        rewardData[_rewardsToken].periodFinish = block.timestamp.add(rewardData[_rewardsToken].rewardsDuration);
        emit RewardDeposited(_rewardsToken, reward, _msgSender());
    }
```

3. Now the value of `rewardData[_rewardsToken].rewardRate` will be 0.
4. User will call any of the functions, which has `updateReward` modifier.
5. The modifier will first call `rewardPerToken(token)`.
6. The return value of that function will be 0(we assume that `_totalSupply != 0`) and `rewardPerTokenStored` will be assigned this value.

```solidity
        return rewardData[_rewardsToken].rewardPerTokenStored.add(
            lastTimeRewardApplicable(_rewardsToken).sub(
                rewardData[_rewardsToken].lastUpdateTime
            ).mul(rewardData[_rewardsToken].rewardRate).mul(1e18).div(_totalSupply) // @audit rewardRate is 0
        );
```

7. Then the modifier will call `earned(account, token)`.

```solidity
    function earned(address account, address _rewardsToken) public view returns (uint256 amount) {
        return _balances[account].mul(
            rewardPerToken(_rewardsToken).sub(accountRewardPerTokenPaid[account][_rewardsToken]) // @audit will underflow here
        ).div(1e18).add(rewards[account][_rewardsToken]);
    }
```

8. This will revert due to underflow as it will try to do `0 - positiveNumber`.

#### Scenario 2(decrease `rewardRate`)
1. Contracts are running fine
2. Someone(not malicious) deposited 1000 USDC(6 decimals) as a reward. The following code will be executed as this is the first call.

```solidity
            rewardData[_rewardsToken].rewardRate = reward.div(rewardData[_rewardsToken].rewardsDuration);
```

3. The rewardRate will be 1000e6 / 2592000(seconds in 30 days) = 385.
4. User decides to stake all his tokens at once. His USDC rewards will be 0 as his balance is not updated.

```solidity
        return _balances[account].mul( // @audit this is 0 as modifier is executed before function logic
            rewardPerToken(_rewardsToken).sub(accountRewardPerTokenPaid[account][_rewardsToken]) // @audit this is also 0 as it is updated on the next line of the modifier
        ).div(1e18).add(rewards[account][_rewardsToken]); // @audit rewards are 0
```

5. After 1 day user decides to get his rewards.
6. Attacker frontruns and calls `depositReward` with 0 as reward.

```solidity
            uint256 remaining = rewardData[_rewardsToken].periodFinish.sub(block.timestamp); // 2505600 as 29 days left
            uint256 leftover = remaining.mul(rewardData[_rewardsToken].rewardRate); // 2505600 * 385 = 964_656_000
            rewardData[_rewardsToken].rewardRate = reward.add(leftover).div(rewardData[_rewardsToken].rewardsDuration); // (0 + 964656000) / 2592000 = 372
```

7. The rewardRate decreased after just 1 day, if more days has passed the rewardRate will decrease more.
8. User will get rewards now, but will receive less than should.

This [example](https://solidity-by-example.org/defi/staking-rewards/) shows Synthetix staking. Notice that the difference is that only owner can change rewardRate by calling `notifyRewardAmount`.

## Impact
Attacker blocking crucial functions or decreasing rewards.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L228-L243
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L352-L367

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L123-L134
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L197-L208

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewards.sol#L180-L184
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeRewardsVesting.sol#L300-L304

## Tool used
Manual Review

## Recommendation
Add the same validation as the Synthetix example provided above.

Duplicate of #11

**Comment by pseudonaut** [comment]
Valid, considering whitelists for depositReward
