### ISSUE TITLE
BiasedMerc - ZivoeLocker doesn't check array lengths, which can lead to erroneous reverts

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#99]
BiasedMerc

medium

# ZivoeLocker doesn't check array lengths, which can lead to erroneous reverts

## Summary

`ZivoeLocker` does not implement array length checks. This can result in erroneous reverts when passed arrays do not have the same length.

## Vulnerability Detail

The functions `pushToLockerMulti`, `pullFromLockerMulti`, `pullFromLockerMultiPartial`, `pushToLockerMultiERC721`, and `pullFromLockerMultiERC721` all accept arrays as parameters, however there are no checks to ensure that all the arrays have the same length. Take `pushToLockerMulti` as an example:

[ZivoeLocker::pushToLockerMulti](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeLocker.sol#L99-L106)
```solidity
    function pushToLockerMulti(
        address[] calldata assets, uint256[] calldata amounts, bytes[] calldata data
    ) external virtual onlyOwner {
        require(canPushMulti(), "ZivoeLocker::pushToLockerMulti() !canPushMulti()");
        for (uint256 i = 0; i < assets.length; i++) {
            IERC20(assets[i]).safeTransferFrom(owner(), address(this), amounts[i]);
        }
    }
```
`assets`, `amounts` and `data` are all input parameters of array types, and all use index `[i]` to access values within the array. If any of the array is shorted than `assets` then the function will revert.

## Impact

The functions `pushToLockerMulti`, `pullFromLockerMulti`, `pullFromLockerMultiPartial`, `pushToLockerMultiERC721`, and `pullFromLockerMultiERC721` will all revert erroneously if array of different lengths are passed due to no checks of array lengths.

## Code Snippet

[ZivoeLocker::pushToLockerMulti](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeLocker.sol#L99-L106)

## Tool used

Manual Review

## Recommendation

Ensure that array lengths are the same for `pushToLockerMulti`, `pullFromLockerMulti`, `pullFromLockerMultiPartial`, `pushToLockerMultiERC721`, and `pullFromLockerMultiERC721` to avoid accessing non-existing array indexes when itterating.

**Comment by pseudonaut** [comment]
Not relevant, these checks are handled in ZivoeDAO
